modules/text/doc/erfilter.rst
modules/text/include/opencv2/text/erfilter.hpp

Noticed in http://docs.opencv.org/trunk/modules/text/doc/erfilter.html that "single" has been written as "sinle" instead. Fixed it at both locations found in the repo.

Fix typo in ERFilter

---

modules/text/src/ocr_tesseract.cpp

The docs specify it to allow 8UC1 and 8UC3 images.

Fix for Bug 4074. Both conditions of if are same

---

modules/matlab/CMakeLists.txt
modules/matlab/include/opencv2/matlab/bridge.hpp

The following fixes were required to compile MATLAB bindings under linux with MATLAB R2014b.

Fixes required to compile MATLAB bindings

---

modules/adas/CMakeLists.txt
modules/saliency/CMakeLists.txt
modules/ximgproc/CMakeLists.txt

adas, saliency and ximgproc modules causes build errors for iOS contrib framework

Disable some modules for iOS framework world build

---

modules/xfeatures2d/include/opencv2/xfeatures2d/cuda.hpp
modules/xfeatures2d/src/surf.cuda.cpp

This fix is required to successfully compile against the current OpenCV HEAD.

Function cuda::integral() does not require an extra buffer any more.

---

modules/tracking/src/tld_utils.cpp

The bug appears on the initialization step, if the initial bounding box width was larger than height. The problem was in function calculating a binary code for ensemble classifiers. In this function “measurement” values were used in wrong order (h1,w1,h2,w2; instead of: w1,w2,h1,h2), generating a access violation error on “patch” data access by the reason that width>height and pointer to data is calculated linearly data.step*height+width

Bug fix #1

---

modules/tracking/src/precomp.hpp
modules/tracking/src/tld_utils.cpp

The bug has the same origin as:
https://github.com/Itseez/opencv_contrib/pull/187
The problem was in "fast" version of function generating a binary code for ensemble classifier posterior probability calculation. Bug was eliminated by fixing the order of "values" in offsets calculating function

Bug fixing

---

modules/latentsvm/src/_lsvmc_function.h
modules/latentsvm/src/_lsvmc_latentsvm.h
modules/latentsvm/src/_lsvmc_matching.h
modules/latentsvm/src/_lsvmc_parser.h
modules/latentsvm/src/_lsvmc_routine.h
modules/latentsvm/src/_lsvmc_types.h
modules/latentsvm/src/lsvmc_featurepyramid.cpp
modules/latentsvm/src/lsvmc_function.cpp
modules/latentsvm/src/lsvmc_latentsvm.cpp
modules/latentsvm/src/lsvmc_latentsvmdetector.cpp
modules/latentsvm/src/lsvmc_matching.cpp
modules/latentsvm/src/lsvmc_parser.cpp
modules/latentsvm/src/lsvmc_routine.cpp
modules/latentsvm/test/test_latentsvmdetector_cascade.cpp
modules/latentsvm/test/test_main.cpp

This pull request is related to the issue
https://github.com/Itseez/opencv_contrib/issues/191
and another pull request on opencv_extra
https://github.com/Itseez/opencv_extra/pull/248
Now, the testing should work:
```sh
$ ./opencv_test_latentsvm 
OpenCV version: 3.0.0-dev
OpenCV VCS version: 3.0.0-beta-732-gd2da7dc
Build type: debug
CPU features: mmx sse sse2 sse3
OpenCL is disabled
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from Objdetect_LatentSVMDetectorCaskade_cpp
[ RUN      ] Objdetect_LatentSVMDetectorCaskade_cpp.regression
[       OK ] Objdetect_LatentSVMDetectorCaskade_cpp.regression (25694 ms)
[----------] 1 test from Objdetect_LatentSVMDetectorCaskade_cpp (25694 ms total)
[----------] Global test environment …
```

corrected the testing data path for latentsvm detector and some typos

---

modules/line_descriptor/include/opencv2/line_descriptor/descriptor.hpp
modules/line_descriptor/src/types.hpp

Reported and investigated in #125 
A developer has to say if this is the correct way to handle this in general.
fixes compilation error for vs2012, 2010, 2008, 2005 and maybe even prior versions
edited: also needed for vs2012

fix issue for vs versions which aren't standarized for the c99 standard

---

modules/line_descriptor/samples/compute_descriptors.cpp
modules/line_descriptor/samples/knn_matching.cpp
modules/line_descriptor/samples/lines_extraction.cpp
modules/line_descriptor/samples/lsd_lines_extraction.cpp
modules/line_descriptor/samples/matching.cpp
modules/line_descriptor/samples/radius_matching.cpp

Bug described here:
http://code.opencv.org/issues/3996
private.hpp should not be included in noninternal opencv code.
Removing is safe, compiled fine for me.

[fix issue #3996] delete private.hpp include in sample code

---

modules/line_descriptor/src/binary_descriptor.cpp

Could not compile binary_descriptor.cpp due to a variable 'near' which is defined in
"Windows Kits\8.1\Include\shared\minwindef.h:95"
```
#define near
```
Using Visual Studio 2013, found the same file and line in Windows Kit 8.0 for VS 2012 so it would probably fail there too due to this bug
renamed threshold variable since this belongs together
edit: tested with 2012, same error there

line_descriptor module fix vs2013 build

---

modules/xfeatures2d/doc/extra_features.rst
modules/xfeatures2d/doc/xfeatures2d.bib
modules/xfeatures2d/include/opencv2/xfeatures2d.hpp
modules/xfeatures2d/src/lucid.cpp
modules/xfeatures2d/test/test_features2d.cpp

Provides a free implementation of LUCID (Ziegler, Andrew, Eric Christiansen, David Kriegman, and Serge J. Belongie. "Locally uniform comparison image descriptor." In Advances in Neural Information Processing Systems, pp. 1-9. 2012.). LUCID should be much faster, while about as robust, or slightly less than, e.g. SURF or BRIEF. This is compatible with BFMatcher and the code was optimized for OpenCV with the help of gliese581h. This commit includes an exposed separable averaging blur function which is required for LUCID.

Locally uniform comparison image descriptor

---

modules/xfeatures2d/src/agast_score.cpp

- This small patch fix an obvious bug in AGAST scoring routine. The bug is due to accidental typo during transcript. AGAST is now verified and produce 1:1 same scoring as the original code.

Fix (typo) bug in AGAST scoring routines.

---

modules/xfeatures2d/include/opencv2/xfeatures2d.hpp
modules/xfeatures2d/perf/perf_latch.cpp
modules/xfeatures2d/src/latch.cpp
modules/xfeatures2d/test/test_features2d.cpp
modules/xfeatures2d/test/test_rotation_and_scale_invariance.cpp

Based on the following paper:
Gil Levi and Tal Hassner, "LATCH: Learned Arrangements of Three Patch Codes", arXiv preprint arXiv:1501.03719, 15 Jan. 2015
link:
http://arxiv.org/abs/1501.03719
Note: this code is submitted to the OpenCV CVPR15 challenge in the category of local image descriptors (specifically, binary descriptors)  - the Affine Covariant Regions Datasets. 
OpenCV challenge page:
http://opencv.org/opencv-vision-challenge.html
Affine Covariant Regions Datasets:
http://www.robots.ox.ac.uk/~vgg/research/affine/
Gil.

Adding the LATCH descriptor

---

modules/xfeatures2d/doc/xfeatures2d.bib
modules/xfeatures2d/include/opencv2/xfeatures2d.hpp
modules/xfeatures2d/perf/perf_daisy.cpp
modules/xfeatures2d/src/daisy.cpp
modules/xfeatures2d/test/test_features2d.cpp
modules/xfeatures2d/test/test_rotation_and_scale_invariance.cpp

This PR add DAISY [1] descriptor specialized for dense stereo problems. It is very fast for  wide-baseline [2] but can be used just as normal keypoint descriptor generated by some detector, with quite superior performance among other descriptors.
Some more infos:
* Implementation here is properly cited in respect with authors.
* Implementation is derived from latest author's original BSD licensed code available in public.
* Implementation booth follows opencv's coding standard and author original code performance.
* Implementation behave 1:1 numerically and by speed with original.
* Implementation pass well QA with very good rotation invariance properties.
* Implementation pass poorly QA for scale invariance (this is expected !)
* Implementation pass with excellent results real SfM …

Add DAISY descriptor for wide-baseline / keypoints.

---

modules/xfeatures2d/src/daisy.cpp

Went through QA tests and some important fixes are done for DAISY dense mode:
1. Norm should be "root of sums of squares" not "sums of rooted squares" !
2. Store and accumulate "sums of squares" into a double not in float, it may overflow !
3. Get rid of unused spurious function and variable from the code.
* Now opencv DAISY produce better results than original one (due to fix no. 2) !
On castle-p11 image set:
original: 4026934 (3d points)
**opencv**: 4179047 (3d points)

BugFix & Enhance DAISY.

---

modules/xobjdetect/src/acffeature.cpp

According to CartToPolar() function documentation, result angles could be in range (0..360). To prevent index overflow this check is important.

Bug fix for feature extraction

---

modules/xfeatures2d/src/daisy.cpp

After more QA tests, went to check if DAISY objects can be further queried with GetDescriptor( double x, double y) optional queries for going from coarse (precomputed descriptors at integer x,y locations) to fine grained double precision (x,y) query mode to find the perfect minima at subpixel level, thus gaining more precise depth at projected 3d location, and some outstanding and important fixes still need to be done for DAISY for this mode:
1. Normalization routines still suffers an outstanding bug ! Apologies that i did not saw it at #243 .
2. Do not aux_release() DAISY's objects in dense mode, thus locations (x,y) can be further queried !
3. For no .2 DAISY object will be destroyed by its destructor or by calling .release() over the object.
4. Remark: Our GetDescriptor() const works …

Bugfix Normalization / Enhance "float/double" mode queries for DAISY.

---

modules/text/src/erfilter.cpp
modules/text/src/ocr_tesseract.cpp

Tesseract API can handle correctly with RGB images (double-checked and it works).

Fix for Bug 4074. This seems to be just a typo-error.

---

modules/ximgproc/src/seeds.cpp

vs2010 does not know, ceil, floor, round and friends.
those are plain integer divisions, that do not need floor at all.
also see https://github.com/Itseez/opencv_contrib/pull/249

remove floor call

---

modules/surface_matching/src/ppf_match_3d.cpp

Fixes compiler error: "index variable in OpenMP 'for' statement must have signed integral type"

SurfaceMatching: OpenMP indices

---

modules/surface_matching/samples/ppf_load_match.cpp

Modified reported poses by constraining to the number of poses found - thus avoiding core dump.

Fix for Itseez/opencv_contrib/issues/278 - core dump in the case of no match(...) results.

---

modules/xfeatures2d/include/opencv2/xfeatures2d.hpp

also see http://code.opencv.org/issues/4470

wrap DAISY and LATCH to scripting

---

modules/line_descriptor/src/LSDDetector.cpp

I noticed the mask feature in LSDDetector::detect wasn't working so I looked at the code and realized that the keyCounter isn't decremented when an line is erased. This causes the loop to skip over a line which ends up screwing the mask feature. Adding the decrement fixed the problem.

Fixed bug in LSDDetector where mask doesn't remove all undesired lines

---

modules/text/src/ocr_hmm_decoder.cpp

Error (Assertion failed in resize) when passing very elongated contours to the recognition module.
See http://code.opencv.org/issues/4373

Fix bug #4373: 

---

modules/line_descriptor/src/binary_descriptor.cpp
modules/line_descriptor/src/bitops.hpp
modules/saliency/src/motionSaliencyBinWangApr2014.cpp
modules/tracking/src/tldDataset.cpp

MSVC had no implemenation for round() in earlier versions.
support for round() was probably first added with MSVC 2013.

make sources compile again on MSVC 2012 (VC 11) by adding round()

---

modules/tracking/include/opencv2/tracking/tracker.hpp
modules/tracking/src/trackerKCF.cpp

optimization

---

modules/optflow/src/deepflow.cpp

On my system DeepFlow sometimes produced invalid results. Proposed change seems to fix the problem.

Fixing uninitialized memory access problem in DeepFlow

---

modules/bioinspired/src/transientareassegmentationmodule.cpp
modules/line_descriptor/src/LSDDetector.cpp
modules/line_descriptor/src/binary_descriptor.cpp
modules/saliency/src/motionSaliencyBinWangApr2014.cpp
modules/xfeatures2d/src/daisy.cpp

These changes are from a set of patches I wrote in order to get my automated builds of [OpenCV3](http://github.com/menpo/conda-opencv3) working in Windows for Python 2.7 and 3.4. Some of the changes had already been fixed (logically, not literally) and thus I did not include them.
These changes are necessary to build the Python bindings *correctly* using the same compiler that Python is compiled with. I will maintain these patches regardless, so that my builds succeed, but thought it may be useful to give these back to the repository.
This PR includes a fix for #332.

MSVC python fixes

---

modules/aruco/include/opencv2/aruco.hpp
modules/aruco/src/aruco.cpp
modules/aruco/src/dictionary.cpp
modules/aruco/tutorials/aruco_detection/aruco_detection.markdown

This PR fixes several bugs in the aruco module:
- Set ```RETR_LIST``` in the ```findContours()``` function. This was an important bug that was producing many false negatives.
- Fix ```DICT_ARUCO_ORIGINAL``` error correction capacity.
- Set a better value for the parameter ```maxErroneousBitsInBorderRate```
I am preparing another PR with all the last comments/changes proposed by Prasanna.  However, I thought it was important to fix these bugs as soon as possible.

Fix several bugs in aruco module

---

modules/line_descriptor/src/draw.cpp

Fix bug that color is not chosen randomly when no color argument is supplied (default) as the documentation depicts and also is the case in drawLineMatches.

Draw keylines in random color by default as documentation depicts

---

modules/aruco/include/opencv2/aruco/dictionary.hpp
modules/aruco/src/dictionary.cpp
modules/aruco/src/predefined_dictionaries.hpp

also avoids manual memcpy: the predefined dictionary data is not
duplicated any more.

aruco: create dictionary from Mat instead of raw pointer

---

modules/datasetstools/README.md

the former datasetstools module got renamed to datasets, this is an obsolete remainder, which got [added again](https://github.com/Itseez/opencv_contrib/commit/38bdd6f3f41bd62295efd768f4626cadbf350a6b), with the readme's

remove datasetstools

---

modules/line_descriptor/include/opencv2/line_descriptor/descriptor.hpp

Useful since it is often needed to have the points from the keyline directly in the cv::Point2f format.

Added getters to the points of the KeyLine class

---

modules/dnn/include/opencv2/dnn/layer.hpp
modules/dnn/src/dnn.cpp

This way, we are certain not to depend on the order of static
variable initialization (LayerFactory::impl in dnn.cpp, vs. init
in init.cpp), which is causing bug #383.

opencv_dnn: replaced static LayerFactory::impl member with a static function that constructs the object on the first use (fix for bug #383)

---

modules/cvv/src/view/linematchview.cpp
modules/cvv/src/view/pointmatchview.cpp
modules/cvv/src/view/translationsmatchview.cpp

This re-creates a fix for a bug reported here: https://github.com/CVVisualPSETeam/CVVisual/issues/46. 
The original fix is show here: https://github.com/CVVisualPSETeam/CVVisual/commit/f7b1c68cb693167c6fd8656e91fab3d1da07d1bb
This fix applies the replacement of 10,50lu with (std::size_t)10,  (std::size_t)50 in the three files.
Replaces pull request #412

use better cast

---

modules/ximgproc/src/structured_edge_detection.cpp

On large images, edge detection can be rather long. I propose to parallelize the two for loops, which can drastically speed up this routine.

Parallelize edges detection

---

modules/cvv/src/stfl/stfl_engine.hpp

According to ISO C++03 14.2/4 it should use the template keyword to fix this => http://stackoverflow.com/a/3786481/724098.
Fixes https://github.com/Itseez/opencv_contrib/issues/272 and https://github.com/Itseez/opencv_contrib/issues/381

Fixes clang compilation error

---

modules/matlab/CMakeLists.txt

This commit aims to fix issue [#5032](https://github.com/Itseez/opencv/issues/5032) posted in opencv.
The missing line causes the following error message when compiling using VS2012:
fatal error C1083: Cannot open include file: 'opencv2/hal/defs.h': No such file or directory
which fails the compilation of matlab binding.

Fixed the issue #5032 posted in opencv

---

modules/dpm/src/dpm_feature.cpp

This commit fixed issue caused by missing round() in VS before 2013.
> According to [discussion on MSDN](https://social.msdn.microsoft.com/Forums/vstudio/en-US/260e04fc-dd05-4a96-8953-9c6ea1ad62fb/cant-find-stdround-in-cmath), ``round()`` function is not implemented in Microsoft Visual Studio before 2013.
The added lines decides whether applying the implementation according to the version of Visual Studio on one's machine. Thus, it suppress the error caused by the missing identifier.

Fixed issue caused by missing round() in VS before 2013

---

modules/face/include/opencv2/face.hpp
modules/face/include/opencv2/face/predict_collector.hpp
modules/face/src/eigen_faces.cpp
modules/face/src/facerec.cpp
modules/face/src/fisher_faces.cpp
modules/face/src/lbph_faces.cpp
modules/face/src/predict_collector.cpp

It's code that can close https://github.com/Itseez/opencv_contrib/issues/401 or can be used as suggestion to close this ticket

Custom handling of FaceRecognizer results

---

modules/tracking/include/opencv2/tracking/kalman_filters.hpp
modules/tracking/src/augmented_unscented_kalman.cpp
modules/tracking/src/unscented_kalman.cpp

For some applications it is useful to have an estimate of how uncertain
the specific variable is estimated. This could help to act accordingly
e.g. increase the measurement zone if the current estimate is very
uncertain.

Expose Error Cross-Covariance in Uncented Kalman Filters

---

modules/ximgproc/include/opencv2/ximgproc/edge_filter.hpp
modules/ximgproc/perf/perf_rolling_guidance_filter.cpp
modules/ximgproc/src/rolling_guidance_filter.cpp
modules/ximgproc/test/test_rolling_guidance_filter.cpp

Rolling guidance filter [1], along with its test code, is added.
Rolling guidance filter is the first of its kind for texture smoothing and edge preserving. It generates unique and practically very useful scale-aware local operators that remove texture under a novel scale measure, which cannot be achieved similarly by any prior filters. Rolling guidance filter also has many advantages - for example, its code is surprisingly simple and the running speed is very fast. It can benefit 3D geometry processing, feature extraction, image and video coding, and many other tasks in computer vision. The following is a simple example. The texture is removed efficiently and effectively by rolling guidance filter while main edges are preserved.
This method was accepted in ECCV 2014 as an oral …

Add rolling guidance filter

---

modules/rgbd/include/opencv2/rgbd.hpp
modules/rgbd/src/depth_registration.cpp
modules/rgbd/test/test_registration.cpp

Adding a new function to the RGBD module that implements registration (+tests). This is a common task when working with depth cameras and external RGB cameras. A user would have to find the intrinsics and extrinsics of the depth/rgb cameras separately.
Portions of this code were written by @vrabaud. Specifically, this runs 40-50% faster when the external camera doesn't have any distortion!
Here's an image of a raw depth map, and then the same depth map from the perspective of an external camera 40cm to the left of the depth camera:

Add RGBD registration function that registers depth to an external camera

---

modules/hdf/include/opencv2/hdf/hdf5.hpp
modules/hdf/src/hdf5.cpp

This PR avoid ambiguity of ```vector<int> X = vector<int>()``` versus ```int * X = NULL``` and by other default values. Other ambiguities are solved too. Some expansion with more explicit overloads  were required. The API described in the doc remain the very same.

BugFix: HDF Explicit overload functions. Avoid any ambiguities.

---

modules/sfm/src/libmv_capi.h

* ```SetCommandLineOption()``` may be in ```gflags::``` not ```google::``` namespace on newer version of libs. This simple patch allows the compiler to choose the appropriate namespace.

CompileFix: SetCommandLineOption may be in gflags:: not google::

---

modules/hdf/include/opencv2/hdf/hdf5.hpp
modules/hdf/src/hdf5.cpp

This PR address:
(1) Fix annoying ```close()``` issue when multiple datasets are opened at same time. Invoking ```close()``` **should not** alter other datasets status !
* It fix this scenario when two sets are opened at same time like below:
```
cv::Ptr<cv::hdf::HDF5> h5io = cv::hdf::open( "test1.h5" );
cv::Ptr<cv::hdf::HDF5> h5iw = cv::hdf::open( "test2.h5" );
h5io->close();
h5iw->close();
HDF5-DIAG: Error detected in HDF5 (1.8.15-patch1) thread 0:
#000: ../../src/H5F.c line 781 in H5Fclose(): invalid file identifier
major: Invalid arguments to routine
minor: Inappropriate type
```
*  First ```h5io->dsclose()``` instance force booth datasets to close due to code bug caused by superfluous call to HDF's internal *H5close()* that shutdown all open sessions: …

Bugfix & Enhance: Fix close() issue and add H5_GETCHUNKDIMS option.

---

modules/xfeatures2d/src/daisy.cpp

This PR address:
* Align numeric and performance indicators to original DAISY descriptor implementation.
(1) **BugFix:** Fix descriptor sampling in interpolated mode over convoluted collection of cubes. Sampling should be done *properly* over the convoluted cubes.
(2) **Enhancement**: Original, and actual ```compute_histograms()``` was ment to convert (h,y,x) to (y,x,h) for the descriptor sampler part. The ```(h,y,x)``` data order was used to perform inplace stacked convolutions *(first one time)* but then the ```(y,x,h)``` order is useful to do fast &memory aligned ```.ptr<float>(y,x,0)[h]``` like sampling for final descriptor *(at any time)*.
All my apologies for letting this latent issue so long, now DAISY should be at full and original quality.

BugFix: Fix & enhance DAISY sampling from convoluted cubes collection.

---

modules/xfeatures2d/src/cuda/surf.cu

Changed statements of type "#if __CUDA_ARCH__ >= 200" to
"#if defined __CUDA_ARCH__ && __CUDA_ARCH__ >= 200" in order to
avoid warnings about __CUDA_ARCH__ being undefined.

opencv_xfeatures2d: CUDA SURF: check if __CUDA_ARCH__ is defined before comparing it

---

modules/aruco/include/opencv2/aruco.hpp
modules/aruco/include/opencv2/aruco/charuco.hpp
modules/aruco/include/opencv2/aruco/dictionary.hpp
modules/aruco/samples/calibrate_camera.cpp
modules/aruco/samples/calibrate_camera_charuco.cpp
modules/aruco/samples/create_board.cpp
modules/aruco/samples/create_board_charuco.cpp
modules/aruco/samples/create_diamond.cpp
modules/aruco/samples/create_marker.cpp
modules/aruco/samples/detect_board.cpp
modules/aruco/samples/detect_board_charuco.cpp
modules/aruco/samples/detect_diamonds.cpp
modules/aruco/samples/detect_markers.cpp
modules/aruco/src/aruco.cpp
modules/aruco/src/charuco.cpp
modules/aruco/src/dictionary.cpp
modules/aruco/test/test_arucodetection.cpp
modules/aruco/test/test_boarddetection.cpp
modules/aruco/test/test_charucodetection.cpp

References and raw pointers are replaced by shared Ptrs to facilitate the generation of bindings and respective macros are added to enable the export.
Also fixes a copy problem observed while testing in Python where returned corners pointed to uninitialized memory.
Remaining problem: drawCharucoDiamond cannot be exported, because core is missing conversion functions for Vec4i.

Make aruco module exportable

---

modules/text/src/ocr_beamsearch_decoder.cpp
modules/text/src/ocr_hmm_decoder.cpp
modules/tracking/src/trackerKCF.cpp

Just a couple of commits adding simple casts that enable building of OpenCV 3.1 for Python 2.7 (which implicitly requires MSVC 2008).

MSVC 2008 Python fixes

---

modules/stereo/include/opencv2/stereo/matching.hpp

Existence of POPCNT is indicated by `CV_POPCNT`, not `CV_SSE4_1`. Fix for [https://github.com/Itseez/opencv_contrib/issues/513].

Use correct test for existence of CPU's POPCNT feature

---

modules/face/include/opencv2/face/predict_collector.hpp
modules/face/src/eigen_faces.cpp
modules/face/src/fisher_faces.cpp
modules/face/src/lbph_faces.cpp
modules/face/src/map_predict_collector.cpp
modules/face/src/mindist_predict_collector.cpp
modules/face/src/predict_collector.cpp
modules/face/src/stat_predict_collector.cpp
modules/face/src/std_predict_collector.cpp
modules/face/src/topn_predict_collector.cpp
modules/face/src/vector_predict_collector.cpp

In prolongation for issue #401 and PR #402
Ported from real project.
Improves previously provided #402 on following manner: filtering, unification, better class model, collector set for buffering set of result and for statistical threshold metric count. 
* PredictCollector base class remaked:
* templated `collect` method 
* `distanceKoef` to allow compare results of distinct algorithms
* `minThreshold` to allow filter out duplicates and keep only similar responses
* `excludeLabel` to allow cross check images in train set without checking with self
* `defaultFilter` that checks not just minthresh but maxthresh, guard label and state, applys `distanceKoef` to dist
* `filter` method for overload to provide cusom filtering logic (non-filtered predicts will not send to emit)
* filters can …

revised PredictCollector with set of implementations

---

modules/datasets/src/or_pascal.cpp

* check for null pointer dereference in parseNodeText()
* pass string references, not copies, to avoid 'dangling pointer' problem

datasets: make or_pascal fail gracefully on absent tags

---

modules/ximgproc/include/opencv2/ximgproc.hpp
modules/ximgproc/samples/niblack_thresholding.cpp
modules/ximgproc/src/niblack_thresholding.cpp

Fixes the issues raised by @mshabunin for #181 in the comments.
I updated the function code, added support for the other threshold types, and included the missing Doxygen comments in the header file.
I also expanded the sample demo with more trackbars to manipulate the thresholding parameters.

[XIMGPROC] Fix Niblack thresholding

---

modules/ximgproc/doc/ximgproc.bib
modules/ximgproc/include/opencv2/ximgproc/edge_filter.hpp
modules/ximgproc/include/opencv2/ximgproc/weighted_median_filter.hpp
modules/ximgproc/perf/perf_weighted_median_filter.cpp
modules/ximgproc/src/weighted_median_filter.cpp
modules/ximgproc/test/test_weighted_median_filter.cpp

Weighted median filter is widely used in various Computer Vision tasks, such as dense correspondence estimation, structure-texture separation and artifact removal. OpenCV has no very good implementation of this filter yet. 
What we provide here is an amazingly efficient implementation of weighted median filter considering both varying weights and order statistics. Our method was published in CVPR 2014 with a lot positive comments [1]. With several new data structures and algorithm modifications, it is 100+ times faster than the straightforward implementation while not sacrificing any accuracy and result quality. For QVGA size images, the performance is near realtime (~ 28 fps). 
For examples and detailed description, please visit …

Add weighted median filter

---

modules/aruco/include/opencv2/aruco.hpp
modules/aruco/src/aruco.cpp

For our application, we want to be able to make a number of uniquely-identifiable boards. I added an optional parameter to GridBoard::create to make this possible. Omitting the optional parameter reproduces existing behavior.

Add option to create GridBoard starting at user-specified marker id

---

modules/hdf/CMakeLists.txt
modules/hdf/src/hdf5.cpp

* This patch fixes hdf5 build for MSVC: https://github.com/Itseez/opencv_contrib/issues/546
* At the PR time the msvc buildbot lacked hdf5 lib thus build verification was not possible.

HDF: Fix MSVC build. (Issues #546, #497, #552).

---

modules/line_descriptor/perf/perf_matching.cpp
modules/line_descriptor/test/test_matcher_regression.cpp

modified:   modules/line_descriptor/perf/perf_matching.cpp
modified:   modules/line_descriptor/test/test_matcher_regression.cpp
If have observed two compiler errors when compiling with MS Visual Studio 2010. The 
reason is the function  pow( 2, i ) . The first argument should not be an integer but rather 
a float or double number. For this reason, I have replaced this function by  pow( 2.0, i ) ,
I have done this in two cases. The changes should not have any effect on the calculation.

Compiler error for VC10 removed

---

modules/xobjdetect/src/precomp.hpp

For some unknown reason xobjdetect.hpp is included twice.

One of 2 includes of xobjdetect.hpp removed

---

modules/tracking/src/trackerMedianFlow.cpp

Basic check on input image number of channels before calling cvtColor() in MedianFlow tracker

Basic fix - Channels check before cvtColor() function

---

modules/text/include/opencv2/text/erfilter.hpp
modules/text/samples/detect_er_chars.py
modules/text/samples/textdetection.py
modules/text/src/erfilter.cpp

first time I try to expose this code to Python. I did it by looking how other modules do it. Since ERStat is a kind of "low-level" struct with no much interest for final users I have wrapped all the process in a single function cv2.text.detectRegions() which returns a vector< vector<Point> > with all regions. (Similarly as MSER function does).
Provided sample script detect_er_chars.py works ok for me in Linux (Ubuntu 15). 
@vpisarev can you please take a look at it? thnkx!

ERFilter python bindings

---

modules/tracking/src/roiSelector.cpp

Added lower 8-bit comparison for key presses.
Fixes https://github.com/Itseez/opencv_contrib/issues/548

roiSelector platform dependency bug

---

modules/aruco/include/opencv2/aruco.hpp
modules/aruco/src/aruco.cpp

type should be OutputArray instead of OutputArrayOfArrays.
at<Vec3d> is one dimensional. (fixes debug assert)
fixes #574

aruco::estimatePoseSingleMarkers rvec/ tvec memory layout fixes

---

modules/tracking/src/roiSelector.cpp

- no ambiguity about last rect (complement #459 and bd20972847615184811553768e2d35b3c4c78451)
also [answer self request](https://github.com/Itseez/opencv_contrib/pull/539#commitcomment-16864422)

no trailing rect capture on escape

---

modules/ximgproc/samples/structured_edge_detection.cpp

The exact model location was missing and thus people do not know how to run the sample.
See https://github.com/Itseez/opencv_contrib/issues/654

add model location info

---

modules/ximgproc/src/seeds.cpp

This tiny patch allows to pass image in ```std::vector<cv::Mat>``` not only in ```cv::Mat``` thus enabling additional raster image layout for SEEDS superpixles algorithm. 
It is enhancement not bugfix, some reasons:
* It is useful e.g. for very large satellite imagery where stack of  2d ```cv::Mat``` rasterbands layout is much more memory friendly since read of large bands happen in sequential way and bands are just concatenated at the end into ```std::vector``` array.
* LSC and SLIC already handle booth ```std::vector<cv::Mat>``` not only in ```cv::Mat``` layouts, so expecting SEEDS too. In fact ```std::vector<cv::Mat>``` is the internal default schema for these two since each bands (it can be multispectral) represents a separate band matrix.

Allow vector<Mat> raster bands for SEEDS.

---

modules/cvv/CMakeLists.txt

Fixes #659
Precompiled headers, samples and tests did not use extra flags and libraries.

Fixed cvv module build

---

modules/tracking/include/opencv2/tracking/onlineMIL.hpp
modules/tracking/src/onlineMIL.cpp

Fixes #618 as suggested by @alalek

Fix sign() macro redefinition compile-time error

---

modules/aruco/include/opencv2/aruco.hpp
modules/aruco/src/aruco.cpp

fixes #692 
`rejectedCorners` should become a list of `np.array` in python, not a `np.array`

aruco: fixed rejectedCorners input type to generate correct python bindings

---

modules/xfeatures2d/src/sift.cpp

- with big images the int multiplication can overflow

fix overflow issue when computing diagonal

---

modules/text/src/erfilter.cpp

Variables p2-p9 are booleans, so combination of logical negation
and use of bit and/or operations in lines 2823 and 2824 results
in the following warning from gcc:
warning: suggest parentheses around operand of ‘!’ or change ‘&’
to ‘&&’ or ‘!’ to ‘~’ [-Wparentheses]

opencv_text: src/erfilter.cpp: replaced bit and/or with their logical counterparts

---

modules/xobjdetect/tools/waldboost_detector/CMakeLists.txt

resolves Itseez/opencv_contrib#497
Works on static builds, i.e. BUILD_SHARED_LIBS unset.
Non-static builds will fail for other irrelevant issues as before.

Fix building waldboost_detector with opencv_world

---

modules/xphoto/include/opencv2/xphoto/bm3d_image_denoising.hpp
modules/xphoto/samples/bm3d_image_denoising.cpp
modules/xphoto/src/bm3d_denoising_invoker_commons.hpp
modules/xphoto/src/bm3d_denoising_invoker_step1.hpp
modules/xphoto/src/bm3d_denoising_invoker_step2.hpp
modules/xphoto/src/bm3d_denoising_invoker_structs.hpp
modules/xphoto/src/bm3d_denoising_transforms.hpp
modules/xphoto/src/bm3d_denoising_transforms_1D.hpp
modules/xphoto/src/bm3d_denoising_transforms_2D.hpp
modules/xphoto/src/bm3d_denoising_transforms_haar.hpp
modules/xphoto/src/bm3d_image_denoising.cpp
modules/xphoto/src/kaiser_window.hpp
modules/xphoto/test/test_denoise_bm3d.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/301
- BM3D denoising algorithm (both first and second step):
http://www.cs.tut.fi/~foi/GCF-BM3D/BM3D_TIP_2007.pdf
- For performance reasons, only Haar transform is used.
TODO list:

BM3D noise reduction algorithm added

---

modules/aruco/samples/calibrate_camera.cpp
modules/xfeatures2d/samples/surf_matcher.cpp

resolves https://github.com/opencv/opencv/issues/7151
remove "false" as default value for args used with CommandLineParser::has()

fix CommandLineParser usage in samples

---

modules/ximgproc/include/opencv2/ximgproc.hpp
modules/ximgproc/src/thinning.cpp

New functionality to thin out blobs if desired. Used it to perform skeletization on segmented blobs in fingerprints, to find minutae (intersections). Example of application can be seen below:

add thinning

---

modules/ximgproc/doc/ximgproc.bib
modules/ximgproc/include/opencv2/ximgproc/edge_filter.hpp
modules/ximgproc/perf/perf_bilateral_texture_filter.cpp
modules/ximgproc/src/bilateral_texture_filter.cpp
modules/ximgproc/test/test_bilateral_texture_filter.cpp

_I sent a pull request few months ago (#550), but I upload again because of my git commit issues._
Bilateral texture filter [1], along with its test code, is added.
Bilateral texture filter is one of its kind for texture smoothing and edge preserving. This method blurs high-frequency texture area while preserving structural edges including object borders. It is done with a simple modification of the original bilateral filter. This method can be applicable to many other researches including feature extraction, depth image noise reduction and detail manipulation. This method was accepted in Siggraph 2014 as an oral presentation.
[1] Cho et al., Bilateral Texture Filtering, in proceedings of SIGGRAPH 2014

Add bilateral texture filter

---

modules/aruco/include/opencv2/aruco.hpp
modules/aruco/src/aruco.cpp
modules/aruco/test/test_boarddetection.cpp
modules/aruco/tutorials/aruco_board_detection/aruco_board_detection.markdown

resolves #744 
If `rvec` and `tvec` arguments are not empty then use them as initial guess for pose estimation.
In case of small amount of object-image point correspondences (as it was described in issue #744) it should help with correct pose estimation.

add initial guess for cv::aruco::estimatePoseBoard()

---

modules/hdf/src/hdf5.cpp

Close unused resource in dscreate and dsread. Otherwise, the file will not be close when close() is called.
See  the following for Delayed close, which is close dataset after exe terminate: https://www.hdfgroup.org/HDF5/doc/RM/RM_H5F.html#File-Close

Close unused resource in HDF, otherwise the file will not be closed after calling close (e.g. delayed close).

---

modules/tracking/src/trackerKCF.cpp

Description of the issue in https://github.com/Itseez/opencv_contrib/issues/640
To solve the problem I used the member variable roi to set the boundingBox variable  as follows:
boundingBox.x=(resizeImage?roi.x*2:roi.x)+(resizeImage?roi.width*2:roi.width)/4;
boundingBox.y=(resizeImage?roi.y*2:roi.y)+(resizeImage?roi.height*2:roi.height)/4;
boundingBox.width = (resizeImage?roi.width*2:roi.width)/2;
boundingBox.height = (resizeImage?roi.height*2:roi.height)/2;
It is worth noticing that roi width and hight are double the boundingBox size as roi is used as searching area for the next frame. 
I have moved the update bounding box code ouside the block if( frame > 0) because in the examples:
modules/tracking/samples/tracker.py
modules/tracking/samples/multitracker.py
the update function is called …

Fix KCF tracker when used in Python

---

modules/face/include/opencv2/face.hpp

This pull request adds virtual method `setThreshold` to `FaceRecognizer` class.
This method is already implemented in its child classes: `BasicFaceRecognizer` and `LBPHFaceRecognizer`.
Currently `FaceRecognizer` has only getter `getThreshold`.

Add threshold setter for FaceRecognizer class

---

modules/ccalib/src/omnidir.cpp

Fix wrong matrix allocation in omnidir::stereoCalibrate

---

.gitignore
modules/xfeatures2d/CMakeLists.txt
modules/xfeatures2d/cmake/download_vgg.cmake
modules/xfeatures2d/doc/xfeatures2d.bib
modules/xfeatures2d/include/opencv2/xfeatures2d.hpp
modules/xfeatures2d/perf/perf_vgg.cpp
modules/xfeatures2d/src/vgg.cpp
modules/xfeatures2d/test/test_features2d.cpp
modules/xfeatures2d/test/test_rotation_and_scale_invariance.cpp

This PR adds VGG descriptor (aka Visual Geometry Group, Oxford). It is the first descriptor trainable end to end by DLCO (Descriptor Learning Using Convex Optimisation) framework [1] . The descriptor is known as state-of-art, with only 48, 64, 80 or 120 dimensions can outperform any descriptor present in OpenCV.
Some infos:
* Implementation here is properly cited in respect with authors.
* Implementation use BSD in accord with original matlab DLCO framework [1].
* Implementation follows opencv's coding standard, and use parallelism.
* Implementation have flexible parameters that are documented and tested.
* Naming of **VGG** comes from acronym related to Oxford's *Visual Geometry Group*.
---------
Full DLCO trainer framework is with *work in progress* status and soon will be PR against …

Add VGG descriptor.

---

modules/sfm/CMakeLists.txt

SFM shouldn't fail overall cmake configuration when no gflags have been found

Fix for SFM module configuration when no gflags have been found

---

modules/aruco/src/aruco.cpp
modules/aruco/src/dictionary.cpp

aruco: correctly round pixels when computing marker size & fix assertion

---

modules/xfeatures2d/CMakeLists.txt
modules/xfeatures2d/cmake/download_boostdesc.cmake
modules/xfeatures2d/cmake/download_vgg.cmake
modules/xfeatures2d/doc/xfeatures2d.bib
modules/xfeatures2d/include/opencv2/xfeatures2d.hpp
modules/xfeatures2d/samples/export-boostdesc.py
modules/xfeatures2d/src/boostdesc.cpp
modules/xfeatures2d/src/vgg.cpp
modules/xfeatures2d/test/test_features2d.cpp
modules/xfeatures2d/test/test_rotation_and_scale_invariance.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/295
This PR adds BoostDesc descriptor described in [Learning Image Descriptors with Boosting](http://cvlab.epfl.ch/research/detect/binboost) [1] paper. The descriptor is known as state-of-art in hamming space with only 64, 128 or 256 bits can outperform any descriptor present in OpenCV.
The descriptor have several modes: **BGM, BGM_HARD, BGM_BILINEAR, BINBOOST_64, BINBOOST_128, BINBOOST_256** providing hamming space metric and **LBGM** is providing euclidian space floating-point metric at only 64 dimensions. BoostDesc descriptors pass rotation and scale invariance test with excellent results.
Some infos:
- Implementation here is properly cited in respect with authors.
- Implementation use BSD with permission from authors, …

Add BoostDesc Descriptor.

---

modules/phase_unwrapping/CMakeLists.txt
modules/phase_unwrapping/README.md
modules/phase_unwrapping/doc/phase_unwrapping.bib
modules/phase_unwrapping/include/opencv2/phase_unwrapping.hpp
modules/phase_unwrapping/include/opencv2/phase_unwrapping/histogramphaseunwrapping.hpp
modules/phase_unwrapping/include/opencv2/phase_unwrapping/phase_unwrapping.hpp
modules/phase_unwrapping/samples/unwrap.cpp
modules/phase_unwrapping/src/histogramphaseunwrapping.cpp
modules/phase_unwrapping/src/precomp.hpp
modules/phase_unwrapping/test/test_main.cpp
modules/phase_unwrapping/test/test_precomp.hpp
modules/phase_unwrapping/test/test_unwrapping.cpp
modules/phase_unwrapping/tutorials/phase_unwrapping.markdown
modules/phase_unwrapping/tutorials/unwrap/unwrap.markdown
modules/structured_light/CMakeLists.txt
modules/structured_light/doc/structured_light.bib
modules/structured_light/include/opencv2/structured_light/sinusoidalpattern.hpp
modules/structured_light/include/opencv2/structured_light/structured_light.hpp
modules/structured_light/samples/capsinpattern.cpp
modules/structured_light/samples/projectorcalibration.cpp
modules/structured_light/src/sinusoidalpattern.cpp
modules/structured_light/test/test_faps.cpp
modules/structured_light/tutorials/capturesinpattern/capturesinpattern.markdown
modules/structured_light/tutorials/structured_light.markdown

**Merge with opencv_extra: https://github.com/opencv/opencv_extra/pull/308**
First PR for GSoC2016. 
In the structured light API:
-Added new sinusoidal patterns. They are to be used in three different structured light algorithms: Fourier transform profilometry (FTP), phase-shifting profilometry (PSP), Fourier-assisted phase-shifting profilometry (FAPS). Those three methods, described in [1], rely on the computation of a phase map. So far, (wrapped) phase map are computed for FTP and PSP. To go further and compute phase map for FAPS, we need to unwrap FTP's phase maps. 
-A short example shows how to generate sinusoidal patterns. 
In the phase unwrapping API:
-Added a new 2D phase unwrapping algorithm. Implementation is based on [2]. It will be used to unwrap phase map from FTP, PSP and …

GSoC 2016: Structured light and phase unwrapping

---

modules/xfeatures2d/doc/xfeatures2d.bib
modules/xfeatures2d/include/opencv2/xfeatures2d.hpp
modules/xfeatures2d/samples/pct_signatures.cpp
modules/xfeatures2d/samples/pct_webcam.cpp
modules/xfeatures2d/src/pct_signatures.cpp
modules/xfeatures2d/src/pct_signatures/constants.hpp
modules/xfeatures2d/src/pct_signatures/distance.hpp
modules/xfeatures2d/src/pct_signatures/grayscale_bitmap.cpp
modules/xfeatures2d/src/pct_signatures/grayscale_bitmap.hpp
modules/xfeatures2d/src/pct_signatures/pct_clusterizer.cpp
modules/xfeatures2d/src/pct_signatures/pct_clusterizer.hpp
modules/xfeatures2d/src/pct_signatures/pct_sampler.cpp
modules/xfeatures2d/src/pct_signatures/pct_sampler.hpp
modules/xfeatures2d/src/pct_signatures/similarity.hpp
modules/xfeatures2d/src/pct_signatures_sqfd.cpp

References:
Martin Krulis, Jakub Lokoc, Tomas Skopal.
Efficient Extraction of Clustering-Based Feature Signatures Using GPU Architectures.
Multimedia tools and applications, 75(13), pp.: 8071–8103, Springer, ISSN: 1380-7501, 2016
http://link.springer.com/article/10.1007/s11042-015-2726-y
Christian Beecks, Merih Seran Uysal, Thomas Seidl.
Signature quadratic form distance.
In Proceedings of the ACM International Conference on Image and Video Retrieval, pages 438-445. ACM, 2010.
http://dl.acm.org/citation.cfm?id=1816105

Implementation of PCT signature extractor (updated commit)

---

modules/text/samples/detect_er_chars.py
modules/text/samples/textdetection.cpp
modules/text/samples/textdetection.py
modules/text/src/erfilter.cpp

and fixes to resolve #872
resolves #870

text: fix valgrind errors, minor changes

---

modules/xfeatures2d/include/opencv2/xfeatures2d.hpp
modules/xfeatures2d/src/lucid.cpp

the default values for LUCID feature and also a note about a color image required as an input.

Add default value for LUCID feature.

---

modules/freetype/src/freetype.cpp
modules/freetype/src/precomp.hpp

resolves https://github.com/opencv/opencv/issues/7886

build(freetype): move 3rdparty include files from precomp.hpp

---

modules/ximgproc/README.md
modules/ximgproc/doc/ximgproc.bib
modules/ximgproc/include/opencv2/ximgproc.hpp
modules/ximgproc/include/opencv2/ximgproc/deriche_filter.hpp
modules/ximgproc/samples/deriche_demo.cpp
modules/ximgproc/src/deriche_filter.cpp

Add deriche Filter implementation

Deriche Filter

---

modules/freetype/CMakeLists.txt

resolves #919 
Change CMakeFile.txt to use ${FREETYPE_LIBRARIES} ${HARFBUZZ_LIBRARIES}

Fix Opencv3.2 freetype module build failed in macOS10.12 #919

---

modules/freetype/include/opencv2/freetype.hpp
modules/freetype/src/freetype.cpp

This getTextSize() funtion helps to print more text, either on the same line or on another line.
To add getTextSize() function, some member variables are removed which are corresponding at putText() function's arguments. And a negative fontHeight must be asserted.
resolves #927 
Add getTextSize() function at freetype2 module similar to imgproc module.
In order to avoid confusion, refactoring is now required for a member variable which are hold the argument of putText (). 
Also, CV_Assert is required for cases where fontHeight is negative.(it is an invalid parameter).

Support getTextSize() to resolve issue #927

---

modules/aruco/src/aruco.cpp

resolves #939
The type checked when creating a board with the board_create python helper function is now CV_32F instead of CV_32FC3

Correcting wrong type check in Aruco Board creation

---

modules/tracking/test/test_aukf.cpp
modules/tracking/test/test_trackerOPE.cpp
modules/tracking/test/test_trackerSRE.cpp
modules/tracking/test/test_trackerTRE.cpp
modules/tracking/test/test_ukf.cpp

Tests was disabled because they are partially broken and take long time.

tracking:Disable all tests except kalman filter

---

modules/aruco/src/aruco.cpp

If `corners_mat` has `CV_32FC1` type, debug assertion failure occurs in `corners_mat.at<Point3f>`.
resolves #963

aruco::Board::create: fix debug assertion fail

---

modules/structured_light/src/graycodepattern.cpp

Changed masks from 3-channel RGB to grayscale. Since rest of the gray code patterns are single channel, the masks should be as well to make it simple to handle. 
For instance, if user adds the mask to the pattern vector as shown in [this](http://docs.opencv.org/3.2.0/db/d56/tutorial_capture_graycode_pattern.html) examples, there could be an issue if you try to run ```cv::cvtColor``` since you'll have to treat the masks individually since they are RGBs

Shadow masks changed to single channel

---

modules/surface_matching/include/opencv2/surface_matching/ppf_helpers.hpp
modules/surface_matching/samples/ppf_normal_computation.cpp
modules/surface_matching/src/ppf_helpers.cpp

Provides a python wrapper for `surface_matching.computeNormalsPC3d()` function.

Wrap `computeNormalsPC3d()` for python

---

modules/rgbd/src/depth_to_3d.cpp

resolves #1021 
The current implementation of `cv::rgbd::depthTo3d` would return CV_64F cloud if camera matrix argument is of type CV_64F and the depth map is non-float type.
However, since `cv::rgbd::warpFrameImpl` uses `Point2f` type for its points internally, it always expects CV_32F clouds. This results in a crash when camera matrix passed to `cv::rgbd::warpFrame` is of type CV_64F (the default data type in numpy).
This PR resolves the above mentioned issue...

Create a float-type cloud when depth map is not double-type

---

modules/surface_matching/include/opencv2/surface_matching/ppf_match_3d.hpp
modules/surface_matching/src/icp.cpp
modules/surface_matching/src/ppf_helpers.cpp
modules/surface_matching/src/ppf_match_3d.cpp

Seems like some variable is being casted at some point, but its step is used at another place without considering the cast. While C++ did not complain, Numpy had some issues with it. Perhaps around this line:
```.cpp
unsigned int ppfInd = corrInd*ppfStep;
```
Anyhow, it is always great to compact the code! And both Numpy and C++ are happy with this PR..

Compacted `(type)&var.data[i*step]` code into `var.ptr<type>(i)`

---

modules/tracking/src/gtrTracker.cpp

Added fix to GOTURN tracker, when creating dnn::Blob objects
Related issue #941 
OpenCV Q&A related question [here](http://answers.opencv.org/question/129140/goturn-tracker-error/)

Partial fix to GOTURN tracker

---

modules/xobjdetect/CMakeLists.txt

Currently if you are building OpenCV with contrib under ios, not as framework, that can leads to errors in config station of cmake.
I suppose it would be better if xobjdetect module tool will be optional with the BUILD_opencv_apps just like others tools in OpenCV
CMakeLists.txt in xobjdetect module. Add option not to build tool at xobjdetect module

Updated xobjdetect module CMakeLists.txt

---

modules/surface_matching/include/opencv2/surface_matching/ppf_match_3d.hpp
modules/surface_matching/src/ppf_match_3d.cpp

Fixes a reallocation issue that causes crashes rarely in Python wrapper (and possibly in C++ apps as well).
Edit: Seems the crashes were caused by OpenMP as in #1055, however, fixing the reallocation is still recommended.

Fix reallocation issue of raw poses vector

---

modules/surface_matching/src/ppf_match_3d.cpp

Fixes thread-unsafe insertion of raw poses

Thread-safe vector insertion while using OpenMP

---

modules/bgsegm/include/opencv2/bgsegm.hpp
modules/bgsegm/src/bgfg_subcnt.cpp

New background subtraction solution, very fast compared with mog2 or Knn. Good solution for low spec hardware. For more details, see: https://www.theimpossiblecode.com/blog/fastest-background-subtraction-opencv/

added BackgroundSubtractorCNT

---

modules/surface_matching/src/c_utils.hpp
modules/surface_matching/src/ppf_match_3d.cpp

When it comes to the angle between two vectors:
- angle in range [-pi/2, pi/2] can be given by: `asin(|a x b|)`
- angle in range [0, pi] can be given by either: `atan2(|a x b|, a dot b)` or `acos((a dot b) / (|a| |b|))`
However, knowing that the two vectors are either:
- Two normalized surface Normals, or
- One normalized surface vector and the normalized distance vector
then, expression could be simplified to just `acos(a dot b)`
In fact, the above expression is largely employed in many software.
Reduces the angle computation between two normalized vectors

Computation reduction of angle between two normalized vectors

---

modules/surface_matching/src/icp.cpp

The `minimizePointToPlaneMetric()` calls `cv::solve()` to solve a linear system consisting of six compoenents:
- Euler angles (3 components: roll, pitch, yaw) 
- Translation (three components: X, Y, Z)
In order to solve such linear system, there should be at least six points corresponding between the model and scene clouds. However, current implementation constrain minimal limit to only one point, which may cause crashes.
Sets a minimum limit of six-points correspondance in order to iterate ICP further

Stop ICP iterations before solver crashes due to underdetermined system

---

modules/optflow/perf/opencl/perf_dis_optflow.cpp
modules/optflow/src/dis_flow.cpp
modules/optflow/src/opencl/dis_flow.cl
modules/optflow/src/precomp.hpp
modules/optflow/test/ocl/test_dis.cpp

This patch adds ocl kernels to accelerate Dense Inverse Search
based optical flow algorithm, it acclerates 3 parts in the algorithm,
including 1) Structure tensor elements compute, 2) Patch inverse search,
3) Densification compute.
Perf and accuracy test are also added. The perf test shows it is 30%
faster than the current implementation.
Signed-off-by: Li Peng <peng.li@intel.com>

OCL implementation of DIS optical flow

---

modules/xfeatures2d/src/precomp.hpp
modules/xfeatures2d/src/sift.cpp

Using AVX2 to optimize SIFT descriptor / histogram calculation.
There are 2 things that I am not too sure about the change
* Should I copy the definition of USE_AVX2 to modules/xfeatures2d/src/precomp.hpp? I see that in the "opencv" repo, every #if CV_AVX2 is followed by if ( USE_AVX2 )
*  "#if 0 //CV_AVX2". Enabling that section will break opencv_test_xfeatures2d test. Descriptors are off by at most 1 because nrm2 is summed up in a different order because of AVX2.
Thanks,
Woody
Recreating PR because https://github.com/opencv/opencv_contrib/pull/1031 was bad.

Optimize SIFT with AVX2

---

modules/tracking/CMakeLists.txt

tldDetector.cpp:465:22: warning: declaration shadows a field of 'cv::tld::TLDDetector' [-Wshadow]

build: eliminate warnings

---

modules/ximgproc/src/lsc.cpp

* Guard access by invalid label value (-1 value), and resolve  #1048 .
resolves #1048

Fix LSC crash, guard against invalid label index.

---

modules/xfeatures2d/src/sift.cpp

- Parallelize calcDescriptors and buildDoGPyramid
- Simplify 2 lines of AVX2 instructions
I have also parallelized findScaleSpaceExtrema in my local branch. The thing is, that will change the order of the keypoints, and I think the tests will break. To get stable result, the keypoints have to be sorted. As that is more involved, I guess I will add that to a separate PR.

Parallelize SIFT

---

modules/ximgproc/src/lsc.cpp

Valgrind complains about jumps depending on uninitialized memory originating from `m_W`. And indeed, when the weights are computed in `FeatureSpaceWeights`, they are not initialized but immediately updated (see https://github.com/opencv/opencv_contrib/blob/ab5f5d6ca20014d1a0200176d4e3dacfd6c8762a/modules/ximgproc/src/lsc.cpp#L1071-L1074). This may be fixed by explicitly setting the `m_W` `Mat` to zero.

Fix uninitialized LSC weights

---

modules/sfm/cmake/FindGflags.cmake

resolves https://github.com/opencv/opencv/issues/8536
`set(... PARENT_SCOPE)` block at the end of the function *__find_exported_gflags* should not be executed in case of failure. Otherwise, following calls to `find_path(GFLAGS_INCLUDE_DIR ...)` will not work.

Fixed gflags search in Ubuntu

---

modules/tracking/include/opencv2/tracking/tracker.hpp
modules/tracking/src/tldTracker.hpp

`TrackerModel` is private stuff, so it's better to hide it.
Related: https://github.com/opencv/opencv/issues/8451

tracking: hide getModel() method in Tracker API

---

modules/ximgproc/src/slic.cpp

resolves #1109 
The variable `m_iterations` is never initialized. This probably leads to the undeterministic behaviour as described in #1109. Maybe @cbalint13 can confirm that `itrnum` is the correct value for `m_iterations`.

MSLIC: fix uninitialized iteration variable

---

modules/aruco/include/opencv2/aruco.hpp
modules/aruco/src/aruco.cpp

The aruco module allows to calibrate a camera using aruco markers using the `cv::aruco::calibrateCameraAruco` function, but not to calibrate a fisheye camera, or a stereo camera. This function simply internally uses `cv::aruco::getBoardObjectAndImagePoints` to extract the object points of the used aruco board for the calibration, and the OpenCV calibration function `cv::aruco::calibrateCameraAruco`.
By making the `cv::aruco::getBoardObjectAndImagePoints` function public it allows to use it with the other OpenCV calibrations function for fisheye cameras and stereo cameras.
- The `cv::aruco::getBoardObjectAndImagePoints` function is now public
- The arguments of this function has been reordered for consistency with `cv::calibrateCamera` and `cv::aruco::calibrateCameraAruco` functions

aruco: make public the getBoardObjectAndImagePoints function

---

modules/aruco/include/opencv2/aruco.hpp
modules/aruco/samples/calibrate_camera.cpp
modules/aruco/samples/calibrate_camera_charuco.cpp
modules/aruco/samples/detect_board.cpp
modules/aruco/samples/detect_board_charuco.cpp
modules/aruco/samples/detect_diamonds.cpp
modules/aruco/samples/detect_markers.cpp
modules/aruco/src/aruco.cpp
modules/aruco/test/test_boarddetection.cpp

The pullrequest is trying to do an extension of the "_doCornerRefinement_" parameter.
The idea is to use the contour-points to calculate the corners, in some cases more accurately.
1. Marker was detected.
2. Group and classify the contour-points according to their position.
3. Evaluates the direction it follows (clockwise or not). This is for saving the corners at the right position.
4. Fit a line who passes through the points (for each group).
5. Find the Points where the edge lines crosses.
6. Save the updated corners.

new corner refinement method :: using the contour-lines

---

modules/matlab/include/opencv2/matlab/bridge.hpp

fixing matlab wrapping

---

modules/dnn_modern/CMakeLists.txt

dnn_modern: include protubuf headers in cmake

---

modules/dnn/src/dnn.cpp

Before PR changes, every `setBlob` call reallocated network. Despite the same shapes.

Removed an extra reallocation of networks every setBlob call.

---

modules/dnn/src/layers/elementwise_layers.cpp

Improve efficiency of networks with ReLU layers by doing it in parallel.
Motivated by another activation layers. With PR changes, efficiency of AlexNet improves on ~9.4%, SqueezeNet v1.1 on ~1.7%, ResNet-50 on ~2.5%.

Enabled parallel computation of ReLU activation layer

---

modules/tracking/include/opencv2/tracking/tracker.hpp
modules/tracking/samples/kcf.cpp
modules/tracking/src/trackerKCF.cpp

Add confidence threshold to TrackerKCF

---

modules/ximgproc/src/anisodiff.cpp

Fixes red builds of the main repo on buildbot: http://pullrequest.opencv.org/buildbot/builders/precommit_opencl/builds/10843

ximgproc: fix warning in OCL related code on Windows platform

---

modules/dnn/src/layers/blank_layer.cpp
modules/dnn/src/layers/elementwise_layers.cpp
modules/dnn/src/layers/pooling_layer.cpp
modules/dnn/src/layers/reshape_layer.cpp

* Removed `allocate` method from Blank layer.
* Correct global average pooling output shape computation (in case of global pooling kernel size initializes properly in `finalize` that calls after all allocations).
* Removed a temporal Mat allocation from Reshape layer.

Fix changes with allocating memory outside layers.

---

modules/dnn/include/opencv2/dnn/all_layers.hpp
modules/dnn/src/layers/batch_norm_layer.cpp
modules/dnn/src/layers/blank_layer.cpp
modules/dnn/src/layers/elementwise_layers.cpp
modules/dnn/src/layers/max_unpooling_layer.cpp
modules/dnn/src/layers/scale_layer.cpp

BatchNorm, Scale, ReLU, Power and MaxUnpool layers parameters and flags are public. Motivated by another layers (Pooling, Conv, etc.).
Added initialization of names of Blank layers (Dropout, Identity).

Visibility of layer options

---

modules/text/CMakeLists.txt
modules/text/include/opencv2/text/erfilter.hpp
modules/text/include/opencv2/text/ocr.hpp
modules/text/src/erfilter.cpp

resolves #1188 
additional constructors were added to ERFilter class where the callback parameter has been replaced with the String designating the filename of the XML or YAML file with the classifier model (e.g. trained_classifierNM1.xml):
```
CV_EXPORTS_W  Ptr<ERFilter> createERFilterNM1(const String& filename,
int thresholdDelta = 1, float minArea = (float)0.00025,
float maxArea = (float)0.13, float minProbability = (float)0.4,
bool nonMaxSuppression = true,
float minProbabilityDiff = (float)0.1);
```
```
CV_EXPORTS_W Ptr<ERFilter> createERFilterNM2(const String& filename,
float minProbability = (float)0.3);
```
The example of calling these constructors from Java:
```
ERFilter erc1 = Text.createERFilterNM1(strClassifierNM1Path,16,0.00015f,0.13f,0.2f,true,0.1f);
ERFilter erc2 = …
```

Contrib.java.wrapper.fix.3.2

---

modules/text/include/opencv2/text/erfilter.hpp
modules/text/include/opencv2/text/ocr.hpp
modules/text/src/erfilter.cpp
modules/text/src/ocr_beamsearch_decoder.cpp
modules/text/src/ocr_hmm_decoder.cpp

resolves #1209 
Overload methods added to ensure usable java wrappers for the following classes of Text module:
1. ERFilter
2. OCRHMMDecoder
3. OCRBeamSearchDecoder
```
void detectRegions(InputArray image, const Ptr<ERFilter>& er_filter1, const Ptr<ERFilter>& er_filter2, CV_OUT std::vector<Rect> &groups_rects,
int method = ERGROUPING_ORIENTATION_HORIZ,
const String& filename = String(),
float minProbability = (float)0.5);
```
This method simplifies usage of ER method for text detection. Example of usage is below:
``` 
ERFilter erc1 = Text.createERFilterNM1(getClass().getResource(DEFAULT_CLASSIFIER_NM1).getPath(),8,0.00015f,0.15f,0.2f,true,0.1f);
ERFilter erc2 = Text.createERFilterNM2(getClass().getResource(DEFAULT_CLASSIFIER_NM2).getPath(), 0.5f);        
MatOfRect mor = new MatOfRect(); …
```

fix java wrappers for ERFilter, OCRHMMDecoder, OCRBeamSearchDecoder

---

modules/dnn/include/opencv2/dnn/all_layers.hpp
modules/dnn/include/opencv2/dnn/dnn.hpp
modules/dnn/src/layers/softmax_layer.cpp
modules/dnn/src/torch/torch_importer.cpp
modules/dnn/test/test_torch_importer.cpp

**Merge with**: https://github.com/opencv/opencv_extra/pull/341
Classification networks trained in Torch use criterion that expected output from `SoftMax` and espetially from `LogSoftMax`: https://github.com/torch/nn/blob/master/doc/criterion.md.
From my point of view, the most popular criterion for multi-class training is a [ClassNLLCriterion](https://github.com/torch/nn/blob/master/doc/criterion.md#classnllcriterion).
SoftMax and LogSoftMax are monotonic functions that means predicted class (maximum of output) is the same if we exclude these computations. Thanks for Torch framework it's so simple doing by [replace layer to nn.Identity](https://github.com/torch/nn/blob/master/doc/module.md#replacefunction) or [remove it at all](https://github.com/torch/nn/blob/65f42723f51d13683a431329452e …

Import SoftMax & LogSoftMax layers from Torch

---

modules/dnn/include/opencv2/dnn/dnn.hpp
modules/dnn/misc/python/pyopencv_dnn.hpp
modules/dnn/src/dnn.cpp
modules/dnn/src/layers/batch_norm_layer.cpp
modules/dnn/src/layers/blank_layer.cpp
modules/dnn/src/layers/elementwise_layers.cpp
modules/dnn/src/layers/reshape_layer.cpp
modules/dnn/src/layers/scale_layer.cpp
modules/dnn/src/layers/split_layer.cpp
modules/dnn/test/test_caffe_importer.cpp

Changed order of choosing blobs. Refactored code.
Now, the largest blobs are fitted in first order.
Memory consumption:
| Model | Before commit| PR#1105 |Mine|
| ------------- | ------------- |------------- |------------- |
|FCN-8s, 500x500x3|4.5GB|2.78GB|2.36GB|
Other models are without changes in terms of memory consumption.

Blobs reuse improvement

---

modules/matlab/CMakeLists.txt
modules/matlab/generator/build_info.py
modules/matlab/generator/cvmex.py
modules/matlab/generator/gen_matlab.py

CMake warning on missing Jinja2 package:
```
Traceback (most recent call last):
File "<string>", line 1, in <module>
ImportError: No module named jinja2
CMake Warning at /home/alalek/projects/opencv/contrib/modules/matlab/CMakeLists.txt:52 (message):
A required dependency of the matlab module (Python Jinja2 package) was not
found (installation command: "pip install jinja2").  Disabling Matlab
bindings...
```

matlab: require installation of Jinja2 Python package

---

modules/optflow/src/deepflow.cpp

resolves #1218 
The while loop in member function buildPyramid in deepflow.cpp terminated as a result of the break statement and never as a result of the termination criteria because the "i" variable in the while loop was never incremented.  The proposed change is to simply add a line that increments "i". Also, this is the first time I submit a pull request :).

Fixed while loop in buildPyramid in deepflow.cpp

---

modules/dnn/include/opencv2/dnn/dnn.hpp
modules/dnn/perf/perf_halide_net.cpp
modules/dnn/perf/perf_main.cpp
modules/dnn/samples/squeezenet_halide.cpp
modules/dnn/src/dnn.cpp
modules/dnn/src/halide_scheduler.cpp
modules/dnn/src/halide_scheduler.hpp
modules/dnn/src/layers/batch_norm_layer.cpp
modules/dnn/src/layers/concat_layer.cpp
modules/dnn/src/layers/convolution_layer.cpp
modules/dnn/src/layers/elementwise_layers.cpp
modules/dnn/src/layers/eltwise_layer.cpp
modules/dnn/src/layers/fully_connected_layer.cpp
modules/dnn/src/layers/lrn_layer.cpp
modules/dnn/src/layers/max_unpooling_layer.cpp
modules/dnn/src/layers/pooling_layer.cpp
modules/dnn/src/layers/scale_layer.cpp
modules/dnn/src/layers/softmax_layer.cpp
modules/dnn/src/layers/split_layer.cpp
modules/dnn/src/op_halide.cpp
modules/dnn/src/op_halide.hpp
modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_halide_layers.cpp
modules/dnn/test/test_halide_nets.cpp
modules/dnn/tutorials/tutorial_dnn_halide.markdown
modules/dnn/tutorials/tutorial_dnn_halide_scheduling.markdown

Layer | Covered all configurations | Test
---------------------------------|----------------------------|-----
Concat                           |          by channels (axis = 1)        | x
Convolution                      |                          x | x
Deconvolution                    |    no group factor    | x
(attachable) ReLU, TanH, Sigmoid, Abs, BNLL, Power, PReLU, Batch normalization, Scale | x | x
Element-wise addition, multiplication, maximum | x | x
Fully-connected | axis = 1 | x
LRN (across and within channels) | x | x
Maximum unpooling with indices support | x | x
Maximum pooling | x | x
Average pooling | only whole kernels, no padding | x
SoftMax | axis == 1, no spatial size more than 1x1 | x
Supported CPU only, float32 computations. No ahead-of-time compilation.
Added …

Added Halide backend support for deep learning layers

---

modules/dnn/src/layers/reshape_layer.cpp
modules/dnn/test/test_torch_importer.cpp

Added more complicated tests for Torch reshape layer in https://github.com/opencv/opencv_extra/pull/340 .
Fixed layer more carefully process `batch_size = 1` and cases with reshape without batching.

Fix reshape layer

---

modules/dnn/src/layers/reshape_layer.cpp
modules/dnn/test/test_layers.cpp

Added one more test for reshape layer. Made changes require for correct output shape of layer. Before PR `{1, 128, 4, 4}` with mask `{-1, 2048}` reshaped to `{1, 1, 2048}`.

Fix implicit mask case in reshape layer.

---

modules/dnn/include/opencv2/dnn/dnn.hpp
modules/dnn/perf/perf_halide_net.cpp
modules/dnn/src/dnn.cpp
modules/dnn/src/halide_scheduler.cpp
modules/dnn/src/layers/batch_norm_layer.cpp
modules/dnn/src/layers/concat_layer.cpp
modules/dnn/src/layers/convolution_layer.cpp
modules/dnn/src/layers/elementwise_layers.cpp
modules/dnn/src/layers/eltwise_layer.cpp
modules/dnn/src/layers/fully_connected_layer.cpp
modules/dnn/src/layers/lrn_layer.cpp
modules/dnn/src/layers/max_unpooling_layer.cpp
modules/dnn/src/layers/padding_layer.cpp
modules/dnn/src/layers/pooling_layer.cpp
modules/dnn/src/layers/softmax_layer.cpp
modules/dnn/src/op_halide.cpp
modules/dnn/src/op_halide.hpp
modules/dnn/test/test_halide_nets.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/345
Added OpenCL target for Halide.
One more interface function: `setPreferableTarget`. Default target is CPU.
| Model | Manual scheduling | Auto scheduling |
|---:|---:|---:|
| GoogLeNet | | 93.66ms|
| AlexNet | 49ms | 63ms (x0.77)|
|ResNet-50| 189ms| 190.32ms (x0.99) |
| SqueezeNet v1.1| 15.61ms | 20.05ms (x0.77)|
| Inception-5h | 89.52ms | 98.43ms (x0.90) |
| ENet @ 512x256 | 39.67ms | 42.12ms (x0.94)|
TODO list:

Halide OpenCL target for deep learning networks

---

modules/dnn/perf/perf_halide_net.cpp
modules/dnn/src/layers/batch_norm_layer.cpp
modules/dnn/src/layers/convolution_layer.cpp
modules/dnn/test/test_halide_nets.cpp

* Replaced `blobFromImage` in Halide tests.
* Removed Halide buffer allocation in Batch norm layer.
* Create fused weights in convolutional layer separately from origin weights. In example, deconvolution's `weightsMat` creates by `transpose` with data copying. So, in this PR added `clone` call in convolution layer in the same way.

Updated Halide pipelines

---

modules/text/README.md
modules/text/include/opencv2/text.hpp
modules/text/include/opencv2/text/erfilter.hpp
modules/text/include/opencv2/text/ocr.hpp
modules/text/samples/character_recognition.cpp
modules/text/samples/cropped_word_recognition.cpp
modules/text/samples/end_to_end_recognition.cpp
modules/text/samples/segmented_word_recognition.cpp
modules/text/samples/webcam_demo.cpp
modules/text/src/erfilter.cpp
modules/text/src/ocr_beamsearch_decoder.cpp

Fixes various spelling errors. Does OpenCV use British English or American English? There seems to be a mix of both in this module, although it primarily seems to tend towards British English. Not all spelling mistakes were fixed. There were a few words that I could not figure out, so I just left them for now.
I just found this module after spending a bunch of time working on my own to use with Tesseract 4, and I'm combining both of them now since there's things in here that I like, and I added some functionality that this module doesn't have. I should have a much bigger commit in a few days, but the spelling mistakes in the documentation were driving me insane.

fix spelling

---

modules/tracking/src/trackerKCF.cpp

resolves #1057
cast rect2d width and height to unsigned int for comparison

tracking: fix rounding error in trackerKCF

---

modules/text/doc/text.bib
modules/text/include/opencv2/text.hpp
modules/text/include/opencv2/text/erfilter.hpp
modules/text/include/opencv2/text/ocr.hpp

Update doc for text module:
insert bibliography
delete duplicate parameters in [CreateERFilterNM1](http://docs.opencv.org/master/da/d56/group__text__detect.html#ga34e6b32cc3db805155ab51dcd7bc61d5)
typo error in  OCR_LEVEL_TEXT_LINE , must be OCR_LEVEL_TEXTLINE [run method](http://docs.opencv.org/master/d7/ddc/classcv_1_1text_1_1OCRTesseract.html#a59190c76d19dfcac40fe011ff16c18d9)

Update doc for text module

---

modules/dnn_modern/CMakeLists.txt

This PR puts ```NO_STRICT``` definition for msvc environment to fix compile error on caffe.pb.h. It will fix #1289.

Fix error on msvc for dnn_modern

---

modules/ximgproc/src/selectivesearchsegmentation.cpp

ximgproc: eliminate per-pixel manual loop

---

modules/plot/include/opencv2/plot.hpp
modules/plot/src/plot.cpp
modules/tracking/samples/benchmark.cpp

related to  #1306
- fix wrong grid drawing when plot is not a square
- add `showGrid` and `showText` flags
- add `gridLinesNumber` parameter
- move `create` functions into `Plot2d` scope.

plot: make the module more customizable

---

modules/aruco/src/charuco.cpp

OpenCV => 3.3
Operating System / Platform => Any
Compiler => Any
Detailed description
CharUco Diamond detection detects too many false positives when the image resolution is high.
The reason is that a variable is that ```minRepDistance``` inside ```detectCharucoDiamond``` is growing in squared proportion to the image width, and then its value is squared again for the thresholding using ```closestCandidateDistance``` inside of ```refineDetectedMarkers```.
The images for testing this problem and the corresponding calibration files can be found in: 
https://github.com/opencv/opencv_contrib/issues/1331

making minRepDistance not quadratically dependent on the image size

---

modules/cnn_3dobj/CMakeLists.txt

WIthout this change, there will be the below cmake configuration error
``````
CMake Error at /home/ubuntu/ppa/opencv_contrib/modules/cnn_3dobj/CMakeLists.txt:39 (target_link_libraries):
The keyword signature for target_link_libraries has already been used with
the target "opencv_test_cnn_3dobj".  All uses of target_link_libraries with
a target must be either all-keyword or all-plain.
The uses of the keyword signature are here:
* /home/ubuntu/ppa/opencv/cmake/OpenCVUtils.cmake:911 (target_link_libraries)
``````

fix cmake configuration error

---

modules/text/src/precomp.hpp

resolves #1324
Added USING_STD_NAMESPACE macro since "-DUSING_STD_NAMESPACE is now needed for all of the tesseract library, not just for training."

Added USING_STD_NAMESPACE macro to text module

---

modules/tracking/src/trackerKCF.cpp

Updated the lambda coefficient to the one suggested in the original paper (http://www.robots.ox.ac.uk/~joao/publications/henriques_tpami2015.pdf, page 11, Table 2) which works (for me) better then the previous default one.

Updated default tracker parameters

---

modules/sfm/CMakeLists.txt

resolves #1353 
Adds required cmake path prefix to allow compilation under Windows MSVC (tested VS2017).
(resolves issue #1353 "sfm is disabled because subdirectory libmv not found")

Fix SFM compilation problem with Windows not finding libmv directory

---

modules/plot/include/opencv2/plot.hpp
modules/plot/samples/plot_demo.cpp
modules/plot/src/plot.cpp

#1278 #540 
added inverted orientation option
added example program
`Ptr<plot::Plot2d> plot = plot::Plot2d::create(data_x, data_y);`
`Ptr<plot::Plot2d> plot = plot::Plot2d::create(data_x, data_y,true);`

Update plot module

---

modules/xfeatures2d/src/sift.cpp

There is one point about this change that I am not sure - Are stable keypoints needed? If not, the sort can be removed
I tried using thread local storage, keeping a vector of keypoints per thread and merge them at the end. It turned out that using a mutex is faster (i7 6700K). It might be slower on computers with 8 physical cores.
Needs https://github.com/opencv/opencv/pull/8820

Multithreading findScaleSpaceExtremaComputer in SIFT

---

modules/aruco/tutorials/aruco_detection/aruco_detection.markdown

rvecs and tvecs should be of type std::vector<cv::Vec3d> as used in the detect_markers.cpp example. Otherwise an exception is thrown.

fixed typo in tutorial

---

modules/xfeatures2d/include/opencv2/xfeatures2d.hpp
modules/xfeatures2d/src/fast.cpp

Some applications only want to know if there are feature at specific locations. To fit these needs the FAST approach is extended in FASTForPointSet to recieve a vector of locations and calculates the FAST response on these positions.
If it is below the threshold, it will be removed from the list.

Enabled FAST feature detection on specific image locations

---

modules/xfeatures2d/include/opencv2/xfeatures2d.hpp
modules/xfeatures2d/src/pct_signatures.cpp
modules/xfeatures2d/src/pct_signatures/pct_sampler.cpp
modules/xfeatures2d/src/pct_signatures/pct_sampler.hpp
modules/xfeatures2d/src/pct_signatures/similarity.hpp

Typos in a property accessor caused incorrect exporting of the property in EmguCV (an OpenCV .NET wrapper).
Moreover, a similarity function typo has been fixed.

Fixed PCT Signature typos.

---

modules/matlab/CMakeLists.txt

- broken bindings generator
- broken conversion functions (uses non-supported cv::Mat types)
- other problems like missing/invalid conversion functions for Moments and other structs
related #1376

matlab: disable module by default

---

modules/saliency/include/opencv2/saliency/saliencySpecializedClasses.hpp
modules/saliency/samples/computeSaliency.cpp
modules/saliency/src/BING/CmFile.cpp
modules/saliency/src/BING/objectnessBING.cpp

resolves #1411
* make the BING path fail better, if the pretrained models are not present or found
* fix some minor assumptions in the sample, like the default trainingpath
* add some visualization for BING to the sample. (bonus, prev. output went entirely unsused.)
* all result files are written to a local "Results" dir. let's assume, "trainingpath" is read-only

saliency: improve BING handling

---

modules/tracking/src/multiTracker.cpp
modules/tracking/src/tldDetector.cpp
modules/tracking/src/tldDetector.hpp
modules/tracking/src/tldModel.cpp
modules/tracking/src/tldTracker.cpp
modules/tracking/src/tldTracker.hpp
modules/tracking/src/tldUtils.cpp
modules/tracking/src/tldUtils.hpp
modules/tracking/src/trackerMedianFlow.cpp
modules/tracking/src/tracking_utils.cpp
modules/tracking/src/tracking_utils.hpp
modules/tracking/test/test_trackers.cpp

Test configuration: Core i7 6700K, Ubuntu 16.04, GCC 7.2, CPU_BASELINE=SSE2
Speedup for TLD tracker:
|FPS|dudek|david|faceocc2|
|------|--------|-------|------------|
| old         | 13.6 | 25.2 | 12.2 | 
| after PR | 23.0 | 49.2 | 48.7 |
Speedup for Median flow tracker:
|FPS|dudek|david|faceocc2|
|------|--------|-------|------------|
| old         | 252.7 | 362.0 | 339.2| 
| after PR | 268.9 | 397.7 | 376.9 |

Improvement of the TLD tracker

---

modules/face/src/face_basic.cpp
modules/face/src/facerec.cpp
modules/face/src/lbph_faces.cpp
modules/face/test/test_loadsave.cpp

resolves #1267
* add a toplevel node to write(String) method, so it does the same as the save(String) method.
(nessecary to preserve compatibility with pretrained models from older versions)
* add a unit test for this
* minor correction to loading the threshold value, make sure to overwrite the default only IF there's a valid entry in the file (older versions might not have this)

face: add a toplevel node to write(String) method

---

modules/ximgproc/doc/ximgproc.bib
modules/ximgproc/include/opencv2/ximgproc.hpp
modules/ximgproc/include/opencv2/ximgproc/fourier_descriptors.hpp
modules/ximgproc/samples/fourier_descriptors_demo.cpp
modules/ximgproc/src/fourier_descriptors.cpp

Fourier descriptors for optimal curve matching

Fourier descriptors

---

modules/README.md
modules/ximgproc/README.md
modules/ximgproc/include/opencv2/ximgproc.hpp
modules/ximgproc/include/opencv2/ximgproc/ridgefilter.hpp
modules/ximgproc/perf/perf_ridge_detection_filter.cpp
modules/ximgproc/src/ridgedetectionfilter.cpp
modules/ximgproc/test/test_ridge_detection_filter.cpp

Also refer to PR #1081 . Continued from PR #1081 . Created different branch, added params,  added tests as well. 
Test data: https://github.com/opencv/opencv_extra/pull/401

Ridge Detection filter

---

modules/aruco/src/predefined_dictionaries.hpp

The description of aruco dictionaries format is incorrect: in fact the rotation number of the marker is before the marker's bytes themselves.
```c++
static unsigned char DICT_4X4_1000_BYTES[][4][2] =
```
In example above array of length 4 is rotations and array of length 2 is marker's bytes.

aruco: fix dictionaries format description

---

modules/xfeatures2d/src/freak.cpp

Similar to other descriptors, if the input image is colored, covert it silently to gray-level rather than terminating the execution

Convert to gray instead of throwing error

---

modules/surface_matching/include/opencv2/surface_matching/pose_3d.hpp
modules/surface_matching/include/opencv2/surface_matching/ppf_helpers.hpp
modules/surface_matching/include/opencv2/surface_matching/ppf_match_3d.hpp
modules/surface_matching/include/opencv2/surface_matching/t_hash_int.hpp
modules/surface_matching/src/c_utils.hpp
modules/surface_matching/src/hash_murmur64.hpp
modules/surface_matching/src/hash_murmur86.hpp
modules/surface_matching/src/icp.cpp
modules/surface_matching/src/pose_3d.cpp
modules/surface_matching/src/ppf_helpers.cpp
modules/surface_matching/src/ppf_match_3d.cpp
modules/surface_matching/src/t_hash_int.cpp

Recreated #1023 by @Sahloul:
Code rebased to latest master to handle merge conflicts
Original PR description
This is supposed to increase efficiency, readability, maintainability, and support Python bindings.
- Rewrites the surface matching module using `cv::Matx` and `cv::Vec`
- Utilize the OpenCV utilities to reduce the code size
- All `unsigned type` have been rewritten to `utype`
- Some complex expressions or resource intense functions are simplified
During the reduction process, no functionality was harmed, and all samples have been tested.

Re-write surface matching using vectors and matrices

---

modules/face/CMakeLists.txt
modules/img_hash/CMakeLists.txt
modules/plot/CMakeLists.txt
modules/ximgproc/CMakeLists.txt
modules/ximgproc/include/opencv2/ximgproc/fourier_descriptors.hpp
modules/xphoto/CMakeLists.txt

enable some modules for java

---

modules/ovis/CMakeLists.txt

Ubuntu 17.10 has OGRE 1.9 [package](https://packages.ubuntu.com/artful/libogre-1.9-dev) which is found by cmake but is not compatible with current module state.
I.e. it is a workaround to a problem with _FindOGRE.cmake_ script [provided](https://packages.ubuntu.com/artful/amd64/libogre-1.9-dev/filelist) in Ubuntu 17.10: the script does not check requested version.

ovis: fixed OGRE search in Ubuntu

---

modules/tracking/samples/multitracker.cpp

Some time ago, I provided a [PR](https://github.com/opencv/opencv_contrib/pull/1370/files) for fixing the runtime bug. But I unintentionally found the bug had not been solved thoroughly, the commited codes changed maybe when merged. I don't know why it happened. Could someone explain it? Thanks in advance.

Fix the runtime bug again.

---

modules/datasets/CMakeLists.txt
modules/datasets/samples/tr_chars_benchmark.cpp
modules/datasets/samples/tr_icdar_benchmark.cpp
modules/datasets/samples/tr_svt_benchmark.cpp

#1436
Makes opencv_text dependency OPTIONAL for opencv_datasets

Reduce dataset module dependencies

---

modules/ximgproc/src/fourier_descriptors.cpp

Remove unused code in FourierDescriptors
(see #1216 : ximgproc: rename global functions with generic names #1459)

Remove unused code

---

modules/xfeatures2d/src/affine_feature2d.cpp

Prevent crashing due to invalid co-variant matrix

Affine feature2D - Bug fix

---

modules/xfeatures2d/include/opencv2/xfeatures2d.hpp
modules/xfeatures2d/src/latch.cpp
modules/xfeatures2d/test/test_features2d.cpp

This PR is reworked change of LATCH descriptor offered by @ofirbb in PR #545
GaussianBlur made optional as suggested by @cbalint13 in PR #545 discussion
Provide ability to disable GaussianBlur of the source image for LATCH descriptor evaluation

GaussianBlur of the source image for LATCH descriptor made optional

---

modules/tracking/src/trackerKCF.cpp
modules/tracking/tutorials/tutorial_introduction_to_tracker.markdown

resolves #1472
* round the input bounding box to integer values
* override params in case of grayscale images (disable colornames feature)
* unrelated to the issue, but docs needed some correction

tracking:fix rounding and grayscale for KCF

---

modules/stereo/include/opencv2/stereo/matching.hpp
modules/stereo/src/stereo_binary_bm.cpp
modules/stereo/src/stereo_binary_sgbm.cpp

- uninitialized variable 'previous_size'
- incorrect Mat element access pattern via address arithmetic
- invalid 'for' range

stereo: fix crash

---

modules/ximgproc/src/disparity_filters.cpp

Recreated #739 by @LeoBras:
Updated `computeMSE`, `computeBadPixelPercent` and `getDisparityVis` to allow F32 handling as well
**Original PR description**
I noted this filter only treats CV_16S, while it converts everything to float and back to CV_16S to get the answer.
This pullrequest changes
Now it accepts both float and CV_16S (and probably future types).
I got really good results with float Disp_Matrices, and I felt no speed change.
If the disparity inputs are float, it only filters, if it's of other type, it converts to float before doing the math. It already did most of that, I just changed the place it does, so it cant treat other kinds of disp matrix.

Changing filter so it treats every type() of disparity Matrix.

---

modules/ccalib/src/randpattern.cpp
modules/dpm/src/dpm_feature.cpp

resolves #1490
Reverted calls back to linear resize for floating point matrices

Reverted calls back to linear resize for floating point matrices

---

modules/xfeatures2d/include/opencv2/xfeatures2d.hpp

resolves #1509
- Removes the unnecessary and problematic headers of `VGG::compute()`

`VGG::compute()` header is unnecessary and problematic for Python binder

---

modules/xphoto/src/learning_based_color_balance.cpp

resolves #1504
* try to load the filestorage in any case, then check result. this also handles the "wrong filename" case.
* the python based training tool writes double values for num_trees and num_tree_nodes. add a check for real values in the c++ code reading those, and convert (until the python filestorage is fixed)

xphoto: fix learning_based_color_balance.cpp

---

modules/xfeatures2d/src/lucid.cpp

RGBA are also colored images, but LUCID rejects them!
- Converts RGBA to RGB

LUCID - Support RGBA

---

modules/hdf/test/test_hdf5.cpp

[MatSize::operator()()][1] supports only 2-d matrices.
[1]: https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core/mat.inl.hpp#L1407
See http://pullrequest.opencv.org/buildbot/builders/precommit-contrib_linux64_no_opt/builds/10065/steps/test_hdf/logs/stdio

Fix the test case for hdf.

---

modules/bgsegm/CMakeLists.txt

resolves #1495
2nd attempt at #1496 
latest changes to java bindings  (great job !), allow to just add "java" to CMakeLists.txt now.
(the previously wrong inheritance got resolved) 
(couldn't re-use the old pr after closing & forced push)

bgsegm: add java bindings

---

modules/xfeatures2d/include/opencv2/xfeatures2d.hpp
modules/xfeatures2d/src/boostdesc.cpp
modules/xfeatures2d/src/vgg.cpp

For most of the features, default parameters are ok but VGG and Boost descriptor require to change the `scale_factor` according to the type of the feature used for the keypoints detection.
This allow to keep the compatibility with some code I have where a class wraps the feature that will be created by using the feature name:
```
cv::Ptr<cv::Feature2D> m_detector;
if (detectorName == "SIFT") {
m_detector = cv::xfeatures2d::SIFT::create();
} else if (detectorName == "SURF") {
m_detector  = cv::xfeatures2d::SURF::create();
} else if (detectorName == "VGG") {
m_detector = cv::xfeatures2d::VGG::create();
} //etc.
```

Add getter and setter for VGG and Boost descriptors

---

modules/text/src/ocr_tesseract.cpp

This statement interferes with regular logging on the client side
where the OpenCV library's outputs cannot be managed by the user
and forcefully print out in the client code. For instance, this
is observed when OpenCV is used as a python library where it is
expected to provide optional loggers instead of direct writes to
stdout.

Comment out direct print statements during tesseract run invocations

---

modules/xfeatures2d/doc/xfeatures2d.bib
modules/xfeatures2d/include/opencv2/xfeatures2d.hpp
modules/xfeatures2d/samples/gms_matcher.cpp
modules/xfeatures2d/src/gms.cpp
modules/xfeatures2d/test/test_gms_matcher.cpp

See also opencv/opencv#8741
Based on the code in repository JiawangBian/GMS-Feature-Matcher@4e64456 with the following changes:
- minor coding style refactoring
- add `thresholdFactor` parameter instead of the `#define`
- minor changes for Visual Studio warnings: `cvFloor` instead of `floor`, ...
Add also:
- a sample file `gms_matcher.cpp`
- `test_gms_matcher.cpp` to test the accuracy: test if the ratio of correct matches is below a threshold or not. The graffiti images and the corresponding ground truth homography matrices are used to determine if a match is correct or not. Note, the test depends also on the ORB features detection / descriptors extraction for the accuracy threshold.

Add GMS matching by JiaWang Bian into xfeatures2d module

---

modules/line_descriptor/src/binary_descriptor_matcher.cpp

resolves #1481
Fixed segmentation fault during search for nearest neighbor if provided descriptors are too far

Fixed segfault during matching of too far descriptors

---

modules/bioinspired/src/parvoretinafilter.hpp
modules/saliency/src/BING/kyheader.hpp
modules/sfm/src/io/io_bundler.h
modules/sfm/src/libmv_capi.h
modules/sfm/src/libmv_light/libmv/multiview/projection.h
modules/sfm/src/projection.cpp
modules/sfm/src/simple_pipeline.cpp
modules/sfm/src/triangulation.cpp
modules/sfm/test/scene.cpp
modules/tracking/src/trackerFeature.cpp
modules/ximgproc/src/edgeaware_filters_common.cpp
modules/ximgproc/src/edgeaware_filters_common.hpp
modules/ximgproc/src/guided_filter.cpp

- removed `register` specifier (deprecated in C++17)
- disabled _sfm_ module when configuring with cmake 2.x
- added `static` to several functions (_sfm_ module)
- infinite recursion in `Project` function (_sfm_ module)

Fixed several warnings produced by clang-6.0.0

---

modules/aruco/include/opencv2/aruco/dictionary.hpp

As described in the documentation https://docs.opencv.org/3.4.0/d5/dae/tutorial_aruco_detection.html the way to manually create custom dictionaries is to edit the `bytesList` property of the Dictionary object, typically using matrices generated via the `Dictionary::getByteListFromBits()` function.  In the current python bindings `bytesList` is read-only and `Dictionary::getByteListFromBits()` is not exported.
This PR makes it possible to manually create custom dictionaries by making `bytesList`, `markerSize`, and `maxCorrectionBits` writable and exporting `Dictionary::getByteListFromBits()` and `Dictionary::getBitsFromByteList()`.
In python creating a custom dictionary can now be accomplished via this pattern
```python
import numpy as np
from cv2.aruco import custom_dictionary, …
```

aurco: support custom dictionaries via python bindngs

---

modules/sfm/CMakeLists.txt

resolves #1122
If Ceres was built using `C++11`, then its headers contain `C++11` features, which breaks the `sfm` build if the features are not enabled in the compiler options.
(1) `CERES_WAS_COMPILED_WITH_CXX11` appears in the Ceres source code, but isn't set for my version of Ceres (1.13.0), so I've used `CERES_COMPILED_COMPONENTS`.

Build SFM with C++11 if Ceres was built with C++11

---

modules/tracking/include/opencv2/tracking/tracker.hpp
modules/tracking/samples/csrt.cpp
modules/tracking/samples/samples_utility.hpp
modules/tracking/src/trackerCSRT.cpp
modules/tracking/src/trackerCSRTScaleEstimation.cpp
modules/tracking/src/trackerCSRTScaleEstimation.hpp
modules/tracking/src/trackerCSRTSegmentation.cpp
modules/tracking/src/trackerCSRTSegmentation.hpp
modules/tracking/src/trackerCSRTUtils.cpp
modules/tracking/src/trackerCSRTUtils.hpp
modules/tracking/test/test_trackers.cpp

This pullrequest implements CSR-DCF tracker based on: 
http://prints.vicos.si/publications/355
http://prints.vicos.si/publications/files/355
I also have one question. In modules/tracking/src/trackerCSRTUtils.cpp, I've copied function:
``void computeHOG32D(const Mat &imageM, Mat &featM, const int sbin, const int pad_x, const int pad_y)
`` from modules/dpm/src/dpm_feature.cpp (with some minor changes). This was mostly used for testing purposes, to see whether this implementation of FHOG could be used in this tracker. I'm asking for your advice on how to go on about this. I'm assuming that a dependency for dpm module should be added to tracking module and then use that function directly.
```
force_builders=Mac
```

Implementation of CSR-DCF tracker

---

modules/tracking/src/gtrTracker.cpp

As the type of `targetPatch` and `searchPatch` is CV_8UC3, subtracting 128 from them will saturate all values smaller than 128 to zero.

fixed a bug in mean subtraction from target and search patches (GOTURN tracker)

---

modules/face/doc/face.bib
modules/face/include/opencv2/face.hpp
modules/face/include/opencv2/face/mace.hpp
modules/face/samples/CMakeLists.txt
modules/face/samples/mace_webcam.cpp
modules/face/src/mace.cpp
modules/face/test/test_mace.cpp

while the existing face recognition classes are good at identification, they cannot solve authentication of a single person, so this pr adds a MACE filter class, which also can be used for two-factor autentication with an additional passphrase.
based on:
"CANCELABLE BIOMETRIC FILTERS FOR FACE RECOGNITION", Marios Savvides, B.V.K. Vijaya Kumar and P.K. Khosla
and  https://code.google.com/archive/p/pam-face-authentication (GSOC 2009)
(got authors permission to re-license it)

face: add a mace filter for authentication

---

modules/ximgproc/include/opencv2/ximgproc/fast_hough_transform.hpp

Enabled export of `FastHoughTransform` and `HoughPoint2Line` to `opencv-contrib-python`.

Enabled FastHoughTransform export to python.

---

modules/face/src/mace.cpp

resolves #1580 
The constants rad1 and rad2 used in mace.cpp are conflicting with constants used in Windows Kits. Seems they are getting from precompiled headers. I fixed it by renaming constants, but probably there is some other reason for this problem.

renamed constants because they conflict with constants in Windows Kit

---

modules/surface_matching/src/ppf_helpers.cpp

In method "samplePCByQuantization" segmentation fault occurred using v3.4.1, in cases where input norm of some points was 0, elements 3,4,5 of the float array were left uninitialized leading to garbage variables which are used later to compute the ppf features and later giving incorrect hash values causing segmentation fault and the whole application crashes.

fixed bug when norm less than eps where float array elements were left uninitialized

---

modules/aruco/include/opencv2/aruco/dictionary.hpp
modules/aruco/src/dictionary.cpp

resolves #1586
use `cv::theRNG()` and `cv::setRNGSeed()` to make results reproducable.

aruco: add a user supplied random seed for creating custom dictionaries

---

modules/ovis/src/ovis.cpp

the latter assumes centered FOV, which is not the case

ovis: use frustum extents instead of setFrustumOffset

---

modules/cvv/src/controller/view_controller.cpp
modules/cvv/src/qtutil/filter/changed_pixels_widget.cpp
modules/cvv/src/qtutil/matchview/keypointmanagement.cpp
modules/cvv/src/qtutil/matchview/matchmanagement.cpp
modules/cvv/src/qtutil/matchview/matchscene.hpp
modules/cvv/src/qtutil/util.cpp
modules/cvv/src/qtutil/zoomableimage.cpp
modules/cvv/src/view/defaultfilterview.cpp
modules/cvv/src/view/dual_filter_view.cpp
modules/cvv/src/view/image_view.cpp
modules/cvv/src/view/linematchview.cpp
modules/cvv/src/view/linematchview.hpp
modules/cvv/src/view/pointmatchview.cpp
modules/cvv/src/view/pointmatchview.hpp
modules/cvv/src/view/singlefilterview.cpp
modules/cvv/src/view/translationsmatchview.cpp
modules/cvv/src/view/translationsmatchview.hpp

_cvv_ module:
* override-related warnings
* local functions without declaration
* complains about move semantics (_std::move_ prevents copy elision, `-Wpessimizing-move`)

Fixed several warnings produced by clang

---

modules/ovis/samples/aruco_ar_demo.py
modules/ovis/src/meshes.cpp
modules/ovis/src/ovis.cpp

logic was broken due to wrong default camera orientation
```
```

 ovis: correct and simplify coordinate system conversions

---

modules/face/src/facemarkAAM.cpp
modules/face/src/facemarkLBF.cpp

```
/build/precommit_opencl_linux/opencv_contrib/modules/face/src/facemarkAAM.cpp:106:10: warning: 'virtual bool cv::face::FacemarkAAMImpl::fitConfig(cv::InputArray, cv::InputArray, cv::OutputArrayOfArrays, const std::vector<cv::face::FacemarkAAM::Config>&)' can be marked override [-Wsuggest-override]
/build/precommit_opencl_linux/opencv_contrib/modules/face/src/facemarkAAM.cpp:110:10: warning: 'virtual bool cv::face::FacemarkAAMImpl::fit(cv::InputArray, cv::InputArray, cv::OutputArrayOfArrays)' can be marked override [-Wsuggest-override]
/build/precommit_opencl_linux/opencv_contrib/modules/face/src/facemarkLBF.cpp:118:10: warning: 'virtual bool cv::face::FacemarkLBFImpl::fit(cv::InputArray, cv::InputArray, cv::OutputArrayOfArrays)' can be marked override [-Wsuggest-override]
```

Add CV_OVERRIDE

---

modules/structured_light/include/opencv2/structured_light/graycodepattern.hpp
modules/structured_light/src/graycodepattern.cpp

resolves #1601
Mark projPix as output value for python bindings

Make getProjPixel output value available in python bindings

---

modules/dpm/CMakeLists.txt
modules/dpm/samples/cascade_detect_camera.cpp
modules/dpm/samples/cascade_detect_sequence.cpp
modules/dpm/src/dpm_cascade.cpp
modules/dpm/src/dpm_cascade.hpp
modules/dpm/src/dpm_feature.cpp
modules/dpm/src/dpm_feature.hpp

Coupled with opencv/opencv#11253
Some of functions in _dpm_ module can be optimized for parallel execution even if TBB is not available by using _cv::parallel_for_.

Cleanup old TBB-related guards

---

modules/face/CMakeLists.txt

swap opencv_tracking dependancy for opencv_video.
the Kazemi FaceMark training code uses `estimateRigidTransform()`, which is from opencv_video, not opencv_tracking.
this also removes the further dependancies on datasets, plot, dnn, flann, ml  for the face module.

face: fix dependancies

---

modules/ovis/CMakeLists.txt

with Ogre 1.11 OGRE_INCLUDE_DIRS has only one element and the '}'
corrupting the last include path becomes noticable.

ovis: remove superficial '}' from cmake

---

modules/aruco/src/aruco.cpp

Destroy `quads` to avoid a small memory leak when using `CORNER_REFINE_APRILTAG` with ArUco tag detection.

Fix memory leak when using CORNER_REFINE_APRILTAG and ArUco

---

modules/optflow/src/dis_flow.cpp

resolves #1355
Fixed coarse scale evaluation for DIS optical flow estimator to handle images with high width to height ratio

Fixed coarse scale evaluation for DIS optical flow estimator

---

modules/ovis/src/ovis.cpp

`near` is an illegal variable name on Windows (if `windef.h` is included),
because a macro with the same name is defined.
Someone else already put your rage into words, see
http://lolengine.net/blog/2011/3/4/fuck-you-microsoft-near-far-macros.

Rename `near` to `zNear`

---

modules/ximgproc/samples/fourier_descriptors_demo.cpp
modules/ximgproc/samples/fourier_descriptors_demo.py
modules/ximgproc/src/fourier_descriptors.cpp
modules/ximgproc/test/test_fourier_descriptors.cpp

Resolves http://answers.opencv.org/question/190847/how-to-use-opencv-contrib-python-fourierdescriptor/?comment=190856#post-id-190856
Add python sample
Add opencv test

remove bug when src is vector Point2i in FourierDescriptors

---

modules/xphoto/samples/learn_color_balance.py

resolves #1647
changed line 224 of learn_color_balance.py  to explicitly return a list, 
map() object returns an iterator, not a list, in python 3.
the fix,  list(map()) is still compatible with python 2

minor fix to allow learn_color_balance.py to work with python 3+

---

modules/ximgproc/src/sparse_match_interpolators.cpp

resolves #1653
Set initial inlier metric value to -FLT_MAX to ensure transform matrices initialization on first try regardless of first hypothesis inlier metric quality.

SparseToDense OpticalFlow fix

---

modules/line_descriptor/src/binary_descriptor.cpp

resolves #1437
Using mask with cv::line_descriptor::BinaryDescriptor to detect feature lines, will get wrong results.
```cpp
Ptr<BinaryDescriptor> bd = BinaryDescriptor::createBinaryDescriptor();
Mat mask = Mat::zeros(src.size(), CV_8UC1);  // With all 0 mask should get no line
vector<KeyLine> lines;
bd->detect(src, lines, mask);  // Still get some lines
Mat desc;
bd->compute(src, lines, desc);  // Get NULL pointer exception
```
* Change BinaryDescriptor::detectImpl method: erasing an element from std::vector in the loop, should not always move iterator forward, let `keyCounter++` only call on no-erasing. This change make `bd->detect(...)` get correct masked key lines.
* Change BinaryDescriptor::computeLBD method: `float* des_Vec = &keyLines[lineIDInScaleVec][0].descriptor.front();` get …

Bug fixes: using mask with BinaryDescriptor 

---

modules/rgbd/include/opencv2/rgbd/kinfu.hpp
modules/rgbd/samples/kinfu_demo.cpp
modules/rgbd/src/fast_icp.cpp
modules/rgbd/src/fast_icp.hpp
modules/rgbd/src/kinfu.cpp
modules/rgbd/src/kinfu_frame.cpp
modules/rgbd/src/kinfu_frame.hpp
modules/rgbd/src/odometry.cpp
modules/rgbd/src/tsdf.cpp
modules/rgbd/src/tsdf.hpp
modules/rgbd/test/test_kinfu.cpp

for this
- move Params struct out of class
- use static create instead of pimpl
- allow demo to be compiled without VIZ

kinfu: allow basic wrapping for bindings

---

modules/ovis/include/opencv2/ovis.hpp
modules/ovis/src/ovis.cpp

enables an ordered chain of full-screen post processing effects

ovis: add setCompositors method

---

modules/xphoto/samples/color_balance_benchmark.py

Python3 compatible. 
Python3 does not support accessing "map" like the "list".
Instead, it propose set to "the list".
I was test it work python3 and python2 also and it work smooth.

python3 compatible

---

modules/xfeatures2d/include/opencv2/xfeatures2d.hpp
modules/xfeatures2d/src/sift.cpp
modules/xfeatures2d/src/surf.cpp
modules/xfeatures2d/src/surf.cuda.cpp
modules/xfeatures2d/src/surf.ocl.cpp

resolves #1668
unless opencv was built with OPENCV_ENABLE_NONFREE, 
the following algorithms are disabled (throw a runtime error):
* SIFT
* SURF
* SURF_OCL
* SURF / CUDA
* xphoto/bm3d_image_denoising (this already existed)

xfeatures2d: throw CV_Error if not built with OPENCV_ENABLE_NONFREE

---

modules/xfeatures2d/perf/perf_latch.cpp
modules/xfeatures2d/perf/perf_surf.cpp
modules/xfeatures2d/perf/perf_surf.cuda.cpp
modules/xfeatures2d/perf/perf_surf.ocl.cpp
modules/xfeatures2d/test/test_detectors.cpp
modules/xfeatures2d/test/test_features2d.cpp
modules/xfeatures2d/test/test_keypoints.cpp
modules/xfeatures2d/test/test_rotation_and_scale_invariance.cpp
modules/xfeatures2d/test/test_surf.cuda.cpp
modules/xfeatures2d/test/test_surf.ocl.cpp

related #1682
[Failed nightly build](http://pullrequest.opencv.org/buildbot/builders/3_4-contrib_noOCL-lin64/builds/54).

xfeatures2d(test): disable tests with required non-free code

---

modules/text/src/erfilter.cpp

New debug assertion failed for some tests:
```
[ RUN      ] Text/Detection.sample/1, where GetParam() = ("text/scenetext01.jpg", true)
Image: text/scenetext01.jpg
Orientation: any
unknown file: Failure
C++ exception with description "OpenCV(3.4.2-dev) /build/precommit-contrib_linux64_no_opt/opencv/modules/core/include/opencv2/core/mat.inl.hpp:865: error: (-215:Assertion failed) res != 0 in function 'elemSize'
" thrown in the test body.
[  FAILED  ] Text/Detection.sample/1, where GetParam() = ("text/scenetext01.jpg", true) (9289 ms)
```

text: do not calculate mean for empty angles list

---

modules/line_descriptor/include/opencv2/line_descriptor/descriptor.hpp
modules/line_descriptor/misc/python/pyopencv_LSDDetector.hpp
samples/python2/lsd_lines_extraction.py

This PR adds python binding for [cv::line_descriptor::LSDDetector](https://docs.opencv.org/3.4.2/d1/dbd/classcv_1_1line__descriptor_1_1LSDDetector.html). A python example is attached as well.
**I don't use java so I don't know whether java binding works.**
Result:
```
foce_builders=linux,windows,macosx,docs
```

Add python binding and sample for LSD

---

modules/stereo/src/stereo_binary_bm.cpp
modules/stereo/src/stereo_binary_sgbm.cpp

I have fixed typos in census transform when using DENSE_CENSUS
stereo_binary_bm.cpp
stereo_binary_sgbm.cpp

fix densecensus when computing stereo matching

---

modules/xphoto/src/bm3d_image_denoising.cpp
modules/xphoto/test/test_denoise_bm3d.cpp

solves http://answers.opencv.org/question/196559/after-applying-cvxphotobm3ddenoising-imshow-is-giving-insertion-error/

Process InputOutputArray when BM3D_STEPALL is set

---

modules/optflow/CMakeLists.txt

"opencv2/flann/miniflann.hpp" is included (and used) in "sparse_matching_gpc.cpp". This patch adds the missing "opencv_flann" dependency declaration to the optflow CMakeLists.txt.

optflow: is depending on opencv_flann

---

modules/face/CMakeLists.txt
modules/face/src/trainFacemark.cpp

* face module now links to calib3d instead of video module
merge with https://github.com/opencv/opencv/pull/12248

replace internal usage of deprecated estimateRigidTransform in face

---

modules/optflow/src/sparse_matching_gpc.cpp

UMat::getMat(): Utilize `ACCESS_READ` instead of 0

---

modules/saliency/src/staticSaliency.cpp
modules/saliency/src/staticSaliencyFineGrained.cpp

resolves #1735
This PR corrects the function cv::saliency::staticSaliencyFineGrained::computeSaliencyImpl() by changing the output image depth (CV_8UC1 to CV_32F) and normalizing it by the max value (as in staticSaliencySpectralResidual). It also adds an assert in cv::saliency::staticSaliency::computeBinaryMap() in order to check the input image depth which must be CV_32F.

Correction for computeBinaryMap crash:

---

modules/hdf/src/hdf5.cpp
modules/hdf/test/test_hdf5.cpp
modules/text/include/opencv2/text/ocr.hpp
modules/text/src/ocr_hmm_decoder.cpp

**Main PR**: https://github.com/opencv/opencv/pull/12293
```
```

cleanup stl string replacement (drop implementation of cv::String)

---

modules/face/src/face_alignmentimpl.hpp
modules/face/src/getlandmarks.cpp
modules/face/src/trainFacemark.cpp

Memory layout of this structure is different, including `sizeof()`.
Fix [failed builds](http://pullrequest.opencv.org/buildbot/builders/3_4-contrib_noOCL-lin32/builds/111).

face: fix I/O for 'splitr' structure on 32-bit platforms

---

modules/bioinspired/src/templatebuffer.hpp
modules/face/include/opencv2/face/predict_collector.hpp
modules/face/src/facerec.cpp
modules/optflow/src/sparse_matching_gpc.cpp
modules/stereo/include/opencv2/stereo/descriptor.hpp
modules/structured_light/src/sinusoidalpattern.cpp
modules/text/src/ocr_tesseract.cpp

Preferably merge with opencv/opencv#12460
Minor change for coding style unification
- Utilized `CV_UNUSED(x);` instead of `(void)x;`

Utilize CV_UNUSED macro

---

modules/tracking/doc/tracking.bib
modules/tracking/include/opencv2/tracking/tracker.hpp
modules/tracking/src/trackerCSRT.cpp

resolves #1783, #1663
add a threshold to the CSRT tracker, so it can properly report "lost" in the update function.
(an empirical value of 0.035 was choosen, so all tests should still pass)
also add a bibref [from the author's github](https://github.com/alanlukezic/csr-dcf)

tracking: add a threshold to the CSRT tracker

---

modules/cvv/samples/cvv_demo.cpp

the pointer to [resolution](https://github.com/opencv/opencv_contrib/blob/3.4/modules/cvv/samples/cvv_demo.cpp#L43) wasn't freed if we return early, also replacing it with simple `width height` params removes a lot of clutter.

cvv: fix small memleak in demo

---

modules/ovis/include/opencv2/ovis.hpp
modules/ovis/src/ovis.cpp

not sure how API breaks are supposed to be handled in contrib, therefore SCENE_RENDER_FLOAT is a separate commit.
To review this change, take a look at:
https://ogrecave.github.io/ogre/api/latest/_compositor-_scripts.html#Format-1
with this change we get access to "rt0" of user defined content and format. Previously we hard-coded all of this via SCENE_RENDER_FLOAT.
```
```

ovis: add getCompositorTexture for reading custom render targets 

---

modules/rgbd/samples/kinfu_demo.cpp

```
/build/precommit_linux64/opencv_contrib/modules/rgbd/samples/kinfu_demo.cpp: In member function 'void DepthSource::updateParams(cv::kinfu::Params&)':
/build/precommit_linux64/opencv_contrib/modules/rgbd/samples/kinfu_demo.cpp:206:69: error: 'initUndistortRectifyMap' was not declared in this scope
undistortMap1, undistortMap2);
```

rgbd: fix build

---

modules/sfm/include/opencv2/sfm/simple_pipeline.hpp
modules/sfm/src/libmv_capi.h
modules/sfm/src/reconstruct.cpp
modules/xfeatures2d/include/opencv2/xfeatures2d.hpp

resolves #1812
SFM::reconstruct ignores value in K matrix K(1,1). The algorithm expects that K(0,0)==K(1,1). There are focal lengths which are normally the same for standard cameras. Cameras on mobile devices have focal length different (e.g. calibrations provided by ARCore or ARKit).
```
```

SFM - reconstruct decomposition of K matrix fix

---

modules/face/samples/facemark_demo_aam.cpp
modules/face/samples/facemark_demo_lbf.cpp
modules/face/samples/facemark_lbf_fitting.cpp
modules/stereo/samples/sample.cpp

Some of samples used copy/assignment operators of `CommandLineParser` object.
```
opencv=
```

Do not copy/assign CommandLineParser object

---

modules/sfm/include/opencv2/sfm/numeric.hpp

don't include internal 3rdparty header

sfm: fix public includes

---

modules/line_descriptor/src/binary_descriptor.cpp

resolves [#1859](https://github.com/opencv/opencv_contrib/issues/1859#issue-375463049)
This pullrequest changes the inner loop for removing useless OctaveSingleLines so that the index does not increase when an element erases thus preventing next element skipping.

Now when the element of the vector is removed j does not increase

---

modules/xfeatures2d/src/surf.cpp

Avoid keypoints from masked region.
relates https://github.com/opencv/opencv/pull/12827

xfeatures2d: validate keypoints mask for SURF

---

modules/ximgproc/doc/ximgproc.bib
modules/ximgproc/include/opencv2/ximgproc/edge_filter.hpp
modules/ximgproc/samples/colorize.cpp
modules/ximgproc/samples/disparity_filtering.cpp
modules/ximgproc/src/fbs_filter.cpp
modules/ximgproc/test/test_fbs_filter.cpp

Adds fixed version of the Fast Bilateral Solver (FBS) from master.
relates #1877
```
force_builders=linux,docs,windows,macosx
```

add fast bilateral solver from master

---

modules/ximgproc/doc/ximgproc.bib
modules/ximgproc/include/opencv2/ximgproc/edge_filter.hpp
modules/ximgproc/samples/disparity_filtering.cpp
modules/ximgproc/src/fbs_filter.cpp

- Fixes Fast Bilateral Solver (FBS) disparity filtering demo, i.e. FBS works now with `int16` disparity images
- Revises data type handling for both input and confidence map images
- Adds option to give command line arguments to FBS in addition to WLS
- Moves Fast Global Smoothing (FGS) pre-filtering from `fbs_filter.cpp` to `disparity_filtering.cpp` demo code
```
force_builders=linux,docs,windows,macosx
```

fbs disparity filtering fix

---

modules/cudalegacy/src/cuda/NCVHaarObjectDetection.cu
modules/cudalegacy/test/test_nvidia.cpp
modules/cudaobjdetect/src/cascadeclassifier.cpp
modules/cudaobjdetect/test/test_objdetect.cpp
modules/cudaoptflow/CMakeLists.txt
modules/cudaoptflow/perf/perf_optflow.cpp
modules/cudaoptflow/perf/perf_precomp.hpp
modules/cudaoptflow/test/test_optflow.cpp
modules/cudaoptflow/test/test_precomp.hpp

To fix CUDA build.
Related tests are disabled too.
```
```

CUDA: disable code using obsolete objdetect API

---

modules/ximgproc/test/test_fbs_filter.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/547
Fix test for Fast Bilateral Solver with a new reference image to be included in opencv_extra.
```
opencv_extra=3.4
```

fix fbs test with new reference image

---

modules/ximgproc/include/opencv2/ximgproc.hpp
modules/ximgproc/include/opencv2/ximgproc/color_match.hpp
modules/ximgproc/samples/color_match_template.cpp
modules/ximgproc/src/quaternion.cpp
modules/ximgproc/test/test_matchcolortemplate.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/534
Sangwine, S. J., Ell, T. A. and Moxey C. E., Vector Phase Correlation, Electronics Letters, 37(25), 6 December 2001, 1513-5. http://dx.doi.org/10.1049/el:20011035
T. A. Ell and S. J. Sangwine. Decomposition of 2D hypercomplex Fourier transforms into pairs of complex Fourier transforms. In Moncef Gabbouj and Pauli Kuosmanen, editors, Proceedings of EUSIPCO 2000, Tenth European Signal Processing Conference, volume II, pages 1061–1064, Tampere, Finland, 5–8 September 2000. European Association for Signal Processing
Quaternion Toolbox for Matlab r . [Online]. Software library, written by Stephen Sangwine and Nicolas Le Bihan. Available: http://qtfm.sourceforge.net/.

Search for matches between a color image patch and an input color image

---

modules/bioinspired/doc/retina.markdown

Hey there, completely new to `openCV` in general and to the `bioinspired` module in particular. I wanted to give this module a try with python and found that the example source code doesn't work with current openCV (that's 3.4.1 on my Fedora machine).  Apparently, there was a change in how a `Retina` object is created. I fixed the python source code correspondingly. I also changed the C++ source code in this doc file, although I think this needs further updating as there are more changes in the actual source code.

bioinspired: make initial python example in the doc work

---

modules/cvv/src/qtutil/filter/sobelfilterwidget.cpp

resolves #1914
Fix the build error. (obelfilterwidget.cpp: error: ‘FILTER_SCHARR’ was not declared in this scope)

Fix build error.

---

modules/sfm/src/libmv_light/libmv/simple_pipeline/bundle.cc

[http://ceres-solver.org/version_history.html#backward-incompatible-api-changes](http://ceres-solver.org/version_history.html#backward-incompatible-api-changes).

num_linear_solver_threads has been deprecated since Ceres 1.14.0

---

modules/ovis/src/ovis.cpp

[PF_DEPTH16 is just an alias introduced in OGRE 1.11.2](https://github.com/OGRECave/ogre/releases/tag/v1.11.2).

use PF_DEPTH for compatibility

---

modules/cvv/src/qtutil/filter/diffFilterWidget.cpp

Add `using namespace cv;` for successful building of the file: **diffFilterWidget.cpp**. 
Current error:
```
In member function ‘virtual void cvv::qtutil::DiffFilterFunction::applyFilter(cvv::qtutil::DiffFilterFunction::InputArray, cvv::qtutil::DiffFilterFunction::OutputArray) const’:
/home/hp/OpenCV_installation/opencv_contrib/modules/cvv/src/qtutil/filter/diffFilterWidget.cpp:72:44: error: ‘COLOR_BGR2HSV’ was not declared in this scope
cv::cvtColor(in.at(0).get(), originalHSV, COLOR_BGR2HSV);
```

Add namespace cv for successful build

---

modules/rgbd/include/opencv2/rgbd/linemod.hpp
modules/rgbd/src/linemod.cpp

<cut/>
draws features like:
(Model Based Training, Detection and Pose
Estimation of Texture-Less 3D Objects in
Heavily Cluttered Scenes, Figure 2)

linemod: add drawFeatures method

---

modules/cudacodec/src/cuvid_video_source.hpp
modules/cudacodec/src/frame_queue.hpp
modules/cudacodec/src/precomp.hpp
modules/cudacodec/src/video_decoder.hpp
modules/cudacodec/src/video_parser.hpp

nvidia video codec sdk need to be installed separately (https://developer.nvidia.com/nvidia-video-codec-sdk#Download)
only Samples/NvCodec/NvDecoder/nvcuvid.h and Samples/NvCodec/NvDecoder/cuviddec.h is necessary
resolves #1786
use nvcuvid.h instead of dynamic_nvcuvid.h when using cuda other than version 9
```
buildworker:Custom=linux-1,linux-2,linux-4
```

add cuda 10 support for opencv_nvcuvid

---

modules/aruco/include/opencv2/aruco.hpp
modules/aruco/tutorials/aruco_detection/aruco_detection.markdown

Fix minor typos in `DetectorParameters` struct doctring and in tutorial for aruco detection

Fix typo of ArUco Detector Parameter

---

modules/rgbd/include/opencv2/rgbd.hpp

resolves #1920
add python/java overloads for some `operator()` instances using `CV_WRAP_AS(apply)`
(main work is done there, and without those the algorithms can only be used from c++)

rgbd: fix python bindings

---

modules/cvv/src/impl/call.hpp
modules/face/src/facemarkLBF.cpp
modules/face/src/mace.cpp
modules/ovis/src/ovis.cpp
modules/rgbd/test/test_kinfu.cpp
modules/sfm/src/numeric.cpp
modules/videostab/src/global_motion.cpp
modules/ximgproc/samples/colorize.cpp
modules/ximgproc/test/test_sparse_match_interpolator.cpp

Merge with opencv/opencv#13705
Fixed warnings:
* `warning: local variable xxxxx will be copied despite being returned by name [-Wreturn-std-move]`
* `warning: explicitly defaulted copy assignment operator is implicitly deleted [-Wdefaulted-function-deleted]`

Fixed warnings produced by clang-9.0.0

---

modules/sfm/CMakeLists.txt
modules/sfm/src/libmv_light/libmv/correspondence/nRobustViewMatching.cc

This built correctly before because tests were run with the highgui module enabled.
The sfm module links against the features2d module, which brings in the highgui module as an optional target if enabled.
Through this path, imread was working correctly despite the file including the wrong header and not declaring its linking dependency.
Module `sfm` now explicitly links against module `imgcodecs`.
See related pull request: https://github.com/opencv/opencv/pull/13849

sfm module calls imread function, which is in imgcodecs module

---

modules/aruco/include/opencv2/aruco/dictionary.hpp
modules/ximgproc/include/opencv2/ximgproc/slic.hpp

relates https://github.com/opencv/opencv/pull/13945
```
```

(3.4) backport bindings generator from OpenCV 4.x

---

modules/ovis/src/ovis.cpp

ovis: allow disabling VSYNC - useful in multiwindow scenarios

---

modules/superres/include/opencv2/superres.hpp
modules/superres/src/btv_l1.cpp
modules/superres/src/btv_l1_cuda.cpp

Fix typos of cv::superres::SuperResolution's lambda parameter accessors.

fix cv::superres::SuperResolution::getLabmda/setLabmda typo

---

modules/ximgproc/src/disparity_filters.cpp

Fix support for `CV_32F` disparity maps in the DisparityWLSFilter.
If the disparity maps have the depth `CV_32F`, they are wls-filtered
in `DisparityWLSFilterImpl::filter` but the result is not saved in the
`OutputArray` of the method. Now, the result is copied to that array.

ximgproc: Fix support for CV_32F WLS Filter

---

modules/text/src/ocr_tesseract.cpp
modules/text/src/precomp.hpp

avoid broken min/max macros from tesseract headers
resolves #2084
replaces #2083

text: fix build on windows

---

modules/xfeatures2d/src/boostdesc.cpp

The bug was obvious, it is triggered when use_scale_orientation is set to false

fix rectifyPatch bug when patch orientation is not extracted

---

modules/optflow/src/rlofflow.cpp

(hopefully) resolves #2087
3 channel images are required for the (default) SR_CROSS RLOF optflow implementation, add a check for the sparse version similar [to the dense one here](https://github.com/opencv/opencv_contrib/blob/master/modules/optflow/src/rlofflow.cpp#L117)

optflow: add a check for 3 channel images for sparse RLOF

---

modules/videostab/include/opencv2/videostab/frame_source.hpp
modules/videostab/include/opencv2/videostab/global_motion.hpp
modules/videostab/include/opencv2/videostab/stabilizer.hpp
modules/videostab/samples/videostab.cpp
modules/videostab/src/global_motion.cpp
modules/videostab/src/stabilizer.cpp

This PR adds an additional video path parameter to modules/videostab/samples/videostab.cpp, which allows to mask features during video stabilization. 
The mask video must contain black (0 values) for parts, which are ignored during stabilization.

Added a parameter to mask features used for video stabilization

---

modules/face/include/opencv2/face.hpp

* Resolves Issue #1997
* Corrects the documentation for `FaceRecognizer::train()` function.
```python
FaceRecognizer::train(InputArrayOfArrays src, InputArray labels); 
```
The type `InputArray` can accept `vector<T>` or `Mat` types as mentioned here: https://docs.opencv.org/3.4/d4/d32/classcv_1_1__InputArray.html
Also added the way of using `Mat` for labels. (with type `CV_32SC1`)
```
force_builders=Docs
```

Incomplete sentence corrected. Resolves Issue #1997

---

modules/aruco/include/opencv2/aruco.hpp
modules/aruco/src/aruco.cpp
modules/aruco/test/test_arucodetection.cpp

i.e. it allows to detect white markers on a black background
<cut/>
Inverted Marker
Enclosed-Inverted Marker

added detection of inverted Markers, tests included

---

modules/face/include/opencv2/face/facemark.hpp
modules/face/include/opencv2/face/facemarkAAM.hpp
modules/face/src/face_alignmentimpl.hpp
modules/face/src/facemarkAAM.cpp
modules/face/src/facemarkLBF.cpp
modules/face/src/getlandmarks.cpp

The interface is not definite so that python binding won't work. 
resolves #1661  
landmark detector related files

Change the interface of face landmark

---

modules/ximgproc/src/selectivesearchsegmentation.cpp

resolves #2102
During one of the stages of selective search, the image is rotated 45 degrees and gradients are computed along the X and Y directions in the rotated image.  The gradient image is then rotated back to the original orientation and cropped to remove surrounding empty space, leaving it with the same shape as the original image.  However, the implementation of the crop will specify an ROI with negative x or y values if the image's native aspect ratio is too high or too low (basically, if the image is far from square).
This is because the bounding box of the rotated image is strictly bigger than the original image if the original is sufficiently close to square; but if the original is too "skinny", the bounding box of its rotation will be less tall or wide than the original.
The …

Fix 2102 redux

---

modules/aruco/include/opencv2/aruco.hpp
modules/bioinspired/include/opencv2/bioinspired/transientareassegmentationmodule.hpp
modules/bioinspired/src/transientareassegmentationmodule.cpp
modules/img_hash/include/opencv2/img_hash/block_mean_hash.hpp
modules/tracking/samples/tracker.cpp
modules/tracking/src/feature.cpp
modules/ximgproc/include/opencv2/ximgproc/edge_filter.hpp

This change is to remove redundant `return` doc, for a method with `void` type.
It prevents the success of https://github.com/opencv/opencv/pull/14667, and the corresponding error is [here](https://pullrequest.opencv.org/buildbot/builders/precommit_docs/builds/20631/steps/make%20doxygen/logs/warnings%20%282%29)
Please suggest if other text should be written instead.
```
opencv=javadoc
**WIP**
force_builders=Docs
```

docs: remove redundant `return`

---

modules/cudacodec/include/opencv2/cudacodec.hpp
modules/cudacodec/perf/perf_video.cpp
modules/cudacodec/src/cuvid_video_source.cpp
modules/cudacodec/src/ffmpeg_video_source.cpp
modules/cudacodec/src/video_decoder.cpp

Currently the latest codecs supported by the Nvidia Video Codec SDK are not supported by 
`cv::cudacodec::VideoReader`
<cut/>
For example creating a video reader with a hevc encoded file ('hevc.mkv') as below
`createVideoReader('hevc.mkv');`
results in the following assertion failure
`OpenCV(4.1.0-dev) cudacodec\src\video_decoder.cpp:70: error: (-215:Assertion failed) cudaVideoCodec_MPEG1 == _codec || cudaVideoCodec_MPEG2 == _codec || cudaVideoCodec_MPEG4 == _codec || cudaVideoCodec_VC1 == _codec || cudaVideoCodec_H264 == _codec || cudaVideoCodec_JPEG == _codec || cudaVideoCodec_YUV420== _codec || cudaVideoCodec_YV12 == _codec || cudaVideoCodec_NV12 == _codec || cudaVideoCodec_YUYV == _codec || cudaVideoCodec_UYVY == _codec in function 'cv::cudacodec::detail::VideoDecoder::create'` …

Add missing codecs to cv::cudacodec::VideoReader which uses Nvidia Video Codec SDK

---

modules/ovis/samples/aruco_ar_demo.cpp
modules/ovis/samples/ovis_demo.cpp

This PR adds samples for the __ovis__ module in _C++_.
These are directly translated from the existing _Python_ samples in the __ovis__ module.
OS: `5.1.7-arch1-1-ARCH`
Platform: `x86_64 GNU/Linux`
Compiler: `g++ (GCC) 8.3.0`
OpenCV: `4.1.0`

ovis: add cpp samples

---

modules/face/include/opencv2/face/facemark.hpp
modules/face/include/opencv2/face/facemarkAAM.hpp
modules/face/samples/landmarks_demo.py
modules/face/src/face_alignmentimpl.hpp
modules/face/src/facemarkAAM.cpp
modules/face/src/facemarkLBF.cpp
modules/face/src/getlandmarks.cpp

python binding for facemark::fit

---

modules/ovis/src/ovis.cpp

Fixes #2177 
1. Animations only played (/stopped) for one entity instance
- Fix: Save each animation **state** instead of the animation name
2. Build failure on the Windows platform because MSVC can't handle a static type conversion (#2177)
- Fix: Add explicit cast to *int* before the static type cast
@paroj

ovis, fixes: windows build, play multiple animations

---

modules/ovis/include/opencv2/ovis.hpp
modules/ovis/src/ovis.cpp

**This pullrequest changes**
This PR adds 2 overloaded methods setEntityLookAt, which add the option to make an entity look at another one or at a given point in world coordinates.
Also it adds a GetEntityPose method, which just was missing. It gives you the position and rotation of an entity.
Tested on:
OpenCV => 4.1.0
Operating System / Platform => Windows 10 64 Bit
Compiler => Visual Studio 2017

Added LookAt-methods and a GetPose-method for entities 

---

modules/bioinspired/src/opencl/retina_kernel.cl

resolves #2108
Also confirmed on Firefly-RK3399 (Aarch64 + Mali-T860) and Tinkerboard (Armv7 + Mali-T760)
```
OpenCL program build log: bioinspired/retina_kernel
Status -11: CL_BUILD_PROGRAM_FAILURE
<source>:299:9: error: call to 'fmax' is ambiguous
vstore4(fmax(magnoXonPixelResult, 0), 0, out_on);
^~~~
note: candidate function
note: candidate function
<source>:301:9: error: call to 'fmax' is ambiguous
vstore4(fmax(magnoXoffPixelResult, 0), 0, out_off);
^~~~
note: candidate function
note: candidate function
error: Compiler frontend failed (error code 59)
```

bioinspired: fix program build failure

---

modules/sfm/include/opencv2/sfm/io.hpp
modules/sfm/src/io.cpp

Change signature of the importReconstruction function to allow for
correct python bindings to be exported.
When using the python bindings exported for `cv2.sfm.importReconstruction`, a crash occurs because of a wrong array type like in #1675. After this change, the import works correctly.

Fix broken pyhton binding for sfm importReconstruction

---

modules/xphoto/src/inpainting.cpp

This should fix the wrong mask behaviour that was noticed in issue #2098

Correct the behaviour of inpainting mask usage

---

modules/ximgproc/src/sparse_match_interpolators.cpp

Enhance limitation in EdgeAwareInterpolation method. Maximal number of matches to be interpolated was restriced to SHORT_MAX and now will be INT_MAX by substituting (short) by (int) types of the label storages.

Enhance EdgeAwareInterpolation no. matches limitation

---

modules/hfs/CMakeLists.txt
modules/xfeatures2d/CMakeLists.txt

- removes noisy warning outside OpenCV
```
[ 40%] Building NVCC (Device) object modules/hfs/CMakeFiles/cuda_compile_1.dir/src/cuda/cuda_compile_1_generated_magnitude.cu.o
In file included from /usr/local/cuda/include/crt/common_functions.h:267:0,
from /usr/local/cuda/include/cuda_runtime.h:120,
from <command-line>:0:
/usr/local/cuda/include/crt/math_functions.h:8929:5: warning: "_GLIBCXX_HAVE_OBSOLETE_ISNAN" is not defined, evaluates to 0 [-Wundef]
#if _GLIBCXX_HAVE_OBSOLETE_ISNAN && !_GLIBCXX_NO_OBSOLETE_ISINF_ISNAN_DYNAMIC
^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
```
[ 48%] Building NVCC (Device) object modules/xfeatures2d/CMakeFiles/cuda_compile_1.dir/src/cuda/cuda_compile_1_generated_surf.cu.o
In file included from /usr/local/cuda/include/crt/common_functions.h:267:0,
from …
```

build: suppress noisy warning

---

modules/cudafeatures2d/include/opencv2/cudafeatures2d.hpp

#1597
Extend the interface of the ORB class by adding a getter and setter for the FastThreshold parameter
```
buildworker:Custom=linux-1,linux-2,linux-4
```

add get/set for FastThreshold

---

modules/text/CMakeLists.txt
modules/text/cmake/checks/tesseract_test.cpp
modules/text/cmake/init.cmake

resolves #1378
tesseract 4.x headers require C++11 (can't be used by OpenCV 3.4 without C++11)
Workaround:
- (OpenCV 3.4.x) build in C++11 mode: `cmake -DENABLE_CXX11=ON ...`
Debug:
- `cmake -DOPENCV_DEBUG_TESSERACT_BUILD=1 ...`
<cut/>
<details>
Error messages:
> In file included from /build/precommit_macosx/3.4/opencv_contrib/modules/text/src/ocr_tesseract.cpp:55:
In file included from /usr/local/Cellar/tesseract/4.1.0/include/tesseract/baseapi.h:26:
In file included from /usr/local/Cellar/tesseract/4.1.0/include/tesseract/apitypes.h:23:
/usr/local/Cellar/tesseract/4.1.0/include/tesseract/publictypes.h:33:1: error: unknown type name 'constexpr'
constexpr int kPointsPerInch = 72;
^
/usr/local/Cellar/tesseract/4.1.0/include/tesseract/publictypes.h:33:11: error: expected unqualified-id …

cmake: fix tesseract detection

---

modules/cudaoptflow/src/nvidiaOpticalFlow.cpp

Added lazy loading of nvcuda.dll. Removed unwanted driver APIs as the final output remains same and replaced driver API with runtime API wherever possible
resolves #2210 
```
docker_image:Custom=ubuntu-cuda:18.04
```

Lazy loading nvcuda.dll

---

modules/superres/src/super_resolution.cpp

Fixed bug in BTVL1 superres with UMat without OpenCL initialization

---

modules/aruco/src/dictionary.cpp

I want to lazy-load my opencv dll, to which I've added the aruco module.
But as these objects are constructed globally the system crashes as I've not loaded the DLL yet.
Moving them into the only place they're used, constructed statically, they construct on first use, and only after I've loaded the DLL.
Having statics hidden in a function isn't the greatest of solutions, but then I wouldn't have made them globals anyway :)

Moved aruco dictionary globals into getPredefinedDictionary to allow lazy-loading of the opencv DLL

---

modules/aruco/src/aruco.cpp
modules/aruco/test/test_arucodetection.cpp

Resolves #2055.
- An accuracy improvement of the white marker corners was achieved.
- A slight improvement for the precision of the black markers corners was achieved.
- The achieved accuracy remains stable along different noises.
This pull request modifies the contour selection for the white marker contours, by modifying the selection process of the corners and contour candidates, in __filterTooCloseCandidates_.
**candidatesSet**: The candidates and the contours are saved in a structur, for future improvements.

Inv marker contour detection improved

---

modules/text/include/opencv2/text/erfilter.hpp
modules/text/src/erfilter.cpp
modules/text/test/test_detection.cpp

text: remove NFA computation code due licensing conflict

---

modules/xphoto/src/simple_color_balance.cpp
modules/xphoto/test/simple_color_balance.cpp

resolves #2260 
Use `cv::calcHist` to fix the wrong implementation on calculating the histogram.
Replace the regression tests with some synthetic tests.

fix histogram calculation and add some tests for simpleWB

---

modules/optflow/samples/motempl.py

**1)**  Resolved Syntax error at
line 14: `def draw_motion_comp(vis, (x, y, w, h), angle, color):`
by adding 
line 14: `def draw_motion_comp(vis, rect, angle, color):`
line 15:     `x, y, w, h = rect`
**2)** Resolved `TypeError: integer argument expected, got float`
Changed division to return integer value instead of float value
by changing from `/` to `//`.
**3)** Released `cam`  variable in a proper way by adding `.release()` method by which program is exiting properly. If `.release()` method is not added, even after destroying all windows program is not get closed.

Updated samples/optflow/motempl.py file to solve 3 issues.

---

modules/cvv/src/impl/call.hpp
modules/face/src/facemarkLBF.cpp
modules/face/src/mace.cpp
modules/optflow/src/optical_flow_io.cpp
modules/ovis/src/ovis.cpp
modules/sfm/src/numeric.cpp
modules/ximgproc/test/test_sparse_match_interpolator.cpp

**Merge with**: https://github.com/opencv/opencv/pull/15573
backport https://github.com/opencv/opencv/pull/13705
backport https://github.com/opencv/opencv_contrib/pull/1980

(3.4) backport: Fixed warnings produced by clang-9.0.0

---

modules/ximgproc/src/l0_smooth.cpp

Adds two asserts to ensure that the input arguments 'lambda' and 'kappa' are valid.
If 'lambda <= 0' or 'kappa <= 1.0', the stop condition for the solver is never met because beta would not be increasing.

Ensures that l0smooth input arguments are valid

---

modules/xobjdetect/src/waldboost.cpp

resolves #457
resolves #633
This simply stops the training early if the number of positive samples becomes ≤ 1.

waldboost_detector train: avoid failed asserts while training by exiting early

---

modules/cudalegacy/include/opencv2/cudalegacy/NCVHaarObjectDetection.hpp

[cudalegacy] Fixes warnings about dereferencing type-punned pointer will break strict-aliasing rules
```
```

Fix compilation warnings about type-punned pointer

---

modules/cudalegacy/src/cuda/NCVHaarObjectDetection.cu

[cudalegacy] Possibly fix assertion to use something more meaningful `totalDetections <= totalMaxDetections`
```
```

[cudalegacy] Fix warnings about tautologies

---

modules/ovis/CMakeLists.txt

https://github.com/opencv/opencv_contrib/blob/83e98d2424bbe3854d4686dc6c9cf9a15812e8d7/modules/ovis/src/ovis.cpp#L638
The `create` API is introduced in commit [63906c8](https://github.com/OGRECave/ogre/commit/63906c8cc1b3d40d829296f1636a8e33bfe59b0d), so requires v1.11.5+.

require OGRE 1.11+ for ovis

---

modules/rgbd/src/plane.cpp
modules/rgbd/test/test_normal.cpp

Hi there!
This PR fixes memory corruption that happens when a block size is not a multiplier of the width and the height.
In this case, traversing over the grid goes beyond an allocated matrix and corrupts memory.
This change makes sure that grid cells are allocated for the remainder after dividing the width and/or the height by a block size, just like it's done here: https://github.com/deni64k/opencv_contrib/blob/7288772fdf973eef9e756c41bf775b7cc7c9aa4d/modules/rgbd/src/plane.cpp#L205.

Fix memory corruption in RgbdPlane

---

modules/xfeatures2d/src/sift.cpp

The buildDoGPyramid operation need not be performed unconditionally. In cases where it is not needed, both memory and speed performance can be improved
resolves #2238 
Build DoG Pyramid conditionally during detectAndCompute in SIFT

Build DoG Pyramid if useProvideKeypoints is false

---

modules/stereo/include/opencv2/stereo/descriptor.hpp

the c array stores the element of binary descriptor, and its all bits should be init as 0.
the origin code will only set lowest 1 byte of c[0] if nr_img is 1. However there will be even worse if nr_img large than 1, the higher element of array c will remain uninit.

fix memset error in CombinedDescriptor

---

modules/xphoto/doc/xphoto.bib
modules/xphoto/include/opencv2/xphoto/inpainting.hpp
modules/xphoto/src/inpainting.cpp
modules/xphoto/src/inpainting_fsr.impl.hpp
modules/xphoto/test/test_inpainting.cpp

This pullrequest adds the implementation of the high-quality extrapolation algorithm Rapid Frequency Selective Reconstruction (FSR) with two quality profiles. As one of its fields of applications is inpainting, it was added to the existing inpainting interface in xphoto.
Please refer to
https://github.com/opencv/opencv_contrib/files/3730212/inpainting_comparison.pdf
for a detailed description of the algorithm and a comparison to existing inpainting methods in OpenCV.
```
#disable_ipp=ON
```

new algorithm Rapid Frequency Selective Reconstruction (FSR) added

---

modules/cudaoptflow/src/nvidiaOpticalFlow.cpp

resolves #2333 
The PR places the CV_Error() inside the constructor of `NvidiaOpticalFlow_1_0`. 
<cut/>
```
```

corrected scope of CV_Error()

---

modules/ximgproc/samples/edgeboxes_demo.py
modules/ximgproc/test/test_edgeboxes.cpp

Adds a regression test for the edgeboxes implementation in ximgproc, and fixes up a Python sample for the edgeboxes which now works for returning scores.

Add test for ximgproc/edgeboxes and fix up Python sample to work with returning scores

---

modules/rgbd/include/opencv2/rgbd.hpp
modules/rgbd/misc/python/test/test_rgbd.py
modules/rgbd/src/odometry.cpp

resolves https://github.com/opencv/opencv_contrib/issues/2277
This PR adds constructors and destructors for RgbdPlane class.

Added constructors and destructors for RgbdPlane

---

modules/cudacodec/include/opencv2/cudacodec.hpp
modules/cudacodec/src/cuda/nv12_to_rgb.cu
modules/cudacodec/src/video_reader.cpp
modules/cudacodec/test/test_video.cpp

Makes the frame argument to cudacodec::VideoReader::nextFrame() optional when called from python.
```
```

Fix cudacodec::VideoReader::nextFrame python bindings

---

modules/aruco/src/aruco.cpp

(3.4) aruco: shift corner positions to the correct rotation (backport #2372)

---

modules/cudaoptflow/src/nvidiaOpticalFlow.cpp

Solve Gentoo bug : https://bugs.gentoo.org/701712
<cut/>
```
```

Fix compilation of optflow with cuda enable and cuda optflow disabled

---

modules/cudacodec/src/cuvid_video_source.cpp
modules/cudacodec/src/video_parser.cpp

Fixes memory leak when `cv::cudacodec::createVideoReader()` is called on a source which needs to be reconfigured during decoding.  This occurs when testing the [1920x1080.avi](https://github.com/opencv/opencv_contrib/blob/7011e1b1cb29af35d0bd526b0060f9d592c40133/modules/cudacodec/test/test_video.cpp#L125) because ffmpeg reports the height as 1080 but the decoder requires a height of 1088.  That said it could happen for different reasons during the decoding of other streams.
This fix is not ideal it would be much better to reconfigure the decoder as performed in the Nvidia [sample code](https://github.com/NVIDIA/video-sdk-samples/blob/aa3544dcea2fe63122e4feb83bf805ea40e58dbe/Samples/NvCodec/NvDecoder/NvDecoder.cpp#L193), however I don't think this is worth the effort because the whole of …

Patch cv::cudacodec::createVideoReader() memory leak

---

modules/cudaarithm/include/opencv2/cudaarithm.hpp

The python bindings for merge and split which are inconsistent with the format of existing cuda python functions.  Currently `cv.cuda.split()` does not return its output and the documentation for `cv.cuda.merge(`) is incorrect.
Tests to confirm this fix will be added to the opencv repository.
<cut/>
```
```

Fix cuda merge and split python bindings

---

modules/xfeatures2d/doc/xfeatures2d.bib
modules/xfeatures2d/include/opencv2/xfeatures2d.hpp
modules/xfeatures2d/src/logos.cpp
modules/xfeatures2d/src/logos/Logos.cpp
modules/xfeatures2d/src/logos/Logos.hpp
modules/xfeatures2d/src/logos/Match.cpp
modules/xfeatures2d/src/logos/Match.hpp
modules/xfeatures2d/src/logos/Point.cpp
modules/xfeatures2d/src/logos/Point.hpp
modules/xfeatures2d/src/logos/PointPair.cpp
modules/xfeatures2d/src/logos/PointPair.hpp
modules/xfeatures2d/test/test_logos_matcher.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/690
Original code: [LOGOS](https://github.com/short-circuitt/LOGOS)
Regression tests consist in comparing the output of the current implementation w.r.t. the original Matlab code, see opencv/opencv_extra#690
Note:
- pointers are used as in the original code. I did not manage to use `cv::Ptr` successfully (got some memory leak issues)
- returned distance for the matches will be zero
- LOGOS parameters cannot be set
- parallelization could be used
- main changes should be code convention and float type instead of double
---
This method requires to build a BoW for a considered image dataset. Something like:
```
std::string pattern = "Oxford City Centre/Images/*.jpg";
vector<String> results;
glob(pattern, results); …
```

Add LOGOS features matching strategy

---

modules/rapid/CMakeLists.txt
modules/rapid/doc/rapid.bib
modules/rapid/include/opencv2/rapid.hpp
modules/rapid/src/precomp.hpp
modules/rapid/src/rapid.cpp
modules/rapid/test/test_main.cpp
modules/rapid/test/test_precomp.hpp

the core algorithm is in `rapid::rapid()`. However most of the internal functions were also exposed to allow different variations of this algorithm.
E.g. this can suit as base for more recent variants like:
https://www.youtube.com/watch?v=trX_AEn2lp0

add rapid module for silhouette based 3D object tracking

---

modules/dnn_superres/CMakeLists.txt
modules/dnn_superres/include/opencv2/dnn_superres.hpp
modules/dnn_superres/samples/dnn_superres_benchmark_quality.cpp
modules/dnn_superres/samples/dnn_superres_benchmark_time.cpp
modules/ximgproc/samples/colorize.cpp
modules/ximgproc/src/fbs_filter.cpp

Fix build of `dnn_superres` module without the `quality` module.
Fix some warnings reported by VS2017.
Remove `opencv_datasets` dependy.

Fix build of dnn_superres module without the quality module

---

modules/xphoto/include/opencv2/xphoto/tonemap.hpp
modules/xphoto/test/test_hdr.cpp

The order of the arguments of `createTonemapDurand` is different between hpp and cpp. 
The test added by this pull request fails on the master branch.
I fixed it according to the order of `cv::bilateralFilter` arguments. (sigma_color first) 
https://github.com/opencv/opencv_contrib/blob/master/modules/xphoto/include/opencv2/xphoto/tonemap.hpp#L53
```cpp
CV_EXPORTS_W Ptr<TonemapDurand>
createTonemapDurand(float gamma = 1.0f, float contrast = 4.0f, float saturation = 1.0f, float sigma_space = 2.0f, float sigma_color = 2.0f);
```
https://github.com/opencv/opencv_contrib/blob/master/modules/xphoto/src/tonemap.cpp#L116
```cpp
Ptr<TonemapDurand> createTonemapDurand(float gamma, float contrast, float saturation, float sigma_color, float sigma_space)
```

Fix order of createTonemapDurand arguments

---

modules/rgbd/src/tsdf.cpp

resolves #2404 
OCL version of TSDF's `fetchPointsNormals()` fixed for the case when there's no data in the volume

Fixed KinFu getCloud() at empty volume

---

modules/surface_matching/src/icp.cpp
modules/surface_matching/src/ppf_helpers.cpp

Fixes https://github.com/opencv/opencv_contrib/issues/2339
This PR tries to fix the out of range error that occurs due to `numSamples=0` and hence `sampleStep` becomes `INT_MIN` which is the root cause of all the errors.

Fixes error occurs in cv::ppf_match_3d::ICP::registerModelToScene()

---

modules/tracking/src/multiTracker.cpp

Minor change in the post-detect loop of `MultiTracker_TLD` to delay early exit in case of low Sc value in NN classification.
Instead of early exit, it continues for all trackers. Return value is `false` in case of failure for all trackers, not just one tracker.

[Multi TLD] Removed early exit in case of sampling failure

---

modules/cudaoptflow/src/nvidiaOpticalFlow.cpp

m_cuContext is the CUDA runtime context which we fetch and use and we should not be destroying it by calling cudaDeviceReset(). There are many applications which pipeline NVIDIA-Optical-Flow as an intermediate block and say if any block after it uses m_cuContext then that blocks will fail because the context they were using was destroyed without their knowledge.
<cut/>
```
```

NVOF-Cuda Bug Fix. Should not reset runtime context

---

modules/ccalib/include/opencv2/ccalib/omnidir.hpp
modules/ccalib/src/omnidir.cpp

Add overload method and fix typos in omnidir module
Addresses part of https://github.com/opencv/opencv/issues/16601

Add overload method and fix typos in omnidir

---

modules/xfeatures2d/src/freak.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/721
resolves #2430, when value of dx/(norm_sq) is -ve, adding -0.5 will lead to better rounding off.

FREAK : better rounding off for weighted dx and dy of orientation pairs

---

modules/ovis/include/opencv2/ovis.hpp
modules/ovis/src/ovis.cpp

ovis: allow setting material at sub-entity granularity

---

modules/phase_unwrapping/include/opencv2/phase_unwrapping/histogramphaseunwrapping.hpp
modules/phase_unwrapping/misc/python/pyopencv_phase_unwrapping.hpp
modules/phase_unwrapping/src/histogramphaseunwrapping.cpp
modules/structured_light/include/opencv2/structured_light/sinusoidalpattern.hpp
modules/structured_light/misc/python/test/test_structured_light.py

SinusoidalPattern::unwrapPhaseMap now takes an InputArray instead of InputArrayOfArrays to correct a Python binding problem
present a scriptable HistogramPhaseUnwrapping::create
This patch solves issue #1704 and allow to write a whole pipeline including reliability computation.

Allows structured_light pipeline to be run from Python

---

modules/rgbd/include/opencv2/rgbd/kinfu.hpp
modules/rgbd/src/kinfu.cpp

Fixes issue #1903. Kindly review @savuor 
Created a default constructor which allows users to configure Parameter values for KinFu algorithm. 
- Created `Params()` constructor with wrapper macro `CV_WRAP` so users can access members of `struct Params`.
- Created `Params::setInitialVolumePose()` with wrapper macro `CV_WRAP` so users can configure the `Affine3f volumePose`. There was no python wrapper on `Affine3f`, so had to create this function.
- Added `CV_Assert` to check if the size of the `Params::icpIterations` is equal to `Params::pyramidLevels`.
- Added `CV_Assert` to check if `Params::intr` is valid.

Adding constructor for kinfu_Params()

---

modules/rgbd/src/depth_registration.cpp
modules/rgbd/test/test_registration.cpp

Fixes #2234
relates #132
The for loop was iterating redundantly which caused it to wrap pixels around boundaries when the color image has a larger field of view than the depth image. 
Also added a test case for the same.
**Before**
**After**

Fix depth registeration 

---

modules/face/src/regtree.cpp

```
opencv_contrib\modules\face\src\regtree.cpp(252): warning C4701: potentially uninitialized local variable 'split' used
```

Fix warning in VS 2019 build

---

modules/ccalib/src/ccalib.cpp

Fixes issue #2064: Fairly straightforward fix
Apologize for the previous PR in the wrong branch. 
Tested compilation on Ubuntu 18.04
@alalek could you please review this
```
force_builders=linux,windows,docs,mac
```

Minor fix for solvePnPRansac params mismatch 

---

modules/ximgproc/include/opencv2/ximgproc.hpp
modules/ximgproc/src/niblack_thresholding.cpp
modules/ximgproc/test/test_niblack_threshold.cpp

Fix https://github.com/opencv/opencv_contrib/issues/2490
This is one idea.
I also fixed a mix of tabs and spaces.

ximgproc: [niBlackThreshold] add R parameter for Sauvola's method

---

modules/xfeatures2d/test/test_surf.cuda.cpp

resolves #2493 
<cut/>
<cut/>
```
```

fix runtime error of test case redefinition

---

modules/bgsegm/src/bgfg_gsoc.cpp
modules/line_descriptor/src/bitops.hpp
modules/saliency/src/BING/kyheader.hpp

Fix #2275
I use `_M_ARM` and `_M_ARM64` to determine if the platform is ARM or not.
https://docs.microsoft.com/ja-jp/cpp/preprocessor/predefined-macros?view=vs-2019
```
Xbuild_image:Win64=msvs2019-arm64
buildworker:Win64=windows-1
```

Fix popcnt errors for UWP ARM/ARM64

---

modules/xfeatures2d/perf/perf_sift.cpp
modules/xfeatures2d/src/sift.cpp

**Tested with main PR**: https://github.com/opencv/opencv/pull/17092
- perf tests
- trace regions
- avoid inplace arrays in `GaussianBlur()` calls
<details>
<summary>SIFT performance results (i5-6600)</summary>
|Name of Test|base|ipp|avx2+ipp|ipp speedup|ipp+avx2 speedup|
|---|:-:|:-:|:-:|:-:|:-:|
|SIFT::SIFT_detect::"leuven/img1.png"|79.523|34.281|34.230|2.32|2.32|
|SIFT::SIFT_detect::"stitching/a3.png"|71.424|31.850|31.629|2.24|2.26|
|SIFT::SIFT_extract::"leuven/img1.png"|78.763|34.135|26.981|2.31|2.92|
|SIFT::SIFT_extract::"stitching/a3.png"|85.059|46.014|33.927|1.85|2.51|
|SIFT::SIFT_full::"leuven/img1.png"|100.167|55.374|48.046|1.81|2.08|
|SIFT::SIFT_full::"stitching/a3.png"|106.117|66.773|54.400|1.59|1.95|
</details>

sift: optimization stage1

---

modules/aruco/include/opencv2/aruco.hpp

resolves #2420
Changed the default value of DetectorParameters.perspectiveRemovePixelPerCell to 4 in the documentation as per the initialization in the code.
Also the default values of some parameters were missing in the documentation, added them.

Fixed the information about default values in aruco documentation

---

modules/dnn_objdetect/include/opencv2/core_detect.hpp

- [x ] I agree to contribute to the project under OpenCV (BSD) License.
- [ x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [ x] The PR is proposed to proper branch
- [ x] There is reference to original bug report and related work
- [ x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
- [ x] The feature is well documented and sample code can be built with the project CMake
this removes a dependancy on highgui.hpp from the core_detect.hpp header, so the module can compile if highgui is disabled from cmake
(it's …

dnn_objdetect: remove highgui header from core_detect.hpp

---

modules/aruco/include/opencv2/aruco/charuco.hpp
modules/aruco/src/charuco.cpp
modules/aruco/test/test_charucodetection.cpp

When using charuco corners for calibration, specifically in the robotics context when full-pattern images of the charuco boards are not gauranteed, there are cases when the chaurco corners identified are collinear.
The corners (in my application) are usually axis aligned, but when these identified corners are axis aligned or just linear (some diagonal within the pattern), using these corners will result in errors via CV_ASSERT checks, or poor results b/c of the numerical issues of using collinear points for estimating calibration parameters.
There does not exist any functionality w/in the opencv_contrib module for checking whether the charuco corners are collinear, given a charuco board.  In `charuco.cpp`, there is function `static bool _arePointsEnoughForPoseEstimation(const vector< …

aruco: new feature testCharucoCornersCollinear() in charuco.hpp/cpp

---

modules/cudaoptflow/samples/optical_flow.cpp

relates #2536
Please check if the below patch resolves build errors. I am able to compile and run the sample app on my machine
- [*] I agree to contribute to the project under OpenCV (BSD) License.
- [*] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [*] The PR is proposed to proper branch
- [*] The feature is well documented and sample code can be built with the project CMake
```
```

NVOF Build Error Fix

---

modules/cudev/test/CMakeLists.txt

**Main PR**: https://github.com/opencv/opencv/pull/17686
```
```

cmake(cuda): update handling of -std=c++11/14 flags

---

modules/ximgproc/test/test_fbs_filter.cpp

resolves #2580 
~~**Merge with** https://github.com/opencv/opencv/pull/17691~~

ximgproc: avoid test failure based on rounding error

---

modules/xfeatures2d/test/test_surf.cuda.cpp

- resolves #2587 
- It's another rounding error, so this is a low priority PR.
- I kept the threshold as low as possible, to make this test pass on Jetson
- This will loosen the threshold on other combinations, so I'm open for discussion on how to avoid this test failure
<cut/>
```
```

CUDA: avoid bit-exact test on Jetson

---

modules/xfeatures2d/test/test_surf.cuda.cpp

xfeatures2d: fix compilation error on MSVS

---

modules/xfeatures2d/test/test_surf.cuda.cpp

relates #2591 
Sorry, I forgot to confirm on Jetson.
#2591 leads to build failure.
<cut/>
```
[ 74%] Building CXX object modules/xfeatures2d/CMakeFiles/opencv_test_xfeatures2d.dir/test/test_surf.cuda.cpp.o
/opencv_contrib/modules/xfeatures2d/test/test_surf.cuda.cpp:182:1: error: reference to ‘internal’ is ambiguous
internal::ValueArray2<SURF_HessianThreshold, SURF_HessianThreshold> thresholdValues =
^~~~~~~~
```
```
```

fix compilation error on Jetson

---

modules/ximgproc/include/opencv2/ximgproc/lsc.hpp

- [ x] I agree to contribute to the project under OpenCV (BSD) License.
- [ x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [ x] The PR is proposed to proper branch

Fix default parameter to be coherent with documentation

---

modules/dnn_superres/include/opencv2/dnn_superres.hpp
modules/dnn_superres/src/dnn_superres.cpp

Hi there,
This PR allows users to set CUDA backend in the dnn_superres module. Now users can use their GPU's for inference while upscaling images via the neural networks. I've tried a few images, and I've seen around an 6x increase in speed (GTX 1080Ti).
I'm not sure this is the best way of doing this. Perhaps it is better to also allow users to choose other types of backends? What do you think? I'll wait for the feedback before adding a tutorial (and test?) for this.

Create CUDA backend support for dnn_superres

---

modules/datasets/src/or_pascal.cpp
modules/datasets/src/tinyxml2/tinyxml2.cpp
modules/datasets/src/tinyxml2/tinyxml2.h
modules/datasets/src/tr_svt.cpp

Rework tinyxml2 in this module to have namespace cv::tinyxml2
instead of just tinyxml2, so will not clash with other versions
of tinyxml2 at linkage time.
Closes opencv#2590

Update tinyxml2 to be under cv namespace

---

modules/aruco/CMakeLists.txt
modules/aruco/misc/objc/gen_dict.json
modules/bgsegm/CMakeLists.txt
modules/bgsegm/misc/objc/gen_dict.json
modules/bioinspired/CMakeLists.txt
modules/bioinspired/misc/objc/gen_dict.json
modules/face/CMakeLists.txt
modules/face/misc/objc/gen_dict.json
modules/img_hash/CMakeLists.txt
modules/img_hash/misc/objc/gen_dict.json
modules/phase_unwrapping/CMakeLists.txt
modules/phase_unwrapping/misc/objc/gen_dict.json
modules/plot/CMakeLists.txt
modules/plot/misc/objc/gen_dict.json
modules/structured_light/CMakeLists.txt
modules/structured_light/misc/objc/gen_dict.json
modules/text/CMakeLists.txt
modules/text/misc/objc/gen_dict.json
modules/tracking/CMakeLists.txt
modules/tracking/misc/objc/gen_dict.json
modules/xfeatures2d/CMakeLists.txt
modules/xfeatures2d/misc/objc/gen_dict.json
modules/ximgproc/CMakeLists.txt
modules/ximgproc/misc/objc/gen_dict.json
modules/xphoto/CMakeLists.txt
modules/xphoto/misc/objc/gen_dict.json

**Main PR**: https://github.com/opencv/opencv/pull/17882
07ba8bd
resolves #2608 
resolves https://github.com/opencv/opencv/issues/17881
Changes in this PR
- add `objc` to the WRAP clause of the relevant `CMakeLists.txt` files
- add relevant argument/constant fix-ups, import config for each module in `gen_dict.json `
<cut/>

Add Objective-C/Swift wrappers for opencv_contrib modules

---

modules/stereo/src/stereo_binary_bm.cpp
modules/stereo/src/stereo_binary_sgbm.cpp

Default kernel size of 9 was used instead of the set one

---

LICENSE

Many files still contain old-style copyrights though.
See https://github.com/opencv/opencv/wiki/OE-32.--Change-OpenCV-License-to-Apache-2
- [N/A ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable

changed OpenCV license from BSD to Apache 2 license

---

modules/ovis/include/opencv2/ovis.hpp
modules/ovis/src/ovis.cpp

this hides textures as named top-level objects. They are now only
referenced as properties of materials.

ovis: streamline updating texture contents

---

modules/viz/src/vtk/vtkCocoaInteractorFix.mm

In attempting to build VTK 9 for macOS as part of Homebrew, opencv fails to build. Building locally on macOS 10.15 with the new VTK, without any changes to the existing code, the following error is output:
```
/Users/username/open/opencv/opencv_contrib/modules/viz/src/vtk/vtkCocoaInteractorFix.mm:58:7: warning: 'VTK_MAJOR_VERSION' is not defined, evaluates to 0 [-Wundef]
#if ((VTK_MAJOR_VERSION < 6) || ((VTK_MAJOR_VERSION == 6) && (VTK_MINOR_VERSION < 2)))
^
/Users/username/open/opencv/opencv_contrib/modules/viz/src/vtk/vtkCocoaInteractorFix.mm:128:50: warning: 'NSApplicationDefined' is deprecated: first deprecated in macOS 10.12 …
```

vtkCocoaInteractorFix.mm: explicity include vtkVersion.h

---

.github/PULL_REQUEST_TEMPLATE.md

The license for opencv and opencv_contrib was changed to Apache 2: (https://github.com/opencv/opencv/pull/18073, https://github.com/opencv/opencv_contrib/pull/2628) and the PR template for opencv was updated with the new license, but not for opencv_contrib.

update PR template to match license

---

modules/ximgproc/include/opencv2/ximgproc/disparity_filter.hpp
modules/ximgproc/misc/python/test/test_disparity.py
modules/ximgproc/src/disparity_filters.cpp

questions:
* should the license be changed ?
* does it need a python test ? (there is already a [c++ one here](https://github.com/opencv/opencv_contrib/blob/master/modules/ximgproc/test/test_disparity_wls_filter.cpp#L19))

ximgproc: add python wrappers for disparity functions

---

modules/rgbd/perf/perf_tsdf.cpp
modules/rgbd/src/hash_tsdf.cpp
modules/rgbd/src/hash_tsdf.hpp
modules/rgbd/src/opencl/tsdf.cl
modules/rgbd/src/tsdf.cpp
modules/rgbd/src/tsdf.hpp
modules/rgbd/src/utils.hpp
modules/rgbd/test/test_tsdf.cpp

/----[ WI ]----/
- Reducing memory consumption:
* Create new type (half)
* Replace float with new type - TsdfType(int8_t):
+ CPU 
+ GPU
+ INTRINSICS
+ HashTSDF
* Replace int with uchar:
+ CPU 
+ GPU
+ INTRINSICS
+ HashTSDF
- TSDF optimization:
* Speeded up the calculation of the pixNorm variable by incrementing this variable on the fixed number
- HashTSDF optimization:
* Vectorized interpolate function
* Reduced the call to the at() function, acceleration of the getNormalVoxel() function by 33%, and the algorithm by 10%
- Tests:
* Create new struct "Settings" for performance test (perf_rgbd)
- Other minor fixes

TSDF Optimization

---

modules/rgbd/src/dynafu.cpp

resolves #2307
`GL/gl.h` from Windows SDK contains only OpenGL 1.1 definitions, and so APIs like glGenRenderbuffers must be bound dynamically using wglGetProcAddress.

[rgbd/dynafu] Fix Windows compilation

---

modules/xfeatures2d/src/stardetector.cpp

- MSVC 19.27.29111.0
Error message (points to the meaningless end of function `}`, looks like a compiler bug):
```
opencv_contrib\modules\xfeatures2d\src\stardetector.cpp(350,1): error C2109: subscript requires array or pointer type
```
```
force_builders=Win64 OpenCL
buildworker:Win64 OpenCL=windows-2
build_image:Win64 OpenCL=msvs2019
```

xfeatures2d: fix MSVS2019 build

---

modules/rgbd/src/opencl/tsdf.cl
modules/rgbd/src/tsdf.cpp
modules/rgbd/src/tsdf.hpp

resolves #2675
Results of GPU optimization:
* before:
[ RUN      ] Perf_TSDF.integrate
[ PERFSTAT ]    (samples=72   mean=2.51   median=2.36   min=1.62   stddev=0.54 (21.7%))
* after:
[ RUN      ] Perf_TSDF.integrate
[ PERFSTAT ]    (samples=72   mean=2.21   median=1.90   min=1.33   stddev=0.82 (37.3%))

TSDF preCalculation pixNorm

---

modules/ximgproc/include/opencv2/ximgproc/fast_line_detector.hpp
modules/ximgproc/samples/fld_lines.cpp
modules/ximgproc/src/fast_line_detector.cpp
modules/ximgproc/test/test_fld.cpp

Fixed issue #2667 in opencv/opencv_contrib
Added the `is_edge` option to the `detect` method in `fast_line_detector`.
The Fast Line Detector used to use the canny method for edge detection internally, but `is_edge=true` makes it possible to input the edge image directly. Parameters for the canny method are ignored. The default value is `false`, so it won't break anyone's code.
This feature will provide users with additional flexibility and versatility in FastLineDetector.

Added edge input feature to fast_line_detector

---

modules/rgbd/src/hash_tsdf.cpp
modules/rgbd/src/hash_tsdf.hpp
modules/rgbd/src/tsdf.cpp
modules/rgbd/src/tsdf_functions.cpp
modules/rgbd/src/tsdf_functions.hpp

Replace int with Point3i at integrateVolumeUnit signature

integrateVolumeUnit fix

---

modules/optflow/src/rlof/berlof_invoker.hpp

[Nightly build](http://pullrequest.opencv.org/buildbot/builders/master-contrib-lin64/builds/11326).
relates #1940

optflow(rlof): fix uninitialized variable

---

modules/rgbd/test/test_dynafu.cpp

relates #2619
resolves #2715
Fixes the following compiler error:
```
rgbd/test/test_dynafu.cpp:44:17: error: 'Params' is not a member of 'cv::dynafu'
44 |     Ptr<dynafu::Params> params;
|                 ^~~~~~
```

Fix build failure in rgbd's test

---

modules/sfm/src/libmv_capi.h
modules/sfm/src/simple_pipeline.cpp

sfm: fix memory leak

---

modules/text/include/opencv2/text/ocr.hpp
modules/text/src/ocr_beamsearch_decoder.cpp

text: drop ambiguous call, fix bindings

---

modules/phase_unwrapping/include/opencv2/phase_unwrapping/phase_unwrapping.hpp
modules/phase_unwrapping/src/histogramphaseunwrapping.cpp

phase_unwrapping: add asserts, documentation for input types

---

modules/sfm/src/libmv_light/libmv/base/vector.h

relates #2740
Failed [nightly build](http://pullrequest.opencv.org/buildbot/builders/3_4-contrib-lin64/builds/892).

sfm: fix build in non-C++11 mode

---

modules/cvv/src/stfl/stringutils.cpp

The UTF-8 string u8"…" causes following errors when building under VS2019:
C2001  newline in constant
C2143 syntax error: missing ';' before '}'
C2146 syntax error: missing ';' before identifier 'str'
#2001 
Build under VS2017/2019

fix: VS compatibility with unicode strings

---

modules/rgbd/include/opencv2/rgbd/depth.hpp
modules/rgbd/include/opencv2/rgbd/dynafu.hpp
modules/rgbd/src/utils.cpp

Add depth_factor argument in rescaleDepth and typedef dynafu::Params for backwards compatibility

---

modules/intensity_transform/src/bimef.cpp
modules/rgbd/src/submap.hpp
modules/sfm/src/libmv_light/CMakeLists.txt

**Main PR**: https://github.com/opencv/opencv/pull/18924

(4.x) build: Xcode 12 support

---

modules/rgbd/src/pose_graph.hpp

**Main PR**: https://github.com/opencv/opencv/pull/19021
- GCC 4.8.5 / CentOS 7
[Nightly build](http://pullrequest.opencv.org/buildbot/builders/master-contrib_etc-centos-lin64/builds/44).
<cut/>
```
/build/master-contrib_etc-centos-lin64/opencv_contrib/modules/rgbd/src/pose_graph.hpp:231:5: warning: unused parameter '_poseGraph' [-Wunused-parameter]
/build/master-contrib_etc-centos-lin64/opencv_contrib/modules/rgbd/src/pose_graph.hpp:231:5: warning: unused parameter '_poseGraph' [-Wunused-parameter]
```

build warnings

---

modules/freetype/README.md
modules/freetype/include/opencv2/freetype.hpp

Fix https://github.com/opencv/opencv_contrib/issues/2771 and related small problems about documentation.
1.  freetype.hpp is fixed.
- putText() is supported for only 8UC3 image with only 8UC3 color.
2. README.md is fixed.
- Use correct markdown format.
- Change document title from "freetype module" to "freetype wrapper module". 
- This module title was "freetype **module**". 
- FText primitive in GAPI uses `freetype **library**". 
- Generally  "module" and "library" in the computer world are similar.
- So that, I think this module title should be changed to not confuse it.
- `Installation` is replaced as `Requested external libraries`
- `Usage` is update to it can be compile in real. 
- `Future work` is removed. 
See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making …

freetype2: Fix comments in freetype.hpp and README.md

---

modules/surface_matching/src/ppf_match_3d.cpp

I think the define guards are wrong, the accumulator is allocated with `calloc` regardless of  `_OPENMP`, so it should be freed in any case.

surface_matching/PPF3DDetector::match : fix memory leak

---

modules/aruco/src/charuco.cpp

Images are InputArrays and need not beeing copied here.

[aruco] do not copy image if already a grey-image

---

modules/cudastereo/CMakeLists.txt
modules/cudastereo/doc/cudastereo.bib
modules/cudastereo/include/opencv2/cudastereo.hpp
modules/cudastereo/perf/perf_stereo.cpp
modules/cudastereo/src/cuda/stereosgm.cu
modules/cudastereo/src/cuda/stereosgm.hpp
modules/cudastereo/src/stereosgm.cpp
modules/cudastereo/test/test_sgm_funcs.cpp
modules/cudastereo/test/test_stereo.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/826
We are developers of [libSGM](https://github.com/fixstars/libSGM), a CUDA implementation of Semi-Global Matching.  
This PR adds libSGM into cudastereo module.
The orginal algorithm is described in [1].
For matching cost, the center-symmetric census transform [2] is used.
[1] Heiko Hirschmuller. Stereo processing by semiglobal matching and mutual information. Pattern Analysis and Machine Intelligence, IEEE Transactions on, 30(2):328–341, 2008.
[2] Robert Spangenberg, Tobias Langner, and Raúl Rojas. Weighted semi-global matching and center-symmetric census transform for robust driver assistance. In Computer Analysis of Images and Patterns, pages 34–41. Springer Berlin Heidelberg, 2013.
<cut/>
See details at …

Add libSGM into cudastereo

---

modules/tracking/src/trackerFeature.cpp

The character literal overload is more efficient. More info at:
http://clang.llvm.org/extra/clang-tidy/checks/performance-faster-string-find.html

Optimize calls to std::string::find() and friends for a single char.

---

modules/aruco/CMakeLists.txt

**Main PR**: https://github.com/opencv/opencv/pull/18985
<cut/>
- [ x] I agree to contribute to the project under Apache 2 License.
- [x ] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x ] The PR is proposed to proper branch
- [x ] There is reference to original bug report and related work
See also corresponding PR in main repo.
```
opencv=feature/aruco_js_fix
```

add js to aruco module

---

modules/cudacodec/include/opencv2/cudacodec.hpp
modules/cudacodec/src/video_decoder.cpp

Nvidia only allows users to download the most recent version of the Nvidia Video Codec SDK.  As a result cudacodec has been broken since the release of v 11.0 when the AV1 codec was added.
This small fix should allow cudacodec to pass the inbuilt tests again.
```
```

Update cudacodec to work with Nvidia Video Codec SDK 11.0

---

modules/ovis/include/opencv2/ovis.hpp
modules/ovis/src/ovis.cpp

- [n/a] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
https://user-images.githubusercontent.com/4941802/103154608-c6bfed00-4798-11eb-9d38-f503c7b55c4e.mp4

ovis: implement real-time shadows

---

modules/cudaimgproc/src/cuda/build_point_list.cu
modules/cudaimgproc/src/cuda/hough_circles.cu
modules/cudaimgproc/src/cuda/hough_lines.cu
modules/cudaimgproc/src/cuda/hough_segments.cu
modules/cudaimgproc/src/hough_circles.cpp
modules/cudaimgproc/src/hough_lines.cpp
modules/cudaimgproc/src/hough_segments.cpp

- Passed the stream to the different cuda, OpenCV and thurst library calls
- Replace all device by cuda synchronizes
- Added extra synchronize calls after device to host transfers
- Replaced the cuda globals by allocated values
<cut/>
```
Xbuild_image:Custom=ubuntu-cuda-cc52:18.04
```

Added stream support on hough circles, lines and segments

---

modules/optflow/include/opencv2/optflow/rlofflow.hpp
modules/optflow/src/rlofflow.cpp

- [X ] I agree to contribute to the project under Apache 2 License.
- [ X] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [ X] The PR is proposed to proper branch
- [X ] The feature is well documented and sample code can be built with the project CMake

rlof optflow: fix crash when no match are found

---

modules/cudaarithm/include/opencv2/cudaarithm.hpp
modules/cudaarithm/misc/python/test/test_cudaarithm.py
modules/cudaarithm/perf/perf_element_operations.cpp
modules/cudaarithm/src/cuda/in_range.cu
modules/cudaarithm/src/element_operations.cpp
modules/cudaarithm/test/test_element_operations.cpp
modules/cudev/include/opencv2/cudev/functional/functional.hpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/834
resolves https://github.com/opencv/opencv/issues/6295
Implementation of `cv::cuda::inRange`, as requested in [this issue](https://github.com/opencv/opencv/issues/6295).  It's not a complete implementation of `cv::inRange`; my implementation supports `cv::Scalar` for the upper and lower bounds, which seems like the most common use case by far, but the CPU version does also support `Mat`s for the bounds as well, which mine does not.  It seemed like more of a challenge to support that as well, but if you don't want to merge this without full feature parity I might be able to spend more time on it to figure that out.
Some questions -
1. Wasn't sure about whether the base branch should be `master` or `3.4`, happy to rebase …

Implement cv::cuda::inRange (Fixes OpenCV #6295)

---

modules/rgbd/samples/io_utils.hpp

Added intrinsic parameters of Orbbec's Astra camera to Kinfu demo. Probably, this matrix should be put into VideoIO module, OpenNI2 backend, rather than to each individual sample.
- [N/A] There is reference to original bug report and related work
- [N/A] There is accuracy test, performance test and test data in opencv_extra repository, if applicable

added orbbec camera intrinsic parameters for kinfu demo

---

modules/stereo/CMakeLists.txt
modules/stereo/include/opencv2/stereo/quasi_dense_stereo.hpp
modules/stereo/misc/python/pyopencv_stereo.hpp
modules/stereo/misc/python/test/test_stereo.py
modules/stereo/samples/dense_disparity.cpp
modules/stereo/samples/sample_quasi_dense.py
modules/stereo/src/quasi_dense_stereo.cpp

solved issue 2813

---

modules/cudaoptflow/CMakeLists.txt
modules/cudaoptflow/src/cuda/nvidiaOpticalFlow.cu
modules/cudaoptflow/src/nvidiaOpticalFlow.cpp

relates #2807 
Just modifying this line will let the build pass for both CUDA 8.0 and CUDA 10.0
/cc @vchiluka5 
I understand that Optical flow API only supports CUDA 10.0 and later. Thank you for the comment.
Though, I'd like to propose this fix as a quick fix of build.
Eventually, I can add to disable Optical Flow API when CUDA is less than 10.0
- Before
```
[ 81%] Building NVCC (Device) object modules/cudaoptflow/CMakeFiles/cuda_compile_1.dir/src/cuda/cuda_compile_1_generated_nvidiaOpticalFlow.cu.o
/opencv_contrib/modules/cudaoptflow/src/cuda/nvidiaOpticalFlow.cu(76): error: no instance of overloaded function "surf2Dwrite" matches the argument list
argument types are: (short2, cudaSurfaceObject_t, unsigned long, int, cudaSurfaceBoundaryMode)
1 error detected in the compilation of …
```

cudaoptflow: disable Optical Flow SDK when CUDA version is insufficient

---

modules/cudaoptflow/src/cuda/nvidiaOpticalFlow.cu

closes #2834 
- `HAVE_NVIDIA_OPTFLOW` doesn't arrive to `cu` file, so switch off directly based on CUDA version 
<cut/>
```
```

cudaoptflow: fix build failure when CUDA >= 10.0

---

modules/README.md

fix readme typo inside modules

---

modules/rgbd/src/tsdf.cpp

Issue 2818 fix

---

modules/xfeatures2d/test/test_surf.cuda.cpp

relates #2587 #2588
I updated the threshold of Hessian to tolerate with rounding error, but I need to raise the bar a bit more on Jetson TX1/TX2.

adjust threshold for Jetson TX1/TX2

---

modules/rgbd/src/opencl/tsdf.cl
modules/rgbd/src/tsdf.cpp

Closes #2830 
<cut/>
```
force_builders=Linux OpenCL
```

rgbd: get rid of kernel build failure

---

modules/mcc/src/distance.cpp
modules/mcc/test/test_ccm.cpp

This function did not pass the test case 17 and 19 of [Gaurav Sharma's test data](http://www2.ece.rochester.edu/~gsharma/ciede2000/).
This was due to a mistake into the "RT" value, it was computed with the value ![image](https://user-images.githubusercontent.com/40139622/106273537-247da400-6233-11eb-9532-ae1ce13627b1.png) instead of ![image](https://user-images.githubusercontent.com/40139622/106273627-4414cc80-6233-11eb-9e01-52ffe648cec8.png).
Sources :
- [Wikipedia](https://en.wikipedia.org/wiki/Color_difference) ;
- [The CIEDE2000 Color-Difference Formula : Implementation Notes, Supplementary Test Data, and Mathematical Observations](http://www2.ece.rochester.edu/~gsharma/ciede2000/ciede2000noteCRNA.pdf).
And now i have a little question about this module, why color conversion and color …

deltaCIEDE2000_ fix into the MCC module

---

modules/ximgproc/include/opencv2/ximgproc/sparse_match_interpolator.hpp
modules/ximgproc/misc/python/test/test_sparse_match_interpolator.py
modules/ximgproc/src/sparse_match_interpolators.cpp
modules/ximgproc/test/test_sparse_match_interpolator.cpp

Pull request to solve issue #2796.
Problem was that python wrapper puts a Mat object into from_points and to_points function parameters of type InputArray. 
The old verision only allows vector to be packed into InputArray.
New version allows vectors and Mat to be packed into the InputArray arguments.
C++ tests have been updated.
Python tests have been added for the EdgeAwareInterpolator and RICInteroplator classes.
- [ x] I agree to contribute to the project under Apache 2 License.
- [ x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x ] The PR is proposed to proper branch
Patch to opencv_extra has the …

Resolve issue 2796 ric interpolation

---

modules/alphamat/src/cm.cpp

fixes #2662
This PR fixes the usage of uninitialized memory that can lead to throws and segfaults.
I think the original author wanted to add ones to a zero-initialized Mat object.
I could have used another Constructor for the Mat object, but i chose to make the minimal amount of changes to the code to work as intended.
My proposed change does not change the used algorithm.

fixes #2662

---

modules/rgbd/src/tsdf.cpp

resolves #2857
<cut/>
```
build_image:Custom=ubuntu32:16.04
buildworker:Custom=linux-1,linux-4,linux-6
```

rgbd: fix segmentation fault on Arm 32bit platform

---

modules/rgbd/src/kinfu_frame.cpp

resolves #2817 
There was an error in the work with NaNs in depth.

Fix issue 2817

---

modules/cudev/test/test_nd.cu

**Main PR**: https://github.com/opencv/opencv/pull/19259
```
opencv=
```

Test code - GpuMatND & Mat interoperability

---

modules/cudaimgproc/src/cuda/gftt.cu
modules/cudaimgproc/src/gftt.cpp

resolves https://github.com/opencv/opencv/issues/18051
<cut/>
```
```

Fix CUDA GoodFeaturesToTrackDetector not threadsafe bug

---

modules/ccalib/src/omnidir.cpp

The relevant bug was reported in https://github.com/opencv/opencv_contrib/issues/1612
The _xi was erroneously applied at points re-projection to camera plane.
_xi parameter was already taken in use while projection of points to unit sphere.

Fix omnidir::undistortPoints

---

modules/stereo/include/opencv2/stereo/quasi_dense_stereo.hpp
modules/stereo/samples/dense_disparity.cpp
modules/stereo/samples/sample_quasi_dense.py
modules/stereo/src/quasi_dense_stereo.cpp
modules/stereo/test/test_block_matching.cpp
modules/stereo/test/test_qds_matching.cpp

This addresses user comments made in #1941 and #2819. The getDisparity function, of QuasiDenseStereo, originally returned a disparity image normalized to span the full range between 0 and 255, which was improper and understandably confused users.
I've made the following changes:
- getDisparity now returns proper CV_32F disparity maps with nan values for unknown matches. 
- included an accuracy test.

Remove normalization in cv::stereo::QuasiDenseStereo getDisparity().

---

modules/ximgproc/src/thinning.cpp

#2894 from berak:imgproc_fix_thinning
Main PR: https://github.com/opencv/opencv/pull/19764
Previous "Merge 3.4": #2891
<cut/>
<details>
```
force_builders=Custom,Win64 OpenCL
buildworker:Win64 OpenCL=windows-2
build_image:Win64 OpenCL=msvs2019
```
</details>

(4.x) Merge 3.4

---

modules/ovis/misc/python/test_ovis.py

the last Ogre release added a self-contained Software Rendering backend, which eases testing:
https://www.ogre3d.org/2021/02/12/ogre-1-12-11-released#Software_RenderSystem
this adds unit-tests for the last two bugs I fixed in ovis. If Ogre will be installed on the runners, they could also be executed as part of the opencv test-suite.
- n/a There is reference to original bug report and related work

ovis: add software-renderer based unit testing

---

modules/wechat_qrcode/src/detector/ssd_detector.cpp

resolves #2877
add a safe score threshold due to https://github.com/opencv/opencv_contrib/issues/2877
<cut/>

fix: add a safe score threshold(1E-5) to wechat_qrcode detector

---

modules/aruco/src/aruco.cpp

_filterTooCloseCandidates was occasionally not choosing the biggest
contour of a candidate group.
Firstly, if the biggest contour of a candidate group happened to be
the first candidate of that group, it would never be chosen due to the
comparison loop skipping it.
Secondly, contour sizes were being compared by their circumference
(via counting the number of points in a contour) rather than area.
In some cases it is possible for a smaller candidate to have more
points than a bigger one. This was fixed by comparing the contour
area as defined by the contour's corners.
<cut/>
```
force_builders=linux,docs
```

Fix aruco _filterTooCloseCandidates

---

modules/rgbd/CMakeLists.txt
modules/rgbd/include/opencv2/rgbd.hpp
modules/rgbd/include/opencv2/rgbd/detail/pose_graph.hpp
modules/rgbd/src/fast_icp.cpp
modules/rgbd/src/large_kinfu.cpp
modules/rgbd/src/nonrigid_icp.cpp
modules/rgbd/src/pose_graph.cpp
modules/rgbd/src/pose_graph.hpp
modules/rgbd/src/precomp.hpp
modules/rgbd/src/sparse_block_matrix.hpp
modules/rgbd/src/submap.hpp
modules/rgbd/test/test_pose_graph.cpp

Pose graph from Large KinFu rewritten using manual analytic differentiation and custom LevMarq solver based on naive block sparse matrix implementation solved by Eigen library.
Connected test data PR: https://github.com/opencv/opencv_extra/pull/869

Pose Graph rewritten without Ceres

---

modules/ximgproc/doc/ximgproc.bib
modules/ximgproc/include/opencv2/ximgproc.hpp
modules/ximgproc/include/opencv2/ximgproc/edge_drawing.hpp
modules/ximgproc/include/opencv2/ximgproc/fast_line_detector.hpp
modules/ximgproc/misc/python/pyopencv_ximgproc.hpp
modules/ximgproc/samples/edge_drawing.py
modules/ximgproc/samples/fld_lines.cpp
modules/ximgproc/src/edge_drawing.cpp
modules/ximgproc/src/edge_drawing_common.hpp
modules/ximgproc/test/test_fld.cpp

initial test PR to add EDGE DRAWING LIBRARY ( original code is in https://github.com/CihanTopal/ED_Lib)

Test ED_Lib

---

modules/aruco/src/aruco.cpp

It is now had been what it was wanted to be here. Or we may do some asserts before e.g. `CV_ASSERT(candidateBits.rows == candidateBits.cols); `.

consider the rectangle marker in the future.

---

modules/ximgproc/src/edge_drawing.cpp

[Nightly build](http://pullrequest.opencv.org/buildbot/builders/3_4-contrib_etc-simd-emulator-lin64/builds/66)
```
opencv=
buildworker:Custom=linux-1
build_image:Custom=ubuntu:16.04
```

Eliminate build warnings

---

modules/dnn_superres/README.md

Corrected arXiv URLs in README.md.
relates #2231
<cut/>
- [+] I agree to contribute to the project under Apache 2 License.
- [+ ] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [+] The PR is proposed to proper branch

dnn_superres: Fix arXiv URL typos in README.md

---

modules/ximgproc/include/opencv2/ximgproc/fast_line_detector.hpp
modules/ximgproc/samples/fld_lines.cpp
modules/ximgproc/src/fast_line_detector.cpp
modules/ximgproc/test/test_fld.cpp

backport #2716
requested here: https://github.com/opencv/opencv_contrib/pull/2912#issuecomment-814152125

(3.4) ximgproc: Added edge input feature to fast_line_detector

---

modules/wechat_qrcode/src/zxing/zxing.hpp

resolves #2862
this also collapses all `#if defined(XXX)` blocks to disable iconv support into a single one
- [x ] I agree to contribute to the project under Apache 2 License.
- [x ] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x ] The PR is proposed to proper branch
- [x ] There is reference to original bug report and related work

wechat_qr: disable iconv dependancy for mingw

---

modules/ximgproc/include/opencv2/ximgproc/run_length_morphology.hpp
modules/ximgproc/src/run_length_morphology.cpp

[ximgproc::rl::createRLEImage] make 'runs' parameter as const

---

modules/cudafeatures2d/include/opencv2/cudafeatures2d.hpp

Related bug: https://github.com/opencv/opencv/issues/19890
Tested changes locally on Ubuntu 18.4. Works as expected.
- [V] I agree to contribute to the project under Apache 2 License.
- [V] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [V] The PR is proposed to proper branch
- [V] There is reference to original bug report and related work
- [V] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
- [V] The feature is well documented and sample code can be built with the project CMake
<cut/>
<details>
``` …
```

fixing return value of python bindings for cudafeatures2d methods

---

modules/cnn_3dobj/CMakeLists.txt

- used FindGlog.cmake has buggy implementation (doesn't follow CMake policies / variable names)
relates #2923

cmake: completelly disable cnn_3dobj

---

modules/rgbd/include/opencv2/rgbd/colored_kinfu.hpp
modules/rgbd/include/opencv2/rgbd/kinfu.hpp
modules/rgbd/include/opencv2/rgbd/large_kinfu.hpp
modules/rgbd/src/colored_kinfu.cpp
modules/rgbd/src/kinfu.cpp
modules/rgbd/src/large_kinfu.cpp

KinFu fix (iss2925)

---

modules/ximgproc/include/opencv2/ximgproc.hpp
modules/ximgproc/include/opencv2/ximgproc/edge_drawing.hpp
modules/ximgproc/src/edge_drawing.cpp
modules/ximgproc/src/edge_drawing_common.hpp

#2314
[documentation preview](https://pullrequest.opencv.org/buildbot/export/pr_contrib/2907/docs/d4/d8b/group__ximgproc__edge__drawing.html)
```
force_builders=Linux x64,docs
```

Edge Drawing Improvements

---

modules/barcode/misc/java/src/cpp/barcode_converters.cpp
modules/barcode/misc/java/test/BarcodeDetectorTest.java
modules/barcode/misc/python/test/test_barcode_detector.py
modules/barcode/src/barcode.cpp
modules/barcode/src/decoder/abs_decoder.cpp
modules/barcode/src/decoder/abs_decoder.hpp
modules/barcode/src/decoder/upcean_decoder.cpp
modules/barcode/src/detector/bardetect.cpp

1. JNI crashing while coping `vector<BarcodeType>` to `ArrayList<Integer>`;
2. In python/java, assertion fails when calling `BarcodeDetector::decode()`;
3. The implementation of `UPCEANDecoder::decodeROI()` is wrong.
**We fixed up all the bugs, and wrote tests for python and java ports.**

Bugfix: barcode module

---

modules/wechat_qrcode/CMakeLists.txt
modules/wechat_qrcode/src/zxing/zxing.hpp

This PR is an alternate approach that fixes #2862, and partially reverts #2916 (with original submitter @berak's approval).
Instead of disabling `wechat_qrcode`'s use of `iconv` in MinGW environments, the module simply needs to be linked with the external library `libiconv`, which is packaged and available as part of the MSYS2 collection.
(On POSIX systems `iconv` is built into libc, but on others it's provided by an external library.)
Fortunately, since CMake 3.11 the standard module `FindIconv.cmake` has been included in the distribution that can handle linking with libiconv if necessary on the target system.
The use of `FindIconv.cmake` is safe on POSIX systems; on my Fedora box it simply noted that iconv is built in to the C library and fell through harmlessly:
```text
-- Performing …
```

Link wechat_qrcode with libiconv on MinGW

---

modules/face/src/facemarkLBF.cpp

Original issue: #2130
The cascade_face parameter is only used by the default face detector, which already complains if the parameter is not set.
Not sure how to determine the appropriate branch.
There is no applicable testing data in opencv_extra.

Removed check for cascade_face as it is not used.

---

modules/face/src/facemarkLBF.cpp

#2129
The proposed change would convert the training image to grayscale AFTER running the face detector. The default face detector already converts the images to grayscale and a custom detector should be able to decide if it want to use grayscale/color images.
I've kept the conversion itself as I'm not sure if the actual training requires grayscale images.

Do conversion to grayscale after face detection.

---

modules/aruco/samples/tutorial_charuco_create_detect.cpp

Check for successful read of `camera_matrix` and `distortion_coefficients` parameters in readCameraParameters()
If the filename exists, but the values are not read, the routine used to return true with empty matricies.  This changes to check if each matrix has a reasonable dimension.
The tutorial file should be robust against bad inputs and help learners recognize and identify problems.
This should solve https://github.com/opencv/opencv_contrib/issues/2949

Sanity check tutorial_charuco_create_detect.cpp::readCameraParameters()

---

modules/rapid/doc/rapid.bib
modules/rapid/include/opencv2/rapid.hpp
modules/rapid/src/histogram.cpp

#2967 from paroj:rapid_gos
Main PR: https://github.com/opencv/opencv/pull/20266
Previous "Merge 4.x": #2966

(5.x) Merge 4.x

---

modules/wechat_qrcode/src/zxing/common/unicomblock.cpp
modules/wechat_qrcode/src/zxing/common/unicomblock.hpp

Fixes #2911
When the hand is covered, there are too many unicomblock, which resulting in a large `m_iNowIdx`, but the data type is`  unsigned short`,  make data overflow to zero.
https://github.com/opencv/opencv_contrib/blob/8eec886808b1352cdb746772ef6e001ff83d2774/modules/wechat_qrcode/src/zxing/common/unicomblock.hpp#L35
and it will fall into an infinite loop:
https://github.com/opencv/opencv_contrib/blob/8eec886808b1352cdb746772ef6e001ff83d2774/modules/wechat_qrcode/src/zxing/common/unicomblock.cpp#L103
so we need modify data type from `unsigned short`  to `unsigned int`.
```
force_builders=linux,docs
```

Date type fixer

---

modules/fuzzy/src/fuzzy_F0_math.cpp

resolves #2977 
using cv::Mat instead of the prev. `new` allocations, since we need Mat later for cv::merge()

fuzzy: fix memleaks

---

modules/aruco/include/opencv2/aruco.hpp
modules/aruco/misc/python/test/test_aruco.py
modules/aruco/src/aruco.cpp

Fixing https://github.com/opencv/opencv-python/issues/451.

Make aruco board ids field accessible from python

---

modules/julia/gen/jl_cxx_files/types_conversion.jl

Fix bug in type conversion in Julia bindings. Previously calling certain functions like `imwrite` will result in an error which this fixes.

julia - Fix type conversion bug

---

modules/bgsegm/src/synthetic_seq.cpp
modules/img_hash/src/radial_variance_hash.cpp
modules/text/src/erfilter.cpp
modules/xfeatures2d/src/pct_signatures/pct_clusterizer.cpp
modules/ximgproc/src/fast_line_detector.cpp

There are several operator= overloads and some compilers can be confused.
This is similar to https://github.com/opencv/opencv/pull/20304 but for opencv_contrib

Do not use = 0 for a cv::Mat.

---

modules/ximgproc/src/seeds.cpp

resolves #2935
When processing a large number of images, a program crash can occur with a divide by zero error in the above function. Changing the order of multiplication / division avoids a division by zero.

Divide by zero error in SEEDS Superpixels #2935

---

modules/cudacodec/src/video_reader.cpp

Currently if a CUDA stream is passed to 
`cv::cudacodec::nextFrame(GpuMat& frame, Stream &stream);`
the mapping (cuvidMapVideoFrame) of a video frame to CUDA from the hardware decoder uses the default instead of the provided stream.
This tiny fix ensures the provided stream is passed to `cuvidMapVideoFrame()`.
```
```

Fix cudacodec so that it can use streams other than the default

---

modules/cudacodec/include/opencv2/cudacodec.hpp
modules/cudacodec/src/cuvid_video_source.cpp
modules/cudacodec/src/cuvid_video_source.hpp
modules/cudacodec/src/ffmpeg_video_source.cpp
modules/cudacodec/src/ffmpeg_video_source.hpp
modules/cudacodec/src/video_parser.cpp
modules/cudacodec/src/video_reader.cpp
modules/cudacodec/src/video_source.cpp
modules/cudacodec/src/video_source.hpp
modules/cudacodec/test/test_video.cpp

When decoding certain resolutions (e.g. 1080p), the size of the frame returned from `nextFrame()` (1920x**1088**) can be larger than the usable area (1920x**1080**) due to the coded sizes being multiples of n bytes, for efficient coding/decoding.
This causes a problem in cudacodec because currently the values of width and height returned by `cudaCodec::Format()` are different depending on which video source is used.  The two possibilities are FFmpeg and cuvid, with FFmpeg returning the usable width and height (1920x**1080**) and cuvid returning the coded width and height (1920x**1088**).
I think it would make sense for both video sources to return the coded width and height if possible because that corresponds to the dimensions of the frame returned by `nextFrame()`.  Unfortunately in the …

Correct width/height returned by cudacodec::VideoReader::FormatInfo()

---

modules/julia/README.md
modules/julia/tutorials/julia.markdown

This pull request concludes the first phase of the Julia Bindings GSoC Project. No code was changed on the OpenCV repostiories. The other pull requests that have been made in this phase are 
- https://github.com/JuliaRegistries/General/pull/39058
- https://github.com/JuliaPackaging/Yggdrasil/pull/3162
- #2979 
Also, a repository hosting OpenCV.jl was made https://github.com/archit120/OpenCV.jl

[GSoC] Julia Bindings - Phase 1

---

modules/aruco/samples/detector_params.yml

Renamed a variable name minCornerDistance on a yml to minCornerDistanceRate since it is used as minCornerDistanceRate at https://github.com/opencv/opencv_contrib/blob/907efb966823ea3ca40b70500068866f6bfb8f3a/modules/aruco/samples/detect_markers.cpp#L93 and https://github.com/opencv/opencv_contrib/blob/907efb966823ea3ca40b70500068866f6bfb8f3a/modules/aruco/samples/detect_diamonds.cpp#L94 .
- [*] I agree to contribute to the project under Apache 2 License.
- [*] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [*] The PR is proposed to proper branch
- [*] There is reference to original bug report and related …

Rename variable name at detector_params.yml since it is differrent from c++ source code

---

modules/aruco/misc/python/test/test_aruco.py

Test utilize error-prone behavior when 2d array is flattened. 
Merge before https://github.com/opencv/opencv/pull/20618 , but without this PR indices shape `squeeze` is required because `std::vector<int>` is returned as 2d Mat `[[1], [2], ...]`  

fix: aruco test tries to pass 2d numpy array as std::vector<int>

---

modules/ovis/src/ovis.cpp

when creating an window with `cv.ovis.SCENE_AA | cv.ovis.SCENE_OFFSCREEN` the contents would always be black, as the target would never be resolved to the backbuffer.

ovis: fix offscreen FSAA target not being resolved

---

modules/datasets/src/or_mnist.cpp

The files from http://yann.lecun.com/exdb/mnist/ are
train-images-idx3-ubyte.gz
train-labels-idx1-ubyte.gz
t10k-images-idx3-ubyte.gz
t10k-labels-idx1-ubyte.gz
after unpacking, ther default names are like xxxx-idxn-ubyte
but the names in the code are
train-images.idx3-ubyte
train-labels.idx1-ubyte
t10k-images.idx3-ubyte
t10k-labels.idx1-ubyte
'-' is replaced by '.' , this cause a segmentation fault when do as the instructions in dataset.hpp:
./opencv/build/bin/example_datasets_or_mnist -p=/home/user/path_to_unpacked_files/

rename the database names in or_mnist.cpp

---

modules/aruco/src/charuco.cpp
modules/aruco/test/test_charucodetection.cpp

The two possible paths of `interpolateCornersCharuco`, `_interpolateCornersCharucoApproxCalib` and `_interpolateCornersCharucoLocalHom`, assume that the top-left corner of the top-left pixel of an image has the coordinate (0,0) whereas for `cornerSubpix` that is the center of that pixel and the top-left corner is actually (-0.5, -0.5). To check this I rendered a ChArUco board in a way that has the board corners (not the marker corners) exactly at integer pixel coordinates. Both `_interpolateCornersCharucoApproxCalib` and `_interpolateCornersCharucoLocalHom` return exactly these coordinates already, however, `cornerSubpix` then optimizes that towards the top-left.
In the test `interpolateCornersCharuco` is once called with the `cameraMatrix` parameter, once without, so both paths …

aruco: fix subpixel coordinates in interpolateCornersCharuco

---

modules/aruco/include/opencv2/aruco/charuco.hpp
modules/aruco/misc/python/test/test_aruco.py

`drawCharucoBoard` function can be exported since `Vec4i` is wrapped in the core

Add wrapper to drawCharucoDiamond

---

modules/line_descriptor/include/opencv2/line_descriptor/descriptor.hpp
modules/line_descriptor/perf/perf_descriptors.cpp
modules/line_descriptor/perf/perf_detection.cpp
modules/line_descriptor/src/binary_descriptor.cpp
modules/line_descriptor/test/test_descriptors_regression.cpp
modules/line_descriptor/test/test_detector_regression.cpp

resolves https://github.com/opencv/opencv_contrib/issues/2524
relates #2020
<cut/>

Restore removed code

---

modules/cudacodec/perf/perf_video.cpp

OpenCV version: 4.5.3
Platform: Windows 10
Compiler: Visual Studio 2019
Cuda: 11.4
Nvidia Video SDK: 11.1.5
Description:
I compiled with Cuda, nvcuvid, tbb, mkl and got an error "CV_FOURCC identifier not found". Change CV_FOURCC to VideoWriter::fourcc solved the problem

Fix CV_FOURCC identifier not found while compiling

---

modules/text/samples/textdetection.py

- [ Y] I agree to contribute to the project under Apache 2 License.
- [ Y] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [ Y] The PR is proposed to proper branch
- [ N] There is reference to original bug report and related work
- [ N] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
- [ N] The feature is well documented and sample code can be built with the project CMake
The sample python code `opencv/opencv_contrib/modules/text/sample/textdetection.py` contained errors and could not be be run. Moreover, the code …

fixed /modules/text/textdetection.py sample

---

modules/viz/samples/viz_sample_02.py
modules/viz/samples/viz_sample_03.py

- Fixes multiple old viz function into new name
- Fix opencv bunny path for viz sample 3
- Fix viz sample 2 for proper cube rotation and example video is in here[1]
[1]: https://docs.opencv.org/4.5.3/d8/df0/tutorial_widget_pose.html

Viz3d sample fixes for python (sample 02 and 03) 

---

modules/cudawarping/test/test_remap.cpp

Related issue: https://github.com/opencv/opencv/issues/18224
Related fix in OpenCV: https://github.com/opencv/opencv/pull/20977
Fix as well as the issue addressed only BORDER_CONSTANT case; maybe later we should check issues for other borders too;
```
Xbuild_image:Custom=ubuntu-cuda:16.04
```

Add regression test for remap in case of overflow

---

modules/ximgproc/src/edge_drawing_common.hpp

add `[]` to array delete calls
(cppcheck found a few: "Mismatching allocation and deallocation" issues)

ximgproc: fix delete calls in edge_drawing_common

---

modules/aruco/tutorials/aruco_detection/aruco_detection.markdown

Fixes #3045
For the pose estimation example, the camera parameters are required. To work with examples from the tutorial, default camera parameters were added:
```
Size imgSize = inputImage.size();
cameraMatrix = Mat::eye(3, 3, CV_64FC1);
cameraMatrix.at<double>(0, 0) = cameraMatrix.at<double>(1, 1) = 650;
cameraMatrix.at<double>(0, 2) = imgSize.width / 2;
cameraMatrix.at<double>(1, 2) = imgSize.height / 2;
distCoeffs = Mat(5, 1, CV_64FC1, Scalar::all(0));
```

add camera parameters for the tutorial

---

modules/cudev/include/opencv2/cudev/functional/detail/color_cvt.hpp

fix a potential overflow bug in cv::cuda::cvtColor(cv::COLOR_Lab2BGR) func, which need to clamp on B/G/R.
```
Xbuild_image:Custom=ubuntu-cuda:18.04
```

Update color_cvt.hpp, fix a potential overflow bug in Lab2BGR func

---

modules/cudaarithm/include/opencv2/cudaarithm.hpp
modules/xobjdetect/src/lbpfeatures.cpp
modules/xobjdetect/src/precomp.hpp
modules/xobjdetect/src/waldboost.cpp
modules/xobjdetect/src/wbdetector.cpp

related https://github.com/opencv/opencv/issues/11000

fix legacy contants

---

modules/cudawarping/src/cuda/warp.cu

- To exclude data raises if warping is done in different streams
- Reduce amount of syscalls and memory transactions
```
```

Pass warping matrix as parameter instead of const memory

---

modules/rgbd/include/opencv2/rgbd/colored_kinfu.hpp
modules/rgbd/include/opencv2/rgbd/volume.hpp
modules/rgbd/src/colored_kinfu.cpp
modules/rgbd/src/colored_tsdf.cpp
modules/rgbd/src/colored_tsdf.hpp

rgbd: colored kinfu - allow fetching colors for pointcloud

---

modules/ximgproc/include/opencv2/ximgproc/edge_drawing.hpp
modules/ximgproc/src/edge_drawing.cpp

Simply adds an optional output to EdgeDrawing lineDetect() for getting the edge segment each line lies on.  
I need this for porting the [STag](https://github.com/bbenligiray/stag) library

EdgeDrawing: Add output of segment index for line detection

---

modules/cudastereo/src/cuda/stereobm.cu
modules/cudastereo/src/stereobm.cpp
modules/cudastereo/test/test_stereo.cpp

- Got rid of texture unit for xSobel mode;
- Implemented NORMALIZED_RESPONSE mode.
```
Xbuild_image:Custom=ubuntu-cuda:18.04
```

Prefiltering for cuda::stereoBM

---

modules/cudastereo/perf/perf_stereo.cpp
modules/cudastereo/src/cuda/stereobm.cu
modules/cudastereo/src/stereobm.cpp
modules/cudastereo/test/test_stereo.cpp

Merge with https://github.com/opencv/opencv_extra/pull/924
```
```

Uniqueness ratio support for cuda::StereoBM

---

modules/cudastereo/src/cuda/stereobm.cu
modules/cudastereo/test/test_stereo.cpp

```
Xbuild_image:Custom=ubuntu-cuda:18.04
```

Fixed cache initialization in cuda::stereoBM

---

modules/ovis/src/ovis.cpp

matches Ogre and makes more sense given float render targets are possible.

ovis: consistently use 0..1 value range for colors

---

modules/rgbd/src/hash_tsdf.cpp

Backport to 4.x from https://github.com/opencv/opencv/pull/21018

HashTSDF fixes backported

---

modules/line_descriptor/src/binary_descriptor.cpp

When extracted line segments number over given size of `lines.sId`(default: `5 * edges.numOfEdges`), it will result in array out of range, which further cause a segment fault as below. This is a small probability event, but it did happen in practical use.
```bash
*** Aborted at 1641264940 (unix time) try "date -d @1641264940" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x3e800001cc8) received by PID 7368 (TID 0x7ff538ff8700) from PID 7368; stack trace: ***
@     0x7ff56ff71390 (unknown)
@     0x7ff56e57e428 gsignal
@     0x7ff56e58002a abort
@     0x7ff56e5c07ea (unknown)
@     0x7ff56e5c79dc (unknown)
@     0x7ff56e5c9678 (unknown)
@     0x7ff56e5cd53c cfree
@     0x7ff56fb2787d cv::line_descriptor::BinaryDescriptor::EDLineDetector::~EDLineDetector()
@ …
```

Fix array out of range when too many line segments extracted

---

modules/xphoto/src/inpainting_fsr.impl.hpp

resolves #3152
- [ x ] I agree to contribute to the project under Apache 2 License.
- [ x ] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [ x ] The PR is proposed to proper branch
- [ x ] There is reference to original bug report and related work
- [ x ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
- [ x ] The feature is well documented and sample code can be built with the project CMake

https://github.com/opencv/opencv_contrib/issues/3152

---

modules/xphoto/src/inpainting.cpp
modules/xphoto/src/photomontage.hpp

resolves #1578
It's not THE SOLUTION because it does not fix the root cause (I don't know the algorithm) but it's a WORKAROUND to fix indexes out of bounds.
Using this changed I was able to do the inpaint (SHIFTMAP) on the example files.
- [ x ] I agree to contribute to the project under Apache 2 License.
- [ x ] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [ x ] The PR is proposed to proper branch
- [ x ] There is reference to original bug report and related work
- [ x ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
Patch to opencv_extra has the same …

https://github.com/opencv/opencv_contrib/issues/1578

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

relates https://github.com/opencv/opencv/pull/21454

Update ISSUE_TEMPLATE.md and PULL_REQUEST_TEMPLATE.md

---

modules/ximgproc/include/opencv2/ximgproc/edge_drawing.hpp
modules/ximgproc/src/edge_drawing.cpp

related: https://github.com/opencv/opencv_contrib/issues/2314

improvements on EdgeDrawing

---

modules/cudaarithm/test/test_gpumat.cpp

**Main PR**: https://github.com/opencv/opencv/pull/21555
Test case for `GpuMat::locateROI()` added to check `GpuMat::dataend` calculation.
Dependant on https://github.com/opencv/opencv/pull/21555.
```
```

Add GpuMat::locateROI test case

---

modules/sfm/src/libmv_light/libmv/correspondence/CMakeLists.txt

replaces #3012
Error is triggered by `-Wl,--no-undefined` compiler option.

cmake(sfm): fix sfm static target dependencies

---

modules/aruco/include/opencv2/aruco.hpp
modules/aruco/perf/perf_aruco.cpp
modules/aruco/perf/perf_main.cpp
modules/aruco/perf/perf_precomp.hpp
modules/aruco/samples/detect_markers.cpp
modules/aruco/samples/detector_params.yml
modules/aruco/src/aruco.cpp
modules/aruco/test/test_arucodetection.cpp
modules/aruco/test/test_boarddetection.cpp

Added improvements to the ArUco module made by the author @urbste. New PR was created to fix issues and rebase with 4.x (and to avoid regression in original PR).
- Original PR: opencv#2790
- [Original article](https://www.researchgate.net/publication/325787310_Speeded_Up_Detection_of_Squared_Fiducial_Markers)
This PR:
- adds new 3 performance tests (19 configurations)
- enables old tests with distance parameter 0.4 for ArUco3 (CV_ArucoBoardPose test)
- fix several "index" bugs
- removes global threshold parameters - to add this parameters need to add PImpl pattern and create `ArucoDetector` class (like QRCodeDetector class). I suggest return global threshold parameters in next PR after create `ArucoDetector` class and API changes (this changes could significantly increase "git diff"). …

Feature/aruco speedup (rebased with 4.x)

---

modules/cudaimgproc/doc/cudaimgproc.bib
modules/cudaimgproc/include/opencv2/cudaimgproc.hpp
modules/cudaimgproc/samples/connected_components.cpp
modules/cudaimgproc/src/connectedcomponents.cpp
modules/cudaimgproc/src/cuda/connectedcomponents.cu
modules/cudaimgproc/test/test_connectedcomponents.cpp

This pull request adds Connected Components Labeling in CUDA.
The implemented algorithm is [Block-Based Komura Equivalence](https://www.researchgate.net/publication/335183975_Optimized_Block-Based_Algorithms_to_Label_Connected_Components_on_GPUs).
```
force_builders=linux,docs,Custom
opencv_extra=4.x
```

Add Connected Components Labeling in CUDA

---

modules/cudafilters/src/filtering.cpp

This aplies the fix identified by @yl070360 in  https://github.com/opencv/opencv_contrib/issues/3163.
The stride information is currently missing inside `cuda::LinearFilter::apply()` producing incorrect results when `GpuMat`'s are constructed using pointers to pre-allocated device memory.
The current tests should to be sufficient to check this because they are wrongly passing at the moment due to another bug (see below) in the construction of `GpuMat`'s which can be fixed once this is merged.
**GpuMat Bug**
`GpuMat::dataend` wrongly points to the last element of an [alocated row ](https://github.com/opencv/opencv/blob/415a42f327104653604fc99314eb215cd938d6d7/modules/core/src/cuda/gpu_mat.cu#L191) instead of the last useable [element of the …

Add missing stride in cuda::LinearFilter::apply - #3163

---

README.md

Small grammatical updates to the readme file.

Grammatically updated the readme

---

modules/aruco/src/aruco.cpp
modules/aruco/test/test_charucodetection.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/935
Fixes https://github.com/opencv/opencv/issues/14014
Problem:
- `detectMarkers()` and `refineDetectedMarkers()` returns `OutputArrayOfArrays corners` and `rejectedCorners` with different dimensions (for similar cases).
- This problem is only relevant for vector<Mat> input.
- In this case `detectMarkers()` **always** returns `corners` and `rejectedCorners` as `vector<Mat>`, with Mat dimension **4x1**.
- In this case `refineDetectedMarkers()` works **differently**, if it finds a new marker. Then the dimension of Mats inside the `vector<Mat>` **changes** from **4x1** to **1x4**.
- The reason for the problem is that `detectMarkers()` and `refineDetectedMarkers()` create `corners` and `rejectedCorners` with different ways.
- …

fixed bad shape of markers (1x4) in several cases and added tests

---

modules/rgbd/include/opencv2/rgbd/colored_kinfu.hpp
modules/rgbd/include/opencv2/rgbd/kinfu.hpp
modules/rgbd/include/opencv2/rgbd/large_kinfu.hpp
modules/rgbd/src/colored_kinfu.cpp
modules/rgbd/src/kinfu.cpp
modules/rgbd/src/large_kinfu.cpp

**Main PR**: https://github.com/opencv/opencv/pull/21189
<cut/>

new Volume pipeline

---

modules/cudaimgproc/src/cuda/hough_segments.cu
modules/cudaimgproc/src/hough_segments.cpp
modules/cudaimgproc/test/test_hough.cpp

This PR fixes #3184 by using texture Object to make `cv::cuda::HoughSegmentDetectorImpl::detect()` thread-safe.
This PR also includes unit test for probabilistic hough segment detector. Previously, there was no unit test for this function.
Also note that, this solution is only thread-safe for `CV_CUDEV_ARCH>=300`. This is the same solution as existing code for canny algorithm that is already part of `opencv_contrib`. See here : https://github.com/opencv/opencv_contrib/commit/6ca24c818f8266c3a7e554e7a583dcdf5dc2010f
<cut/>
```
```

Use texture Object to make cv::cuda::HoughSegmentDetectorImpl::detect() thread-safe

---

modules/cudaarithm/include/opencv2/cudaarithm.hpp
modules/cudaarithm/src/reductions.cpp
modules/cudaarithm/test/test_reductions.cpp

Added 32FC1 type support and mask to cuda::meanStdDev implementation

---

modules/cudacodec/include/opencv2/cudacodec.hpp
modules/cudacodec/misc/python/test/test_cudacodec.py

Fix issue identified in https://github.com/opencv/opencv_contrib/issues/3195 by exposing cudacodec::VideoReader::format() to python bindings and updating the python test to check verify this.
```
```

Expose cudacodec::VideoReader::format() to python bindings

---

modules/aruco/include/opencv2/aruco.hpp
modules/aruco/src/aruco.cpp

fix [cv::aruco::detectMarkers consumes all available memory when CORNER_REFINE_CONTOUR #2738](https://github.com/opencv/opencv_contrib/issues/2738)
The problem is that `undistortPoints()` is missing for `nCorners`. Therefore, the algorithm does not find any corner points:
```
for ( unsigned int i =0; i < nContours.size(); i++ ) {
for(unsigned int j=0; j<4; j++){
if ( nCorners[j] == contour2f[i] ){ // nCorners[j] != contour2f[I] after `undistortPoints()`
cornerIndex[j] = i;
group=j;
}
}
cntPts[group].push_back(contour2f[i]);
}
```
The most logical solution is to make `undistort()` for the original image and look for ArUco markers on an undistorted image.
Also added a check that each of the four corners is found to avoid an infinite loop.
See details at …

fix CORNER REFINE CONTOUR

---

modules/aruco/src/aruco.cpp
modules/aruco/test/test_arucodetection.cpp
modules/aruco/test/test_charucodetection.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/965
This PR fixes:
- Unable to detect Aruco marker under some circumstances #3192 
- Aruco detection is worsened since OpenCV 4.1.2 #2492
The problem was in `_filterTooCloseCandidates()`. Fixed and added regression_3192, regression_2492 tests.
`opencv_extra=fix_filterTooCloseCandidates`

fix search for one contour in _filterTooCloseCandidates()

---

modules/cudaarithm/include/opencv2/cudaarithm.hpp
modules/cudaarithm/misc/python/test/test_cudaarithm.py

As reported [here](https://forum.opencv.org/t/how-to-use-the-cv-minmaxloc-function-in-python/8056) the python bindings do not output the results from both cuda::minMax and cuda::minMaxLoc.  This PR adds this functionality and includes a python test for verification.
```
```

Fix cuda::minMax and cuda::minMaxLoc python bindings

---

modules/cudacodec/include/opencv2/cudacodec.hpp
modules/cudacodec/src/video_decoder.hpp
modules/cudacodec/src/video_parser.cpp
modules/cudacodec/src/video_reader.cpp
modules/cudacodec/test/test_video.cpp

`cv::cudacodec::VideoReader` uses the minimum number of decode surfaces for correct decoding.  From the NVIDIA documentation:
> This guarantees correct functionality and optimal video memory usage but not necessarily the best performance, which depends on the design of the overall application. The optimal number of decode surfaces (in terms of performance and memory utilization) should be decided by experimentation for each application, but it cannot go below ..
Therefore this pull request allows the user to specify a higher minimum number of decode surfaces when creating `cv::cudacodec::VideoReader` to increase the decoding performace at the cost of GPU memory, if required.
<cut/>
Patch to …

Set higher minimum number of decode surfaces when creating cv::cudacodec::VideoReader

---

modules/wechat_qrcode/src/zxing/common/binarizer/hybrid_binarizer.cpp
modules/wechat_qrcode/src/zxing/common/binarizer/hybrid_binarizer.hpp

This should fixes #3156 #3008 
The size of block array `blocks_` is `subWidth * subHeight` but the block integral size is `width * height`. I believe something wrong when calculating the `blockIntegral` with that size.
https://github.com/opencv/opencv_contrib/blob/508c8db05e438635c84825629c069252bb53771a/modules/wechat_qrcode/src/zxing/common/binarizer/hybrid_binarizer.cpp#L41
https://github.com/opencv/opencv_contrib/blob/508c8db05e438635c84825629c069252bb53771a/modules/wechat_qrcode/src/zxing/common/binarizer/hybrid_binarizer.cpp#L58
I suggest change it size to `(subWidth + 1) * (subHeight + 1)` (These extra row and column is just for padding 0 arroud). Also update the precalculation of the `blockIntegral`, calculate sum base on that `blockIntegral`
See details at …

[WeChat QR] Fixing issue that Hybrid Binarizer not working due to integral calculation.

---

modules/ximgproc/src/edge_drawing.cpp

This is to quiet the -Wunused-but-set-parameter clang diagnostic warning.

Remove unused nrot variable.

---

modules/aruco/test/test_charucodetection.cpp

Merge with extra: https://github.com/opencv/opencv_extra/pull/969
This PR fix and enable `testBoardSubpixelCoords` test.
**Old test image:**
This ChArUco board configuration is currently not possible. The top left square should always be black.
**New test image:**
Blur added to the new test image to make the test more useful (the old image was also blurry, but not as much).

fix testBoardSubpixelCoords

---

modules/aruco/src/apriltag_quad_thresh.cpp
modules/aruco/test/test_arucodetection.cpp

Software entered infinite loop when image height
was smaller than 10*cv::getNumThreads(). With high
core count machines this could happen with very
reasonable image sizes.
Fix is to ensure that chunksize is at least 1.
The bug can be triggered with following test program:
```
#include <opencv2/aruco.hpp>
#include <opencv2/core/utility.hpp>
#include <iostream>
#include <opencv2/imgcodecs.hpp>
int main(int argc, char *argv[]) {
// Bug will happen even with 1 thread, but then the image
// will be too small to detect corners.
// cv::setNumThreads(1);
const auto num_th = cv::getNumThreads();
std::cout << "Number of threads: " << num_th << std::endl;
// If 'freeze' is set to true, bug is triggered
constexpr bool freeze = true;
std::cout << "Should freeze: " << freeze << std::endl;
// When …
```

Fix infinite loop on ArUco apriltag refinement

---

modules/aruco/include/opencv2/aruco.hpp
modules/aruco/include/opencv2/aruco/dictionary.hpp
modules/aruco/misc/python/test/test_aruco.py
modules/aruco/samples/aruco_dict_utils.cpp
modules/aruco/samples/calibrate_camera.cpp
modules/aruco/samples/calibrate_camera_charuco.cpp
modules/aruco/samples/create_board.cpp
modules/aruco/samples/create_board_charuco.cpp
modules/aruco/samples/create_marker.cpp
modules/aruco/samples/detect_board.cpp
modules/aruco/samples/detect_board_charuco.cpp
modules/aruco/samples/detect_diamonds.cpp
modules/aruco/samples/detect_markers.cpp
modules/aruco/src/aruco.cpp
modules/aruco/src/dictionary.cpp
modules/aruco/test/test_arucodetection.cpp
modules/aruco/test/test_charucodetection.cpp
modules/aruco/tutorials/aruco_faq/aruco_faq.markdown

This PR fixes:
- readDictionary() and readDetectorParameters() for Python
This PR adds:
- writeDictionary()
- add dict distance
- add dict utils sample

Aruco improvements

---

modules/aruco/test/test_arucodetection.cpp

Fix warning `comparison between signed and unsigned integer expressions` in `ArucoThreading` test from PR #3220.

Fix warning for Aruco threading test

---

modules/aruco/include/opencv2/aruco/dictionary.hpp
modules/aruco/misc/python/test/test_aruco.py

Added python bindings for `identify()/getDistanceToId()`

Add dictionary bindings

---

.github/workflows/PR-3.4-U20.yaml

This PR adds a workflow for GitHub Actions to build and test OpenCV Contrib on ubuntu-20.04 for 3.4 branch.

Workflow for Github Actions to build and test OpenCV on Linux for 3.4

---

modules/cudacodec/include/opencv2/cudacodec.hpp
modules/cudacodec/src/video_decoder.cpp
modules/cudacodec/src/video_reader.cpp
modules/cudacodec/test/test_video.cpp

Currently `VideoReader` only supports 8 bit YUV 422/420 video's.  This fix allows all supported YUV inputs 10 bit 420, and 8 and 16 bit 444 to be decoded.  The approach taken is to truncate all YUV formats to to NV12 instead of including CUDA kernels to convert from P016, YUV444 and YUV444_16Bit to BGR, which is probably overkill for OpenCV and can be included at a later date if desired.
The PR also allows the raw YUV frame to be output as well if desired.

Force VideoReader to decode all YUV video formats to NV12

---

modules/sfm/src/libmv_light/libmv/simple_pipeline/bundle.cc

Use ceres::Manifolds instead of ceres::LocalParameterization.
The latter is deprecated.
This fixes https://github.com/opencv/opencv_contrib/issues/3218

Use ceres::Manifolds instead of ceres::LocalParameterization.

---

modules/cudacodec/include/opencv2/cudacodec.hpp
modules/cudacodec/src/frame_queue.cpp
modules/cudacodec/src/frame_queue.hpp
modules/cudacodec/src/video_decoder.cpp
modules/cudacodec/src/video_parser.cpp
modules/cudacodec/src/video_parser.hpp
modules/cudacodec/src/video_reader.cpp
modules/cudacodec/test/test_video.cpp

Add the below two features to `cudacodec::VideoReader` to help when streaming from live sources.
1) Lift the limit on the maximum number of unparsed packets if streaming from a source over UDP, see https://github.com/opencv/opencv_contrib/issues/3225#issuecomment-1100206377
2) Internally drop frames if the rate which frames are requested by `nextFrame()/grab()` is less than the source FPS.  Although this is something which a user would eventually accomodate for themselves (by reading at the appropriate rate and choosing which packets to discard) it would be a useful for this to be "automatic" until they have implemented that functionality.
Testing - currently the additional tests only check that the new parameters have been set inside `VideoReader` and do not verify the functionality of …

Add RTSP features to cudacodec::VideoReader

---

modules/bioinspired/include/opencv2/bioinspired/retina.hpp
modules/bioinspired/include/opencv2/bioinspired/transientareassegmentationmodule.hpp
modules/bioinspired/src/retina.cpp
modules/bioinspired/src/retina_ocl.cpp
modules/bioinspired/src/retina_ocl.hpp
modules/bioinspired/src/transientareassegmentationmodule.cpp
modules/rgbd/include/opencv2/rgbd/colored_kinfu.hpp
modules/rgbd/include/opencv2/rgbd/dynafu.hpp
modules/rgbd/include/opencv2/rgbd/kinfu.hpp
modules/rgbd/include/opencv2/rgbd/large_kinfu.hpp
modules/rgbd/src/colored_kinfu.cpp
modules/rgbd/src/dynafu.cpp
modules/rgbd/src/kinfu.cpp
modules/rgbd/src/large_kinfu.cpp
modules/xfeatures2d/src/msd_pyramid.hpp

Applying https://github.com/opencv/opencv/pull/22041 to contrib.

remove const from functions returning by value

---

modules/cudacodec/include/opencv2/cudacodec.hpp
modules/cudacodec/misc/python/test/test_cudacodec.py
modules/cudacodec/src/video_reader.cpp
modules/cudacodec/test/test_video.cpp
modules/cudastereo/include/opencv2/cudastereo.hpp
modules/cudastereo/misc/python/test/test_cudastereo.py

The python bindings for `cudastero::reprojectImageTo3D` (see https://forum.opencv.org/t/cv2-cuda-reprojectimageto3d-dispcu-q-error-5-bad-argument/5242) and some newere methods in `cudacodec::VideoReader` and  are not functioning correctly.
The PR fixes this issue and adds tests to check the input output functionality.

Fix cudacodec and cudastereo python bindings

---

modules/aruco/src/aruco.cpp

aruco: fix missing solvePnP parameter, build warning

---

modules/cudastereo/src/cuda/stereobm.cu

Without this fix, the error is:
"ordered comparison between pointer and zero ('volatile unsigned int *' and 'int')"

Fix compilation because of pointer/int comparison.

---

modules/ovis/src/ovis.cpp

Hi, this fixes the build error that I started to get while building the ovis module with OGRE 1.12.9 since OpenCV 4.6.0.
The error was:
```
/home/pro/projects/opencv-lib/opencv-4.6/opencv_contrib-4.6.0/modules/ovis/src/ovis.cpp: In member function ‘virtual void cv::ovis::WindowSceneImpl::setBackground(cv::InputArray)’:
/home/pro/projects/opencv-lib/opencv-4.6/opencv_contrib-4.6.0/modules/ovis/src/ovis.cpp:456:65: error: cannot convert ‘std::__shared_ptr_access<Ogre::Material, __gnu_cxx::_S_atomic, false, false>::element_type’ {aka ‘Ogre::Material’} to ‘const String&’
456 |                 RTShader::ShaderGenerator::DEFAULT_SCHEME_NAME, *bgplane->getMaterial());
|                                                                 ^~~~~~~~~~~~~~~~~~~~~~~
| …
```

Fix ovis module building error with OGRE 1.12.9

---

modules/sfm/src/libmv_light/libmv/simple_pipeline/bundle.cc

Fixes #3270 . 
When using the ceres manifold, we should set the manifold instead of the parameterization. 
This was tested by building successfully with the latest ceres, which previously failed. 

Fix ceres manifold build

---

.github/workflows/PR-3.4.yaml

4.x: #3280
5.x: #3279
Main PR: https://github.com/opencv/opencv/pull/22103

Add workflows for macOS ARM64 and macOS x86_64 for branch 3.4

---

modules/freetype/include/opencv2/freetype.hpp
modules/freetype/src/freetype.cpp
modules/freetype/test/test_basic.cpp
modules/freetype/test/test_main.cpp
modules/freetype/test/test_precomp.hpp
modules/freetype/test/test_putText.cpp

Fix https://github.com/opencv/opencv_contrib/issues/2009 (Request for 8UC4)
Fix https://github.com/opencv/opencv_contrib/issues/3276 (Request for 8UC1)
Related https://github.com/opencv/opencv_extra/pull/981
- [ X There is accuracy test, performance test and test data in opencv_extra repository, if applicable

freetype: support 8UC1/8UC4 image

---

modules/sfm/CMakeLists.txt

The latest version of glog provides native CMake support, meaning that find_package(glog) can be used without hassle. The Ceres project supports this. However, if Ceres finds the new glog, it sets variables glog_FOUND and not Glog_FOUND, which the CMakeLists.txt of the SFM module checks for. The assumption that glog has not been found then leads to errors later on, as valid variables are replaced with NOT-FOUND in the following search scripts.
This PR adds support for the new glog by simply checking for both Glog_FOUND AND glog_FOUND. While there may be more sophisticated ways to solve this (e.g. I would recommend updating FindGlog.cmake to the newest version included in Ceres) this seemed to be the minimal effort solution which worked for me, at least as a temporary fix before newer …

Allow new glog in SFM CMake Project

---

modules/cudaimgproc/src/cuda/gftt.cu
modules/cudaimgproc/src/gftt.cpp

Fixes https://github.com/opencv/opencv_contrib/issues/3042, also mentioned in https://github.com/opencv/opencv_contrib/pull/2868
Also added a fix for https://github.com/opencv/opencv_contrib/issues/3194
Fixes cuda mem leak in `GoodFeaturesToTrackDetector` and moves cuda malloc/free into the ctor/dtor, out of critical path

Fix CUDA mem leak in GFTT and move CUDA malloc out of critical path

---

modules/aruco/CMakeLists.txt
modules/ccalib/CMakeLists.txt
modules/datasets/CMakeLists.txt
modules/dnn_objdetect/CMakeLists.txt
modules/dpm/CMakeLists.txt
modules/face/CMakeLists.txt
modules/line_descriptor/CMakeLists.txt
modules/optflow/CMakeLists.txt
modules/rgbd/CMakeLists.txt
modules/text/CMakeLists.txt
modules/tracking/CMakeLists.txt
modules/xfeatures2d/CMakeLists.txt
modules/ximgproc/CMakeLists.txt
modules/xobjdetect/CMakeLists.txt
modules/xphoto/CMakeLists.txt

**Main PR**: https://github.com/opencv/opencv/pull/22350
revert #3298

build: rework psabi warning

---

modules/sfm/src/libmv_light/libmv/multiview/robust_estimation.h

```
uint is defined in sys/types.h in Linux for compatibility.
But it is not defined in Win32 platform. This fixes the following error:
opencv_contrib/modules/sfm/src/libmv_light/libmv/multiview/robust_estimation.h:59:8: error: 'uint' does not name a type; did you mean 'int'?
59 | static uint IterationsRequired(int min_samples,
|        ^~~~
|        int
```

sfm: Fix unknown uint type error in mingw

---

modules/matlab/CMakeLists.txt

This fixes #3312 
Previously the OpenCV modules was found using `CMAKE_SOURCE_DIR` which always points to the top level CMake directory. 
Using `OpenCV_SOURCE_DIR` allows for a more robust way of getting the path to the OpenCV modules root and ensures that the `HDR_PARSER_PATH` is correctly set.

matlab: Use OpenCV_SOURCE_DIR instead of CMAKE_SOURCE_DIR to find the modules root

---

modules/cudacodec/src/ffmpeg_video_source.cpp
modules/cudacodec/test/test_video.cpp

Currently cudacodec does not support all the codecs supported by nvdec or all possible fourcc codes returned by FFmpeg.  This PR should address this by adding the av1 codec and dealing with all combinations of upper/lower case and 3 character fourcc combinations.

Add support for missing codecs to cudacodec

---

modules/barcode/src/detector/bardetect.cpp

Without this fix, we will get a floating point error in `calCoherence` method due to divide by zero.

Set window_size to 1 if round down results in 0 for barcodes

---

modules/mcc/src/common.cpp
modules/mcc/src/common.hpp

To match the input data type.
Cast inner computation to double to prevent int overflows for any input type.

Use T as temp var type in polyanticlockwise()

---

modules/sfm/src/libmv_light/libmv/numeric/numeric.h

```
sincos function is defined by mingw-w64 for both 32 bit and 64 bit environments.
Previously, sincos function was hidden for 64 bit mingw-w64 with __MINGW64__ macro.
This change also hides the sincos definition for 32 bit mingw-w64 with __MINGW32__ macro.
```

sfm: Fix redefinition error in 32 bit mingw-w64 environment

---

modules/wechat_qrcode/src/decodermgr.cpp
modules/wechat_qrcode/src/decodermgr.hpp
modules/wechat_qrcode/src/wechat_qrcode.cpp
modules/wechat_qrcode/test/test_qrcode.cpp

WeChat detectAndDecode() return "raw" and inaccurate corners.

fix output qr corners

---

modules/mcc/src/checker_detector.cpp
modules/mcc/src/checker_detector.hpp

The argument size of get_subbox_chart_physical() is unused.
get_subbox_chart_physical() is called only in one place.
The local variable h could overflow the cast to int and lead to a SIGILL in some environments, see https://github.com/opencv/opencv_contrib/issues/3320.

Remove unused size of get_subbox_chart_physical()

---

modules/aruco/src/aruco_detector.cpp
modules/aruco/src/charuco.cpp
modules/aruco/test/test_boarddetection.cpp

fixes #3327
```
force_builders=linux,Win64
```

fix aruco: build warnings (MSVS 2015)

---

modules/cudacodec/CMakeLists.txt
modules/cudacodec/include/opencv2/cudacodec.hpp
modules/cudacodec/src/video_decoder.cpp
modules/cudacodec/src/video_decoder.hpp
modules/cudacodec/src/video_parser.cpp
modules/cudacodec/src/video_reader.cpp
modules/cudacodec/test/test_precomp.hpp
modules/cudacodec/test/test_video.cpp

Nivida's Video Codec SDK allows the user to specify the following parameters  to control the final output:
- Scaling dimension
- Cropping dimension
- Dimension if the user wants to change the aspect ratio
this pull request adds this capability to `cudacodec::VideoReader`.
From local experiments this does not effect the decoding utilization, however choosing for example a smaller ROI from the decoded video stream reduces the CUDA overhead from the post processing routines (ConvertNV12BLtoNV12).  
Additionaly [this ](https://github.com/cudawarped/opencv_contrib/blob/587207bd9bca9c555e4549ae8f8d4fad0de8275c/modules/cudacodec/src/video_parser.cpp#L128) addition makes the checks described in https://github.com/opencv/opencv_contrib/pull/3001 unecessary.
See details at …

Add scaling and cropping options to `cudacodec::VideoReader`

---

modules/cudacodec/src/frame_queue.cpp
modules/cudacodec/src/frame_queue.hpp
modules/cudacodec/src/video_reader.cpp

In https://github.com/opencv/opencv_contrib/pull/3098 I carelessly introduced a memory leak, this fix should address that issue.

Fix memory leak in cudacodec

---

.vscode/settings.json
modules/wechat_qrcode/samples/qrcode_example_without_nn.cpp
modules/wechat_qrcode/samples/qrcode_without_nn.py
modules/wechat_qrcode/src/decodermgr.cpp
modules/wechat_qrcode/src/decodermgr.hpp
modules/wechat_qrcode/src/wechat_qrcode.cpp
modules/wechat_qrcode/src/zxing/qrcode/qrcode_reader.cpp
modules/wechat_qrcode/src/zxing/qrcode/qrcode_reader.hpp
modules/wechat_qrcode/src/zxing/reader.cpp
modules/wechat_qrcode/src/zxing/reader.hpp
modules/wechat_qrcode/test/test_qrcode.cpp

A new PR based on the top of 4.x and fix the conflicts
related issus https://github.com/opencv/opencv_contrib/issues/3343

fix the bug that cannot detect multi qrcode when use_nn_detector is false

---

modules/xphoto/src/inpainting_fsr.impl.hpp

resolves #2855
use a temporal Mat header for convertTo()
(this goes to the 4.x branch, there is no fsr inpainting in 3.4)

xphoto fix inpaint fsr

---

modules/cvv/CMakeLists.txt
modules/cvv/src/qtutil/matchview/matchscene.cpp
modules/cvv/src/qtutil/matchview/singlecolorkeypointpen.cpp
modules/cvv/src/qtutil/matchview/singlecolormatchpen.cpp
modules/cvv/src/qtutil/matchview/zoomableproxyobject.cpp
modules/cvv/src/qtutil/zoomableimage.cpp
modules/cvv/src/qtutil/zoomableimage.hpp
modules/cvv/src/stfl/stfl_engine.hpp

OpenCV can be compiled against Qt5 and Qt6. The Contrib CVV module depends on Qt5 and has received an incomplete patch with #3072 that allows configuring but not compiling. CVV previously used some features that were deprecated in Qt5 and removed in Qt6.
This patch replaces the corresponding lines in the source code with functions that work in Qt5.15 LTS and Qt6.
This does fix the Issue #3146.
Note: CVV still uses `QRegExp` which can not directly replaced by `QRegularExpression`. Therefor Qt6 moved `QRegExp` to the module `Core5Compat`, which requires a `find_package` because it is not required by OpenCV main project.
<cut/>
- This is a bug fix without additional tests.
- It would be useful to add a CI pipeline which builds against Qt6 or …

make CVV module work with Qt6

---

modules/cudacodec/include/opencv2/cudacodec.hpp
modules/cudacodec/src/video_writer.cpp

Fix https://github.com/opencv/opencv/issues/22721#issuecomment-1304837204

Fix opencv issue #22721

---

modules/cudacodec/src/NvEncoder.cpp
modules/cudacodec/src/NvEncoder.h

Remove previously unsued variable which has been depreciated and prevented building against Nvidia Video Codec SDK 12.

Update cudacodec to build against Nvidia Video Codec SDK 12

---

modules/ximgproc/src/find_ellipses.cpp
modules/ximgproc/test/test_find_ellipses.cpp

**Main PR**: https://github.com/opencv/opencv/pull/22940
```
force_builders=Win64,Win64 OpenCL
```

build: fix/eliminate MSVC warnings

---

modules/rgbd/src/colored_kinfu.cpp
modules/rgbd/src/dynafu.cpp
modules/rgbd/src/kinfu.cpp
modules/rgbd/src/large_kinfu.cpp

Connected PR in main repo: [#22925@main](https://github.com/opencv/opencv/pull/22925)
`OdometryFrame` constructor signature changed to more convenient where depth goes at 1st place, RGB image at 2nd.
This works better for depth-only `Odometry` algorithms.

OdometryFrame: arg order changed

---

modules/cudev/include/opencv2/cudev/common.hpp

Make behaviour of `cudev::checkCudaError()` consistent with `cuda::checkCudaError()`.  See [Reset cuda runtime error code to cudasuccess on runtime failure.](https://github.com/opencv/opencv/pull/22633) for details.

Reset cuda runtime error code to cudasuccess on runtime failure.

---

modules/cudaarithm/src/arithm.cpp

on some CUDA versions creating/destroying cufftPlan2d is very time consuming we now create/destroy them in ConvolveImpl::create() when `dft_size` change and destroy them in the dtor
this solves issue #3385

keep cufftPlan2d across ConvolveImpl::convolve calls

---

modules/cnn_3dobj/include/opencv2/cnn_3dobj.hpp
modules/cudalegacy/src/fgd.cpp
modules/freetype/src/precomp.hpp
modules/rgbd/samples/linemod.cpp

There were several places where obsolete API has been used. I could not fully test these changes (_cudalegacy_ and _rgbd_ example), but build process is fine.
This PR must be merged before opencv/opencv#22754 to preserve compatibility. Technically this PR can be backported to 4.x, I think.

C-API cleanup for OpenCV 5.x (imgproc, highgui)

---

modules/ximgproc/include/opencv2/ximgproc/find_ellipses.hpp
modules/ximgproc/samples/find_ellipses.py
modules/ximgproc/src/find_ellipses.cpp

Update find ellipses

---

modules/aruco/misc/pattern_generator/MarkerPrinter.py

This change replaces references to a number of deprecated NumPy type aliases (np.bool, np.int, np.float, np.complex, np.object, np.str) with their recommended replacement (bool, int, float, complex, object, str).
Those types were deprecated in 1.20 and are removed in 1.24, cf numpy/numpy#22607.

Remove references to deprecated NumPy type aliases.

---

modules/aruco/include/opencv2/aruco.hpp
modules/aruco/samples/detect_board.cpp
modules/aruco/samples/detect_markers.cpp
modules/aruco/tutorials/aruco_board_detection/aruco_board_detection.markdown
modules/aruco/tutorials/aruco_detection/aruco_detection.markdown

Fix code snippets and some text in Aruco tutorial.

Fix aruco tutorials

---

modules/cudev/test/test_cvt.cu

Fix additional CUDA 12.0 build errors not observed in https://github.com/opencv/opencv/issues/23034 introduced when cudev tests are built (without world).
Companion fix to https://github.com/opencv/opencv/pull/23037
Confirmed builds with  CUDA 12.0, CuDNN 8.7.0.84, Nvidia Video Codec SDK 12.0 on both
- Windows 11 22H2: Visual Studio 2022 (17.43)
- Ubuntu 20.04 LTS (WSL): g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

Fix CUDA 12.0 build errors

---

modules/cudalegacy/src/cuda/NCVBroxOpticalFlow.cu
modules/cudawarping/test/test_remap.cpp
modules/cudev/include/opencv2/cudev/ptr2d/texture.hpp

This fixes issue https://github.com/opencv/opencv_contrib/issues/3412 returning incorrect results for single `GpuMat`'s with a single row, which was a result of an error in https://github.com/opencv/opencv_contrib/pull/3378.
Unfortunatley because `GpuMat`'s with a single row or column are allocated with `cudaMalloc` and not `cudaMallocPitch` and 2D texture objects require pitched memory this PR introduces extra staging memory, when the row/col dimension is 1.  This is a quick fix for the issue which only introduces extra overhead for single dimension `GpuMat`'s who's use should not be that common.
A "better" fix would be to rework the `TexturePtr` class so that
```
__device__ __forceinline__ R operator ()(index_type y, index_type x) const;
```
staticly dispatches a call to `tex1Dfetch` …

cudev: fix 1D error introduced in PR 3378

---

modules/cudev/include/opencv2/cudev/ptr2d/texture.hpp
modules/xfeatures2d/src/cuda/surf.cu

similar to #3417, but this one starts from 4.x
```
FilterMode, cudaTextureAddressMode, cudaTextureReadMode)’:
/opencv_contrib/modules/cudev/include/opencv2/cudev/ptr2d/texture.hpp:254:99: warning: declaration of ‘xoff’ shadows a member of ‘cv::cudev::TextureOff<T, R>’ [-Wshadow]
254 |             const cudaTextureAddressMode addressMode = cudaAddressModeClamp, const cudaTextureReadMode readMode = cudaReadModeElementType) :
|                                                                                                   ^
/opencv_contrib/modules/cudev/include/opencv2/cudev/ptr2d/texture.hpp:267:14: note: shadowed declaration is here
267 |         int xoff = 0;
|             ^~~~
/opencv_contrib/modules/cudev/include/opencv2/cudev/ptr2d/texture.hpp:254:99: warning: declaration of ‘yoff’ …
```

build: fix warnings

---

modules/xfeatures2d/test/test_surf.cuda.cpp
modules/xfeatures2d/test/test_surf.ocl.cpp

closes #3377
relates #2587
Stop using condition build and make the test itself tolerance to rounding error.
Sooner or later same issue might appear on OpenCL implementation, so make the UMat version also telerate

SURF: make test tolerate to rounding error

---

modules/alphamat/include/opencv2/alphamat.hpp

alphamat header depends on `InputArray`, `OutputArray` and `CV_EXPORTS_W` but doesn't include related opencv2/core.hpp, so this header can break depending on include order.

Make alphamat public header auto sufficient

---

modules/optflow/src/rlofflow.cpp

The bug has already been reported and explained on the OpenCV forum:
- [optflow-calcopticalflowsparserlof-giving-assertion-error](https://forum.opencv.org/t/cv2-optflow-calcopticalflowsparserlof-giving-assertion-error/4835)
- [calcopticalflowsparserlof-assertion-error-in-initialflow](https://forum.opencv.org/t/calcopticalflowsparserlof-assertion-error-in-initialflow/8669)
The bug is manifested only if 'UseInitialFlow' is set to true and 'ForwardBackwardThreshold' > 0 (enabled).

RLOF OptFlow Bug Fix

---

modules/ccalib/src/ccalib.cpp
modules/line_descriptor/src/binary_descriptor_matcher.cpp
modules/stereo/src/stereo_binary_bm.cpp
modules/structured_light/src/graycodepattern.cpp
modules/tracking/src/multiTracker.cpp
modules/tracking/src/tldDetector.cpp
modules/ximgproc/src/brightedges.cpp

Patch for 4.x: https://github.com/opencv/opencv_contrib/pull/3434
Merge with https://github.com/opencv/opencv/pull/23214

3.4: -Wunused-but-set-variable warnings fix after XCode update

---

modules/rgbd/samples/linemod.cpp

Flag CAP_OPENNI is obsolete. It Changed to CAP_OPENNI2 flag.

changed CAP_OPENNI flag to CAP_OPENNI2 in linemod sample

---

modules/rgbd/samples/linemod.cpp

Because CAP_OPENNI flag is obsolete. It was removed from openCV. 

changed CAP_OPENNI to CAP_OPENNI2 flag

---

modules/cudaimgproc/include/opencv2/cudaimgproc.hpp
modules/cudaimgproc/src/cuda/hough_segments.cu
modules/cudaimgproc/src/hough_segments.cpp

Tested locally that looks working roughly as much as non-CUDA counterpart relying on `threshold`.
Does not modify the behavior of existing call without the parameter. Doc comment simply copied from https://github.com/opencv/opencv/blob/4.x/modules/imgproc/include/opencv2/imgproc.hpp.
Closes #3444.
Closes #3023.

Add `threshold` parameter to cuda::HoughSegmentDetector

---

modules/cudacodec/include/opencv2/cudacodec.hpp
modules/cudacodec/src/cuda/nv12_to_rgb.cu
modules/cudacodec/src/precomp.hpp
modules/cudacodec/src/video_parser.cpp
modules/cudacodec/src/video_reader.cpp
modules/cudacodec/test/test_video.cpp

Fixes https://github.com/opencv/opencv_contrib/issues/3458.
Dependent on https://github.com/opencv/opencv_extra/pull/1051

`cudacodec::VideoReader`: fix nv12 to bgr/bgra/grey conversion

---

modules/cudacodec/src/video_parser.cpp
modules/cudacodec/test/test_video.cpp

Now that cropping can automatically be applied inside `cudacodec::VideoReader` (https://github.com/opencv/opencv_contrib/pull/3355) in addition to the fixes in https://github.com/opencv/opencv_contrib/pull/3001 this PR automatically removes any redundant rows in decoded video's.  E.g 1080p is internally decoded to 1920x1088, currently this results in a 1920x1088 frame being returned from `VideoReader->nextFrame()` which the user has to manually crop using the information contained in `VideoReader::FormatInfo`, with this PR it will result in a 1920x1080 frame being returned.
This resolves issues such as https://github.com/opencv/opencv_contrib/issues/3195 and https://github.com/opencv/opencv/issues/21207#issuecomment-1473930858
See details at …

`cudacodec::VideoReader`: force output frame resolution to be display not coded size

---

modules/text/include/opencv2/text/ocr.hpp
modules/text/src/ocr_tesseract.cpp

Fix https://github.com/opencv/opencv_contrib/issues/3457
This patch changes char_whitelist default from [0-9a-zA-Z] to all characters.
Current setting text module missrecognizes in CJK and other languages in default because it accepts only [0-9a-zA-Z]. 
And in "eng" language, wordlist contains some characters outside of [0-9a-zA-Z].
Those words are not recognized with default parameters.
So to disable whitelist is better than using "0-9a-zA-Z". 

text: change default char_whitelist parameter.

---

modules/cudacodec/include/opencv2/cudacodec.hpp
modules/cudacodec/src/frame_queue.cpp
modules/cudacodec/src/frame_queue.hpp
modules/cudacodec/src/video_decoder.cpp
modules/cudacodec/src/video_decoder.hpp
modules/cudacodec/src/video_parser.cpp
modules/cudacodec/src/video_parser.hpp
modules/cudacodec/test/test_video.cpp

Add decoder reconfiguration functionality on resolution change, see [Nvidia Docs](https://docs.nvidia.com/video-technologies/video-codec-sdk/nvdec-video-decoder-api-prog-guide/index.html#reconfiguring-the-decoder).
PR test is dependent on multi-resolution test video from https://github.com/opencv/opencv_extra/pull/1047

`cudacodec::VideoReader` add reconfigure decoder functionality

---

modules/cudacodec/src/video_decoder.cpp
modules/cudacodec/src/video_decoder.hpp
modules/cudacodec/src/video_reader.cpp
modules/cudacodec/test/test_video.cpp

As discussed in https://github.com/opencv/opencv_contrib/pull/3468#discussion_r1165613962 it would be useful if `VideoReader::FormatInfo` was valid in the constructor to make validation tasks simpler.

`cudacodec::VideoReader` - ensure `FormatInfo.valid == true` on return from constructor

---

modules/cudacodec/src/ffmpeg_video_source.cpp
modules/cudacodec/test/test_video.cpp

Update `cudacodec::VideoReader` to use codec fourcc.
Dependant on https://github.com/opencv/opencv/pull/23540

`cudacodec::VideoReader` FORCC update with main #23540

---

modules/cudacodec/src/video_decoder.cpp
modules/cudacodec/src/video_reader.cpp

The minor version which is compared to the `CUDART_VERSION` inside `cudacodec::VideoReader` is an order of magnitude too big.

`cudacodec::VideoReader` - fix CUDART_VERSION tests

---

modules/cudaimgproc/src/cuda/hist.cu
modules/cudaimgproc/src/histogram.cpp
modules/cudaimgproc/test/test_histogram.cpp

Modified histogram kernels to work with non aligned data to fix https://github.com/opencv/opencv_contrib/issues/3473.

Modified histogram kernels to work with non aligned data

---

modules/ximgproc/src/find_ellipses.cpp

Relates to https://github.com/opencv/opencv_contrib/pull/3322
More accurate replacement for https://github.com/opencv/opencv_contrib/pull/3393

Fixed memory leak in EllipseDetector and Mat addressing

---

modules/cudacodec/include/opencv2/cudacodec.hpp
modules/cudacodec/misc/python/test/test_cudacodec.py
modules/cudacodec/src/video_decoder.cpp
modules/cudacodec/src/video_decoder.hpp
modules/cudacodec/src/video_parser.cpp
modules/cudacodec/src/video_reader.cpp
modules/cudacodec/src/video_source.cpp
modules/cudacodec/test/test_video.cpp

Histogram data is collected by NVDEC during the decoding process resulting in zero performance penalty, details can be found under [Getting Histogram Data](https://docs.nvidia.com/video-technologies/video-codec-sdk/12.0/nvdec-video-decoder-api-prog-guide/index.html#Getting-histogram-data) in the Nvidia Video SDK docs.
This PR allows that histogram to be requested and if supported returned from `VideoReader::nextFrame`.  Both C++ and python tests have been included.
Additionaly:
1. A utility function `MapHist()` has been included to remap the histogram when `FormatInfo::videoFullRangeFlag == false`
2. Errors in `test_cudacodec.py` have been addressed, this could be performed in an additional PR if necessary?
See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-goo …

`cudacodec::VideoReader` return luma hist from `nextFrame` if requested

---

modules/cudacodec/misc/python/test/test_cudacodec.py
modules/cudaoptflow/misc/python/test/test_nvidiaopticalflow.py

1. Not all GPUs support histogram generation by codec. Related to https://github.com/opencv/opencv_contrib/pull/3477.
2. Syntax fixes

Fixed several test failures in Python tests for CUDA modules

---

modules/cudacodec/include/opencv2/cudacodec.hpp
modules/cudacodec/src/video_decoder.hpp

Avoid `using namespace` statements in public header without any reason.
merge after opencv/opencv#24029 and opencv/opencv#24046

fix: remove using namespace cuda from public header

---

modules/face/samples/landmarks_demo.py

The [landmarks_demo.py](https://github.com/opencv/opencv_contrib/blob/4593e631b2771ee3f449742672b6a700966dc6be/modules/face/samples/landmarks_demo.py) fails with a cryptic error when no faces are detected in the input image. Added some error handling so that this behavior is more transparent.
See issue [here](https://github.com/opencv/opencv_contrib/issues/3548) and forum discussion [here](https://forum.opencv.org/t/troubleshooting-15-bad-number-of-channels-for-face-landmarks-detection/14199).

small improvement to landmarks_demo.py

---

modules/ximgproc/src/find_ellipses.cpp
modules/ximgproc/src/lsc.cpp
modules/ximgproc/src/run_length_morphology.cpp
modules/ximgproc/src/sparse_match_interpolators.cpp

This is opencv_contrib part of [this PR](https://github.com/opencv/opencv/pull/24232) to opencv itself.
NB: we only build superres, optflow and ximgproc modules, so I can not be sure if all similar problems have been fixed.

Add missing std namespace qualifiers

---

modules/cudaimgproc/test/test_histogram.cpp
modules/cudev/include/opencv2/cudev/util/vec_traits.hpp
modules/cudev/test/test_nd.cu
modules/face/src/facemarkAAM.cpp
modules/face/src/facemarkLBF.cpp
modules/face/test/test_facemark_aam.cpp
modules/intensity_transform/src/bimef.cpp
modules/mcc/src/colorspace.cpp
modules/rapid/src/rapid.cpp
modules/wechat_qrcode/test/test_qrcode.cpp
modules/xphoto/test/test_oil_painting.cpp

this is a satellite for https://github.com/opencv/opencv/pull/23473

attempt to add 0d/1d mat support

---

modules/rgbd/src/tsdf_functions.hpp

related https://github.com/opencv/ci-gha-workflow/pull/111
One function in tsdf was not wrapped by an appropriate macro guard.

Fixed compilation with SIMD disabled or with scalable SIMD

---

modules/aruco/src/charuco.cpp

use diamond detector instead of board detector in detectCharucoDiamond()

fix wrong detector in detectCharucoDiamond

---

modules/cudacodec/include/opencv2/cudacodec.hpp
modules/cudacodec/src/NvEncoder.cpp
modules/cudacodec/src/NvEncoder.h
modules/cudacodec/src/video_writer.cpp
modules/cudacodec/test/test_video.cpp

Where supported, allows the raw encoded video output from Nvidia's hardware decoder to be encapsulated in a suitable (mp4/mkv/etc.) container.
Dependant on https://github.com/opencv/opencv/pull/24363.
Fixes https://github.com/opencv/opencv_contrib/issues/3556

`cudacodec::VideoWriter` add container output

---

modules/cudaarithm/test/test_event.cpp
modules/datasets/src/tinyxml2/tinyxml2.h
modules/xphoto/src/oilpainting.cpp

Set of build fixes for ## 3580, 3574.

---

modules/cudacodec/include/opencv2/cudacodec.hpp
modules/cudacodec/src/ffmpeg_video_source.cpp
modules/cudacodec/src/ffmpeg_video_source.hpp
modules/cudacodec/src/video_reader.cpp
modules/cudacodec/src/video_source.cpp
modules/cudacodec/src/video_source.hpp
modules/cudacodec/test/test_video.cpp

Allow seeking of video source on initialization of `cudacodec::VideoReader` when new variable `VideoReaderInitParams::iFirstFrame` != 0.
Dependant on https://github.com/opencv/opencv/pull/24012
Fixes https://github.com/opencv/opencv_contrib/issues/3541.

`cudacodec::VideoReader`: allow frame seek on initialization

---

modules/freetype/include/opencv2/freetype.hpp
modules/freetype/src/freetype.cpp
modules/freetype/test/test_basic.cpp

Original pull request is https://github.com/opencv/opencv_contrib/pull/3586 .
Current pull request contains additional patches for review.

freetype: Add function to load font from buffer(additional patch)

---

modules/freetype/include/opencv2/freetype.hpp
modules/freetype/src/freetype.cpp
modules/freetype/test/test_basic.cpp

There currently is no way to load a freetype font from a memory buffer (for example embedded resources etc). This small PR adds a simple function adding that functionality.

freetype: Add function to load font from buffer

---

modules/cudaoptflow/src/farneback.cpp
modules/cudaoptflow/test/test_optflow.cpp

Fix https://github.com/opencv/opencv/issues/24540 and add test to confirm.

`cudaoptflow`: fix `FarnebackOpticalFlow` internal stream synchronization when used with an external CUDA stream

---

modules/xfeatures2d/include/opencv2/xfeatures2d.hpp
modules/xfeatures2d/misc/python/test/test_descriptors.py

Fixes https://github.com/opencv/opencv_contrib/issues/3589

Binding fix for matchLOGOS with python test.

---

modules/xfeatures2d/src/cuda/surf.cu

In case if `OPENCV_ENABLE_NONFREE` disabled, the kernel was still included into binary, but not available via API.

Disable SUFF CUDA kenrel build by default

---

modules/README.md
modules/signal/CMakeLists.txt
modules/signal/README.md
modules/signal/include/opencv2/signal.hpp
modules/signal/include/opencv2/signal/signal_resample.hpp
modules/signal/perf/perf_main.cpp
modules/signal/perf/perf_precomp.hpp
modules/signal/perf/perf_resample.cpp
modules/signal/src/precomp.hpp
modules/signal/src/signal_resample.cpp
modules/signal/test/test_main.cpp
modules/signal/test/test_precomp.hpp
modules/signal/test/test_signal.cpp

Added signal module with resampling function implemented with cubic interpolation function and a filtering function based on Kaiser window and Bessel function, used to construct a FIR filter.
Detail: https://en.wikipedia.org/wiki/Sample-rate_conversion
There are provided:
* signal resampling API
* optimization done with universal intrinsics
* functional tests with reference signals
* performance tests
```
force_builders=Linux x64 Debug,Win32,ARMv7,ARMv8
```

Add signal module with signal resampling function

---

modules/cudaimgproc/include/opencv2/cudaimgproc.hpp
modules/cudaimgproc/src/cuda/moments.cu
modules/cudaimgproc/src/moments.cpp
modules/cudaimgproc/test/test_moments.cpp

Fix https://github.com/opencv/opencv_contrib/issues/3612 and address out of bounds memory error when not calculating all image moments.

`cudaimgproc`: update for CUDA 8.0 and fix out of bounds memory error in `cuda::moments`

---

modules/cudacodec/src/ffmpeg_video_source.cpp
modules/cudacodec/src/video_writer.cpp
modules/cudacodec/test/test_video.cpp

Enable disabled windows features (https://github.com/opencv/opencv_contrib/pull/3569, https://github.com/opencv/opencv_contrib/pull/3488, https://github.com/opencv/opencv_contrib/pull/3542) which are now available in the ffmpeg shared libary.

`cudacodec`: Enable features available with updated ffmpeg dll

---

modules/signal/src/signal_resample.cpp

fixup #3613
failed weekly validation:
- http://pullrequest.opencv.org/buildbot/builders/4_x-contrib_coverage-lin64-debug/builds/100049
- http://pullrequest.opencv.org/buildbot/builders/4_x-contrib_valgrind-lin64-debug/builds/100049
Caused by memory access errors in AVX mode.
<cut/>
Perf report:
|Name of Test|scalar base|SSE42 base|Scalar PATCH|SSE42 PATCH|AVX2 PATCH|
|---|:-:|:-:|:-:|:-:|:-:|
|resample_sin_signal::TestResampleFunc::(1234, 16000, 16000)|0.000|0.000|0.000|0.000|0.000|
|resample_sin_signal::TestResampleFunc::(1234, 16000, 32000)|0.043|0.047|0.044|0.043|0.032|
|resample_sin_signal::TestResampleFunc::(1234, 16000, 44100)|0.055|0.054|0.052|0.052|0.035|
|resample_sin_signal::TestResampleFunc::(1234, 16000, 48000)|0.057|0.055|0.054|0.052|0.037| …

signal: fix memory access

---

modules/sfm/CMakeLists.txt
modules/sfm/src/libmv_light/libmv/correspondence/CMakeLists.txt
modules/sfm/src/libmv_light/libmv/multiview/CMakeLists.txt
modules/sfm/src/libmv_light/libmv/numeric/CMakeLists.txt
modules/sfm/src/libmv_light/libmv/simple_pipeline/CMakeLists.txt

Fix https://github.com/opencv/opencv/issues/24890
```
kmtr@ubuntu:~/work/build4-full$ ls lib/*.a
lib/libopencv.sfm.correspondence.a  lib/libopencv.sfm.numeric.a
lib/libopencv.sfm.multiview.a       lib/libopencv.sfm.simple_pipeline.a
```
- At creating pull request, this issue is located at opencv issue, not opencv_contrib issue.
- My test is to check build only, because this fix changes only CMakeLists.txt

sfm: add opencv.sfm prefix for static libraries

---

modules/README.md
modules/ccalib/CMakeLists.txt
modules/ccalib/src/precomp.hpp
modules/cudacodec/src/ffmpeg_video_source.cpp
modules/cudacodec/src/video_writer.cpp
modules/cudacodec/test/test_video.cpp
modules/cudaimgproc/include/opencv2/cudaimgproc.hpp
modules/cudaimgproc/src/cuda/moments.cu
modules/cudaimgproc/src/moments.cpp
modules/cudaimgproc/test/test_moments.cpp
modules/sfm/CMakeLists.txt
modules/sfm/src/libmv_light/libmv/correspondence/CMakeLists.txt
modules/sfm/src/libmv_light/libmv/multiview/CMakeLists.txt
modules/sfm/src/libmv_light/libmv/numeric/CMakeLists.txt
modules/sfm/src/libmv_light/libmv/simple_pipeline/CMakeLists.txt
modules/signal/CMakeLists.txt
modules/signal/README.md
modules/signal/include/opencv2/signal.hpp
modules/signal/include/opencv2/signal/signal_resample.hpp
modules/signal/perf/perf_main.cpp
modules/signal/perf/perf_precomp.hpp
modules/signal/perf/perf_resample.cpp
modules/signal/src/precomp.hpp
modules/signal/src/signal_resample.cpp
modules/signal/test/test_main.cpp
modules/signal/test/test_precomp.hpp
modules/signal/test/test_signal.cpp

Related PR in main repo: https://github.com/opencv/opencv/pull/24912
Related PR in extra: https://github.com/opencv/opencv_extra/pull/1144
#3613 from amishutin:signal_module
#3615 from cudawarped:cudacodec_enable_win32_for_updated_dll
#3616 from vrabaud:4.x
#3618 from cudawarped:cudaimgproc_moments_fix
#3620 from opencv-pushbot:gitee/alalek/signal_hotfix
#3624 from Kumataro:fix24890
Previous "Merge 4.x": #3621

5.x merge 4.x

---

modules/cudaimgproc/include/opencv2/cudaimgproc.hpp
modules/cudaimgproc/src/gftt.cpp

Currently, there is no way to change max corners & min distance once GoodFeaturesToTrackDetector is created.

add maxconers and mindistance setter to gftt

---

modules/cudafeatures2d/src/brute_force_matcher.cpp

After I started using a mask with `knnMatchAsync`, I found that the result from `knnMatchConvert` would be clipped at random.
Investigating the issue, I found that `knnMatchAsync` will initialize all `trainIdx` to `-1`, which will be overwritten by the CUDA kernel. A mask can be used to prevent certain features from being matched and this will prevent the CUDA kernel from setting the match distance. `knnMatchConvert` is not properly incrementing the pointers when `trainIdx == -1`, so an unmatched feature will get it stuck at `if (trainIdx == -1)`. Eventually the outer for-loop finishes and returns a vector with the matches up until the first missing match distance.
My solution is to increment the counters the same way as a succesful iteration would.
See details at …

Fix a bug in knnMatchConvert when a feature couldn't be matched

---

modules/alphamat/README.md
modules/aruco/README.md
modules/line_descriptor/README.md

- [N/A] There is a reference to the original bug report and related work
- [N/A] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
- [+] The feature is well documented and sample code can be built with the project CMake

updated readme for several opencv_contrib modules (done by Gary)

---

modules/cannops/CMakeLists.txt
modules/cannops/ascendc_kernels/CMakeLists.txt
modules/cannops/ascendc_kernels/kernel_tiling_types.h
modules/cannops/ascendc_kernels/threshold_opencv_kernel.cpp
modules/cannops/ascendc_kernels/vector_tiling.h
modules/cannops/include/opencv2/ascendc_kernels.hpp
modules/cannops/include/opencv2/cann_call.hpp
modules/cannops/perf/perf_element_operations.cpp
modules/cannops/src/ascend_mat.cpp
modules/cannops/src/cann_call.cpp
modules/cannops/src/element_operations.cpp
modules/cannops/src/precomp.hpp
modules/cannops/test/test_element_operations.cpp
modules/cannops/test/test_kernel.cpp
modules/cannops/test/test_precomp.hpp

AscendC is an extended syntax for the C/C++ language that can be used to write operators that run on Ascend NPU.
This commit introduce an operator(threshold) written in AscendC. Others can refer to this to implement other operators.
AscendC can implement efficient fusion operators according to needs, in this case, threshold execution speed increased by nearly 4 times.
- N/A There is a reference to the original bug report and related work

Enable AscendC kernel operator

---

modules/xfeatures2d/src/latch.cpp

Fixes https://github.com/opencv/opencv/issues/25081
As mentioned by WennPaper making it `grayImage = image.clone();` will make a deep copy. It prevents the `InputArray` from being modified.

fixes #25081:Latch input corruption fix

---

modules/mcc/src/checker_detector.cpp
modules/mcc/test/test_mcc.cpp

merge with https://github.com/opencv/opencv_extra/pull/1153
Added a full pipeline tests:
1. detector->process(img, (TYPECHART)0, 1, true);
2. ColorCorrectionModel model(src, COLORCHECKER_Macbeth); model.run();
3. calibratedImage = model.infer(calibratedImage)*255.;

add to mcc detect and infer test

---

modules/aruco/test/test_aruco_tutorial.cpp

Because the tests are failing, e.g. https://pullrequest.opencv.org/buildbot/builders/precommit-contrib_linux64/builds/101043/steps/test_aruco/logs/tests%20summary
relates #3401

fix aruco tests

---

modules/wechat_qrcode/perf/perf_wechat_qrcode_pipeline.cpp
modules/wechat_qrcode/src/decodermgr.cpp
modules/wechat_qrcode/src/zxing/common/unicomblock.cpp

Two simple fixes to We Char QR Code module:
\- decodemgr.cpp: fix messed: width <--> height
\- unicomblock.cpp: fix wrong type at `sizeof(...)`
```
```

4.x: Two simple fixes to We Chat QR Code module

---

modules/wechat_qrcode/src/zxing/qrcode/detector/finder_pattern_finder.cpp
modules/wechat_qrcode/test/test_qrcode.cpp

Should fix weekly valgrind builds.

wechat: fix uninitialized values in tests

---

modules/wechat_qrcode/src/wechat_qrcode.cpp

Data corruption may lead to incorrect results if multiple QR found at image
```
```

4.x: Fix data corruption in WeChatQRCode::impl::decode

---

modules/videostab/src/precomp.hpp
modules/wechat_qrcode/src/zxing/common/binarizer/adaptive_threshold_mean_binarizer.cpp
modules/xphoto/src/annf.hpp
modules/xphoto/src/gcgraph.hpp
modules/xphoto/src/inpainting.cpp
modules/xphoto/src/norm2.hpp
modules/xphoto/src/oilpainting.cpp
modules/xphoto/src/photomontage.hpp

This is necessary to get https://github.com/opencv/opencv/pull/25248 working.

Use proper C++ types.

---

modules/mcc/perf/perf_main.cpp
modules/mcc/perf/perf_mcc.cpp
modules/mcc/perf/perf_precomp.hpp
modules/mcc/src/ccm.cpp
modules/mcc/src/checker_detector.cpp
modules/mcc/src/colorspace.cpp
modules/mcc/src/colorspace.hpp
modules/mcc/src/utils.cpp
modules/mcc/src/utils.hpp

Added perf tests to mcc module.
Also these optimizations have been added:
- added `parallel_for_` to `performThreshold()`
- removed `toL`/`fromL` and added `dst` to avoid copy data
- added `parallel_for_` to `elementWise()` ("batch" optimization improves performance of Windows version, Linux without changes).
Configuration:
Ryzen 5950X, 2x16 GB 3000 MHz DDR4
OS: Windows 10, Ubuntu 20.04.5 LTS
Performance results in milliseconds:
| OS and alg version   | process, ms | infer, ms |
| -------------------- | ----- | ------ |
| win_default          | 63.09 | 457.57 |
| win_optimized_without_batch       | 48.69 | 111.78 |
| win_optimized_batch  | 48.42 | 47.28  |
| linux_default        | 50.88 | 300.7  |
| linux_optimized_batch| 36.06 | 41.62  |
See details at …

Mcc add perf tests improve performance

---

modules/mcc/include/opencv2/mcc/checker_model.hpp
modules/mcc/src/checker_detector.cpp
modules/mcc/src/checker_detector.hpp
modules/mcc/src/checker_model.cpp
modules/mcc/src/checker_model.hpp

merge this PR after https://github.com/opencv/opencv_contrib/pull/3647
Computes and returns the coordinates of the central parts of the charts modules.

added getColorCharts()

---

modules/ximgproc/perf/perf_thining.cpp
modules/ximgproc/src/thinning.cpp

This implement of `cv::ximgproc::thinning` achieves the same results as the original codes but with improvement in efficiency(10x speedup).
However, there are a few issues with this PR:
- Loss of Code Readability: The implementation sacrifices code readability for performance. To mitigate this, I have retained the original code and commented it out, so it remains accessible for reference.
- Lack of Expertise in OpenCV Development: The implementation may seem inelegant, I am uncertain whether this approach is good enough.

Faster thinning implementation

---

modules/aruco/test/test_aruco_tutorial.cpp

Add detectDiamonds() + goldDiamondCorners to diamond test

add detectDiamonds to diamond test

---

modules/xfeatures2d/misc/java/test/MSDFeatureDetectorTest.java

This patch is need to merge same time with  https://github.com/opencv/opencv/pull/25351
If you merge only one or the other, MSDFeatureDetectorTest will be failed.

xfeatures2d: MSDFeatureDetector: output reals as human-friendly expression

---

modules/cudacodec/src/NvEncoder.cpp

fix #3711 by updating *NVEncoder.cpp* to reflect the changes contained in Nvidia's sample code.

cudacodec: fix #3711 (update for Nvidia Video Codec SDK 12.2)

---

modules/ximgproc/src/fast_line_detector.cpp

Fixes https://github.com/opencv/opencv_contrib/issues/3715
This bug can be recurrent when there are only two segments on one line , if `do_merge` is set to be true. 
The `while` loop will not enter in , then output has still two segments but not one merged one segment.

fix not merging when there are only two segs on one line

---

modules/tracking/doc/tracking.bib
modules/tracking/include/opencv2/tracking/twist.hpp
modules/tracking/src/twist.cpp
modules/tracking/test/test_twist.cpp

---
see https://github.com/opencv/opencv_contrib/pull/3641
cc @simutisernestas @savuor
I prefer to use `computeInteractionMatrix()` instead of `getInteractionMatrix()` naming.
I have added references to some classical papers on this subject. Even if it is out of scope, they can be useful.
Warning, one bibtex reference already exist in the main `opencv` repo. I don't know if we can use `@cite` defined in the main repo?

Rename getInteractionMatrix() to computeInteractionMatrix()

---

modules/ovis/CMakeLists.txt
modules/ovis/samples/aruco_ar_demo.cpp
modules/ovis/samples/aruco_ar_demo.py
modules/ovis/src/ovis.cpp

ovis: force camera extent update to get correct bbox

---

modules/face/src/facemarkLBF.cpp
modules/face/src/mace.cpp
modules/mcc/test/test_mcc.cpp
modules/rgbd/perf/perf_tsdf.cpp
modules/rgbd/test/ocl/test_tsdf.cpp
modules/rgbd/test/test_colored_kinfu.cpp
modules/rgbd/test/test_kinfu.cpp
modules/rgbd/test/test_tsdf.cpp
modules/videostab/src/global_motion.cpp
modules/ximgproc/test/test_sparse_match_interpolator.cpp

Fixed Wredundant-move produced by GCC 13.2 (Ubuntu 24.04).

---

modules/cudaarithm/src/reductions.cpp

A slight API change of nppiMeanStdDevGetBufferHostSize_8u_C1R and nppiMeanStdDevGetBufferHostSize_32f_C1R in NPP of CUDA 12 has caused the #3725. I will try to fix this. I found that the type of bufSize is `size_t` instead of `int` in the `reductions.cpp` in the NPP header file, where the ` nppi_statistics_functions.h`  changed the type of second parameter from` * int` to `* size_t`.
**nppi_statistics_functions.h 5392:5408**
```
NppStatus 
nppiMeanStdDevGetBufferHostSize_32f_C1R_Ctx(NppiSize oSizeROI, size_t * hpBufferSize/* host pointer */, NppStreamContext nppStreamCtx);
/** 
* Buffer size for \ref nppiMean_StdDev_32f_C1R.
* 
* For common parameter descriptions, see \ref CommonMeanStdDevGetBufferHostSizeParameters.
*
*/
NppStatus 
nppiMeanStdDevGetBufferHostSize_32f_C1R(NppiSize …
```

Try to Fix #3725: cudaarithm: fix the compile faiure of CUDA 12.

---

modules/ximgproc/doc/ximgproc.bib
modules/ximgproc/include/opencv2/ximgproc/edge_filter.hpp
modules/ximgproc/perf/perf_guided_filter.cpp
modules/ximgproc/src/guided_filter.cpp
modules/ximgproc/test/test_guided_filter.cpp

This PR implements fast guided filter. The concept is explained in this [paper](https://arxiv.org/pdf/1505.00996.pdf).
TLDR:
Added a 'scale' parameter to the current guided filter interface, allowing resampling inside the algorithm, to speed up computation. The resampling has to be done inside guided filter because the intermediate result has to be combined with original input to generate the final result.
The performance and behavior of the default code path (scale == 1.0) is unaltered. [before](https://pullrequest.opencv.org/buildbot/builders/precommit-contrib_linux64/builds/100981/steps/perf_ximgproc/logs/stdio) vs [after](https://pullrequest.opencv.org/buildbot/builders/precommit-contrib_linux64/builds/100980/steps/perf_ximgproc/logs/stdio)
See details at …

Implement fast guided filter

---

modules/cudaimgproc/src/histogram.cpp

This fixes https://github.com/opencv/opencv_contrib/issues/3741

Get code to compile with CUDA 12.4

---

modules/ximgproc/src/thinning.cpp
modules/ximgproc/test/test_thinning.cpp

- edges could be modified
- 2 sets of iterations were always done even if the first set did not return any change
- countNonZero is slow compared to hasNonZero

Misc thinning fixes.

---

modules/cudaarithm/src/cuda/polar_cart.cu
modules/cudaarithm/src/cuda/split_merge.cu
modules/cudev/include/opencv2/cudev/block/detail/reduce.hpp
modules/cudev/include/opencv2/cudev/block/detail/reduce_key_val.hpp
modules/cudev/include/opencv2/cudev/block/reduce.hpp
modules/cudev/include/opencv2/cudev/grid/detail/split_merge.hpp
modules/cudev/include/opencv2/cudev/grid/detail/transform.hpp
modules/cudev/include/opencv2/cudev/grid/split_merge.hpp
modules/cudev/include/opencv2/cudev/grid/transform.hpp
modules/cudev/include/opencv2/cudev/ptr2d/glob.hpp
modules/cudev/include/opencv2/cudev/ptr2d/zip.hpp
modules/cudev/test/test_split_merge.cu

Tries to fix https://github.com/opencv/opencv_contrib/issues/3690 for CUDA 12.4+
Related patch to main repo: https://github.com/opencv/opencv/pull/25658
Changes:
- Added branches to support new variadic implementation of thrust::tuple
- Added branch with std::array instead of std::tuple in split-merge and grid operations. The new branch got rid of namespace clash: cv::cuda in OpenCV and ::cuda in CUDA standard library (injected by Thrust). Old tuple branches presumed for compatibility with old code and CUDA versions before 12.4.

Added CUDA 12.4+ support

---

modules/cudev/include/opencv2/cudev/ptr2d/zip.hpp

Fixes https://github.com/opencv/opencv_contrib/issues/3752
Adds a preprocessor check to conditionally include <cuda/std/tuple>  only for CUDA versions 12.4 and above. This ensures backward compatibility  with older legacy CUDA versions.
Related to pull request #3744

Add conditional include for <cuda/std/tuple> to support CUDA 12.4+

---

.github/PULL_REQUEST_TEMPLATE.md

Force contributors to define Apache 2.0 license for the new PRs

---

modules/cudafilters/include/opencv2/cudafilters.hpp
modules/cudafilters/src/filtering.cpp
modules/cudafilters/test/test_filters.cpp

[#25408](https://github.com/opencv/opencv/issues/25408)
When only 1D convolution is needed (row or column filter only), `cuda::LinearFilter` might be slower than `cuda::SeparableLinearFilter`
Using `cuda::SeparableLinearFilter` for 1D convolution can be done by using a `(1)` kernel for the ignored dimension.
By supporting empty kernels in `cuda::SeparableLinearFilter`, there is no need for that `(1)` kernel any more.
Additionaly, the inner `_buf ` used to store the intermediate convolution result can be saved when a single convolution is needed.
In "legacy" usage (row+col kernels), there is no regression in `cuda::SeparableLinearFilter` performance.
As soon as an empty kernel is used, the performance is largely increased.
Devil in the details : the "in-place" processing is supported and …

supports empty kernels in cuda::SeparableLinearFilters

---

modules/ml/tutorials/cpp_ml/introduction_to_svm/introduction_to_svm.markdown
modules/ml/tutorials/cpp_ml/non_linear_svms/non_linear_svms.markdown

Correct some links in the tutorials

---

modules/face/samples/sample_face_swapping.cpp
modules/rapid/src/rapid.cpp
modules/xfeatures2d/test/test_features2d.cpp
modules/xfeatures2d/test/test_keypoints.cpp

Related https://github.com/opencv/opencv/pull/26022

imgproc: use double to determine whether the corners points are within src

---

modules/viz/misc/python/test/test_viz_simple.py

As per https://numpy.org/doc/stable/numpy_2_0_migration_guide.html for users of NumPy 2.0.
Also https://numpy.org/doc/stable/reference/constants.html#numpy.nan says
> NaN and NAN are aliases of `nan`.

Replace np.NAN by np.nan in test_viz_simple.py

---

modules/ml/src/rtrees.cpp

Port of https://github.com/opencv/opencv/pull/26046
Speedup `DTreesImplForRTrees::getVotes` method in about x2 times.
`Mat` objects are usually not expensive for creation or copying. But if algorithm itself is fast, operations on `Mat` objects start to take significant time. Naive extraction of loop invariant temporary `Mat` wrapper object creation allows to decrease `getVotes` method run time in about x2 times.

speedup random forest getVotes method.

---

modules/cudacodec/include/opencv2/cudacodec.hpp
modules/cudacodec/src/NvEncoder.cpp
modules/cudacodec/src/NvEncoder.h
modules/cudacodec/src/video_writer.cpp
modules/cudacodec/test/test_video.cpp

Update `cudacodec::VideoWriter` to set the correct PTS when using P frames using properties (`CAP_PROP_PTS` and `CAP_PROP_DTS_DELAY`) added in https://github.com/opencv/opencv/pull/25874

`cudacodec`: update `VideoWriter` to correctly set the PTS inside the encapsulated video stream

---

modules/wechat_qrcode/src/zxing/zxing.hpp

fix #3150
Merge with https://github.com/opencv/opencv/pull/23881
Reference: https://stackoverflow.com/questions/7263404/mingw32-stdisnan-with-ffast-math

fix(wechat_code): Modify `isnan` for compatibility with -ffast_math.

---

modules/bioinspired/src/retina_ocl.cpp
modules/bioinspired/src/retinafasttonemapping.cpp
modules/bioinspired/src/transientareassegmentationmodule.cpp
modules/ml/src/svm.cpp
modules/tracking/src/trackerBoostingModel.cpp
modules/tracking/src/trackerFeature.cpp
modules/tracking/src/trackerStateEstimator.cpp
modules/videostab/src/frame_source.cpp

Fixed build error after OpenCV #26101.

---

modules/dpm/samples/cascade_detect_camera.cpp

C-API cleanup: highgui, videoio

---

modules/wechat_qrcode/src/zxing/zxing.hpp

Address CI warning:
```
c:\build\precommit_windows64\4.x\opencv_contrib\modules\wechat_qrcode\src\zxing\common\../zxing.hpp(58): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning) [C:\build\precommit_windows64\build\modules\wechat_qrcode\opencv_wechat_qrcode.vcxproj]
c:\build\precommit_windows64\4.x\opencv_contrib\modules\wechat_qrcode\src\zxing\common\../zxing.hpp(59): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning) [C:\build\precommit_windows64\build\modules\wechat_qrcode\opencv_wechat_qrcode.vcxproj]
```
Introduced in https://github.com/opencv/opencv_contrib/pull/3490

Build warning fix on Windows.

---

modules/cudaarithm/src/cuda/polar_cart.cu

Fixes https://github.com/opencv/opencv_contrib/issues/3773

Workaround for CUDA 12.6 tuple_size issue #3773.

---

modules/ml/misc/python/test/test_digits.py
modules/xfeatures2d/test/test_detectors.cpp

Merge with https://github.com/opencv/opencv/pull/25984
New`onfusionMatrixes[1]` is
```
[[45  0  0  0  0  0  0  0  0  0]
[ 0 57  0  0  0  0  0  0  0  0]
[ 0  0 58  2  0  0  0  0  1  0]
[ 0  0  0 43  0  0  0  1  0  0]
[ 0  0  0  0 39  0  0  0  0  1]
[ 0  0  0  1  0 49  0  0  1  0]
[ 0  0  0  0  0  0 52  0  0  0]
[ 0  0  1  0  0  0  0 54  0  0]
[ 0  0  0  0  0  0  0  0 47  0]
[ 0  1  0  1  0  0  0  0  2 44]]
```
which is about of pixel value 1 shift in each 4x or 5x pixel value.

slightly alter threshold for warpAffine optimization

---

modules/dnn_superres/src/dnn_superres.cpp
modules/text/src/ocr_holistic.cpp

This is a companion for https://github.com/opencv/opencv/pull/26056

New dnn engine

---

modules/cudev/test/test_cvt.cu
modules/julia/gen/funclist.csv

Behavour change: cuda::convertFp16 returns CV_16F instead of CV_16S for fp16 values. 
Main PR: https://github.com/opencv/opencv/pull/26327

drop convertFp16 in favor of cv::Mat::convertTo.

---

modules/cudaarithm/src/arithm.cpp
modules/cudaarithm/src/cuda/polar_cart.cu
modules/cudaarithm/src/element_operations.cpp
modules/cudaarithm/src/reductions.cpp
modules/cudacodec/src/cuda/nv12_to_rgb.cu
modules/cudaimgproc/src/color.cpp
modules/cudaimgproc/src/connectedcomponents.cpp
modules/cudaimgproc/src/cuda/canny.cu
modules/cudaimgproc/src/cuda/connectedcomponents.cu
modules/cudaimgproc/src/cuda/generalized_hough.cu
modules/cudaimgproc/src/cuda/hough_circles.cu
modules/cudaimgproc/src/cuda/hough_lines.cu
modules/cudaimgproc/src/cuda/hough_segments.cu
modules/cudaimgproc/src/cuda/moments.cu
modules/cudaimgproc/src/histogram.cpp
modules/cudaimgproc/src/moments.cpp
modules/cudaoptflow/src/cuda/farneback.cu
modules/cudaoptflow/src/cuda/nvidiaOpticalFlow.cu
modules/cudaoptflow/src/farneback.cpp
modules/cudaoptflow/src/precomp.hpp
modules/cudev/include/opencv2/cudev/grid/detail/minmaxloc.hpp
modules/hfs/src/cuda/gslic_seg_engine_gpu.cu
modules/hfs/src/cuda/magnitude.cu

Changelist:
- there are some syntactic changes: `<< <` -> `<<<`. For some reason, I do not need to change all those in the code.
-  `::min` -> `std::min` in `__host__` code
- `modules/cudaimgproc/src/moments.cpp` needs to have the CUDA code in the `#ifdef`
- The signature of `cv::cuda::swapChannels` is not exactly the same as the C++ one in `modules/cudaimgproc/src/color.cpp` 
- `cv::cuda::FarnebackOpticalFlow::create` needs to be explicit about which FarnebackOpticalFlow it returns

Get CUDA code to compile with clang CUDA and without CUDA

---

modules/cudaarithm/include/opencv2/cudaarithm.hpp
modules/cudaarithm/misc/python/test/test_cudaarithm.py

Fix https://github.com/opencv/opencv_contrib/issues/3814 by adding python specific overloads.

`cudaarithm`: fix python bindings for binary ops involving scalars

---

modules/cudaarithm/src/core.cpp
modules/cudaarithm/src/cuda/bitwise_scalar.cu
modules/cudaarithm/src/cuda/threshold.cu
modules/cudaarithm/src/cuda/transpose.cu
modules/cudaarithm/src/element_operations.cpp
modules/cudaarithm/src/reductions.cpp
modules/cudacodec/src/video_reader.cpp
modules/cudafilters/src/filtering.cpp
modules/cudaimgproc/src/color.cpp
modules/cudaimgproc/src/histogram.cpp
modules/cudawarping/src/warp.cpp

Requires changes in https://github.com/opencv/opencv/pull/26245
Update calls to Nvidia's NPP library to use the newer NppStreamContext API introduced in CUDA 10.1 ([release notes](https://docs.nvidia.com/cuda/archive/10.1/cuda-toolkit-release-notes/index.html#npp-new-features))
Although this was introduced in CUDA 10.1 at that point not all of the functions either had a `_Ctx` version which took a `NppStreamContext` or an implementation present in the NPP library.  Therefore in this PR the `USE_NPP_STREAM_CTX` flag which selects the new API is only enabled for versions of NPP >= 12205 (the version included with CUDA toolkit 12.4) which I have verified as working.  Currently the only function called inside OpenCV which does not work with the new API is `nppiEvenLevelsHost_32s_Ctx` which …

cuda - update npp calls to use the new NppStreamContext API if available

---

modules/wechat_qrcode/src/zxing/qrcode/qrcode_reader.cpp

This PR fixes a logic error in the `QRCodeReader::decode` function
when handling inverted images. Previously, the function would return
an empty result list even when successful decoding occurred on an
inverted image. The change ensure that:
1. If decoding fails on the original image, we attempt decoding on an inverted image.
2. If decoding succeeds on the inverted image, we now correctly return those results.
3. We maintain the behavior of returning an empty list if both original and inverted image decoding fail.

wechat_qrcode: fix ineffective decoding retrial after inverting image

---

modules/cudaimgproc/src/histogram.cpp

In https://github.com/opencv/opencv_contrib/pull/3803 the `NppStreamHandler` was added for the `nppiEvenLevelsHost_32s`  due to the documentation having a streaming version (_Ctx see https://docs.nvidia.com/cuda/archive/11.0/npp/group__image__histogrameven.html#ga1586db7ec07d9a7b5929b981e99676e0).  I have since found out that this is a host-only function and the header for the streaming version will be removed in the next version of CUDA so unnecessary delay from the call to `NppStreamHandler` can be removed.

`cudaimgproc`: remove incorrectly added `NppStreamHandler` from `cv::cuda:evenLevels`

---

modules/xfeatures2d/include/opencv2/xfeatures2d.hpp
modules/xfeatures2d/src/tbmr.cpp

all other contrib feature has this function but tbmr

getDefaultName() added

---

modules/ximgproc/src/find_ellipses.cpp

The `ximgproc::findEllipses` function modifies the src image during execution, resulting in a blurred output.
This PR ensures that the source image remains unchanged.

Fix: ximgproc::findEllipses modifies src image unexpectedly

---

modules/gapi/test/gapi_sample_pipelines.cpp

Port of https://github.com/opencv/opencv/pull/26529

Fixed missing include chrono in g-api tests

---

modules/dnn_superres/src/dnn_superres.cpp

Workaround for https://github.com/opencv/opencv_contrib/issues/3833

Force to use dnn_supperres module to the use classic engine

---

modules/cudalegacy/include/opencv2/cudalegacy.hpp
modules/cudalegacy/src/NCV.cpp
modules/cudalegacy/src/cuda/NCVBroxOpticalFlow.cu
modules/cudalegacy/src/cuda/NCVHaarObjectDetection.cu
modules/cudalegacy/src/cuda/NCVPixelOperations.hpp
modules/cudalegacy/src/cuda/NPP_staging.cu
modules/cudalegacy/src/cuda/needle_map.cu
modules/cudalegacy/src/precomp.hpp

Get cudalegacy to compile with clang CUDA and without CUDA

---

modules/text/src/erfilter.cpp

- cast to calicurate mixing different enums
- initilize member variables
related https://github.com/opencv/opencv/pull/26590

support C++20 standard

---

modules/fastcv/test/test_smooth.cpp

Test files updated: `baboon` instead of `lena`, amount of files reduced
Connected PR: https://github.com/opencv/opencv_extra/pull/1222

FastCV bilateral recursive: test files updated

---

modules/cudalegacy/include/opencv2/cudalegacy/private.hpp

This was actually forgotten in https://github.com/opencv/opencv_contrib/pull/3843
This is useful for some modules because of https://github.com/opencv/opencv_contrib/blob/1b841632ef188078ae545d2755556cbb7f06b084/modules/cudaobjdetect/src/precomp.hpp#L59

Get cudalegacy dependents to build without CUDA

---

modules/fastcv/include/opencv2/fastcv.hpp
modules/fastcv/include/opencv2/fastcv/histogram.hpp
modules/fastcv/include/opencv2/fastcv/moments.hpp
modules/fastcv/perf/perf_bilateral.cpp
modules/fastcv/perf/perf_histogram.cpp
modules/fastcv/src/bilateralFilter.cpp
modules/fastcv/src/histogram.cpp
modules/fastcv/src/moments.cpp
modules/fastcv/test/test_bilateral.cpp
modules/fastcv/test/test_moments.cpp

- Add support for cv::fastcv::calcHist
Depends on: [opencv/opencv_contrib#3844](https://github.com/opencv/opencv_contrib/pull/3844)
Depends on: [opencv/opencv#26619](https://github.com/opencv/opencv/pull/26619)
Requires binary from: [opencv/opencv_3rdparty#90](https://github.com/opencv/opencv_3rdparty/pull/90)

FastCV Extension code for OpenCV 2ndpost-2

---

modules/cudacodec/src/nvidia_surface_format_to_color_converter.cpp

The 4D array wouldn't compile on GCC 8, so I had to split it into separate 3D arrays to fix the compilation error.
Ref #3828 

cudacodec: Split 4D function pointer array into per-surface-format arrays for GCC 8 compatibility

---

modules/xobjdetect/CMakeLists.txt

Closed https://github.com/opencv/opencv_contrib/issues/3861
This patch is to build `world` module with `xobjdetect` successfully.

xobjdetect: (5.x) fix to build world with xobjdetect

---

modules/cudacodec/include/opencv2/cudacodec.hpp
modules/cudacodec/src/ffmpeg_video_source.cpp
modules/cudacodec/src/video_decoder.cpp
modules/cudacodec/src/video_writer.cpp
modules/cudacodec/test/test_video.cpp

Currently `cudacodec::VideoWriter` only encodes 8 bit YUV input.  This PR adds the capacity to encode 10 bit YUV input as well.
Discussed in [this](https://forum.opencv.org/t/status-and-usage-of-cudacodec-videowriter/17396/3?u=cudawarped) forum post.

`cudacodec::VideoWriter`: Add 10 bit YUV420 and YUV444 encoding

---

modules/xfeatures2d/test/test_rotation_and_scale_invariance.cpp

This PR resolves a warning caused by an unused variable `IMAGE_BIKES` in the file `test_rotation_and_scale_invariance.cpp` within the `xfeatures2d` module of the OpenCV contrib repository.
- **Issue:** The variable `IMAGE_BIKES` was declared but not used in the test file, leading to a compiler warning (`-Wunused-const-variable`).
```
warning: unused variable 'IMAGE_BIKES' [-Wunused-const-variable]
static const char* const IMAGE_BIKES = "detectors_descriptors_evaluation/
```

Fix Unused Variable Warning in `test_rotation_and_scale_invariance.cpp`

---

modules/cudacodec/include/opencv2/cudacodec.hpp
modules/cudacodec/src/video_writer.cpp
modules/cudacodec/test/test_video.cpp

Currently the meta data in all encoded video's is not updated to reflect the range (full of limited as defined in Annex E of the ITU-T Specification) of encoded luma/chroma values.  With all video's indicating that they use the limited range.  This means that when a full range YUV source is encoded the decoder will incorrectly decode it to a limited range resulting in poor color reproduction.
This PR correctly sets this meta data field for all encoded video's.

`cudacodec::VideoWriter` add flag for writing full range luma chroma video

---

.github/workflows/PR-3.4.yaml

See https://github.com/opencv/opencv/pull/26792
Ubuntu 14 is not compatible with Node.js 20.x used by GHA.

Disable obsolete GHA pipelines for 3.4

---

modules/cudalegacy/include/opencv2/cudalegacy/private.hpp

This line generates unnecessary warning
```
/opencv_contrib/modules/cudalegacy/include/opencv2/cudalegacy/private.hpp:94:8: warning: extra tokens at end of #endif directive [-Wendif-labels]
94 | #endif HAVE_CUDA
|        ^~~~~~~~~   
```

build: suppress warning

---

modules/mcc/src/checker_detector.cpp

+ The link to pretrained tensorflow model for detecting Macbeth Color-checker:
https://drive.google.com/drive/folders/1JNWlmyfZKxiYQoYk6f0RzcGtHuiZq1Pz
When loading the pretrained Macbeth color-checker detector model, and set it successfully to CCheckerDetector,
```
Ptr<CCheckerDetector> detector = CCheckerDetector::create();
if (!detector->setNet(net))
{
cout << "Loading Model failed: Aborting" << endl;
return 0;
}
```
then 
```
if(!detector->process(image, cv::mcc::MCC24, color_checker_roi, 1, true, params)) {
std::cout<<"Color-checker not found\n";
}
Ptr<mcc::CChecker> checker = detector->getBestColorChecker();
Ptr<CCheckerDraw> cdraw = CCheckerDraw::create(checker);
cdraw->draw(image);
```
+ problem 1:
cdraw function failed to draw the correct result due to the following code block …

fix bugs in checker_detector.cpp after resolving conflicts from PR #3599

---

modules/cudacodec/src/NvEncoder.cpp

Incorrect nvencapi version checking macros were introduced in https://github.com/opencv/opencv_contrib/pull/3717.  These are preventing OpenCV from building against the latest Nvidia Video Codec SDK (version 13).

cudacodec: fix VideoWriter version check bug introduced in #3711

---

modules/ml/misc/python/test/test_goodfeatures.py

Partial port of https://github.com/opencv/opencv/pull/26932

Replace deprecated tostring() with tobytes()

---

modules/fastcv/perf/perf_hough.cpp
modules/fastcv/test/test_mser.cpp

Warning fixes for FastCV module

---

modules/matlab/CMakeLists.txt
modules/matlab/generator/parse_tree.py
modules/matlab/include/opencv2/matlab/bridge.hpp

This PR resolves a VERY long-standing issue where the `MATLAB` module in opencv_contrib fails to compile due to namespace changes in `cv::optflow` and `cv::xphoto`. The MATLAB module has been broken since OpenCV **4.0.0-rc** due to these changes, and this fix restores compilation compatibility.
* Clarification: This fix aims to and restores **compilation** of the MATLAB module, but I have not tested full functionality within MATLAB itself.
1. **Namespace Changes**  
- The **DualTVL1OpticalFlow** algorithm was moved from `opencv` to `opencv_contrib/optflow`, breaking references in the MATLAB module.  This was done during `4.0.0-beta` and `4.0.0-rc`, but never reflected in `cv::matlab`
- `cv::xphoto` also underwent similar changes, but I am yet to find the exact version such change was made …

Fix: Restore MATLAB Module Compilation for OpenCV 4.x

---

modules/mcc/src/bound_min.cpp

This PR addresses infinite division bug mentioned in this issue: https://github.com/opencv/opencv_contrib/issues/3316

[BUG FIX] Resolves inf/inf issue in MCC

---

modules/cudaimgproc/src/color.cpp
modules/cudaimgproc/src/cuda/debayer.cu

This pull request adds support for CUDA 16-bit MHT demosaicking handled identically to 8-bit input. This means the output can be 1, 3, or 4 channels. The same template is used for 8-bit, so there is no need for additional tests unless desired and there is 16-bit test data available.
credit @shane-nichols
- [N/A] There is a reference to the original bug report and related work
- [N/A] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
- [N/A] The feature is well documented and sample code can be built with the project CMake

Adds support for CUDA MHT 16-bit demosaicking

---

modules/fastcv/include/opencv2/fastcv/blur.hpp
modules/fastcv/perf/perf_blur.cpp
modules/fastcv/src/blur.cpp
modules/fastcv/test/test_blur.cpp

Fastcv extension for normalizeLocalBox u8 and f32

Adding FastCV extension for normalizeLocalBox u8 and f32

---

modules/fastcv/include/opencv2/fastcv/arithm.hpp
modules/fastcv/perf/perf_arithm.cpp
modules/fastcv/src/arithm.cpp
modules/fastcv/src/channel.cpp
modules/fastcv/test/test_arithm.cpp

Fastcv extension for integrate YUV(YCbCr) image and bug fix in split extension

Fastcv extn for integrate YUV(YCbCr) image and bug fix in split extn

---

modules/bgsegm/tutorials/bgsegm_bg_subtraction/bgsegm_bg_subtraction.markdown

From his paper: https://scispace.com/pdf/an-improved-adaptive-background-mixture-model-for-real-time-1l517cez5l.pdf

Typo fix: KadewTraKuPong to KaewTraKulPong

---

modules/mcc/src/checker_detector.cpp
modules/mcc/src/checker_detector.hpp

This pull request addresses the MCC checker detector's checker box alignment issue in DNN based method https://github.com/opencv/opencv/issues/27219

[BUG FIX] Fix DNN-based MCC checker detector's checker box alignment issue

---

.github/workflows/PR-4.x.yaml

Related PR: https://github.com/opencv/ci-gha-workflow/pull/228

Added CI pipeline with FastCV back-end.

---

modules/aruco/include/opencv2/aruco/aruco_calib.hpp

Changed PatternPositionType to aruco::PatternPositionType to explicitly specify its scope. This allows gen_java.py to correctly register disc_type, preventing constructors and methods using this enum type from being skipped during Java wrapper generation.
Related issues
#3506
https://github.com/opencv/opencv/issues/23753

Explicitly specify enum type scope to improve Java wrapper generation

---

modules/fastcv/include/opencv2/fastcv/warp.hpp
modules/fastcv/perf/perf_warp.cpp
modules/fastcv/src/warp.cpp
modules/fastcv/test/test_warp.cpp

Add WarpPerspective in FastCV extension

---

modules/mcc/src/bound_min.cpp

Properly fix https://github.com/opencv/opencv_contrib/issues/3316
Without this fix, we could end up with 4 corners, which might seem valid, while some of those are (0,0).

Properly fix inf/inf issue in MCC

---

modules/fastcv/include/opencv2/fastcv.hpp
modules/fastcv/include/opencv2/fastcv/allocator.hpp
modules/fastcv/include/opencv2/fastcv/blur_dsp.hpp
modules/fastcv/include/opencv2/fastcv/dsp_init.hpp
modules/fastcv/include/opencv2/fastcv/edges_dsp.hpp
modules/fastcv/include/opencv2/fastcv/fft_dsp.hpp
modules/fastcv/include/opencv2/fastcv/sad_dsp.hpp
modules/fastcv/include/opencv2/fastcv/thresh_dsp.hpp
modules/fastcv/perf/perf_blur_dsp.cpp
modules/fastcv/perf/perf_edges_dsp.cpp
modules/fastcv/perf/perf_fft_dsp.cpp
modules/fastcv/perf/perf_main.cpp
modules/fastcv/perf/perf_precomp.hpp
modules/fastcv/perf/perf_sad_dsp.cpp
modules/fastcv/perf/perf_thresh_dsp.cpp
modules/fastcv/src/allocator.cpp
modules/fastcv/src/blur_dsp.cpp
modules/fastcv/src/dsp_init.cpp
modules/fastcv/src/edges_dsp.cpp
modules/fastcv/src/fft_dsp.cpp
modules/fastcv/src/precomp.hpp
modules/fastcv/src/sad_dsp.cpp
modules/fastcv/src/thresh_dsp.cpp
modules/fastcv/test/test_blur_dsp.cpp
modules/fastcv/test/test_edges_dsp.cpp
modules/fastcv/test/test_fft_dsp.cpp
modules/fastcv/test/test_main.cpp
modules/fastcv/test/test_precomp.hpp
modules/fastcv/test/test_sad_dsp.cpp
modules/fastcv/test/test_thresh_dsp.cpp

Merge with https://github.com/opencv/opencv/pull/27290
**Detailed Description**
This PR introduces FastCV DSP Extension APIs within the '**cv::fastcv::dsp**' namespace.
The following APIs have been added:
1. **fcvdspinit**: Initializes the FastCV DSP environment.
2. **fcvdspdeinit**: Deinitializes the FastCV DSP environment.
3. **sumOfAbsoluteDiffs**: Computes the sum of absolute differences of an image against an 8x8 template.
4. **thresholdOtsu**: Binarizes a grayscale image using Otsu's method.
5. **FFT**: Computes the 1D or 2D Fast Fourier Transform of a real-valued matrix.
6. **IFFT**: Computes the 1D or 2D Inverse Fast Fourier Transform of a complex-valued matrix.
7. **canny**: Applies the Canny edge detector to an 8-bit grayscale image.
8. **filter2D**: Applies a generic 2D filter …

Add FastCV DSP Initialization, QcAllocator and FastCV DSP Extension APIs

---

modules/fastcv/include/opencv2/fastcv/scale.hpp
modules/fastcv/include/opencv2/fastcv/warp.hpp
modules/fastcv/perf/perf_scale.cpp
modules/fastcv/perf/perf_warp.cpp
modules/fastcv/src/scale.cpp
modules/fastcv/src/warp.cpp
modules/fastcv/test/test_scale.cpp
modules/fastcv/test/test_warp.cpp

- Added warpAffine function to apply affine transformations.
2x3 affine transformations for both CV_8UC1 and CV_8UC3 input
2x2 matrix-based patch extraction for grayscale images, with ROI.
- Deprecated resizeDownBy2 and resizeDownBy4 functions.
- Introduced resizeDown function to down-scale images using specified scaling factors or dimensions, supporting both single-channel (CV_8UC1) and two-channel (CV_8UC2) images.

Add warpAffine and resizeDown APIs in FastCV Extension

---

modules/ximgproc/doc/ximgproc.bib
modules/ximgproc/include/opencv2/ximgproc.hpp
modules/ximgproc/include/opencv2/ximgproc/edge_drawing.hpp
modules/ximgproc/samples/edge_drawing.py
modules/ximgproc/samples/edge_drawing_demo.cpp
modules/ximgproc/samples/fld_lines.cpp
modules/ximgproc/src/edge_drawing.cpp
modules/ximgproc/src/edge_drawing_common.hpp
modules/ximgproc/test/test_fld.cpp

Add EDColor related algorithms to EdgeDrawing Class

---

modules/fastcv/include/opencv2/fastcv/allocator.hpp
modules/fastcv/src/allocator.cpp

Add support to store the file descriptor (fd) of the allocated memory in the userdata field of cv::UMatData
fcvHwMemAlloc API has been updated to support fd.
Updated Hash: [opencv/opencv#27525](https://github.com/opencv/opencv/pull/27525)
Updated libs PR [opencv/opencv_3rdparty#101](https://github.com/opencv/opencv_3rdparty/pull/101)

Modified QcAllocator to store File Descriptor

---

modules/fastcv/include/opencv2/fastcv.hpp
modules/fastcv/include/opencv2/fastcv/color.hpp
modules/fastcv/src/color.cpp
modules/fastcv/test/test_color.cpp

This pull request introduces FastCV-based color conversions:
```
COLOR_YUV2YUV444sp_NV12      //!< FastCV: YCbCr420PseudoPlanar to YCbCr444PseudoPlanar
COLOR_YUV2YUV422sp_NV12      //!< FastCV: YCbCr420PseudoPlanar to YCbCr422PseudoPlanar
COLOR_YUV422sp2YUV444sp      //!< FastCV: YCbCr422PseudoPlanar to YCbCr444PseudoPlanar
COLOR_YUV422sp2YUV_NV12      //!< FastCV: YCbCr422PseudoPlanar to YCbCr420PseudoPlanar
COLOR_YUV444sp2YUV422sp      //!< FastCV: YCbCr444PseudoPlanar to YCbCr422PseudoPlanar
COLOR_YUV444sp2YUV_NV12      //!< FastCV: YCbCr444PseudoPlanar to YCbCr420PseudoPlanar
COLOR_YUV2RGB565_NV12        //!< FastCV: YCbCr420PseudoPlanar to RGB565
COLOR_YUV422sp2RGB565        //!< FastCV: YCbCr422PseudoPlanar to RGB565
COLOR_YUV422sp2RGB           //!< FastCV: YCbCr422PseudoPlanar to …
```

Added fastcv color conversions

---

modules/videostab/src/cuda/global_motion.cu

Fix build errors introduced by the removal of `thrust::not1` in CUDA 13.0
```
modules\videostab\src\cuda\global_motion.cu(63): error: namespace "thrust" has no member "not1"
dmask, thrust::not1(thrust::identity<uchar>()))
```

cuda: update videostab for cuda 13.0

---

modules/cudev/include/opencv2/cudev/warp/shuffle.hpp

Draft fix for https://github.com/opencv/opencv_contrib/issues/3962.
Support for `__shfl_down` on `long long` was not introduced until CUDA Toolkit 9.0.  I don't know if this is just software support or if hardware support was added as well.  Its a long shot but it may be the reason that the tests are failing on Compute Capbability 5.3 devices.  

cudev: Add __shfl_down implementation for long long and unsigned long for CUDA Tookit < 9.0

---

modules/bgsegm/src/bgfg_gsoc.cpp

This PR enables use of the `__popcnt` intrinsic for ARM/ARM64 targets when building with MSVC. Previously, these targets(ARM/ARM64) were explicitly excluded using macro guards.
When building OpenCV on Windows on ARM64 with MSVC (cl.exe), the BackgroundSubtractor_LSBP.Accuracy test fails because the code falls into the else block using different bit counting method, which leads to incorrect results and causes the test to fail.

bgsegm: Enable __popcnt intrinsic for MSVC on ARM to fix LSBP test failure

---

modules/cudawarping/include/opencv2/cudawarping.hpp

The issue was reported first at:
https://github.com/opencv/opencv_contrib/issues/3973

Add INTER_AREA interpolation method on `resize` Doxygen string

---

modules/cudacodec/src/video_writer.cpp

Fixed support for NVIDIA Codec SDK 11.x
