modules/surface_matching/PATENTS.txt, modules/surface_matching/include/opencv2/surface_matching.hpp
=> added information about the patents related to the surface matching algorithm

modules/adas/tools/fcw_detect/CMakeLists.txt, modules/adas/tools/fcw_train/CMakeLists.txt, modules/bioinspired/src/retinacolor.hpp, modules/bioinspired/src/retinafilter.hpp, modules/contrib_world/CMakeLists.txt, modules/contrib_world/include/opencv2/contrib_world.hpp, modules/contrib_world/src/dummy.cpp, modules/datasets/src/ar_hmdb.cpp, modules/datasets/src/or_imagenet.cpp, modules/datasets/src/or_sun.cpp, modules/line_descriptor/src/binary_descriptor.cpp, modules/surface_matching/src/icp.cpp, modules/text/src/erfilter.cpp, modules/xphoto/src/dct_image_denoising.cpp
This pull request contains new module (_opencv_contrib_world_) similar to _opencv_world_ but containing only _opencv_contrib_ modules. It uses compound module mechanism implemented in Itseez/opencv#3666.
Some other changes has been made to avoid compilation warnings on iOS platform.
=> contrib_world module

modules/bgsegm/CMakeLists.txt, modules/bioinspired/CMakeLists.txt, modules/ccalib/CMakeLists.txt, modules/cvv/CMakeLists.txt, modules/datasets/CMakeLists.txt, modules/face/CMakeLists.txt, modules/latentsvm/CMakeLists.txt, modules/line_descriptor/CMakeLists.txt, modules/optflow/CMakeLists.txt, modules/reg/CMakeLists.txt, modules/rgbd/CMakeLists.txt, modules/saliency/CMakeLists.txt, modules/surface_matching/CMakeLists.txt, modules/text/CMakeLists.txt, modules/xfeatures2d/CMakeLists.txt, modules/ximgproc/CMakeLists.txt, modules/xobjdetect/CMakeLists.txt, modules/xphoto/CMakeLists.txt
Compatible with Itseez/opencv#3759
=> Java and python wrappers for contrib modules

modules/face/include/opencv2/face/facerec.hpp, modules/rgbd/include/opencv2/rgbd.hpp, modules/saliency/include/opencv2/saliency/saliencySpecializedClasses.hpp, modules/ximgproc/include/opencv2/ximgproc/edge_filter.hpp
__note__: also removed some trailing whitespaces
=> Replaced property macros in headers

modules/face/include/opencv2/face/facerec.hpp
Added CV_WRAP markers to some methods in _face_ module
=> Wrap face module with python and java

modules/reg/samples/map_test.cpp
Adapt to changes in the interface of feature detectors, using now Feature2D interface.
=> Adapt reg sample to changes in features detectors

modules/datasets/include/opencv2/datasets/dataset.hpp
Corrected Link for corresponding dataset
=> Link Correction

modules/datasets/samples/fr_lfw_benchmark.cpp
to get the exact setup for "view2" in http://vis-www.cs.umass.edu/lfw/#views
(10-fold cross validation based on pairs.txt)
=> add a 'split' train method to datasets/lfw_benchmark

modules/adas/tools/fcw_detect/CMakeLists.txt, modules/adas/tools/fcw_train/CMakeLists.txt
=> Support for HAL module

modules/matlab/include/opencv2/matlab/bridge.hpp
added missing typedef typePtr_DualTVL1OpticalFlow
=> missing type Ptr_DualTVL1OpticalFlow

modules/optflow/src/motempl.cpp, modules/rgbd/src/depth_to_3d.h, modules/xfeatures2d/src/sift.cpp
this is complimentary patch to https://github.com/Itseez/opencv/pull/3935
=> fixed contrib code to match the HAL

modules/tracking/src/TrackingFunctionPF.hpp, modules/xphoto/src/gcgraph.hpp
this is complementary to https://github.com/Itseez/opencv/pull/3987
=> fixed compile error and warning

modules/xfeatures2d/include/opencv2/xfeatures2d.hpp
this pr adds FREAK, StarDetector, BriefDescriptorExtractor and LUCID to the python wrappers.
=> wrapping remaining xfeature2d classes to scripting

modules/bioinspired/src/retina_ocl.cpp, modules/saliency/include/opencv2/saliency/saliencyBaseClasses.hpp, modules/saliency/include/opencv2/saliency/saliencySpecializedClasses.hpp, modules/saliency/src/BING/objectnessBING.cpp, modules/saliency/src/motionSaliencyBinWangApr2014.cpp, modules/saliency/src/saliency.cpp, modules/saliency/src/staticSaliencySpectralResidual.cpp, modules/xfeatures2d/test/test_features2d.cpp
**WIP**
added test for http://code.opencv.org/issues/3943 (cannot reproduce it)
=> Features2d fixes

modules/text/README.md, modules/text/src/erfilter.cpp, modules/xfeatures2d/include/opencv2/xfeatures2d.hpp, modules/xfeatures2d/src/daisy.cpp
Also, added tesseract installation mini-guide in text/readme.md
=> fixed several warnings in opencv_contrib (text, xfeatures2d)

modules/ximgproc/CMakeLists.txt, modules/ximgproc/include/opencv2/ximgproc/disparity_filter.hpp, modules/ximgproc/include/opencv2/ximgproc/edge_filter.hpp, modules/ximgproc/samples/disparity_filtering.cpp, modules/ximgproc/src/disparity_filters.cpp, modules/ximgproc/src/wls_filter.cpp
Current results: https://www.dropbox.com/sh/vfwhrcvq37dlqmk/AACo-LFiodnDUtVBqzxzossNa?dl=0
=> Interface and demo for disparity filtering, basic WLS implementation

modules/datasets/include/opencv2/datasets/pd_inria.hpp, modules/datasets/samples/pd_inria.cpp, modules/datasets/src/pd_inria.cpp
@bmagyar Could you please help me to review this patch?
=> added INRIA pedestrian dataset

modules/ximgproc/src/structured_edge_detection.cpp
avoid overflow in histogram access
=> fix for issue #195

modules/xfeatures2d/src/daisy.cpp
vs2010 breaks (not knowing floor,ceil, round or such)
=> change round to cvRound

modules/datasets/include/opencv2/datasets/or_pascal.hpp, modules/datasets/samples/or_pascal.cpp, modules/datasets/src/or_pascal.cpp
=> added PASCAL VOC dataset

modules/xfeatures2d/src/stardetector.cpp
In addition to Itseez/opencv#4222
=> Fixing GCC 4.9 warning

modules/text/src/ocr_tesseract.cpp
http://code.opencv.org/issues/4420
=> Fix memory leak bug #4420

modules/text/include/opencv2/text/ocr.hpp, modules/text/samples/cropped_word_recognition.cpp, modules/text/src/ocr_hmm_decoder.cpp
allows to create a tailored language model transitions table from a given list of words (lexicon).
=> Adds createOCRHMMTransitionsTable() utility function

modules/ximgproc/include/fast_hough_transform.hpp, modules/ximgproc/include/opencv2/ximgproc.hpp, modules/ximgproc/include/opencv2/ximgproc/fast_hough_transform.hpp, modules/ximgproc/perf/perf_fast_hough_transform.cpp, modules/ximgproc/samples/fast_hough_transform.cpp, modules/ximgproc/src/fast_hough_transform.cpp, modules/ximgproc/test/test_fast_hough_transform.cpp
Moved code from https://github.com/Itseez/opencv/pull/3968 to opencv_contrib
=> added a calculation of the Fast Hough Transform of an image

modules/datasets/include/opencv2/datasets/tr_icdar.hpp, modules/datasets/samples/tr_icdar.cpp, modules/datasets/samples/tr_icdar_benchmark.cpp, modules/datasets/src/tr_icdar.cpp
Adds interface for the ICDAR2015 dataset and benchmark code using the text module.
=> ICDAR2015 dataset

modules/datasets/samples/tr_svt_benchmark.cpp
Changes SVT recognition evaluation to be Case Insensitive.
Report the total F1 score (0.37) and not the mean-f1.
=> Fix SVT dataset standard evaluation protocol

modules/tracking/include/opencv2/tracking/tracker.hpp
This class offers functionality to track multiple objects at once. 
The user can add the tracked object one by one with different tracker algorithm or several objects at once with same tracker algorithm. 
The sample program is available.
Usage: example_tracking_multitracker "video_name" [algorithm]
example:
example_tracking_multitracker Bolt/img/%04d.jpg
example_tracking_multitracker faceocc2.webm MEDIANFLOW
choose the tracked object(s) by drag and drop, press space or enter button to confirm the selection.
Push backspace button to finish the selection process.
=> Multiple Trackers (Naive Implementation)

modules/tracking/src/trackerMIL.cpp
A pull request to fix a minor bug on reading and writing trackerMIL::Param (a problem on duplicated keys).
=> Fixed a minor bug on reading/writing trackerMIL::Param.

modules/datasets/src/util.cpp, modules/line_descriptor/src/bitarray.hpp, modules/line_descriptor/src/bitops.hpp, modules/line_descriptor/src/precomp.hpp, modules/line_descriptor/src/types.hpp, modules/surface_matching/src/icp.cpp
Successfully built OpenCV with mingw-w64 (4.8.2) on Ubuntu 14.04.
Related issues: #256, #257.
=> Fixed some mingw-w64 compilation issues

modules/structured_light/CMakeLists.txt, modules/structured_light/samples/pointcloud.cpp, modules/structured_light/src/graycodepattern.cpp, modules/structured_light/test/test_getProjPixel.cpp, modules/structured_light/test/test_plane.cpp
currently the structured_light module does not build without viz/vtk, 
but actually only the pointcloud sample depends on viz
=> remove viz/vtk dependancy

modules/xfeatures2d/src/freak.cpp
see https://github.com/Itseez/opencv/pull/4219
=> Pull Request 4219 from main opencv repo

modules/aruco/src/dictionary.cpp
store marker internally as 
- `r0_b0, r0_b1, .. , r0_bn, r1_b0, ..` instead of 
- `r0_b0, r1_b0, .. , rn_b0, r1_b0, ..`
i.e. the same as in predefined_dictionaries.cpp.
This makes loading a dictionary a simple memcpy and also allows to get
rid of the custom hammingDistance implementation in favor of
`hal::normHamming`.
=> aruco: simplify Dictionary by not interleaving the marker rotations

modules/matlab/CMakeLists.txt, modules/matlab/generator/gen_matlab.py
Removing the dependencies with help of @berak 
should solve https://github.com/Itseez/opencv_contrib/issues/167
=> Remove dependency on RST parser for the matlab module

CONTRIBUTING.md
as suggested in https://github.com/Itseez/opencv/issues/5200#issuecomment-132197315
=> add contributions guidelines

modules/tracking/samples/tracker.cpp
* Adding comments of tracker algorithm for the sample program. 
* Beginners don't need to look at contrib_to_opencv/opencv_contrib/modules/tracking/src/tracker.cpp to know which tracker algorithm that opencv offers. 
* The name of tracker algorithm should be uppercase letters.
=> update comments of tracker algorithm

modules/optflow/CMakeLists.txt, modules/optflow/include/opencv2/optflow.hpp, modules/optflow/samples/optical_flow_evaluation.cpp, modules/optflow/src/interfaces.cpp, modules/optflow/src/sparsetodenseflow.cpp, modules/optflow/test/test_sparsetodenseflow.cpp, modules/ximgproc/doc/ximgproc.bib, modules/ximgproc/include/opencv2/ximgproc.hpp, modules/ximgproc/include/opencv2/ximgproc/sparse_match_interpolator.hpp, modules/ximgproc/src/sparse_match_interpolators.cpp, modules/ximgproc/test/test_sparse_match_interpolator.cpp
This PR adds sparsetodenseflow to the optflow module. It is ~2x faster than Farneback flow, while providing better quality. Here is objective and subjective comparison with other dense optical flow algorithms on 10 MPI-Sintel videos (around 50 frames each) and 7 Middlebury frame pairs: https://www.dropbox.com/sh/03ziwt23n21pumm/AABppwrw9IIPn1S4rwzPZ1Qva?dl=0
=> New fast dense optical flow algorithm (sparse-to-dense flow)

modules/aruco/include/opencv2/aruco.hpp, modules/aruco/samples/detect_board.cpp, modules/aruco/samples/detect_board_charuco.cpp, modules/aruco/samples/detect_diamonds.cpp, modules/aruco/samples/detect_markers.cpp, modules/aruco/src/aruco.cpp, modules/aruco/test/test_charucodetection.cpp, modules/aruco/tutorials/aruco_board_detection/aruco_board_detection.markdown, modules/aruco/tutorials/aruco_detection/aruco_detection.markdown, modules/aruco/tutorials/charuco_detection/charuco_detection.markdown, modules/aruco/tutorials/charuco_diamond_detection/charuco_diamond_detection.markdown
allows using Mat and vector<Vec3d> as argument for rvecs, tvecs that are
allocated at once.
=> aruco: use densely packed array for pose computation

modules/dnn/3rdparty/protobuf/CMakeLists.txt, modules/optflow/src/motempl.cpp, modules/xfeatures2d/src/surf.ocl.cpp
Should be tested with Itseez/opencv#5531
=> Visual Studio 2015 fixes for contrib

modules/tracking/samples/tutorial_customizing_cn_tracker.cpp, modules/tracking/samples/tutorial_introduction_to_tracker.cpp, modules/tracking/samples/tutorial_multitracker.cpp, modules/tracking/tutorials/tutorial_customizing_cn_tracker.markdown, modules/tracking/tutorials/tutorial_introduction_to_tracker.markdown, modules/tracking/tutorials/tutorial_multitracker.markdown
There are 3 tutorials on this pull request:
•Introduction to OpenCV Tracker and roiSelector GUI
•Using custom function for TrackerKCF
•Using MultiTracker class
=> Tutorials for KCF tracker, moved from #353

modules/tracking/src/tldDetector.cpp, modules/ximgproc/samples/live_demo.cpp
**Main repo: https://github.com/Itseez/opencv/pull/5388**
=> disable String(int) ctor

modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/im2col.cpp, modules/dnn/src/layers/im2col.hpp, modules/tracking/src/tldDetector.cpp, modules/tracking/src/tldDetector.hpp, modules/tracking/src/tldModel.cpp, modules/tracking/src/tldModel.hpp, modules/tracking/src/tldTracker.cpp, modules/xfeatures2d/src/surf.cpp, modules/xfeatures2d/src/surf.hpp, modules/xfeatures2d/src/surf.ocl.cpp
Main repo: https://github.com/Itseez/opencv/pull/5340
=> OCL: fix "off" mode

modules/tracking/src/multiTracker.cpp, modules/tracking/src/multiTracker.hpp
Otherwise, it will block building of opencv_contrib in my platform. Please help check it. Thanks
=> Add macro definition to avoid building error.

modules/tracking/CMakeLists.txt, modules/tracking/include/opencv2/tracking/onlineMIL.hpp, modules/tracking/include/opencv2/tracking/tracker.hpp, modules/tracking/samples/multitracker.py, modules/tracking/samples/tracker.py, modules/tracking/src/roiSelector.cpp
see [#415](https://github.com/Itseez/opencv_contrib/issues/415)
also added 2 samples, tracker.py and multitracker.py
=> add python bindings for Tracker and MultiTracker

modules/text/include/opencv2/text/ocr.hpp, modules/text/src/ocr_beamsearch_decoder.cpp, modules/text/src/ocr_hmm_decoder.cpp, modules/text/src/ocr_tesseract.cpp
Adds specific member functions and functions in order to export to the python api (cv2.text module) the text module API.
=> text module: python binding

modules/ximgproc/README.md, modules/ximgproc/doc/ximgproc.bib, modules/ximgproc/include/opencv2/ximgproc.hpp, modules/ximgproc/include/opencv2/ximgproc/segmentation.hpp, modules/ximgproc/samples/cpp/graphsegmentation_demo.cpp, modules/ximgproc/src/graphsegmentation.cpp, modules/ximgproc/src/precomp.hpp
This is a proposition of an implementation of a very fast segmentation algorithm, described in [Efficient graph-based image segmentation](http://cs.brown.edu/~pff/papers/seg-ijcv.pdf).
This is my first opencv module - I hope everything is correct :)
=> Graphsegmentation: First implementation

modules/dnn/3rdparty/protobuf/CMakeLists.txt, modules/dnn/CMakeLists.txt, modules/dpm/src/dpm_model.hpp, modules/saliency/include/opencv2/saliency/saliencySpecializedClasses.hpp, modules/saliency/src/BING/FilterTIG.cpp, modules/stereo/src/matching.hpp, modules/xobjdetect/CMakeLists.txt
!!! Merge with Itseez/opencv#5654
- disabled dnn module (can not build protobuf)
- disabled tools build from xobjdetect module
=> Fix iOS framework issues

modules/cvv/src/impl/call.cpp
It doesn't support thread_local.
=> Fixes cvv compilation for Apple's clang

modules/aruco/samples/calibrate_camera.cpp, modules/aruco/samples/calibrate_camera_charuco.cpp, modules/aruco/samples/create_board.cpp, modules/aruco/samples/create_board_charuco.cpp, modules/aruco/samples/create_diamond.cpp, modules/aruco/samples/create_marker.cpp, modules/aruco/samples/detect_board.cpp, modules/aruco/samples/detect_board_charuco.cpp, modules/aruco/samples/detect_diamonds.cpp, modules/aruco/samples/detect_markers.cpp
results in less code and more consistent parameter handling.
=> aruco: port samples to cv::CommandLineParser

modules/optflow/src/simpleflow.cpp
Several optimizations to SimpleFlow:
Before
```
[----------] 1 test from Video_OpticalFlowSimpleFlow
[ RUN      ] Video_OpticalFlowSimpleFlow.accuracy
[       OK ] Video_OpticalFlowSimpleFlow.accuracy (6186 ms)
[----------] 1 test from Video_OpticalFlowSimpleFlow (6186 ms total)
```
After
```
[----------] 1 test from Video_OpticalFlowSimpleFlow
[ RUN      ] Video_OpticalFlowSimpleFlow.accuracy
[       OK ] Video_OpticalFlowSimpleFlow.accuracy (2327 ms)
[----------] 1 test from Video_OpticalFlowSimpleFlow (2327 ms total)
```
On a Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
=> SimpleFlow optimizations

LICENSE
like suggested in issue https://github.com/Itseez/opencv_contrib/issues/302
=> add license to contrib repo

modules/stereo/include/opencv2/stereo.hpp, modules/stereo/include/opencv2/stereo/descriptor.hpp, modules/stereo/include/opencv2/stereo/matching.hpp, modules/stereo/src/descriptor.cpp, modules/stereo/src/stereo_binary_bm.cpp, modules/stereo/src/stereo_binary_sgbm.cpp
Fixed an include error in the stereo module
=> Fixed include error

modules/datasets/src/fr_lfw.cpp
LFW database tests consist of View 1 and View 2.
View 1 consists of train and test set. However, the original code only contains View 1 train set and View 2 set. I added View 2 test set to validation vector. Simply put,
| Original | Modified
------------|------------ | -------------
train       | View 1 train | View 1 train
test        | View 2 | View 2
validation | empty | View 1 test
=> added dev_test

modules/dnn/CMakeLists.txt, modules/xobjdetect/tools/waldboost_detector/CMakeLists.txt
**Main repo**: https://github.com/Itseez/opencv/pull/5784
**Merge with extra**: https://github.com/Itseez/opencv_extra/issues/282
=> Distribution package fix

modules/aruco/src/dictionary.cpp, modules/optflow/src/motempl.cpp, modules/sfm/src/libmv_light/CMake/Installation.cmake, modules/xfeatures2d/src/sift.cpp, modules/ximgproc/src/fgs_filter.cpp, modules/ximgproc/src/precomp.hpp, modules/ximgproc/src/sparse_match_interpolators.cpp, modules/xphoto/src/grayworld_white_balance.cpp
Needed by Itseez/opencv#5810
+ fixed static build of sfm module
=> Hal interface

modules/xfeatures2d/doc/xfeatures2d.bib, modules/xfeatures2d/include/opencv2/xfeatures2d.hpp, modules/xfeatures2d/perf/perf_msd.cpp, modules/xfeatures2d/src/msd.cpp, modules/xfeatures2d/test/test_keypoints.cpp
Same as #409 
Should be merged with Itseez/opencv_extra#283
=> Add msd detector

modules/rgbd/include/opencv2/rgbd.hpp, modules/rgbd/src/normal.cpp, modules/rgbd/test/test_normal.cpp
=> Normals linemod fix

modules/ximgproc/src/lsc.cpp, modules/ximgproc/src/seeds.cpp, modules/ximgproc/src/slic.cpp
* This fix Issue https://github.com/Itseez/opencv_contrib/issues/481 . Thanks a lot @ehku !
=> BugFix: Issue #481 related to SLIC & LSC contour mask values.

modules/face/include/opencv2/face/predict_collector.hpp
let's keep consistancy with the docs and recent behaviour
cc @comdiv
=> face: change the 'not found' label back to -1

modules/face/include/opencv2/face/predict_collector.hpp
=> fix a bug for qt

modules/aruco/src/aruco.cpp, modules/aruco/src/dictionary.cpp
Fix some signed/unsigned comparisons and unsafe casts I stumbled upon while working on the code.
=> Fix type/signedness mismatches in aruco

modules/sfm/src/libmv_capi.h
Signed-off-by: Konstantin Volokh <Konstantin.Volokh@transas.com>
=> fix fc20 builds

modules/ximgproc/README.md, modules/ximgproc/doc/ximgproc.bib, modules/ximgproc/include/opencv2/ximgproc/segmentation.hpp, modules/ximgproc/samples/graphsegmentation_demo.cpp, modules/ximgproc/samples/selectivesearchsegmentation_demo.cpp, modules/ximgproc/src/graphsegmentation.cpp, modules/ximgproc/src/selectivesearchsegmentation.cpp
This is a proposition of an implementation of a segmentation algorithm, described in [Selective search for object recognition](http://koen.me/research/pub/uijlings-ijcv2013-draft.pdf).
It use #361 as a base algorithm, I put it in the same module, I don't know if it's ok but I can move it :)
=> Implementation of SelectiveSearchSegmentation

modules/ximgproc/src/graphsegmentation.cpp
This fix obvious and sads memory leaks in `GraphSegmentation`.
=> Fix memory leaks in GraphSegmentation

modules/dnn/CMakeLists.txt, modules/matlab/CMakeLists.txt, modules/xobjdetect/CMakeLists.txt, modules/xobjdetect/tools/waldboost_detector/CMakeLists.txt
Closes https://github.com/Itseez/opencv/issues/6011
=> cmake: fix build on MacOSX

modules/hdf/include/opencv2/hdf/hdf5.hpp, modules/hdf/src/hdf5.cpp
Closes: https://github.com/Itseez/opencv/issues/6016
=> Fix: public hdf headers

modules/tracking/src/roiSelector.cpp
https://github.com/Itseez/opencv_contrib/issues/492
=> typo-correction roiSelector.cpp

modules/dpm/src/dpm_nms.cpp
It resolves an open issue, #456.
=> Resolving an open issue, #456

modules/cvv/CMakeLists.txt, modules/cvv/src/impl/filter_call.cpp, modules/cvv/src/impl/match_call.cpp, modules/cvv/src/impl/single_image_call.cpp, modules/cvv/src/qtutil/matchview/colorutil.hpp, modules/cvv/src/qtutil/util.cpp, modules/cvv/src/view/defaultfilterview.cpp, modules/cvv/src/view/dual_filter_view.cpp, modules/cvv/src/view/linematchview.cpp, modules/cvv/src/view/pointmatchview.cpp, modules/cvv/src/view/singlefilterview.cpp, modules/cvv/src/view/translationsmatchview.cpp
This should address #166 . I tested it on Windows 10 with Visual Studio 2013 with both Microsoft and Intel compilers. I have not tested the patch on other OS's, but hopefully the build bot will succeed.
=> some fixes to get CVV module compiling with Visual Studio 2013

modules/face/tutorials/face_tutorial.markdown
create_cv needs to be called with path, fix for  #403
=> Correction in tutorial wrt calling of create_csv

modules/line_descriptor/samples/knn_matching.cpp, modules/optflow/samples/optical_flow_evaluation.cpp
fix #578 
I'm tested optical flow sample after build/ Look like everything is in order.
=> fix errors on build samples with VS2010

modules/contrib_world/CMakeLists.txt
=> Added new packages added since last update

modules/cnn_3dobj/README.md
Smoother, more grammatical description.
=> Just edited the english instructions

modules/cnn_3dobj/tutorials/table_of_content_cnn_3dobj.markdown
=> Minor grammar edit

modules/aruco/tutorials/aruco_board_detection/aruco_board_detection.markdown, modules/aruco/tutorials/aruco_detection/aruco_detection.markdown, modules/aruco/tutorials/charuco_detection/charuco_detection.markdown, modules/aruco/tutorials/charuco_diamond_detection/charuco_diamond_detection.markdown
to fix warnings in new doxygen (1.8.11)
=> Using iframe to embed youtube videos in aruco tutorials

modules/bioinspired/src/opencl/retina_kernel.cl
see https://github.com/Itseez/opencv/issues/6370
=> quick fix to avoid CMake 3.5 crashing in cl2cpp.cmake

modules/tracking/src/roiSelector.cpp
`key_` variable was not updated in loop, this should fix #635 and #655
=> tracking: fix selectRoi()

modules/face/data/cascades/haarcascade_mcs_eyepair_big.xml, modules/face/data/cascades/haarcascade_mcs_eyepair_small.xml, modules/face/data/cascades/haarcascade_mcs_leftear.xml, modules/face/data/cascades/haarcascade_mcs_lefteye.xml, modules/face/data/cascades/haarcascade_mcs_mouth.xml, modules/face/data/cascades/haarcascade_mcs_nose.xml, modules/face/data/cascades/haarcascade_mcs_rightear.xml, modules/face/data/cascades/haarcascade_mcs_righteye.xml, modules/face/data/cascades/haarcascade_mcs_upperbody.xml
https://github.com/Itseez/opencv_contrib/issues/644
=> fix for width&height problem in haarcascade_mcs_xxx.xml files

modules/aruco/samples/calibrate_camera_charuco.cpp
=> Fix a typo

modules/ximgproc/README.md, modules/ximgproc/doc/ximgproc.bib, modules/ximgproc/include/opencv2/ximgproc.hpp, modules/ximgproc/include/opencv2/ximgproc/paillou_filter.hpp, modules/ximgproc/samples/paillou_demo.cpp, modules/ximgproc/src/paillou_filter.cpp
Implementation of Detecting step edges in noisy SAR images: a new linear operator IEEE Transactions on Geoscience and Remote Sensing (Volume:35 , Issue: 1 ) 1997
=> Paillou Filter

modules/optflow/include/opencv2/optflow.hpp, modules/optflow/src/dis_flow.cpp
Change DISOpticalFlow in module "optflow".
Add methods for get/set weights of variational refinement part of DISOpticalFlow.
=> Add methods for get/set weights of variational refinement part of DISOpticalFlow

modules/dnn/CMakeLists.txt
Related: https://github.com/opencv/opencv/pull/6737 (https://github.com/opencv/opencv/pull/6866)
=> disable dnn for aarch64 platform

modules/face/include/opencv2/face/bif.hpp, modules/face/src/bif.cpp, modules/face/test/test_bif.cpp, modules/face/test/test_main.cpp, modules/face/test/test_precomp.hpp
This PR adds an implementation of bio-inspired features (BIF) from the paper: Guo, Guodong, et al. "Human age estimation using bio-inspired features."  Computer Vision and Pattern Recognition, 2009. CVPR 2009.
It's added into module 'face'.
=> Bif descriptor

modules/aruco/include/opencv2/aruco.hpp, modules/aruco/include/opencv2/aruco/charuco.hpp, modules/aruco/src/aruco.cpp, modules/aruco/src/charuco.cpp
Update functions `calibrateCameraCharuco` and `calibrateCameraAaruco`
=> Add calibration error estimation into Aruco module

modules/optflow/src/dis_flow.cpp, modules/optflow/src/pcaflow.cpp, modules/xphoto/src/learning_based_color_balance.cpp
=> fix vs2010 build error

modules/xphoto/src/inpainting.cpp
**Merge with https://github.com/opencv/opencv/pull/7167**
resolves #7147
=> fix modules deps

modules/cvv/src/qtutil/zoomableimage.cpp, modules/cvv/test/test_location.cpp, modules/cvv/test/test_main.cpp, modules/dnn/test/cnpy.h, modules/dnn/test/test_layers.cpp, modules/ximgproc/src/l0_smooth.cpp
Companion for opencv/opencv#7210
=> Fix GCC 5.x warnings

modules/aruco/include/opencv2/aruco.hpp, modules/aruco/src/aruco.cpp
=> Added extra method to Board::create() to provide raw interface to python

modules/xfeatures2d/src/freak.cpp
**Merge with opencv_extra**: https://github.com/opencv/opencv_extra/pull/313
resolves #478 
resolves #477
=> Fix rounding in FREAK descriptor

modules/ximgproc/src/guided_filter.cpp, modules/ximgproc/test/test_guided_filter.cpp
=> Guided filter fix

modules/aruco/src/charuco.cpp
=> Add uncontinious corners Mat support to charuco.cpp

modules/dnn/3rdparty/protobuf/src/google/protobuf/descriptor.cc, modules/dnn/3rdparty/protobuf/src/google/protobuf/stubs/strutil.cc, modules/dnn/3rdparty/protobuf/src/google/protobuf/wire_format.cc, modules/dnn/samples/fcn_semsegm.cpp, modules/dnn/src/caffe/layer_loaders.cpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/op_blas.cpp
=> fixed some compile warnings in dnn & protobuf; improved convolution speed

modules/xfeatures2d/src/freak.cpp, modules/xfeatures2d/test/test_features2d.cpp, modules/xfeatures2d/test/test_rotation_and_scale_invariance.cpp
Add check that input image is gray
=> Check that image is gray in FREAK

modules/plot/CMakeLists.txt, modules/plot/include/opencv2/plot.hpp, modules/plot/src/plot.cpp
Python bindings for plot module are enabled.
resolves #581
=> Plot module update

modules/face/src/bif.cpp
resolves #802
wrong access of sum Mat in line 204 was causing NaN values.
=> face: fix NaN's in bif.cpp

modules/plot/include/opencv2/plot.hpp
=> Add missed doxygen group in plot module

modules/tracking/src/tldTracker.cpp
=> Fix TLD fail on gray images

modules/line_descriptor/src/bitops.hpp
=> Fix line descriptor module build on Win64

modules/aruco/CMakeLists.txt, modules/aruco/include/opencv2/aruco.hpp, modules/aruco/include/opencv2/aruco/charuco.hpp, modules/aruco/include/opencv2/aruco/dictionary.hpp, modules/aruco/src/aruco.cpp, modules/aruco/src/charuco.cpp, modules/aruco/src/dictionary.cpp
This pull request is adding support for java wrapper generation. It is dependent on https://github.com/opencv/opencv/pull/7050 pull request from opencv.
=> Add support for java in aruco module

modules/saliency/CMakeLists.txt, modules/saliency/include/opencv2/saliency/saliencyBaseClasses.hpp, modules/saliency/include/opencv2/saliency/saliencySpecializedClasses.hpp, modules/saliency/src/BING/objectnessBING.cpp, modules/saliency/src/staticSaliency.cpp
=> Exporting saliency classes to Python

modules/ccalib/include/opencv2/ccalib/omnidir.hpp, modules/ccalib/src/omnidir.cpp
revise omnidir::calibrate API (InputArray to InpurArrayOfArray) so that Python bindings will work
=> revise omnidir::calibrate API (InputArray to InpurArrayOfArray) 

modules/saliency/CMakeLists.txt, modules/saliency/src/BING/objectnessBING.cpp
Fix for @mshabunin 's comment in #796
=> Revert last changes in CMake for saliency module

modules/aruco/include/opencv2/aruco.hpp, modules/aruco/src/aruco.cpp
=> aruco: correct marker coordinates in drawPlanarBoard

modules/optflow/src/motempl.cpp, modules/saliency/CMakeLists.txt, modules/ximgproc/test/test_adaptive_manifold_ref_impl.cpp
**Merge with:** https://github.com/opencv/opencv/pull/7428
=> eliminate compiler warnings

modules/sfm/CMakeLists.txt
**Merge with main repo**: https://github.com/opencv/opencv/pull/7457
=> CMake: fix ios build

modules/text/src/ocr_hmm_decoder.cpp
resolves #529
added a delete[] call in ocr_hmm_decoder.cpp
=> text: fix memleak in ocr_hmm_decoder

modules/aruco/include/opencv2/aruco/charuco.hpp, modules/aruco/src/charuco.cpp
allows trading corner precision for corner quantity
=> aruco: interpolateCornersCharuco - make minMarkers property configurable

modules/optflow/doc/optflow.bib
Please, see comments in #708 for details.
=> Updated BIB reference to DISFlow paper

modules/xfeatures2d/src/precomp.hpp
Minor clean up. There was no need to keep these lines.
=> Removed redundant commented code

modules/saliency/doc/saliency.bib, modules/saliency/include/opencv2/saliency/saliencySpecializedClasses.hpp, modules/saliency/samples/computeSaliency.cpp, modules/saliency/src/saliency.cpp, modules/saliency/src/staticSaliencyFineGrained.cpp
=> Add Fine Grained Saliency algorithm

modules/face/src/facerec.cpp
Fixes the error message when loading a FaceRecognizer from a file fails.
=> face: Fix error message on failed loading attempt

modules/dpm/src/dpm_convolution.cpp
=> Accelerating convolution by changing the way of memory access.

modules/text/src/erfilter.cpp
=> Fix ERFilterNM fails on some images

modules/face/src/bif.cpp
=> fixed NaNs in BIF::compute()

modules/line_descriptor/src/LSDDetector.cpp, modules/line_descriptor/src/binary_descriptor.cpp, modules/line_descriptor/test/test_descriptors_regression.cpp
=> Fix crash when no lines found in BinaryDescriptor

modules/text/include/opencv2/text/erfilter.hpp, modules/text/src/erfilter.cpp
=> Replace dummy pointer with smart in ERStat

modules/hdf/src/hdf5.cpp, modules/xfeatures2d/src/pct_signatures/grayscale_bitmap.cpp
https://github.com/opencv/opencv/pull/7641
=> Fix build warnings

modules/cnn_3dobj/CMakeLists.txt, modules/cnn_3dobj/tutorials/data_generation/data_generation.markdown, modules/cnn_3dobj/tutorials/feature_classification/classify.markdown, modules/cnn_3dobj/tutorials/model_analysis/model_analysis.markdown
also fix some minor doxygen issues
=> cnn_3dobj: add call to ocv_module_disable so documentation is generated

modules/tracking/include/opencv2/tracking/kalman_filters.hpp, modules/tracking/src/augmented_unscented_kalman.cpp, modules/tracking/src/precomp.hpp, modules/tracking/src/unscented_kalman.cpp
Local copy of Colesky decomposition function was replaced with the similar function from `hal` namespace.
=> Remove duplicated code in UnscentedKalmanFilter

modules/tracking/CMakeLists.txt, modules/tracking/samples/multiTracker_dataset.cpp, modules/tracking/samples/tracker_dataset.cpp
=> tracking: make datasets dependancy optional

modules/tracking/src/trackerModel.cpp
=> Fix memory leak in MIL tracker

modules/tracking/CMakeLists.txt, modules/tracking/samples/benchmark.cpp
- used C++ to handle resources and output
- simplified and refactored the code
- changed statistic calculation (precision, recall, etc)
- used CommandLineParser -> CL interface has changed
=> Updated tracking benchmark script

modules/xphoto/src/simple_color_balance.cpp, modules/xphoto/test/simple_color_balance.cpp, modules/xphoto/test/test_grayworld.cpp
Replaces #594
Resolves #154
PR in extra: https://github.com/opencv/opencv_extra/pull/317
=> Fix wrong max value in SimpleWB

modules/line_descriptor/include/opencv2/line_descriptor/descriptor.hpp, modules/line_descriptor/src/binary_descriptor_matcher.cpp
=> Fix memory leak in binaryDescriptorMatcher

modules/ximgproc/include/opencv2/ximgproc.hpp, modules/ximgproc/samples/thinning.cpp, modules/ximgproc/src/thinning.cpp, modules/ximgproc/test/test_thinning.cpp
Added the option to choose which thinning algorithm you want to use
=> added multiple thinning algorithms

modules/line_descriptor/src/binary_descriptor.cpp
=> Fix coordinates overflow in binary line descriptor

modules/ximgproc/samples/structured_edge_detection.cpp, modules/ximgproc/src/structured_edge_detection.cpp
=> Fix rounding in StructuredEdgeDetection

modules/tracking/src/tldDetector.cpp, modules/tracking/src/tldDetector.hpp, modules/tracking/src/tldModel.cpp, modules/tracking/src/tldModel.hpp
=> TLD with parallel_for_ (targeting TBB enabled builds)

modules/ximgproc/include/opencv2/ximgproc.hpp, modules/ximgproc/include/opencv2/ximgproc/fast_line_detector.hpp
Added a group ximgproc_fast_line_detector to ximgproc.hpp for better documentation
=> Add a group ximgproc_fast_line_detector

modules/aruco/src/aruco.cpp, modules/aruco/src/charuco.cpp
=> aruco: use Mat().copyTo idiom instead of for loops

modules/datasets/include/opencv2/datasets/track_alov.hpp, modules/datasets/src/track_alov.cpp, modules/tracking/CMakeLists.txt, modules/tracking/doc/tracking.bib, modules/tracking/include/opencv2/tracking/tracker.hpp, modules/tracking/perf/perf_Tracker.cpp, modules/tracking/samples/goturnTracker.cpp, modules/tracking/src/gtrTracker.cpp, modules/tracking/src/gtrTracker.hpp, modules/tracking/src/gtrUtils.cpp, modules/tracking/src/gtrUtils.hpp, modules/tracking/src/tracker.cpp, modules/tracking/test/test_trackerOPE.cpp, modules/tracking/test/test_trackerSRE.cpp, modules/tracking/test/test_trackerTRE.cpp
PR #718 rebased, squashed and updated (minor code-style comments fixed)
=> GOTURN tracker fixes

modules/dnn/3rdparty/protobuf/CMakeLists.txt, modules/dnn/cmake/OpenCVFindLibProtobuf.cmake, modules/dnn/cmake/download_protobuf.cmake
=> cmake: unpack protobuf into binary directory

modules/bioinspired/include/opencv2/bioinspired/retina.hpp, modules/bioinspired/src/retina.cpp, modules/bioinspired/src/transientareassegmentationmodule.cpp
verbose option to avoid unnecessary prints. Some typos are also fixed.
@amroamroamro Can you test to see if the modifications did not break anything and solve your issue?
Related: [unnecessary print statements #7781](https://github.com/opencv/opencv/issues/7781)
=> Bioinspired module: fix some typos, add verbose option.

modules/ximgproc/include/opencv2/ximgproc/paillou_filter.hpp, modules/ximgproc/samples/paillou_demo.cpp, modules/ximgproc/src/paillou_filter.cpp
Improve paillou filter
add license
InputArray OutputArray use as parameter
template for IIR filter
use Ptr<Mat> for example
=> Improve paillou filter

modules/ximgproc/include/opencv2/ximgproc.hpp
=> fix link for thinningTypes

modules/text/src/ocr_beamsearch_decoder.cpp, modules/text/src/ocr_hmm_decoder.cpp
Bug when set Optimization Level to "-Ofast" (Fastest, Aggressive Optimizations) in xcode, read the wrong patch_size parameters to 7 (should be 8). 
Take the following code for example:
`patch_size  = (int)sqrt((float)kernels.cols);`
if `kernels.cols == 64.0`,  `patch_size` may assigned by `(int)sqrt(64.0f) = (int)(7.99999999) = 7`, It was dangerous and crashed in "-Ofast" setting. Therefore, the code needs to be changed to:
`patch_size  = (int)round(sqrt((float)kernels.cols));`
This bug will occured in `loadOCRHMMClassifierCNN` function called by `example_text_character_recognition` and `example_text_segmented_word_recognition`.
I also optimized a little bit of code by the way.
In addition, I also found a potential risk, but did **not** modify them, I hope the authors can improve them.
In …
=> Bug in Text module when set Optimization Level to "-Ofast" in xcode

modules/dnn/CMakeLists.txt, modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/include/opencv2/dnn/dnn.hpp, modules/dnn/samples/torch_enet.cpp, modules/dnn/src/caffe/layer_loaders.cpp, modules/dnn/src/dnn.cpp, modules/dnn/src/init.cpp, modules/dnn/src/layers/batch_norm_layer.cpp, modules/dnn/src/layers/batch_norm_layer.hpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/convolution_layer.hpp, modules/dnn/src/layers/elementwise_layers.cpp, modules/dnn/src/layers/elementwise_layers.hpp, modules/dnn/src/layers/eltwise_layer.cpp, modules/dnn/src/layers/max_unpooling_layer.cpp, modules/dnn/src/layers/max_unpooling_layer.hpp, modules/dnn/src/layers/padding_layer.cpp, modules/dnn/src/layers/padding_layer.hpp, modules/dnn/src/layers/pooling_layer.cpp, modules/dnn/src/layers/pooling_layer.hpp, modules/dnn/src/layers/shift_layer.cpp, modules/dnn/src/opencl/pooling.cl, modules/dnn/src/torch/torch_importer.cpp, modules/dnn/test/test_layers.cpp, modules/dnn/test/test_tf_importer.cpp
Added loading Torch ENet model: changed Torch models reader and added all necessary layers
=> Added Torch ENet support

modules/dnn/CMakeLists.txt
**Merge with**: https://github.com/opencv/opencv/pull/7999
=> cmake: fix LAPACK support

modules/dnn/samples/torch_enet.cpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/convolution_layer.hpp, modules/dnn/src/layers/elementwise_layers.hpp, modules/dnn/src/layers/op_im2col.hpp, modules/dnn/src/torch/torch_importer.cpp
Made some optimizations: added im2row, rewrite some frequently called loops
Rewrited Torch ENet sample to make it more useful
=> Added im2row, tiny optimiziations

modules/aruco/include/opencv2/aruco.hpp, modules/aruco/include/opencv2/aruco/charuco.hpp, modules/aruco/src/aruco.cpp, modules/aruco/src/charuco.cpp, modules/aruco/test/test_boarddetection.cpp
=> Add useExtrinsicGuess flag in estimatePoseBoard() for aruco and charuco

modules/dnn/CMakeLists.txt
=> Just for testing purpose

modules/dnn/CMakeLists.txt, modules/dnn/src/torch/THDiskFile.cpp
=> dnn: enable on iOS and aarch64

modules/aruco/src/aruco.cpp, modules/aruco/src/charuco.cpp
=> aruco: let solvePnP allocate rvec and tvec

modules/dnn/src/torch/torch_importer.cpp
=> Fix python bindings for dnn build when Torch is disabled

modules/xfeatures2d/src/boostdesc.cpp, modules/xfeatures2d/src/harris_lapace_detector.cpp, modules/xfeatures2d/src/pct_signatures.cpp
Minor changes to fix visual studio 2010 build errors.
resolves #975
=> Fixed issue 975 - fixed visual studio 2010 build errors on module xfeatures2d

modules/reg/src/mapper.cpp, modules/reg/test/test_reg.cpp
=> reg: add support of different data types in Mapper::grid()

modules/tracking/CMakeLists.txt
i think tracking module is ready to use in java
=> enable tracking for java

modules/text/src/ocr_beamsearch_decoder.cpp, modules/text/src/ocr_hmm_decoder.cpp, modules/ximgproc/src/fast_line_detector.cpp
#975
Minor changes to fix lower visual studio version build errors.
round function changes to cvRound.
Below is the modified list.
modules\ximgproc\src\fast_line_detector.cpp
modules\text\src\ocr_hmm_decoder.cpp
modules\text\src\ocr_beamsearch_decoder.cpp
resolves #980
=> issue #980 resolves - Some module has a round error similar to #975. 

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/misc/caffe/caffe.pb.cc, modules/dnn/misc/caffe/caffe.pb.h, modules/dnn/src/caffe/caffe.proto, modules/dnn/src/caffe/caffe_io.cpp, modules/dnn/src/caffe/layer_loaders.cpp, modules/dnn/src/init.cpp, modules/dnn/src/layers/batch_norm_layer.cpp, modules/dnn/src/layers/scale_layer.cpp, modules/dnn/src/layers/scale_layer.hpp, modules/dnn/src/torch/torch_importer.cpp, modules/dnn/test/test_layers.cpp, modules/dnn/test/test_torch_importer.cpp, modules/dnn/testdata/dnn/torch/torch_gen_test_data.lua
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/323
resolves #912 
Updated caffe models importer, so it can read models with BatchNormalization layer. Also added some tests
=> Updated proto files, added layers to caffe

modules/ccalib/tutorials/omnidir_tutorial.markdown, modules/rgbd/include/opencv2/rgbd.hpp, modules/rgbd/src/odometry.cpp
Provides Python wrapper for `cv2.rgbd.depthTo3d()` and `cv2.rgbd.warpFrame()` functions.
@alalek Kindly review this pull. It is the same of #990, but you might notice some extra (but irrelevant) empty lines removed by the editor, kindly ignore them!
=> Features/python wrapper/rgbd

modules/dnn/src/caffe/layer_loaders.cpp, modules/dnn/src/layers/elementwise_layers.cpp
* Added missed initializations of layer names and types.
* Parameters initializations of elementwise layers created with functors. Inherited parameter fields are not initialized.
=> Missed layer params

modules/dnn/samples/torch_enet.cpp, modules/dnn/src/layers/max_unpooling_layer.cpp, modules/dnn/test/test_torch_importer.cpp, modules/dnn/testdata/dnn/torch/torch_gen_test_data.lua
Added few tests for torch part while testing ENet accuracy
=> Added few tests for torch

modules/dnn/include/opencv2/dnn/dnn.hpp, modules/dnn/src/dnn.cpp
Added function for getting input layers of specific layer from Net by layerId.
=> Getting layer inputs

modules/tracking/test/test_trackers.cpp
=> tracking: update TLD overlap threshold

modules/sfm/CMakeLists.txt
=> sfm: fix missing module include in cmake

modules/tracking/test/test_trackers.cpp
Add tests for KCF, disable tests for TLD
=> Tracking tests changes

modules/dnn_modern/src/caffe_converter.cpp
resolves #1012 as suggested by @berak
=> fix dnn_modern build

modules/freetype/CMakeLists.txt
**Merge with contrib**: https://github.com/opencv/opencv/pull/8234
=> freetype: disable for Apple frameworks

modules/surface_matching/include/opencv2/surface_matching/icp.hpp, modules/surface_matching/samples/ppf_icp.py, modules/surface_matching/src/icp.cpp
Exposes the `ICP` class to Python wrapper
=> Wrap ICP for Python

modules/tracking/include/opencv2/tracking/tracker.hpp, modules/tracking/src/trackerKCF.cpp, modules/tracking/test/test_trackerParametersIO.cpp
=> KCF parameters IO improvement

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/src/caffe/layer_loaders.cpp, modules/dnn/src/layers/max_unpooling_layer.cpp, modules/dnn/src/layers/max_unpooling_layer.hpp, modules/dnn/src/torch/torch_importer.cpp
list of parameters, which are passed to unpooling layer. Now this layer computes output size by itself.
=> Changed parameters of unpooling layer

modules/datasets/CMakeLists.txt, modules/datasets/samples/fr_lfw_benchmark.cpp
changed fr_lfw_benchmark, so it no more needs classes from opencv_face, so we can remove the dependancy (tracking module also depends on datasets).
(lfw also is a verification task, same / not-same, and should be trained without looking at labels)
=> datasets: remove face dependancy

modules/saliency/include/opencv2/saliency/saliencySpecializedClasses.hpp
Add CV_WRAP to getobjectnessValues().
=> Add CV_WRAP to getobjectnessValues() of saliency module

modules/tracking/CMakeLists.txt, modules/tracking/samples/goturnTracker.cpp, modules/tracking/samples/multiTracker_dataset.cpp, modules/tracking/samples/tracker_dataset.cpp, modules/tracking/src/gtrTracker.cpp, modules/tracking/src/gtrTracker.hpp, modules/tracking/src/gtrUtils.cpp, modules/tracking/src/gtrUtils.hpp, modules/tracking/src/tracker.cpp
resolves #1036
resolves #1030
resolves #1046
add a few HAVE_OPENCV_DNN conditionals, based on opencv_modules.hpp
=> tracking: make opencv_dnn dependancy optional

modules/surface_matching/src/icp.cpp
A uniform sampling is needed in order to ensure accurate ICP
As a proof of concept, the ICP residual of samples decreases after applying this patch!
For each ICP level:
- downsample scene points
- compute FLANN index
=> Downsampling of the scene points in ICP for further optimization

modules/surface_matching/include/opencv2/surface_matching/ppf_helpers.hpp, modules/surface_matching/src/icp.cpp, modules/surface_matching/src/ppf_helpers.cpp
Speedup processing poses passed to `registerModelToScene()`
=> Parallelize `ICP::registerModelToScene`

modules/text/samples/end_to_end_recognition.cpp
Line 139: Fixed typo of word "length".
=> fixed typo in comment

modules/optflow/samples/dis_opticalflow.cpp
it takes a video file as input and shows colored optical flow.
Signed-off-by: Li Peng <peng.li@intel.com>
=> add dis optical flow sample app

modules/text/samples/textdetection.py
=> fix erGrouping parameter error

modules/dnn/src/layers/padding_layer.cpp
=> Fixed issue 1007

modules/dnn/cmake/OpenCVFindLibProtobuf.cmake, modules/xfeatures2d/cmake/download_boostdesc.cmake, modules/xfeatures2d/cmake/download_vgg.cmake
**Merge with**: https://github.com/opencv/opencv/pull/8474
=> cmake: update ocv_download

modules/ximgproc/include/opencv2/ximgproc/weighted_median_filter.hpp, modules/ximgproc/src/weighted_median_filter.cpp, modules/ximgproc/test/test_weighted_median_filter.cpp
=> ximgproc: fix weightedMedianFilter crash on empty mask

modules/surface_matching/src/ppf_match_3d.cpp
=> Fix not initialized raw pointers in PPF3DDetector

modules/ximgproc/doc/ximgproc.bib, modules/ximgproc/include/opencv2/ximgproc/slic.hpp, modules/ximgproc/src/slic.cpp
Main author (Mr. Yong-Jin Liu) asked me to update citation and contact info. It does not affect the code or runtime.
=> Update MSLIC citation and author's contact.

modules/ximgproc/include/opencv2/ximgproc/segmentation.hpp, modules/ximgproc/samples/selectivesearchsegmentation_demo.py
process method of createSelectiveSearchSegmentation don't returns bounding boxes in python bindings.
This PR fixes this. I also added a sample in python.
=> Added CV_OUT in process() of selective search segmentation module.

modules/xphoto/src/annf.hpp
=> xphoto::inpaint(): fixed data copying from Mat to vector

modules/rgbd/include/opencv2/rgbd/linemod.hpp, modules/rgbd/misc/python/pyopencv_linemod.hpp
requires https://github.com/opencv/opencv/pull/8654
=> linemod: add rudimentary python bindings

modules/ximgproc/src/structured_edge_detection.cpp
=> [bugfix] Rounding error in cv::ximgproc::StructuredEdgeDetection

modules/dnn/src/dnn.cpp, modules/dnn/src/layers/op_im2col.cpp, modules/dnn/src/torch/THDiskFile.cpp, modules/dnn/src/torch/THDiskFile.h, modules/dnn/src/torch/THFile.cpp, modules/dnn/src/torch/THFile.h, modules/dnn/src/torch/THFilePrivate.h, modules/dnn/src/torch/torch_importer.cpp, modules/dnn/test/test_common.hpp, modules/dnn/test/test_googlenet.cpp, modules/dnn/test/test_layers.cpp, modules/dnn/test/test_torch_importer.cpp
Fixed some bugs after refactoring dnn. Added new tests, testdata is here: https://github.com/opencv/opencv_extra/pull/334
=> Fixed bugs after dnn refactoring. Added new tests for layers

modules/aruco/tutorials/aruco_board_detection/aruco_board_detection.markdown, modules/aruco/tutorials/aruco_calibration/aruco_calibration.markdown, modules/aruco/tutorials/aruco_detection/aruco_detection.markdown, modules/aruco/tutorials/charuco_detection/charuco_detection.markdown, modules/aruco/tutorials/charuco_diamond_detection/charuco_diamond_detection.markdown
I fixed a tutorial of aruco module.
* I removed unnecessary character from document in tutorial(aruco module)
* I fixed sample code in tutorial(aruco module)
=> fixed a tutorial of aruco module

modules/ximgproc/include/opencv2/ximgproc/structured_edge_detection.hpp, modules/ximgproc/samples/structured_edge_detection.cpp, modules/ximgproc/src/structured_edge_detection.cpp
This PR have two functions:
- computeOrientation: computes orientation map from edge image.
- edgesNms: suppress edges.
both functions helps to edgeboxes algorithm implementation.
=> added computeOrientation and edgenms in structured_edge_detection

modules/dnn/test/test_caffe_importer.cpp, modules/dnn/test/test_googlenet.cpp, modules/dnn/test/test_main.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/337
Enabled large models tests, fixed issues with them
=> Enable large models tests

modules/optflow/include/opencv2/optflow/sparse_matching_gpc.hpp, modules/optflow/src/dis_flow.cpp, modules/optflow/src/sparse_matching_gpc.cpp
=> solve issue 1165

modules/sfm/include/opencv2/sfm/reconstruct.hpp, modules/sfm/include/opencv2/sfm/simple_pipeline.hpp, modules/sfm/samples/scene_reconstruction.cpp, modules/sfm/samples/trajectory_reconstruccion.cpp, modules/sfm/src/reconstruct.cpp, modules/sfm/src/simple_pipeline.cpp, modules/sfm/tutorials/sfm_installation/sfm_installation.markdown
Try to solve issue #8748 and update sfm doc for windows
=> try to solve issue #8748

modules/dnn/include/opencv2/dnn/shape_utils.hpp
=> fixed shape() function

modules/ximgproc/include/opencv2/ximgproc.hpp, modules/ximgproc/samples/filterdemo.cpp, modules/ximgproc/src/anisodiff.cpp, modules/ximgproc/src/opencl/anisodiff.cl, modules/ximgproc/test/test_anisodiff.cpp
This is rewrite of https://github.com/opencv/opencv/pull/8362. Thanks to sav-chris for the reference implementation
=> added optimized anisotropic diffusion filter

modules/dnn/include/opencv2/dnn/dnn.hpp, modules/dnn/src/dnn.cpp, modules/dnn/src/layers/batch_norm_layer.cpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/elementwise_layers.cpp, modules/dnn/src/layers/eltwise_layer.cpp, modules/dnn/src/layers/fully_connected_layer.cpp, modules/dnn/src/layers/lrn_layer.cpp, modules/dnn/src/layers/mvn_layer.cpp, modules/dnn/src/layers/pooling_layer.cpp, modules/dnn/src/layers/prior_box_layer.cpp, modules/dnn/src/layers/scale_layer.cpp, modules/dnn/src/layers/shift_layer.cpp, modules/dnn/src/layers/softmax_layer.cpp, modules/dnn/test/test_caffe_importer.cpp, modules/dnn/test/test_torch_importer.cpp
Added statistics functions for models: counting FLOPS, getting all used layer types, getting count of layers with certain type, computing memory consumption
=> Added statistics functions

modules/dnn/src/dnn.cpp
=> Changed blobFromImages() function, so it can handle 1-channel images

modules/aruco/samples/detector_params.yml, modules/aruco/tutorials/aruco_detection/aruco_detection.markdown, modules/aruco/tutorials/charuco_detection/charuco_detection.markdown
the last `doCornerRefinement()` parameters to `cornerRefinementMethod()`.
=> Update doCornerRefinement() parameter to cornerRefinementMethod().

modules/optflow/perf/opencl/perf_dis_optflow.cpp, modules/optflow/perf/perf_disflow.cpp, modules/optflow/src/sparse_matching_gpc.cpp, modules/optflow/test/test_OF_reproducibility.cpp, modules/structured_light/samples/projectorcalibration.cpp, modules/structured_light/src/sinusoidalpattern.cpp, modules/xfeatures2d/samples/pct_webcam.cpp, modules/ximgproc/src/bilateral_texture_filter.cpp
Some changes to fix VS2010 build errors
=> Some changes to make VS2010 compiler happy.

modules/dnn/misc/caffe/caffe.pb.cc, modules/dnn/misc/caffe/caffe.pb.h, modules/dnn/samples/ssd_object_detection.cpp, modules/dnn/src/caffe/caffe.proto, modules/dnn/src/init.cpp, modules/dnn/src/layers/detection_output_layer.cpp, modules/dnn/src/layers/flatten_layer.cpp, modules/dnn/src/layers/permute_layer.cpp, modules/dnn/src/layers/prior_box_layer.cpp, modules/dnn/test/test_caffe_importer.cpp
Made SSD sample work again!
Updated caffe.proto file to support the latest ssd models
Fixed all things which cause differences between dnn and caffe outputs for SSD
Added test for SSD
=> Fixed SSD example, added test

modules/dnn/src/layers/fully_connected_layer.cpp, modules/dnn/src/layers/layers_common.avx2.cpp
Fully connected layer crashed in debug mode
=> dnn: fixed GEMM1T AVX2 implementation

modules/line_descriptor/include/opencv2/line_descriptor/descriptor.hpp, modules/plot/src/plot.cpp, modules/sfm/test/test_common.cpp, modules/surface_matching/src/ppf_helpers.cpp
=> Get rid of exit() calls in algorithms and tests

modules/dnn/perf/perf_halide_net.cpp, modules/dnn/samples/squeezenet_halide.cpp, modules/dnn/test/test_halide_layers.cpp, modules/dnn/test/test_halide_nets.cpp, modules/dnn/tutorials/tutorial_dnn_halide.markdown, modules/dnn/tutorials/tutorial_dnn_halide_scheduling.markdown
`cv::Net` interface changes in Halide tests and docs.
=> Update Halide tests

modules/aruco/src/aruco.cpp, modules/aruco/test/test_misc.cpp
=> aruco: fix non-square marker size in _drawPlanarBoardImpl

modules/dnn/include/opencv2/dnn/dnn.hpp, modules/dnn/samples/caffe_googlenet.cpp, modules/dnn/samples/squeezenet_halide.cpp, modules/dnn/samples/torch_enet.cpp, modules/dnn/src/dnn.cpp, modules/dnn/test/test_caffe_importer.cpp, modules/dnn/test/test_tf_importer.cpp
Added blobFromImage functions which can crop input from the center and subtract mean
=> Added another overloads of blobFromImage functions 

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/src/dnn.cpp, modules/dnn/src/layers/batch_norm_layer.cpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/layers_common.avx2.cpp, modules/dnn/src/layers/layers_common.hpp, modules/dnn/src/layers/pooling_layer.cpp, modules/dnn/test/test_googlenet.cpp
**WIP**
improved GoogLeNet perf by ~10%
=> enabled convolution & activation fusion

modules/dnn/src/dnn.cpp, modules/dnn/test/test_googlenet.cpp
Fixed code to enable tests for intermediate blobs in googlenet test
=> Enabled tests for intermediate blobs in goolgenet

modules/face/include/opencv2/face.hpp, modules/face/include/opencv2/face/facerec.hpp, modules/face/samples/facerec_lbph.cpp, modules/face/samples/facerec_save_load.cpp, modules/face/src/face_basic.cpp, modules/face/src/lbph_faces.cpp, modules/face/tutorials/face_tutorial.markdown
* change some leftover createXXXRecognizer mentioning in docs / examples / header comments
* to make Algorithm::load() work without any loss, the threshold member variable should be serialized, too.
=> face: minor cleanup after #1239

modules/optflow/samples/gpc_evaluate.cpp, modules/optflow/src/sparse_matching_gpc.cpp
Fixed two recently found bugs inside GPC code. Thanks @boulderZ !
https://github.com/opencv/opencv/issues/9183
https://github.com/opencv/opencv/issues/9220
resolves opencv/opencv#9183
resolves opencv/opencv#9220
=> Fixes for Global Patch Collider evaluation tool

modules/ximgproc/src/structured_edge_detection.cpp
=> ximgproc: change M_PI to CV_PI in structured_edge_detection

modules/rgbd/include/opencv2/rgbd.hpp, modules/rgbd/src/odometry.cpp
Exposes RGBD Odometry classes and functions to Python
=> Added python bindings for rgbd module

modules/line_descriptor/samples/compute_descriptors.cpp, modules/line_descriptor/samples/knn_matching.cpp, modules/line_descriptor/samples/lines_extraction.cpp, modules/line_descriptor/samples/lsd_lines_extraction.cpp, modules/line_descriptor/samples/matching.cpp, modules/line_descriptor/samples/radius_matching.cpp, modules/xfeatures2d/CMakeLists.txt, modules/xfeatures2d/samples/bagofwords_classification.cpp, modules/xfeatures2d/samples/shape_transformation.cpp, modules/xfeatures2d/samples/video_homography.cpp
see http://answers.opencv.org/question/169646
=> Update line descriptor samples

modules/dnn_modern/CMakeLists.txt
https://github.com/opencv/opencv/pull/9415
=> cmake: deprecated policies

modules/structured_light/include/opencv2/structured_light/sinusoidalpattern.hpp, modules/structured_light/samples/capsinpattern.cpp, modules/structured_light/src/sinusoidalpattern.cpp, modules/structured_light/test/test_faps.cpp
=> structured light: wrap create method of the SinusoidalPattern class

modules/ccalib/include/opencv2/ccalib/omnidir.hpp, modules/ccalib/src/omnidir.cpp
=> omnidir: fix wrong memory access in estimateUncertainties

modules/tracking/include/opencv2/tracking/tracker.hpp
=> Updated KCF original paper link

modules/bgsegm/src/bgfg_gmg.cpp, modules/ccalib/include/opencv2/ccalib.hpp, modules/ccalib/src/ccalib.cpp, modules/optflow/src/simpleflow.cpp, modules/rgbd/include/opencv2/rgbd/linemod.hpp, modules/saliency/src/BING/FilterTIG.cpp, modules/structured_light/include/opencv2/structured_light/structured_light.hpp, modules/structured_light/src/graycodepattern.cpp, modules/structured_light/src/sinusoidalpattern.cpp, modules/ximgproc/src/dtfilter_cpu.inl.hpp, modules/ximgproc/src/fgs_filter.cpp, modules/ximgproc/src/joint_bilateral_filter.cpp, modules/ximgproc/test/test_domain_transform.cpp, modules/ximgproc/test/test_joint_bilateral_filter.cpp, modules/ximgproc/test/test_structured_edge_detection.cpp
**Merge with**: https://github.com/opencv/opencv/pull/9457
=> fix type traits

modules/tracking/src/gtrTracker.cpp
Replace `createCaffeImporter` to `readNetFromCaffe` in tracking module.
=> Replace createCaffeImporter to readNetFromCaffe

modules/tracking/samples/tutorial_multitracker.cpp
=> fix a runtime bug.

modules/face/tutorials/face_tutorial.markdown
=> Fixed minor doc issue

modules/tracking/src/gtrTracker.cpp, modules/tracking/test/test_trackers.cpp
Resolves https://github.com/opencv/opencv/issues/9625
**Merge with opencv**: https://github.com/opencv/opencv/pull/9676
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/382
Set swapRB to false in GOTURN tracker.
=> Set swapRB to false in GOTURN tracker

modules/xfeatures2d/src/sift.cpp
_mm256_cvtps_epi32 will do the rounding.
=> Remove unnecessary _mm256_round_ps

modules/tracking/src/tldTracker.cpp
=> TLD with gray scale images

modules/plot/include/opencv2/plot.hpp, modules/plot/samples/plot_demo.cpp, modules/plot/src/plot.cpp
=> Update plot module

modules/xfeatures2d/perf/perf_surf.cpp, modules/xfeatures2d/src/opencl/surf.cl, modules/xfeatures2d/src/surf.ocl.cpp, modules/xfeatures2d/test/test_features2d.cpp, modules/xfeatures2d/test/test_precomp.hpp, modules/xfeatures2d/test/test_rotation_and_scale_invariance.cpp, modules/xfeatures2d/test/test_surf.ocl.cpp
=> Fix SURF OCL

modules/xfeatures2d/src/surf.cpp, modules/xfeatures2d/test/test_features2d.cpp, modules/xfeatures2d/test/test_surf.ocl.cpp
related #1371
http://pullrequest.opencv.org/buildbot/builders/precommit_opencl/builds/12567/steps/test_java-ippicv-opencl/logs/junit-report-html
=> surf: fix OpenCL condition

modules/face/include/opencv2/face/facerec.hpp, modules/face/src/eigen_faces.cpp, modules/face/src/fisher_faces.cpp, modules/face/src/lbph_faces.cpp
Just a pr to update doc see http://answers.opencv.org/question/26777/createlbphfacerecognizer-radius-parameter/ and method getDefaultName which is not defined in FaceRecognizer fisher, eigen or lbph
=> Update doc and method String getDefaultName()

modules/datasets/samples/tr_icdar_benchmark.cpp, modules/datasets/samples/tr_svt_benchmark.cpp
**Merge with**: https://github.com/opencv/opencv/pull/9746
=> build: fix MSVS2017 warning

modules/surface_matching/include/opencv2/surface_matching/ppf_helpers.hpp, modules/surface_matching/src/ppf_helpers.cpp
in addition to ascii there is a binary .ply format, which this function does not support. I added code to report that unsupported data is being read.
=> surface_matching loadPLYSimple() now reports that only ascii format is supported

modules/aruco/tutorials/aruco_board_detection/aruco_board_detection.markdown, modules/aruco/tutorials/aruco_calibration/aruco_calibration.markdown, modules/aruco/tutorials/aruco_detection/aruco_detection.markdown, modules/aruco/tutorials/charuco_detection/charuco_detection.markdown, modules/aruco/tutorials/charuco_diamond_detection/charuco_diamond_detection.markdown
resolves https://github.com/opencv/opencv_contrib/pull/1153#issuecomment-300806186
I updated a tutorial of aruco module.
- I used <code>@code</code> command to insert code in tutorial
=> Updated aruco tutorial

modules/tracking/doc/tracking.bib, modules/tracking/include/opencv2/tracking/tracker.hpp, modules/tracking/samples/samples_utility.hpp, modules/tracking/samples/tracker.cpp, modules/tracking/src/mosseTracker.cpp, modules/tracking/test/test_trackers.cpp
this pr adds a MOSSE tracker to the tracking module, quite similar to the python sample in opencv main.
=> tracking: adding a mosse tracker

modules/ccalib/src/multicalib.cpp
=> Fix name extraction from path in multicalib

modules/face/include/opencv2/face/facemark.hpp, modules/face/include/opencv2/face/facemarkAAM.hpp, modules/face/include/opencv2/face/facemarkLBF.hpp, modules/face/samples/facemark_demo_aam.cpp, modules/face/samples/facemark_demo_lbf.cpp, modules/face/samples/facemark_lbf_fitting.cpp, modules/face/src/facemark.cpp, modules/face/src/facemarkAAM.cpp, modules/face/src/facemarkLBF.cpp, modules/face/src/precomp.hpp, modules/face/test/test_facemark.cpp, modules/face/test/test_facemark_aam.cpp, modules/face/test/test_facemark_lbf.cpp, modules/face/tutorials/facemark_usage/facemark_usage.markdown
=> PR #1257 refactoring

modules/matlab/README.md
Patch moved to non-master branch to allow automated PR testing
resolves #664 
resolves #1201 
Matlab module readme documentation is updated with more correct example code.
=> Update matlab module readme to fix #664 and #1201

modules/README.md, modules/ovis/CMakeLists.txt, modules/ovis/README.md, modules/ovis/include/opencv2/ovis.hpp, modules/ovis/samples/aruco_ar_demo.py, modules/ovis/samples/ovis_demo.py, modules/ovis/src/meshes.cpp, modules/ovis/src/ovis.cpp, modules/ovis/src/precomp.hpp
=> add Ogre3D based visualizer module

modules/xfeatures2d/src/fast.cpp
FAST feature detection on specific locations fixed
Related: https://github.com/opencv/opencv_contrib/pull/1387#pullrequestreview-74286688
=> Fix for FAST feature detection on specific locations

modules/cvv/samples/cvv_demo.cpp, modules/cvv/src/stfl/stringutils.cpp
- Replace getopt with CommandLineParser
- Workaround for VS compatibility with Unicode strings [Ü, Ö, Ä]
=> Cvv parser compatibility issues

modules/ximgproc/include/opencv2/ximgproc/peilin.hpp, modules/ximgproc/samples/peilin.cpp, modules/ximgproc/src/peilin.cpp
https://github.com/opencv/opencv_contrib/pull/1379#pullrequestreview-74291694
=> ximgproc: fix namespace

modules/surface_matching/samples/ppf_icp.py
=> ppf_icp.py: Python 3 support

modules/ximgproc/include/opencv2/ximgproc/fourier_descriptors.hpp, modules/ximgproc/samples/fourier_descriptors_demo.cpp, modules/ximgproc/src/fourier_descriptors.cpp
=> ximgproc: rename global functions with generic names

modules/saliency/src/BING/kyheader.hpp, modules/sfm/src/libmv_light/libmv/numeric/numeric.h, modules/xfeatures2d/samples/bagofwords_classification.cpp
=> Fix incorrect windows definition.

modules/bioinspired/src/opencl/retina_kernel.cl, modules/bioinspired/src/retina.cpp, modules/bioinspired/src/retina_ocl.cpp, modules/bioinspired/src/retina_ocl.hpp, modules/bioinspired/test/test_retina_ocl.cpp
https://github.com/opencv/opencv_contrib/pull/1318#issuecomment-342971194
=> OCL: bioinspired: refactor OpenCL conditions

modules/text/samples/textbox.prototxt
=> Update PriorBox layer

modules/bioinspired/samples/retinaDemo.cpp, modules/ccalib/samples/omni_stereo_calibration.cpp, modules/datasets/src/track_vot.cpp, modules/sfm/test/test_projection.cpp, modules/text/samples/textdetection.cpp, modules/tracking/src/tldDetector.cpp, modules/tracking/src/tldDetector.hpp, modules/ximgproc/test/test_adaptive_manifold.cpp
**Note:** some `-Wstrict-overflow` warnings have been disabled for GCC 7.2.0
```
docker_image:Custom=ubuntu:17.10
```
=> Fixed several warnings produced by GCC 7

modules/bgsegm/CMakeLists.txt, modules/bgsegm/doc/bgsegm.bib, modules/bgsegm/include/opencv2/bgsegm.hpp, modules/bgsegm/samples/evaluation.py, modules/bgsegm/samples/viz.py, modules/bgsegm/samples/viz_synthetic_seq.py, modules/bgsegm/src/bgfg_gsoc.cpp, modules/bgsegm/src/synthetic_seq.cpp, modules/bgsegm/test/test_backgroundsubtractor_lsbp.cpp
Added stub implementation with interface.
Added evaluation tool.
Most likely I will need more methods to the BackgroundSubtractorLSBP in the future so this interface is not complete.
@mshabunin
=> [GSoC 17] Background subtraction algorithms.

modules/ximgproc/samples/paillou_demo.cpp
* better cmdline arg check
* remove global pointer to image
=> ximgproc: fix paillou_demo

modules/bgsegm/samples/evaluation.py, modules/bgsegm/samples/viz.py, modules/bgsegm/samples/viz_synthetic_seq.py, modules/bioinspired/doc/retina.markdown, modules/bioinspired/tutorials/retina_illusion/retina_illusion.markdown, modules/optflow/samples/motempl.py, modules/optflow/src/learn_prior.py, modules/ovis/samples/aruco_ar_demo.py, modules/ovis/samples/ovis_demo.py, modules/reg/samples/reg_shift.py, modules/surface_matching/samples/ppf_icp.py, modules/text/samples/deeptextdetection.py, modules/text/samples/detect_er_chars.py, modules/text/samples/textdetection.py, modules/tracking/samples/multitracker.py, modules/tracking/samples/tracker.py, modules/ximgproc/samples/edgeboxes_demo.py, modules/ximgproc/samples/findredlinedpolygonfromgooglemaps.py, modules/ximgproc/samples/selectivesearchsegmentation_demo.py, modules/xphoto/samples/color_balance_benchmark.py, modules/xphoto/samples/learn_color_balance.py, samples/python2/common.py, samples/python2/dis_opt_flow.py, samples/python2/seeds.py, samples/python2/video.py
related https://github.com/opencv/opencv/pull/10280
related https://github.com/opencv/opencv/pull/9260
=> Python: 'cv2.' -> 'cv.' via 'import cv2 as cv'

modules/optflow/include/opencv2/optflow/sparse_matching_gpc.hpp, modules/rgbd/test/test_normal.cpp
Addition to opencv/opencv#8198
- removed submodules (contrib_world)
- fixed issues with exported functions
=> Fixing exporting problems

modules/ovis/src/meshes.cpp, modules/ovis/src/ovis.cpp
=> ovis: allow point sprites with point clouds and tame the logging

modules/sfm/samples/scene_reconstruction.cpp
- Fixed a typo in the help text
- Fixed a typo in a comment line
=> Just a tiny fix of two typos

modules/tracking/include/opencv2/tracking/tracker.hpp
Fix some wrong comments in `modules/tracking/include/opencv2/tracking/tracker.hpp`.
=> Fix some wrong comments in tracker.hpp

modules/xfeatures2d/src/harris_lapace_detector.cpp
resolves #1513
If the aspect ratio is far from one, DoG octaves size differs from the global parameters.
This change needed to propagate properly to later iterations.
- Propagates the in-use DoG octaves size to later iterations
=> closes #1513 - HarrisLaplace bug

modules/xfeatures2d/include/opencv2/xfeatures2d.hpp
- Exposes `matchGMS` to Python binder
=> GMS for Python

modules/ximgproc/src/ridgedetectionfilter.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/439
resolves #1537 
Fixed eigenvalue estimation in getRidgeFilteredImage()
=> Fixed estimation of Hessian matrix eigenvalue in getRidgeFilteredImage()

modules/optflow/src/sparse_matching_gpc.cpp, modules/xfeatures2d/samples/bagofwords_classification.cpp
C++17 build is [here](http://pullrequest.opencv.org/buildbot/builders/precommit_windows64-vc15/builds/247)
=> build: fix C++17 build

modules/ovis/include/opencv2/ovis.hpp, modules/ovis/src/ovis.cpp
- render to float buffer
- flag to control FSAA
- set shader uniforms via setMaterialProperty
```
```
=> ovis: add advanced rendering capabilites

modules/sfm/samples/scene_reconstruction.cpp, modules/sfm/samples/trajectory_reconstruccion.cpp
- fixed minor compilation warnings
=> Fixed samples compilation warnings (no previous declaration)

modules/text/src/ocr_tesseract.cpp
=> text: don't delete null pointer in ocr_tesseract.cpp

modules/ovis/samples/ovis_demo.py, modules/ovis/src/ovis.cpp
=> ovis: make sure entities are oriented by the OpenCV CS conventions

modules/ovis/include/opencv2/ovis.hpp, modules/ovis/src/ovis.cpp
=> ovis: implement getDepth function for reading the camera depth

modules/datasets/src/tinyxml2/tinyxml2.cpp, modules/saliency/src/BING/CmShow.hpp, modules/saliency/src/BING/CmTimer.hpp, modules/saliency/src/BING/objectnessBING.cpp, modules/xfeatures2d/src/pct_signatures/distance.hpp, modules/xfeatures2d/src/pct_signatures/similarity.hpp
**Main PR**: https://github.com/opencv/opencv/pull/11112
=> build: fix includes

modules/ximgproc/samples/edgeboxes_demo.cpp, modules/ximgproc/src/edgeboxes.cpp
Solves a bug and show edge and Nms edges in edge_boxes_demo
resolves #1596
=> solves #1596

modules/face/src/facemarkLBF.cpp
=> face: fix missing faceDetectorData arg in facemarkLBF.cpp

modules/ximgproc/src/weighted_median_filter.cpp
=> ximgproc: fix weightedMedianFilter() hang

modules/datasets/src/or_pascal.cpp, modules/face/src/face_alignment.cpp, modules/face/src/facemark.cpp, modules/face/src/lbph_faces.cpp, modules/face/src/regtree.cpp, modules/face/src/trainFacemark.cpp, modules/line_descriptor/src/binary_descriptor.cpp, modules/rgbd/src/linemod.cpp, modules/tracking/src/gtrTracker.cpp, modules/tracking/src/tracker.cpp, modules/tracking/src/trackerBoostingModel.cpp, modules/tracking/src/trackerFeature.cpp, modules/tracking/src/trackerMILModel.cpp, modules/tracking/src/trackerModel.cpp, modules/tracking/src/trackerSamplerAlgorithm.cpp, modules/tracking/src/trackerStateEstimator.cpp, modules/xfeatures2d/samples/bagofwords_classification.cpp, modules/xfeatures2d/src/pct_signatures/distance.hpp, modules/xfeatures2d/src/pct_signatures/similarity.hpp, modules/xfeatures2d/src/surf.cuda.cpp, modules/ximgproc/src/disparity_filters.cpp, modules/ximgproc/src/weighted_median_filter.cpp
**Main PR**: https://github.com/opencv/opencv/pull/11381
```
```
=> refactor: don't use CV_ErrorNoReturn() internally

modules/bioinspired/src/retina_ocl.cpp, modules/surface_matching/src/hash_murmur86.hpp, modules/ximgproc/src/selectivesearchsegmentation.cpp
Main PR: https://github.com/opencv/opencv/pull/11391
- simplified big/little-endian detection
=> android: fix contrib build

modules/datasets/CMakeLists.txt, modules/surface_matching/src/hash_murmur64.hpp, modules/text/src/ocr_hmm_decoder.cpp, modules/ximgproc/src/seeds.cpp
**Main PR**: https://github.com/opencv/opencv/pull/11537
**Fixup PR**: https://github.com/opencv/opencv/pull/11555
=> eliminate build warnings / fix bug in text module

modules/face/samples/sampleDetectLandmarks.cpp
Added if condition, whether faces are detected or not, will help to keep program running for some images.
If imwrite used along with imshow, it may produce error for :  No faces found.Aborting.. in function 'fit' (Bad Argument).
Adds an if condition, for the condition when no face detected. Thus, proper flow of the code maintained.
=> Check if faces detected or not.

modules/rgbd/samples/kinfu_demo.cpp, modules/rgbd/src/tsdf.cpp
* Added support for live input from Kinect2 device
* fixed several minor bugs
=> KinectFusion demo: live input support added

modules/ximgproc/src/deriche_filter.cpp, modules/ximgproc/src/paillou_filter.cpp
1 One bug removed in deriche filter
2 add support for float image
3 move assert in ParallelGradientNAME:ParallelLoopBody constructor
=> Some bugs in deriche and paillou filter

modules/aruco/src/apriltag_quad_thresh.cpp, modules/aruco/src/zmaxheap.cpp, modules/optflow/src/dis_flow.cpp, modules/rgbd/src/linemod.cpp, modules/rgbd/src/odometry.cpp, modules/tracking/src/feature.cpp, modules/tracking/src/trackerKCF.cpp, modules/xfeatures2d/src/fast.cpp, modules/xfeatures2d/src/sift.cpp, modules/xfeatures2d/src/surf.cpp
**Main PR**: https://github.com/opencv/opencv/pull/11719
=> opencv: use cv::AutoBuffer<>::data()

modules/xfeatures2d/src/surf.cuda.cpp
=> xfeatures2d: fix CUDA nonfree build

modules/bgsegm/src/bgfg_gsoc.cpp, modules/bioinspired/samples/OpenEXRimages_HDR_Retina_toneMapping.cpp, modules/rgbd/src/linemod.cpp, modules/sfm/src/libmv_light/CMakeLists.txt
**Main PR**: https://github.com/opencv/opencv/pull/11986
```
docker_image:Custom=fedora:28
```
=> build: eliminate GCC8 warnings

modules/stereo/src/descriptor.cpp
See [error log](https://ptpb.pw/PqEB)
=> stereo: unbreak build using Clang 7.0

modules/ovis/src/meshes.cpp, modules/ovis/src/ovis.cpp, modules/text/src/text_detectorCNN.cpp, modules/tracking/src/tracking_utils.cpp
**Main PR**: https://github.com/opencv/opencv/pull/12219
replace to CV_Assert_N()
=> opencv-core: avoid using of multi-argument CV_Assert()

modules/ximgproc/doc/ximgproc.bib, modules/ximgproc/include/opencv2/ximgproc/ridgefilter.hpp
This pull request adds documentation to bib and include files. removing unrequired hyperlinks. ( no change, only documentation refactor )
=> Refactored include and bib files with additional documentation

modules/ovis/src/meshes.cpp
resolves https://github.com/opencv/opencv/issues/12282
=> ovis: fix build

modules/aruco/src/apriltag_quad_thresh.cpp
related https://github.com/opencv/opencv/pull/12219
=> aruco: fix debug build

modules/aruco/include/opencv2/aruco/dictionary.hpp
Merge with or before opencv/opencv#12303
Fix a minor glitch that causes the new wrapper to fail.
=> Fix enum wrapper

modules/face/src/facemarkAAM.cpp
**Merge with main PR**: https://github.com/opencv/opencv/pull/12433
resolves #1746
=> face: update FacemarkAAMImpl::delaunay() implementation

modules/xfeatures2d/src/surf.cpp
n/t
```
docker_image:Custom=ubuntu:18.04
**WIP**
CPU_BASELINE:Custom=AVX2
```
=> trying to fix the custom AVX2 builder test failures (false alarms)

modules/rgbd/samples/linemod.cpp
**Merge with**: https://github.com/opencv/opencv/pull/11630
=> C-API: eliminate constructors

modules/bioinspired/src/retina.cpp, modules/rgbd/src/odometry.cpp, modules/text/src/erfilter.cpp, modules/tracking/samples/tracker.cpp, modules/tracking/samples/tracker_dataset.cpp, modules/tracking/src/multiTracker.cpp, modules/tracking/src/tracker.cpp, modules/tracking/src/trackerFeatureSet.cpp, modules/tracking/src/trackerModel.cpp, modules/tracking/src/trackerSampler.cpp, modules/xfeatures2d/test/test_features2d.cpp
**Merge with**: https://github.com/opencv/opencv/pull/12467
=> core: replace cv::Ptr implementation => std::shared_ptr

modules/sfm/src/libmv_light/libmv/correspondence/nRobustViewMatching.h
=> solves I1767

modules/rgbd/src/odometry.cpp
Suppress some meaningless warnings that originate from external libraries
=> Fix MSVC warnings

modules/cnn_3dobj/test/test_cnn_3dobj_feature_extract.cpp
This module can be built in Ubuntu 18 with installed `libcaffe-cpu-dev` package.
=> Fixed cnn_3dobj module build

modules/matlab/CMakeLists.txt, modules/matlab/cmake/OpenCVFindMatlab.cmake, modules/matlab/cmake/hooks/STATUS_DUMP_EXTRA.cmake, modules/matlab/cmake/init.cmake
**Merge with**: https://github.com/opencv/opencv/pull/12541
`WITH_MATLAB` is disabled by default.
=> cmake: move Matlab scripts to opencv_contrib

modules/ovis/src/ovis.cpp
=> ovis: fix setCompositors if frameSrc == rWin

modules/cvv/CMakeLists.txt, modules/cvv/src/gui/call_window.hpp, modules/cvv/src/gui/main_call_window.hpp, modules/cvv/src/gui/overview_group_subtable.hpp, modules/cvv/src/qtutil/filter/diffFilterWidget.hpp, modules/cvv/src/qtutil/filter/overlayfilterwidget.hpp, modules/cvv/src/qtutil/matchview/cvvkeypoint.hpp, modules/cvv/src/qtutil/matchview/cvvmatch.hpp, modules/cvv/src/qtutil/matchview/keypointmanagement.hpp, modules/cvv/src/qtutil/matchview/keypointselectionselector.hpp, modules/cvv/src/qtutil/matchview/matchmanagement.hpp, modules/cvv/src/qtutil/matchview/matchselectionselector.hpp, modules/cvv/src/qtutil/matchview/showinrawviewwidget.hpp, modules/cvv/src/qtutil/matchview/zoomableproxyobject.hpp, modules/cvv/src/qtutil/stfl_query_widget_lineedit.hpp, modules/cvv/src/view/rawview.hpp, modules/ovis/src/ovis.cpp, modules/sfm/CMakeLists.txt
Several `-Wsuggest-override` warnings in _cvv_, _ovis_ and _sfm_ modules.
=> Fixed or disabled some warnings in several cvv, ovis and sfm modules

modules/face/src/eigen_faces.cpp, modules/face/src/face_utils.hpp, modules/face/src/fisher_faces.cpp, modules/face/src/lbph_faces.cpp, modules/hdf/src/hdf5.cpp, modules/xfeatures2d/src/pct_signatures/pct_clusterizer.cpp, modules/xfeatures2d/src/pct_signatures/pct_sampler.cpp
Fixed warnings made visible by opencv/opencv#12599
=> Fixed several incorrect printf format specifiers

modules/xfeatures2d/misc/python/pyopencv_xfeatures2d.hpp, modules/ximgproc/include/opencv2/ximgproc/slic.hpp
Merge with opencv/opencv#12678
Improve the bindings automation
- Automatically generate the enum bindings
- Fix an ambiguity in enum having a name same as its member
=> Generate enum bindings automatically

modules/cudacodec/misc/python/pyopencv_cudacodec.hpp
resolves opencv/opencv#12704
```
**WIP**
```
=> CUDA/Python: Cleanup some manual enum wrappers

README.md
I had trouble figuring out how to build the aruco samples and I thought I'd put in this breadcrumb for others who are on the same search and haven't found -DBUILD_EXAMPLES=ON
=> Added instructions on using BUILD_EXAMPLES=ON to build the samples

modules/rgbd/src/depth_to_3d.hpp, modules/rgbd/src/fast_icp.cpp, modules/rgbd/src/kinfu.cpp, modules/rgbd/src/kinfu_frame.cpp, modules/rgbd/src/kinfu_frame.hpp, modules/rgbd/src/precomp.hpp, modules/rgbd/src/tsdf.cpp, modules/rgbd/src/tsdf.hpp, modules/rgbd/src/utils.cpp, modules/rgbd/src/utils.hpp
https://github.com/opencv/opencv_contrib/pull/1798#issuecomment-429433270
=> rgbd: fix OpenCL includes

modules/rgbd/src/kinfu.cpp
=> use the c++11's shiny initializer list feature

modules/xphoto/src/grayworld_white_balance.cpp
Merge with opencv: opencv/opencv#12516
```
force_builders=Custom,armv7,armv8,linux
docker_image:Custom=powerpc64le
pw_compilers=gcc-4.9, gcc-5, gcc-6, clang-4, clang-5, clang-6
pw_with_opencv=branch:changeUnvMultiply16
```
=> replace unv 16-bit multiplication operator with v_mul_wrap 

modules/rgbd/samples/kinfu_demo.cpp
=> The kinfu_demo should open the default camera if I don't specify the camera in the cli

modules/face/src/mace.cpp
=> face: MACE filter workaround

modules/face/src/mace.cpp
resolves #1848
the D Mat in question should have been a single channel, real (not complex) one in the 1st place
also, i discovered some Vec2d Mat's not initialized correctly (0.0 -> Vec2d(0,0))
=> face: cleanup after #1849

modules/optflow/src/pcaflow.cpp, modules/optflow/src/variational_refinement.cpp
relates https://github.com/opencv/opencv/issues/12932
=> fix includes

modules/ovis/include/opencv2/ovis.hpp, modules/ovis/src/ovis.cpp
=> ovis: updates

modules/sfm/src/simple_pipeline.cpp
resolves #1872
```
docker_image:Custom=fedora:28
```
=> sfm: fix build with Ceres

modules/rgbd/test/test_normal.cpp, modules/rgbd/test/test_odometry.cpp
=> rgbd: avoid test failing of Rgbd_Normals.compute on Aarch64

modules/superres/CMakeLists.txt, modules/superres/include/opencv2/superres.hpp, modules/superres/include/opencv2/superres/optical_flow.hpp, modules/superres/perf/perf_main.cpp, modules/superres/perf/perf_precomp.hpp, modules/superres/perf/perf_superres.cpp, modules/superres/src/btv_l1.cpp, modules/superres/src/btv_l1_cuda.cpp, modules/superres/src/cuda/btv_l1_gpu.cu, modules/superres/src/frame_source.cpp, modules/superres/src/input_array_utility.cpp, modules/superres/src/input_array_utility.hpp, modules/superres/src/opencl/superres_btvl1.cl, modules/superres/src/optical_flow.cpp, modules/superres/src/precomp.hpp, modules/superres/src/ring_buffer.hpp, modules/superres/src/super_resolution.cpp, modules/superres/test/test_main.cpp, modules/superres/test/test_precomp.hpp, modules/superres/test/test_superres.cpp
Main PR: https://github.com/opencv/opencv/pull/13026
Commit: https://github.com/opencv/opencv/commit/a920ed9e1edc0490b5090f2f4bb43a65c738018b
=> superres: move to opencv_contrib

modules/reg/samples/map_test.cpp, modules/xobjdetect/src/precomp.hpp, modules/xobjdetect/tools/waldboost_detector/waldboost_detector.cpp
=> remove obsolete C API in the following modules: photo, video, imgcodecs, videoio

modules/xfeatures2d/src/surf.cpp
=> (3.4) xfeatures2d: validate keypoints mask for SURF

modules/aruco/src/aruco.cpp, modules/aruco/src/charuco.cpp, modules/cnn_3dobj/src/cnn_feature.cpp, modules/cvv/samples/cvv_demo.cpp, modules/cvv/src/qtutil/filter/diffFilterWidget.cpp, modules/face/tutorials/face_landmark/face_landmark_detection.markdown, modules/face/tutorials/face_landmark/face_landmark_trainer.markdown, modules/face/tutorials/face_landmark/face_landmark_video.markdown, modules/face/tutorials/face_landmark/sample_face_swapping.markdown, modules/img_hash/src/average_hash.cpp, modules/img_hash/src/block_mean_hash.cpp, modules/img_hash/src/color_moment_hash.cpp, modules/img_hash/src/marr_hildreth_hash.cpp, modules/img_hash/src/phash.cpp, modules/img_hash/src/radial_variance_hash.cpp, modules/line_descriptor/src/binary_descriptor.cpp, modules/reg/samples/map_test.cpp, modules/tracking/samples/tutorial_customizing_cn_tracker.cpp, modules/tracking/src/TrackingFunctionPF.hpp, modules/tracking/src/trackerBoosting.cpp, modules/tracking/src/trackerCSRT.cpp, modules/tracking/src/trackerCSRTUtils.cpp, modules/tracking/src/trackerKCF.cpp, modules/xphoto/samples/inpainting.cpp
=> minor changes

modules/bioinspired/samples/cpp/OpenEXRimages_HDR_Retina_toneMapping.cpp, modules/bioinspired/samples/cpp/OpenEXRimages_HDR_Retina_toneMapping_video.cpp, modules/bioinspired/samples/cpp/retinaDemo.cpp, modules/bioinspired/samples/cpp/tutorial_code/bioinspired/retina_tutorial.cpp, modules/bioinspired/samples/ocl/retina_ocl.cpp, modules/bioinspired/src/retina.cpp, modules/bioinspired/src/retina_ocl.cpp, modules/bioinspired/src/transientareassegmentationmodule.cpp, modules/face/samples/facerec_demo.cpp, modules/face/samples/facerec_eigenfaces.cpp, modules/face/samples/facerec_fisherfaces.cpp, modules/face/samples/facerec_lbph.cpp, modules/face/samples/facerec_save_load.cpp, modules/face/samples/facerec_video.cpp, modules/matlab/generator/templates/functional.cpp, modules/matlab/test/cv_exception.cpp, modules/matlab/test/std_exception.cpp, modules/ovis/src/ovis.cpp
relates to https://github.com/opencv/opencv/pull/12878
=> refactoring catching all exceptions as const ref

modules/ximgproc/include/opencv2/ximgproc/deriche_filter.hpp, modules/ximgproc/samples/dericheSample.py, modules/ximgproc/src/deriche_filter.cpp, modules/ximgproc/test/test_deriche_filter.cpp
Use same notation as paper-
add test (using impulse repsonse) 
python warpper 
python example
=> Rewrite deriche filter- add test - add python wrapper

modules/optflow/doc/optflow.bib
**Merge with**: https://github.com/opencv/opencv/pull/13104
=> docs: fix Kroeger2016 bib reference

modules/optflow/src/dis_flow.cpp, modules/optflow/src/variational_refinement.cpp
resolves #1894 in 3.4 opencv_contrib branch
relates https://github.com/opencv/opencv/pull/13115
=> fix include and use #if CV_SIMD128 instead of #ifdef CV_SIMD128

modules/ximgproc/include/opencv2/ximgproc/edge_filter.hpp, modules/ximgproc/samples/disparity_filtering.cpp, modules/ximgproc/src/fbs_filter.cpp
Fast Bilateral Solver revision & bug fix
- Add `lambda` parameter to fbs filter + disparity filter demo
- Add `uint16` input 
- Fix `int16` output
=> fbs_filter revision + fix

modules/text/include/opencv2/text/erfilter.hpp, modules/text/src/erfilter.cpp
=> text: reset counters in ERFilterNM::run()

modules/cvv/src/qtutil/filter/sobelfilterwidget.cpp, modules/face/include/opencv2/face.hpp, modules/xobjdetect/src/wbdetector.cpp, modules/xobjdetect/tools/waldboost_detector/waldboost_detector.cpp
Merge with: https://github.com/opencv/opencv/pull/13195
=> fix legacy contants

modules/xphoto/CMakeLists.txt, modules/xphoto/doc/xphoto.bib, modules/xphoto/include/opencv2/xphoto.hpp, modules/xphoto/include/opencv2/xphoto/tonemap.hpp, modules/xphoto/src/tonemap.cpp, modules/xphoto/test/test_hdr.cpp
**Merge with**: https://github.com/opencv/opencv/pull/13362
=> photo: move TonemapDurand to opencv_contrib

modules/ximgproc/src/fbs_filter.cpp
=> Fast Bilateral Solver bug fix

modules/ovis/src/ovis.cpp
=> ovis: free camera yaw and fix shutdown sequence

modules/tracking/include/opencv2/tracking.hpp, modules/tracking/include/opencv2/tracking/tracker.hpp
Update documentation of Tracking API
[preview](https://pullrequest.opencv.org/buildbot/export/pr_contrib/1922/docs/d9/df8/group__tracking.html)
=> Update documentation of Tracking API

modules/sfm/src/projection.cpp
=> sfm: avoid variable-names starting with underscore

modules/line_descriptor/include/opencv2/line_descriptor/descriptor.hpp, modules/line_descriptor/src/LSDDetector.cpp
Line detector/descriptor are now available to be used in Python
=> Expose line descriptor python

modules/optflow/src/pcaflow.cpp, modules/optflow/src/sparse_matching_gpc.cpp, modules/ximgproc/samples/colorize.cpp
Fixed issues found by enabling type narrowing warning (opencv/opencv#13889)
=> Fixed type narrowing issues

modules/cudev/include/opencv2/cudev/functional/detail/color_cvt.hpp
* update the coefficient value
* close #2027 
```
buildworker:Custom=linux-1
```
=> cudaimgproc: fix test failure of CUDA_ImgProc

modules/ximgproc/include/opencv2/ximgproc.hpp
This PR was created to resolve issue #1970
=> Changed mismatch grayscale to image with 3 channels

modules/surface_matching/include/opencv2/surface_matching/icp.hpp, modules/surface_matching/include/opencv2/surface_matching/pose_3d.hpp, modules/surface_matching/include/opencv2/surface_matching/ppf_match_3d.hpp, modules/surface_matching/misc/python/pyopencv_ppf_match_3d.hpp, modules/surface_matching/samples/ppf_load_match.py
- A binder for `PPF3DDetector`, `registerModelToScene` variant, and `Pose3D`
- A python sample code
=> A pythonic interface for surface_matching module

modules/ovis/src/ovis.cpp
=> ovis: addResourceLocation - only retain unique locations

modules/optflow/src/rlofflow.cpp
relates #2091
relates #2094 (1)
=> optflow: fix RLOF SR_CROSS check

modules/optflow/include/opencv2/optflow/rlofflow.hpp, modules/optflow/src/rlof/rlof_invokerbase.hpp, modules/optflow/src/rlof/rlof_localflow.cpp, modules/optflow/src/rlof/rlof_localflow.h, modules/optflow/src/rlofflow.cpp, modules/optflow/test/test_OF_accuracy.cpp
=> optflow: RLOF fixes (python-binding, status flag, flat textures)

modules/aruco/include/opencv2/aruco.hpp, modules/aruco/include/opencv2/aruco/charuco.hpp, modules/aruco/src/aruco.cpp, modules/aruco/src/charuco.cpp, modules/ccalib/include/opencv2/ccalib.hpp, modules/ccalib/src/ccalib.cpp
=> Update code after solvePnP and solvePnPRansac InputOutputArray changes

modules/videostab/include/opencv2/videostab/global_motion.hpp, modules/videostab/src/global_motion.cpp
resolves #2107
relates #2052
```
buildworker:Custom=linux-1,linux-2,linux-4
```
=> videostab: fix CUDA build

modules/rgbd/src/fast_icp.cpp, modules/rgbd/src/kinfu_frame.cpp, modules/rgbd/src/opencl/icp.cl, modules/rgbd/src/tsdf.cpp
* Option `-cl-fast-relaxed-math` for OpenCL code disabled
* Some old TODOs fixed (not related to bug fixing)
resolves #2029
```
force_builders=Linux OpenCL
test_modules=rgbd
```
=> KinFu: try to fix OCL fails

modules/rgbd/include/opencv2/rgbd/kinfu.hpp, modules/rgbd/samples/kinfu_demo.cpp, modules/rgbd/src/kinfu.cpp, modules/rgbd/src/kinfu_frame.cpp, modules/rgbd/src/kinfu_frame.hpp, modules/rgbd/src/odometry.cpp
* depth truncation added as a parameter of KinectFusion
* demo updated to support RealSense device
=> KinectFusion: several updates

modules/aruco/src/aruco.cpp, modules/aruco/src/charuco.cpp
=> aruco: simplify code by using lambdas

modules/bioinspired/samples/retinaDemo.cpp
=> push frame when videoCapture opened

modules/text/CMakeLists.txt
**Main PR**: https://github.com/opencv/opencv/pull/15301
=> (3.4): backported changes from 'master' branch

modules/reg/samples/reg_shift.py
The reg module methods that were being used were incorrect
=> Fixed the names of methods

modules/quality/src/qualitybrisque.cpp
Clamp BRISQUE output to 0-100
Resolves #2226
=> Clamp BRISQUE output to 0-100

modules/face/src/mace.cpp, modules/face/test/test_mace.cpp
fix sidelobe area calculation and slim down unit test (from ~10s to ~150ms)
=> face: fix mace code / test

modules/aruco/misc/pattern_generator/MarkerPrinter.py
Fix fixes dogod621/OpenCVMarkerPrinter#3
relates #2250
```
force_builders=docs
```
=> Fix incorrect pattern when sizeY is odd

modules/text/src/text_detectorCNN.cpp
- instead of validation checks
resolves #2279
=> text: filter CNN detection results

modules/xfeatures2d/src/sift.cpp
**Main PR**: https://github.com/opencv/opencv/pull/15692
=> xfeatures2d: use updated TLS API

modules/ovis/include/opencv2/ovis.hpp, modules/ovis/src/meshes.cpp
to create a mesh from arbitrary sources
=> ovis: add createTriangleMesh method

modules/optflow/include/opencv2/optflow/sparse_matching_gpc.hpp, modules/sfm/src/libmv_light/CMakeLists.txt, modules/surface_matching/src/ppf_match_3d.cpp
**Main PR**: https://github.com/opencv/opencv/pull/15896
=> build: GCC9 compilation

modules/ximgproc/src/structured_edge_detection.cpp, modules/ximgproc/test/test_edgeboxes.cpp, modules/ximgproc/test/test_structured_edge_detection.cpp, modules/ximgproc/test/test_thinning.cpp, modules/ximgproc/tutorials/training.markdown
=> ximgproc: avoid data race in StructuredEdgeDetection::detectEdges()

modules/line_descriptor/test/test_descriptors_regression.cpp, modules/xfeatures2d/test/test_gms_matcher.cpp, modules/xfeatures2d/test/test_rotation_and_scale_invariance.cpp, modules/ximgproc/test/test_ridge_detection_filter.cpp
**Main PR**: https://github.com/opencv/opencv/pull/15855
=> Update tests (gaussianBlur fix)

modules/line_descriptor/misc/python/pyopencv_LSDDetector.hpp, modules/rgbd/misc/python/pyopencv_linemod.hpp, modules/surface_matching/include/opencv2/surface_matching/pose_3d.hpp, modules/surface_matching/misc/python/pyopencv_ppf_match_3d.hpp
**Main PR**: https://github.com/opencv/opencv/pull/15919
=> python: force using of ArgInfo

modules/rgbd/src/odometry.cpp, modules/rgbd/src/plane.cpp
https://github.com/opencv/opencv_contrib/pull/2341#discussion_r348105772
This PR moves the constructor and destructors of RgbdPlane to plane.cpp from odometry.cpp
=> Shifted constructor and destructor definitions of RgbdPlane

modules/ovis/include/opencv2/ovis.hpp, modules/ovis/src/ovis.cpp
=> ovis: add support for off-screen windows

modules/rgbd/src/dynafu.cpp
VLA is part of C99, but still not part of C++ standard
Replace float variable-length-arrays with unique_ptr arrays (which are
part of C++14)
This makes code compilable by MSVC
=> Do not use VLA in dynafu.cpp

modules/aruco/src/aruco.cpp
continuation of #2236 
Mayor change :: shift the order of the corners to get the right position
Minor change :: automatize the selection of the '_candidatesSet' on '_identifyCandidates'
=> Correct the corner order for white markers

modules/rgbd/samples/linemod.cpp
**Main PR**: https://github.com/opencv/opencv/pull/16046
<cut/>
```
```
=> build: fix C API usage

modules/xfeatures2d/doc/xfeatures2d.bib
This try to follow the rules introduced in opencv/opencv#13228
The entries are sorted alphabetically by the last name of the first paper author, and then by date if needed.
=> Harmonise bibtex formatting

modules/optflow/src/sparse_matching_gpc.cpp, modules/xphoto/src/learning_based_color_balance.cpp
**Main PR**: https://github.com/opencv/opencv/pull/16236
=> core(SIMD): allow to build modules with SIMD emulator

modules/aruco/include/opencv2/aruco/charuco.hpp, modules/aruco/samples/detect_board.cpp, modules/aruco/samples/detect_markers.cpp, modules/aruco/tutorials/aruco_board_detection/aruco_board_detection.markdown, modules/bioinspired/doc/retina.markdown, modules/bioinspired/include/opencv2/bioinspired/retina.hpp, modules/bioinspired/src/basicretinafilter.hpp, modules/bioinspired/src/imagelogpolprojection.cpp, modules/bioinspired/src/imagelogpolprojection.hpp, modules/bioinspired/src/retina.cpp, modules/bioinspired/src/retina_ocl.cpp, modules/bioinspired/src/retina_ocl.hpp, modules/bioinspired/src/retinafilter.cpp, modules/bioinspired/src/retinafilter.hpp, modules/bioinspired/src/templatebuffer.hpp, modules/datasets/samples/tr_icdar_benchmark.cpp, modules/datasets/samples/tr_svt_benchmark.cpp, modules/sfm/tutorials/sfm_trajectory_estimation/sfm_trajectory_estimation.markdown, modules/text/samples/end_to_end_recognition.cpp
I fixed the following typo in opencv_contrib.
- `lenght` -> `length`
- `Strenght` -> `Strength`
=> fixed typo

modules/dnn_superres/samples/dnn_superres_multioutput.cpp
```
force_builders_only=Custom
build_image:Custom=centos:7
buildworker:Custom=linux-1
```
=> build: fix build with GCC 4.8

modules/xfeatures2d/src/gms.cpp
=> Fix GMSMatcher crash

.github/ISSUE_TEMPLATE.md
=> Synchronized issue template with main repository

modules/rapid/samples/track_marker.py, modules/rapid/src/rapid.cpp
=> rapid: bugfix & sample

modules/aruco/src/charuco.cpp
This PR is related to #2505
The issue is: no test for matrix singularity in _interpolateCornersCharucoLocalHom(), which results in mislocalized charuco corners in rare cases.
The PR amends `_interpolateCornersCharucoLocalHom()` by adding a test for matrix singularity by testing if the determinant is different from zero.  I chose the particular construction `(determinant != 0.)` to be consistent with other singularity tests in OpenCV (`solve()`, for instance).  Then, only those aruco markers with non-singular transformations are used to interpolate charuco corners.
=> aruco: test for singular matrix in  _interpolateCornersCharucoLocalHom()

modules/intensity_transform/CMakeLists.txt, modules/intensity_transform/doc/intensity_transform.bib, modules/intensity_transform/include/opencv2/intensity_transform.hpp, modules/intensity_transform/misc/python/test/test_intensity_transform_bimef.py, modules/intensity_transform/samples/intensity_transform.cpp, modules/intensity_transform/src/bimef.cpp, modules/intensity_transform/src/precomp.hpp, modules/intensity_transform/test/test_intensity_transform.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/737
@baidut
I have ported the BIMEF Matlab code to C++. I have used this [repository](https://github.com/baidut/OpenCE) as reference, the license is MIT.
Feel free to comment if you do not agree with this porting.
---
First test shows that it is slower than the original Matlab code, most likely due to the computation time of the Eigen Sparse Linear Solver.
---
**Left: original image**
**Middle: gamma correction with `0.4` value**
**Right: BIMEF**
- [Challenging dataset for enhancement](https://sites.google.com/site/vonikakis/datasets/challenging-dataset-for-enhancement)
---
- [source](http://www.mendosa.com/fitnessblog/?p=4932)
- [source](https://www.fujirumors.com/exposing-right/)
---
See details at …
=> BIMEF: A Bio-Inspired Multi-Exposure Fusion Framework for Low-light Image Enhancement

modules/cudafilters/include/opencv2/cudafilters.hpp, modules/cudafilters/src/cuda/median_filter.cu
Added a reference to the paper that shows the details of the GPU median filtering algorithm.
This should help with longer-term maintainability as there will be a paper to refer to if additional modifications are needed.
=> Added references to GPU median filtering algorithm

modules/ximgproc/include/opencv2/ximgproc.hpp
This is in regard to #1970 
I've completed the initial part and I think we now have to change the code, could I have some pointers on how to go about changing the code and subsequent document updation??
Review pleasee?? @alalek @LaurentBerger
=> Fixed mismatch

modules/intensity_transform/include/opencv2/intensity_transform.hpp
Warn the user that this is a C++ implementation of the original algorithm written in MATLAB.
It does not provide the same results with some issues with bright areas.
- Left: OpenCV ; Middle: MATLAB ; Right: [Python implementation](https://github.com/AndyHuang1995/Image-Contrast-Enhancement)
- Sky is overexposed
- Left: OpenCV ; Middle: MATLAB ; Right: [Python implementation](https://github.com/AndyHuang1995/Image-Contrast-Enhancement)
- Artifacts in the sky.
=> Add documentation warning about BIMEF implementation

modules/cudaoptflow/include/opencv2/cudaoptflow.hpp, modules/cudaoptflow/samples/optical_flow.cpp, modules/cudaoptflow/src/nvidiaOpticalFlow.cpp
Modified stream support functionality
Added streams to optical_flow.cpp sample app
Modified documentation of streams wrt NVIDIA Optical Flow
<cut/>
```
```
=> Modified Stream support functionality.

modules/cudaoptflow/samples/optical_flow.cpp
relates #2536
This PR is to check if build fails using non NULL streams or not. 
```
```
=> NVOF - Passing non null streams to create API

modules/ovis/src/ovis.cpp
=> ovis: bugfixes for scene corner cases

modules/viz/CMakeLists.txt, modules/viz/src/precomp.hpp, modules/viz/src/types.cpp, modules/viz/src/vizimpl.cpp, modules/viz/src/vtk/vtkOBJWriter.cpp, modules/viz/src/vtk/vtkXYZReader.cpp, modules/viz/src/vtk/vtkXYZWriter.cpp, modules/viz/test/test_tutorial2.cpp, modules/viz/test/test_tutorial3.cpp, modules/viz/test/test_viz3d.cpp, modules/viz/test/tests_simple.cpp
Related opencv/opencv#17431
Resolves #2555
~Note: the code builds but does not work, additional investigation required~
=> Added VTK 9 support

modules/ovis/src/ovis.cpp
=> ovis: fix two texture loading related bugs

modules/rapid/doc/rapid.bib, modules/rapid/include/opencv2/rapid.hpp, modules/rapid/samples/track_marker.py, modules/rapid/src/histogram.cpp, modules/rapid/src/precomp.hpp, modules/rapid/src/rapid.cpp, modules/rapid/test/test_main.cpp
=>  rapid: add "Optimal Local Search" implementation 

modules/cudaarithm/src/core.cpp, modules/cudaarithm/test/test_core.cpp
This PR is port for https://github.com/opencv/opencv/pull/17863
```
```
=> cuda::flip - Use in-place npp function for inplace arguments

README.md
=> Edit grammar, punctuation in readme

modules/stereo/src/descriptor.cpp
=> Fix CV_Assert in descriptor.cpp

modules/ovis/include/opencv2/ovis.hpp
https://pullrequest.opencv.org/buildbot/export/pr_contrib/2625/docs/d2/d17/group__ovis.html#details
---
=> ovis: add brief usage documentation

modules/stereo/src/descriptor.hpp
=> Fix mctkernel issues

modules/ovis/src/ovis.cpp
previously no new shaders were generated
=> ovis: correctly handle material property updates at runtime

modules/cudev/include/opencv2/cudev/ptr2d/detail/gpumat.hpp
<cut/>
- [X ] I agree to contribute to the project under Apache 2 License.
- [X ] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [X ] The PR is proposed to proper branch
```
```
=> Replace DataType in cudev with traits::Type<T>

modules/freetype/src/freetype.cpp
* Use FreeType coordinate in drawing/getting textsize.
* Add comment to help understanding coordinates.
<cut/>
```
build_image:Custom=ubuntu-gapi-freetype:16.04
buildworker:Custom=linux-1
```
=> freetype2: Fix 'A function call in freetype.cpp causes overflow'

modules/ovis/include/opencv2/ovis.hpp, modules/ovis/src/ovis.cpp
=> ovis: update camera drawing to new Ogre API

modules/rgbd/src/tsdf.cpp
=> Fix issue 2691

modules/rgbd/include/opencv2/rgbd/depth.hpp
=> Fixed a typo

modules/line_descriptor/src/LSDDetector.cpp
**Main PR**: https://github.com/opencv/opencv/pull/18707
=> line_descriptor: removed LineSegmentDetector

modules/cvv/src/util/observer_ptr.hpp
=> fix win, vs2019 build. missing header

modules/viz/tutorials/transformations/transformations.markdown
=> fix tutorials doc: not display pictures by default

modules/aruco/src/aruco.cpp
=> fix(aruco): add check to avoid infinite loop

modules/rgbd/src/hash_tsdf.cpp
Replace lower_bound with upper_bound
=> Minor HashTSDF bugfix

modules/wechat_qrcode/src/zxing/common/mathutils.hpp
see https://build.opencv.org.cn/job/precommit/job/windows10/311/
- [N/A] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
- [N/A] The feature is well documented and sample code can be built with the project CMake
```
build_image:Win64 OpenCL=msvs2019
```
=> hopefully fixed compile error on Windows

modules/ovis/src/ovis.cpp
@andy-held
- n/a There is reference to original bug report and related work
- n/a There is accuracy test, performance test and test data in opencv_extra repository, if applicable
- n/a The feature is well documented and sample code can be built with the project CMake
=> ovis: also take down SceneManager when Window is deleted

modules/ovis/src/ovis.cpp
8c385d58f683163fd5c56c5e43ce571bb9584564 was incomplete
- n/a There is reference to original bug report and related work
- n/a There is accuracy test, performance test and test data in opencv_extra repository, if applicable
- n/a The feature is well documented and sample code can be built with the project CMake
```
```
=> ovis: also unregister SceneManager when Window is deleted

modules/ccalib/src/omnidir.cpp
=> Fixed R2 returned by stereoRectify 

modules/ccalib/src/omnidir.cpp
#2890 from dzywater:master
Main PR: https://github.com/opencv/opencv/pull/19722
Previous "Merge 3.4": #2876
<cut/>
<details>
```
force_builders=Custom,Win64 OpenCL
buildworker:Win64 OpenCL=windows-2
build_image:Win64 OpenCL=msvs2019
```
</details>
=> (4.x) Merge 3.4

modules/ximgproc/src/thinning.cpp
=> ximgproc: add an assert in thinning()

modules/tracking/include/opencv2/tracking/tracking_internals.hpp
**Main PR**: https://github.com/opencv/opencv/pull/19817
=> cmake: fix tracking detail headers

modules/ximgproc/src/edge_drawing.cpp, modules/ximgproc/test/test_fld.cpp
fixes some issues & code clean up.
=> Edge Drawing Improvements

modules/rapid/doc/rapid.bib, modules/rapid/include/opencv2/rapid.hpp, modules/rapid/src/histogram.cpp
also fix error in LOS regarding tau
- n/a There is reference to original bug report and related work
=> rapid: add global optimal search implementation

modules/julia/cmake/init.cmake, modules/matlab/cmake/init.cmake
**Main PR**: https://github.com/opencv/opencv/pull/20446
=> cmake: process modules in the same CMake scope

modules/aruco/README.md
=> corrected a typo

modules/line_descriptor/src/LSDDetector.cpp, modules/saliency/include/opencv2/saliency/saliencySpecializedClasses.hpp, modules/tracking/src/trackerCSRT.cpp, modules/tracking/src/trackerCSRTScaleEstimation.cpp, modules/tracking/test/test_trackers.cpp, modules/xfeatures2d/src/msd.cpp, modules/ximgproc/src/graphsegmentation.cpp
**Main PR**: https://github.com/opencv/opencv/pull/20625
=> build: eliminate build warnings

modules/barcode/src/barcode.cpp
=> barcode - remove multiple color to gray conversion

modules/julia/CMakeLists.txt
=> julia: Determine availability based on whether the HAVE_JULIA is defined

modules/rgbd/CMakeLists.txt
relates https://github.com/opencv/opencv/pull/21213
<cut/>
```
build_image:Custom=qt:16.04
buildworker:Custom=linux-1,linux-4,linux-6
```
=> cmake: fix OPENGL_LIBRARIES handling

modules/rgbd/src/large_kinfu.cpp, modules/rgbd/src/precomp.hpp
Connected PR: https://github.com/opencv/opencv/pull/21018
=> New LevMarq implementation

modules/ovis/src/ovis.cpp
=> ovis: handle bg material change after shader genration

modules/ovis/include/opencv2/ovis.hpp
notably, make param order match the argment order
=> ovis: update documentation

modules/ximgproc/src/edge_drawing.cpp, modules/ximgproc/test/test_fld.cpp
ref: https://forum.opencv.org/t/circle-detection-for-fourier-mellin-shear-estimation/7674
=> bug-fix (edge_drawing.cpp)

modules/cudafeatures2d/include/opencv2/cudafeatures2d.hpp, modules/cudafeatures2d/misc/python/test/test_cudafeatures2d.py, modules/cudafeatures2d/src/orb.cpp
=> Extend the interface of the ORB class

.github/workflows/PR-4.x-U20.yaml
This PR adds a workflow for GitHub Actions to build and test OpenCV Contrib on ubuntu-20.04 for 4.x branch.
=> Workflow for Github Actions to build and test OpenCV on Linux for 4.x

.github/workflows/PR-5.x.yaml
=> Move workflows to a dedicated repository for 5.x branch

modules/stereo/samples/sample_quasi_dense.py, modules/tracking/samples/multitracker.py, modules/tracking/samples/tracker.py, modules/wechat_qrcode/samples/qrcode.py, modules/ximgproc/samples/dericheSample.py, modules/ximgproc/samples/radon_transform_demo.py, samples/python2/seeds.py
=> update python samples

.github/workflows/PR-4.x.yaml
=> Add workflows for macOS ARM64 and macOS x86_64 for branch 4.x

.github/workflows/PR-5.x.yaml
=> Add workflows for macOS ARM64 and macOS x86_64 for branch 5.x

modules/aruco/src/aruco.cpp
=> aruco: fix solvePnP parameters

modules/aruco/CMakeLists.txt, modules/ccalib/CMakeLists.txt, modules/datasets/CMakeLists.txt, modules/dnn_objdetect/CMakeLists.txt, modules/dpm/CMakeLists.txt, modules/face/CMakeLists.txt, modules/line_descriptor/CMakeLists.txt, modules/optflow/CMakeLists.txt, modules/rgbd/CMakeLists.txt, modules/text/CMakeLists.txt, modules/tracking/CMakeLists.txt, modules/xfeatures2d/CMakeLists.txt, modules/ximgproc/CMakeLists.txt, modules/xobjdetect/CMakeLists.txt, modules/xphoto/CMakeLists.txt
=> suppress warning on GCC 7 and later

modules/ximgproc/src/edge_drawing.cpp
=> ximgproc: fix mismatched new delete

.github/workflows/PR-3.4.yaml
=> Workflow on Ubuntu 14.04 for 3.4 branch

.github/workflows/PR-5.x.yaml
=> Rename jobs in GHA for 5.x

modules/wechat_qrcode/test/test_qrcode.cpp
```
force_builders=linux,Win64
```
=> fix wechat: build warnings (MSVS 2015)

modules/wechat_qrcode/src/wechat_qrcode.cpp, modules/wechat_qrcode/test/test_qrcode.cpp
=> remove upscale from wechat

modules/ximgproc/samples/edge_drawing.py
=> fix for a bug in edge_drawing.py

.github/workflows/PR-4.x.yaml
=> Workflow Ubuntu 20.04 x64 with CUDA support (4.x)

.github/workflows/PR-5.x.yaml
=> Workflow Ubuntu 20.04 x64 with CUDA support (5.x)

modules/rgbd/src/colored_kinfu.cpp, modules/rgbd/src/dynafu.cpp, modules/rgbd/src/kinfu.cpp, modules/rgbd/src/large_kinfu.cpp, modules/rgbd/test/test_colored_kinfu.cpp, modules/rgbd/test/test_kinfu.cpp
Complement PR for [#22598@main](https://github.com/opencv/opencv/pull/22598)
*KinFu classes updated to comply with a new semantics.
=> OdometryFrame made RAII and UMat-based

modules/rgbd/src/large_kinfu.cpp
This PR is related to [#22845@main](https://github.com/opencv/opencv/pull/22845)
=> Volume interface, etc: compilation fix

.github/workflows/PR-4.x.yaml
=> 4.x: Always run CUDA branch on CI.

.github/workflows/PR-5.x.yaml
=> 5.x: Always run CUDA branch on CI

modules/xfeatures2d/include/opencv2/xfeatures2d.hpp, modules/xfeatures2d/include/opencv2/xfeatures2d/nonfree.hpp, modules/xfeatures2d/misc/java/test/DAISYDescriptorExtractorTest.java, modules/xfeatures2d/misc/java/test/FREAKDescriptorExtractorTest.java, modules/xfeatures2d/misc/java/test/HARRISFeatureDetectorTest.java, modules/xfeatures2d/misc/java/test/LATCHDescriptorExtractorTest.java, modules/xfeatures2d/misc/java/test/LUCIDDescriptorExtractorTest.java, modules/xfeatures2d/misc/java/test/MSDFeatureDetectorTest.java, modules/xfeatures2d/misc/java/test/STARFeatureDetectorTest.java, modules/xfeatures2d/misc/java/test/SURFDescriptorExtractorTest.java, modules/xfeatures2d/misc/java/test/SURFFeatureDetectorTest.java, modules/xfeatures2d/src/beblid.cpp, modules/xfeatures2d/src/boostdesc.cpp, modules/xfeatures2d/src/brief.cpp, modules/xfeatures2d/src/daisy.cpp, modules/xfeatures2d/src/freak.cpp, modules/xfeatures2d/src/harris_lapace_detector.cpp, modules/xfeatures2d/src/latch.cpp, modules/xfeatures2d/src/lucid.cpp, modules/xfeatures2d/src/msd.cpp, modules/xfeatures2d/src/stardetector.cpp, modules/xfeatures2d/src/surf.cpp, modules/xfeatures2d/src/surf.hpp, modules/xfeatures2d/src/vgg.cpp
=> Features2d rw

modules/aruco/samples/aruco_dict_utils.cpp
Merge before https://github.com/opencv/opencv/pull/23005
=> aruco(cleanup): don't use Ptr<FileStorage>

modules/tracking/misc/objc/gen_dict.json, modules/xfeatures2d/misc/objc/gen_dict.json
**Main PR**: https://github.com/opencv/opencv/pull/23002
=> obj-c: remove 'const_fix' usage

modules/aruco/misc/objc/gen_dict.json
These changes fix the Objective-C mapping for the Aruco module
=> Fix for Aruco Objective-C binding

modules/xfeatures2d/src/surf.cpp
=> Fixed SURF linkage issue without nonfree.

modules/cudalegacy/src/fgd.cpp
=> build: Fix warning

modules/datasets/src/fr_adience.cpp, modules/datasets/src/track_alov.cpp, modules/line_descriptor/src/binary_descriptor_matcher.cpp, modules/optflow/src/motempl.cpp, modules/optflow/src/rlof/berlof_invoker.hpp, modules/optflow/src/rlof/geo_interpolation.cpp, modules/rgbd/src/nonrigid_icp.cpp, modules/stereo/test/test_qds_matching.cpp, modules/surface_matching/src/icp.cpp, modules/text/src/ocr_beamsearch_decoder.cpp, modules/text/src/ocr_hmm_decoder.cpp, modules/text/src/text_detector_swt.cpp, modules/tracking/src/multiTracker.cpp, modules/tracking/src/tldDetector.cpp, modules/tracking/src/tldModel.cpp, modules/tracking/src/tldTracker.cpp, modules/tracking/src/trackerSamplerAlgorithm.cpp, modules/ximgproc/src/edge_drawing.cpp, modules/ximgproc/src/fast_hough_transform.cpp, modules/ximgproc/src/find_ellipses.cpp, modules/ximgproc/src/slic.cpp, modules/ximgproc/src/sparse_match_interpolators.cpp, modules/ximgproc/test/test_adaptive_manifold_ref_impl.cpp
Companion of opencv/opencv#23225
Skipped modules: `cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev cvv java julia matlab ovis python2 sfm viz`
=> Fix clang 14 warnings

modules/viz/include/opencv2/viz/vizcore.hpp
=> Typo in viz3d doc

modules/wechat_qrcode/perf/perf_main.cpp, modules/wechat_qrcode/perf/perf_precomp.hpp, modules/wechat_qrcode/perf/perf_wechat_qrcode_pipeline.cpp
Added perfomance tests for detection and decoding with and without nn. 
Download model files from https://github.com/WeChatCV/opencv_3rdparty/tree/wechat_qrcode.
=> Wechat qrcode perfomance tests

modules/cudacodec/src/ffmpeg_video_source.cpp, modules/cudacodec/test/test_video.cpp
=> Promote cv::VideoCapture properties in VideoReader

modules/xfeatures2d/include/opencv2/xfeatures2d/cuda.hpp, modules/ximgproc/include/opencv2/ximgproc/edge_drawing.hpp
Needed for https://github.com/opencv/opencv/pull/23724
=> Add missed parameters descriptions

modules/cudacodec/test/test_video.cpp
Merge with https://github.com/opencv/opencv/pull/23846
=> FFmpeg/4.x: update FFmpeg wrapper 2023.6

.github/workflows/PR-4.x.yaml
Related to https://github.com/opencv/ci-gha-workflow/pull/101
=> Add Ubuntu 22.04 to CI.

modules/dnn_superres/CMakeLists.txt, modules/dnn_superres/misc/java/test/DnnSuperresTest.java
Address: https://github.com/opencv/opencv_contrib/issues/3532
=> Added Java bindings for dnn_superres module

.github/workflows/PR-5.x.yaml
=> Add CI configuration with Ubuntu 22.04 for 5.x branch.

modules/cudacodec/src/ffmpeg_video_source.cpp, modules/cudev/include/opencv2/cudev/util/vec_traits.hpp, modules/cudev/test/test_integral.cu
This is a satellite of https://github.com/opencv/opencv/pull/23865
=> Added new data types

modules/ccalib/src/omnidir.cpp
=> fix typing error

modules/face/samples/landmarks_demo.py
OpenCV: #24254
#3549 from kkawabat:added_no_face_error_handling_to_landmarks_demo
Previous "Merge 4.x": #3538
=> (5.x) Merge 4.x

modules/ximgproc/src/structured_edge_detection.cpp
=> More fixes for iterators-are-pointers case

modules/wechat_qrcode/src/zxing/qrcode/detector/detector.cpp
=> Corrected misspelling

modules/optflow/src/rlof/berlof_invoker.hpp, modules/optflow/src/rlof/plk_invoker.hpp, modules/optflow/src/rlof/rlof_invoker.hpp, modules/optflow/src/rlof/rlof_invokerbase.hpp, modules/optflow/src/rlof/rlof_localflow.cpp, modules/rgbd/src/colored_tsdf.cpp, modules/rgbd/src/fast_icp.cpp, modules/rgbd/src/hash_tsdf.cpp, modules/rgbd/src/tsdf.cpp, modules/rgbd/src/tsdf_functions.cpp, modules/rgbd/src/tsdf_functions.hpp, modules/rgbd/src/utils.hpp, modules/ximgproc/src/anisodiff.cpp, modules/ximgproc/src/fgs_filter.cpp, modules/xphoto/src/grayworld_white_balance.cpp, modules/xphoto/src/learning_based_color_balance.cpp
Related: https://github.com/opencv/opencv/pull/24371
=> Use new Universal Intrinsic API to fix compilation.

modules/sfm/src/libmv_light/libmv/numeric/numeric.h
This is a simple one-line patch to make the build work with GNU13.
=> fix build with GNU13

.github/workflows/PR-5.x.yaml, modules/cudaarithm/test/test_event.cpp, modules/cudacodec/include/opencv2/cudacodec.hpp, modules/cudacodec/src/NvEncoder.cpp, modules/cudacodec/src/NvEncoder.h, modules/cudacodec/src/video_writer.cpp, modules/cudacodec/test/test_video.cpp, modules/datasets/src/tinyxml2/tinyxml2.h, modules/optflow/src/rlof/berlof_invoker.hpp, modules/optflow/src/rlof/plk_invoker.hpp, modules/optflow/src/rlof/rlof_invoker.hpp, modules/optflow/src/rlof/rlof_invokerbase.hpp, modules/optflow/src/rlof/rlof_localflow.cpp, modules/rgbd/src/utils.hpp, modules/sfm/src/libmv_light/libmv/numeric/numeric.h, modules/ximgproc/src/anisodiff.cpp, modules/ximgproc/src/fgs_filter.cpp, modules/xphoto/src/grayworld_white_balance.cpp, modules/xphoto/src/learning_based_color_balance.cpp, modules/xphoto/src/oilpainting.cpp
OpenCV: https://github.com/opencv/opencv/pull/24486
OpenCV Extra: https://github.com/opencv/opencv_extra/pull/1119
#3568 from daizhirui:4.x
#3569 from cudawarped:videoio_ffmpeg_add_stream_encapsulation
#3572 from hanliutong:clean-up
#3576 from mshabunin:enable-riscv-ci
#3579 from mshabunin:fix-riscv-workflow
#3584 from asmorkalov:as/build_fixes
Previous "Merge 4.x": #3578
=> 5.x merge 4.x

modules/ccalib/CMakeLists.txt, modules/ccalib/src/precomp.hpp
This is useful if highgui is built without the imgcodecs dependency.
=> Add imgcodecs dependency.

modules/mcc/src/checker_detector.cpp, modules/mcc/src/precomp.hpp
=> Got rid of global mutex in Macbeth

modules/text/src/ocr_holistic.cpp
Fix after https://github.com/opencv/opencv/pull/24411
=> Added dnn type inference support

modules/cudev/test/test_nd.cu
Relates https://github.com/opencv/opencv/pull/25217
=> rename cv::float16_t to cv::hfloat

modules/xphoto/src/norm2.hpp
This is necessary to get https://github.com/opencv/opencv/pull/25248 working.
This was missed in 5300337197b7f580c96101953606e5f78890103c
=> Use proper C++ types again.

modules/julia/gen/funclist.csv
Related PR: https://github.com/opencv/opencv/pull/24785
=> Remove darknet function

modules/xobjdetect/tutorials/js_tutorials/js_assets/js_face_detection.html, modules/xobjdetect/tutorials/js_tutorials/js_assets/js_face_detection_camera.html
The HaarCascades related are not completely cleaned up #25311 after #25198, which [breaks the JavaScript build](https://github.com/opencv/opencv/pull/25198#issuecomment-2031835822). The PR is to fix the issue.
Main PR: opencv/opencv#25324
=> Fix broken js build after moving HaarCascades to contrib

modules/intensity_transform/src/bimef.cpp
=> More warning fixes for Ubuntu 24.04.

.github/workflows/PR-4.x.yaml
=> Added Ubuntu 24.04 to regular CI.

modules/bgsegm/include/opencv2/bgsegm.hpp, modules/bgsegm/src/bgfg_gmg.cpp, modules/bgsegm/test/test_backgroundsubtractor_gbh.cpp
=> bgsegm: gmg: Relax source type and add test

modules/wechat_qrcode/samples/qrcode.py
=> Fixed a clerical error in qrcode.py

modules/wechat_qrcode/src/detector/ssd_detector.cpp
The issue introduced in https://github.com/opencv/opencv/pull/26208
=> Do not use forward to layer feature in WeChat to support the new dnn engine

modules/xfeatures2d/test/test_rotation_and_scale_invariance.cpp
=> xFeatures2d build fix.

.github/workflows/PR-4.x.yaml
Use unified Linux pipeline
see also https://github.com/opencv/opencv/pull/26607
=> CI: update GHA pipelines

.github/workflows/PR-5.x.yaml
Use unified Linux pipeline
see also https://github.com/opencv/opencv/pull/26607
see also #3855
=> CI: update GHA pipelines (5.x)

modules/gapi/src/compiler/gislandmodel.hpp
Port of https://github.com/opencv/opencv/pull/26879
=> Added missing includes to G-API

modules/fastcv/test/test_tracking.cpp
Fixes https://github.com/opencv/opencv_contrib/issues/3958
=> Tunned FastCV tracking test for OpenCV 5.x
